tachiyomiorg/tachiyomi-extensions

src/en/kissmanga/src/eu/kanade/tachiyomi/extension/en/kissmanga/Kissmanga.kt
Should fix the indexing issue after the Romance genre in filters.
This issue started with the "Romance" genre and continued until the end. Everything before that seems okay. It's due to Kissmanga adding a Reincarnation genre. 
ex.
Select Seinen and you get Sci-fi.
Supernatural = Sports.
Tachiyomi(dev) - v0.6.3-1266 (fdroid)
en.Kissmanga - v1.0.2
=> Introduction of "Reincarnation" genre on Kissmanga

src/en/mangahere/src/eu/kanade/tachiyomi/extension/en/mangahere/Mangahere.kt
This pull request mirrors [tachiyomi#1052](https://github.com/inorichi/tachiyomi/pull/1052), as the page detection is the same in the Mangahere extension and the parser in Tachiyomi.
An extra page exists at the end of all chapters on Mangahere called "featured.html", but that page has no image, so downloading always fails. I'm not sure when this was added or when it might be removed, but it is no longer added to a chapter's page list.
=> Fix extra (advertisement) page being added in Mangahere.

src/en/readmangatoday/build.gradle, src/en/readmangatoday/src/eu/kanade/tachiyomi/extension/en/readmangatoday/Readmangatoday.kt
Hello!
Readmangatoday recently updated their HTML. So I updated the selector for the images.
This PR closes #128
=> Fix crash when downloading manga from Readmangatoday

src/en/mangahere/build.gradle, src/en/mangahere/src/eu/kanade/tachiyomi/extension/en/mangahere/Mangahere.kt
mangahere hides licensed content so updated to mark status licensed when available
also updated url to .cc since .co was just redirecting
=> Mangahere licensed status and url

src/en/mangapark/build.gradle, src/en/mangapark/src/eu/kanade/tachiyomi/extension/en/mangapark/MangaPark.kt
1. Fix low quality covers when browsing
2.  Adjust chapter names to include the title
3. Pull from all versions instead of expanded.  This prevents manga from not showing chapters cause there is no default expanded.  Also shows all chapters including duplicates compared to previously only showing what was in the expanded. I originally wrote to choose the last non expanded but upon looking into mangapark more some versions have more chapters then others and it wasnt consistent.  Easiest solution is to show them all similar to  how batoto had duplicates when more then one scanlator was working on it.
Cover change:
Old
Would update after clicking a manga
New
@null-dev as an FYI dont set the url in the mangaFromElement method, everything that shows on screen calls the mangadetailsparse and …
=> MangaPark fixes

src/all/mangadex/build.gradle, src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
Mangadex switched to adding the manga title at the end of the url.  This remove it back to just id so manga in library are shown as in library when searching the source.
=> remove name from manga url to keep backwards compat

src/all/mangadex/build.gradle, src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt, src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangadexLanguages.kt
I added the languages for which I believe there is some uploaded content.
On MangaDex there are other selectable languages:
1 | 1 | 1
-- | -- | --
2 | jp | Japanese
4 | rs | Serbo-Croatian
11 | fi | Finnish
13 | gr | Greek
17 | pt | Portuguese (Pt)
20 | dk | Danish
22 | bd | Bengali
23 | ro | Romanian
24 | cz | Czech
25 | mn | Mongolian
28 | kr | Korean
30 | ir | Persian
31 | my | Malaysian
36 | ua | Ukrainian
A note: the [Dmzj](https://github.com/inorichi/tachiyomi-extensions/blob/master/src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt), [NHentai](https://github.com/inorichi/tachiyomi-extensions/blob/7929a768c4cb65536c852e81daf2e52432247700/src/all/nhentai/src/eu/kanade/tachiyomi/extension/all/nhentai/NHLangs.kt) and …
=> mangadex: add more languages and isekai genre

src/all/foolslide/build.gradle, src/all/foolslide/src/eu/kanade/tachiyomi/extension/en/foolslide/FoolSlideFactory.kt
AkaiYuhiMun was removed in #322 from the MyMangaReader CMS extension as they no longer use a MyMangaReader CMS reader. Instead, since they now use FoolSlide, it is being moved to the FoolSlide extension.
Thanks to @Taumer for discovering this!
=> Add AkaiYuhiMun team to FoolSlide

src/all/foolslide/build.gradle, src/all/foolslide/src/eu/kanade/tachiyomi/extension/en/foolslide/FoolSlideFactory.kt
This enables the use of TLS encryption for those websites that have valid certificates like https://sensescans.com/
=> FoolSlide: enable HTTPS for websites that support it

src/all/foolslide/build.gradle, src/all/foolslide/src/eu/kanade/tachiyomi/extension/en/foolslide/FoolSlide.kt, src/all/wpmanga/build.gradle, src/all/wpmanga/src/eu/kanade/tachiyomi/extension/all/wpmanga/WpManga.kt
This is so that date_upload doesn't change on every refresh.
The use of Calendar.getInstance() in these causes the date_upload value for a chapter to change every time the source manga is refreshed, but only if that chapter's upload date was 'today' or 'yesterday'.
With the introduction of https://github.com/inorichi/tachiyomi/pull/1535, this would cause any manga with 'today' or 'yesterday' chapters to display as updated even if they were not updated.
One caveat to this is that if the same chapter is uploaded twice in a single day (with the same metadata), ChapterSourceSync.shouldUpdateDbChapter() won't be able to tell that the chapter has changed. However, this is consistent with the source's actual website, where the chapter would display "Today" for both uploads such that users …
=> [FoolSlide/WpManga] Set time to midnight for 'today' and 'yesterday' date handling

src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
I noticed that when copying/pasting text from websites into the catalog search, the MangaDex extension would sometimes come back with empty search results. The cause appears to be due to other whitespace characters (e.g. tab and newline) not being stripped before sending the API request. I've attached some GIFs to hopefully better show what I mean.
=> Replace any whitespace characters with spaces in query before searching

src/en/dynasty/build.gradle, src/en/dynasty/src/eu/kanade/tachiyomi/extension/en/dynasty/DynastyAnthologies.kt, src/en/dynasty/src/eu/kanade/tachiyomi/extension/en/dynasty/DynastyChapters.kt, src/en/dynasty/src/eu/kanade/tachiyomi/extension/en/dynasty/DynastyDoujins.kt, src/en/dynasty/src/eu/kanade/tachiyomi/extension/en/dynasty/DynastyIssues.kt, src/en/dynasty/src/eu/kanade/tachiyomi/extension/en/dynasty/DynastySeries.kt
Tachiyomi version: 0.7.4
Dynasty-Scans version: 1.2.7
For all 5 views of the Dynasty-Scans plugin, search results only return the first page of 20. You can continue to scroll and scroll and it will keep duplicating those results.
I checked the source and the search requests were missing the $page parameter. I added it to all 5 views and tested with the following queries:
Dynasty-Anthologies: `touhou`
Dynasty-Chapters: `touhou`
Dynasty-Doujins: `doujin`
Dynasty-Issues: `vol`
Dynasty-Series: `touhou`
=> Dynasty-Scans: search results return page 1, only and infinitely

src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
I didn't feel this warrant a full extension version bump, it can just get included with the next change to MD.
=> [Mangadex] Remove erroneous manga.author from searchMangaFromElement()

src/en/webtoons/build.gradle, src/en/webtoons/src/eu/kanade/tachiyomi/extension/en/webtoons/Webtoons.kt
Currently, multiple genres are combined into one with no separation.
This fixes that.
=> webtoons: handle multiple genres

src/es/tumangaonline/build.gradle, src/es/tumangaonline/src/eu/kanade/tachiyomi/extension/es/tumangaonline/TuMangaOnline.kt
Fixes #561.
Overriding headersBuilder and adding headers to the GET request.
Reopened because I forgot to change the extension version.
=> Fixes TuMangaOnline, #561

src/en/dynasty/build.gradle, src/en/dynasty/src/eu/kanade/tachiyomi/extension/en/dynasty/DynastyChapters.kt
The Dynasty website does support sorting by date added for all the other classes as well, but the results don't seem to make much sense (might be using the started date instead of updated?), so I only added this for chapters.
=> Add Latest Updates to Dynasty-Chapters

src/all/myreadingmanga/build.gradle, src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt
Fixes #577 
The Page parser was setting 1 as index on every page, making it impossible to download, also the selector was not totally correct, since some mangas randomly have a different html structure.
=> Fixes MyReadingManga downloads and selector

src/all/myreadingmanga/build.gradle, src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt
Hello and apologies in advanced as this is my first time using github, contributing to this project, and teaching myself enough code within the last few hours to patch some fixes. This pull should fix:
- "page list in empty" error (again). Instead of using the attribute [data-lazyloaded='1'] which I could not find (maybe due to an update on lazyloader), I switched it out to just [data-original-width] which is part of each page (leaving the exclusions)
- I noticed a few thumbnails were not loading. They were jpegs which was supposed to be fixed in a previous patch but one of the elements was a duplicate so I fixed it from element.attr("data-src") to element.attr("src") in the get image section. 
Hope this was helpful and can be accepted.
=> Fixes MyReadingManga selector and jpeg thumbnails

src/pt/unionmangas/build.gradle, src/pt/unionmangas/src/eu/kanade/tachiyomi/extension/pt/unionmangas/UnionMangas.kt
Fixes the "HTTP error 403" when trying to access the catalogue.
=> Update UnionMangas with their new host

src/zh/manhuaren/build.gradle, src/zh/manhuaren/src/eu/kanade/tachiyomi/extension/zh/manhuaren/Manhuaren.kt
This just addresses the crashing issue from #614, which is likely due to the extension using classes that are only available in SDK 26+.
The pages don't seem to load, but maybe the original extension author would know better about that.
=> Fix crash from Manhuaren (fixes #614)

src/pt/mangahost/build.gradle, src/pt/mangahost/src/eu/kanade/tachiyomi/extension/pt/mangahost/MangaHost.kt
I fixed some things that was making the crawler detection easier and other stuff.
- Popular, latest and search mangas now have thumbnails directly;
- Latest mangas now include some mangas that are not showing;
- Better thumbnail resolution;
- Prevent crawler detection in search by using another url;
- Remove the `(PT-BR)` and `(BR)` in manga titles;
- Remove non-chapter elements in chapter list selector;
- Join the two date parsing methods in one;
- Better page list and chapter details parsing using Jsoup;
- Add custom headers to prevent crawler detection;
- Remove unused import statements;
- Fix indentation;
- Better code legibility.
Just a note: as I know, MangaHost doesn't have an friendly history with apps that use their content, so I don't really know how long this version will work. …
=> Improvements for MangaHost.

src/ko/mangashowme/build.gradle, src/ko/mangashowme/src/eu/kanade/tachiyomi/extension/ko/mangashowme/MSMImageDecoder.kt, src/ko/mangashowme/src/eu/kanade/tachiyomi/extension/ko/mangashowme/MangaShowMe.kt
MangaShowMe change the domain due to DDoS and Internet censorship.
(Which govs lookup the plaintext SNI and send RST packet if matches before handshake successful, like DPI)
Edit: Add temporary workaround for next time.
=> Update MSM Domain

src/en/mangaplus/build.gradle, src/en/mangaplus/src/eu/kanade/tachiyomi/extension/en/mangaplus/MangaPlus.kt
`X-Requested-With` header no-longer appears in requests on the website
=> MangaPlus: Add UUID header (fixes #833)

src/fr/japscan/build.gradle, src/fr/japscan/src/eu/kanade/tachiyomi/extension/fr/japscan/Japscan.kt
fix #847 
fix #698
Original code is written by @Nosrob,  See https://github.com/inorichi/tachiyomi-extensions/issues/698#issuecomment-467929831
I'm not sure what image is encrypted. (I'm not japscan user)
It seems uri contains `clel` when it is scrambled. (normal one is just `lel`)
=> Implement Nosrob's Japscan Image Discrambler

src/en/mangazuki/build.gradle, src/en/mangazuki/src/eu/kanade/tachiyomi/extension/en/mangazuki/Mangazuki.kt
Doesn't address the issue of duplicate entries in the latest list that was present in the old version as well though.
=> Add pagination to MangaZuki (closes #835)

src/all/mangadex/build.gradle, src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
Allows to search manga on Mangadex using their respective IDs and prefixing the search with "id:".
=> mangadex: Add search by id

src/all/nhentai/build.gradle, src/all/nhentai/src/eu/kanade/tachiyomi/extension/all/nhentai/NHentai.kt
This probably isn't the best way of handling it, but it's the most rudimentary form of "throttling" I could think of within the constraint of an extension.
I'm open to suggestions.
=> NHentai: update user agent, introduce artificial delay for fetching images (fixes #938)

src/fr/japscan/build.gradle, src/fr/japscan/src/eu/kanade/tachiyomi/extension/fr/japscan/Japscan.kt
Changed the CSS selector to exclude chapter names  containing "Spoiler SPOILER" as described in
inorichi/tachiyomi#1925 
(would be great to somehow separate that feature request above and the issue described in it, to actually put that issue here instead.)
Still draft as I'm awaiting confirmation that these chapters are ALWAYS named "Spoiler SPOILER".
=> Filter out "untranslated preview pictures" and RAWs from JapScan.

build.gradle, common.gradle, src/all/mangadex/AndroidManifest.xml, src/all/mangadex/build.gradle, src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangadexUrlActivity.kt, src/all/mangadex/src/mangadex/MangadexUrlActivity.kt
Typing "id:xxx" in the searchbox due to the mangadex ddos is a drag. Here's a shortcut:
Second pr for supporting "tachiyomi://search" links: inorichi/tachiyomi#1936
=> create mangadex.org intent filter to open mangadex urls with tachiyomi

src/en/webtoons/src/eu/kanade/tachiyomi/extension/en/webtoons/Webtoons.kt
Does not affect Tachiyomi currently as JSoup is lenient when parsing CSS selectors
=> Fix invalid selector in Webtoons extension

src/all/comicake/build.gradle, src/all/comicake/src/eu/kanade/tachiyomi/extension/en/comicake/ComiCake.kt
Addresses one of the issues with older Android versions. (#354)
Referenced in documentation here: https://developer.android.com/reference/java/text/SimpleDateFormat.html
The use of 'X' only works above API 24. 'Z' is universally used and fixes the issue.
I have tested this on Lollipop 5.0 and Nougat 7.0.
=> ComiCake: Fixed date format for older Android API

src/zh/manhuaren/build.gradle, src/zh/manhuaren/src/eu/kanade/tachiyomi/extension/zh/manhuaren/Manhuaren.kt
Include only the manga id in SManga.url. The remaining required parameters
are attached by overriding *Request() functions.
This makes manga urls consistent, so mangas already in the library will
be correctly displayed as such, and user won't be able to add the same
manga to the library multiple times (although mangas added to the
library before this update will still have this problem).
=> manhuaren: make manga urls consistent

src/all/mangadex/build.gradle, src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
More specifically, fixes how cookies are added to requests.
It seems that the R18+ cookie still works, but the language filtering one (`mangadex_filter_langs`) is no longer a thing.
=> Fix MangaDex R18+ filter

src/en/mangaplus/build.gradle, src/en/mangaplus/src/eu/kanade/tachiyomi/extension/en/mangaplus/MangaPlus.kt
- Potentially fix thumbnail images not showing (#1143);
- Remove duplicate content, only showing the english titles (#866);
- Fix the "Open in browser" with a workaround based on the MangaRock one;
- Show the error message from the API when it occurs.
I pretend to implement the Spanish version (#845), but I am not sure what the steps to do that. Is it okay to create a new extension in the `all` folder that includes the both and create an update to the existing one where all the methods throws an Exception telling the user to install the new Extension and migrate the existing titles in their library? If this is okay, I pretend to do that with Manga Plus; and in a similar case unite the MangasProject and MangaLivre with another english source (7Sama) that is from the same site in a new …
=> Some fixes for Manga Plus

src/all/mangadventure/build.gradle, src/all/mangadventure/src/eu/kanade/tachiyomi/extension/all/mangadventure/MangAdventure.kt
This PR fixes the `Open in browser` action for the MangAdventure extension based on the workaround in  alessandrojean/tachiyomi-extensions@385abf9. Closes inorichi/tachiyomi#1755.
=> Open in browser workaround for MangAdventure

.editorconfig
Adds the `.editorconfig` file to keep code style similar on supporting configurations.
Also prevents the case where spaces are switched to tabs when the editor disagrees.
=> Adds a .editorconfig file

src/all/mangadex/build.gradle, src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
The app defaults to popularManga when no sorting options are selected, so the default sort should be updated to match that behavior instead of showing 'update date'. In this case, that default sort should be 'rating descending'.
=> [Mangadex] Change default sort selection to match popularMangaRequest behavior

src/all/foolslide/build.gradle, src/all/foolslide/src/eu/kanade/tachiyomi/extension/en/foolslide/FoolSlideFactory.kt
Can close: https://github.com/inorichi/tachiyomi-extensions/issues/702
Removed dead sources:
Sea Otter Scans - website points to MangaDex
Hirano MoeScans Bureau - dead, long term
PinkFatale - dead, long term
Mangaichi Scanlation Division - dead for months
Angelic Scanlations - dead, long term
Hot Chocolate Scans - dead for months
NieznaniReader - dead, long term
Helheim - dead, long term
Url change:
Anata No Motokare
The Cat Scans
Yuri-ism
=> Foolslide refresh

src/en/mangahere/build.gradle, src/en/mangahere/src/eu/kanade/tachiyomi/extension/en/mangahere/Mangahere.kt
Mangahere doesn't mark their manga as licensed on their manga's details page, only on the chapters themselves.  With this, Tachiyomi will request a chapter and parse the response to see if the manga is licensed and mark it so if it is.
Added those 2 lines to the gradle to stop Android Studio giving a compiler warning.
=> Check if Mangahere manga is licensed

src/en/mangareader/build.gradle, src/en/mangareader/src/eu/kanade/tachiyomi/extension/en/mangareader/Mangareader.kt
Latest updates request wasn't working anymore, fixed that.
Changed sort order for chapters--source provided them oldest to newest, now it's newest to oldest in Tachiyomi (how most sources are).
Chapters should show titles now if they have them (Chapter #: Title vs just Chapter #)
Better handling of getting the next pages of popular/latest/search.
=> Mangareader fixes and improvements

src/all/madara/build.gradle, src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/Madara.kt, src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Fixed a few sources that had broken chapters, think they were 1stKiss, Yokai, Tritinia, maybe others.
Filtering out chapters in Mangazuki.me and Mangazuki.online that aren't hosted on their own sites.  I think it's better to potentially have a "no chapters found" message pop up rather than clicking on chapters that get you nothing.
Fixed Mangazuki.online lateinit error.
New chapter dates are sometimes represented by a graphic instead of a text date, now parsing that image's alt text for a date.
Cleaned up some no longer used imports.
AOC is a little nutty.  Like Mangazuki they link chapters to sites other than their own (MangaDex and Imgur)--filtered those out.  Also, they have 2 different ways of managing their chapters--one's a simple chapter list and the other is by volume and chapter. …
=> Madara tweaks

src/all/genkan/build.gradle, src/all/genkan/src/eu/kanade/tachiyomi/extension/all/genkan/Genkan.kt
Fixes an issue where relative dates in the format of 'n minutes ago' where wrongly parsed as 'n months ago', resulting in chapters not displaying in the "Library updates" tab.
=> Fixed relative date parsing for 'n minutes ago' in Genkan

src/all/mmrcms/build.gradle, src/all/mmrcms/src/eu/kanade/tachiyomi/extension/all/mmrcms/MyMangaReaderCMSSource.kt
Apparently some of mangas.pw's image urls are base64 encoded, added decoding for them.  Also rewrote a comment from my previous PR for a little more clarity.
=> MMRCMS (Mangas.pw decoding)

src/en/guya/build.gradle, src/en/guya/src/eu/kanade/tachiyomi/extension/en/guya/Guya.kt
This is just a small change for the Guya extension, to group and separate calls to the website's API from Tachi and the website itself.
=> Added headers to Guya calls.

src/en/guya/build.gradle, src/en/guya/src/eu/kanade/tachiyomi/extension/en/guya/Guya.kt
An API change broke the page list request, so this update fixes that. 
I also took the opportunity to clean up the code a bit, sneak some additional user-agent info in the header, and add a description for the preferred scanlator option.
=> Additional bug-fixes and improvements to Guya extension.

src/all/myreadingmanga/build.gradle, src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt
Additional Features:
- Parses chapter names from manga page when available
If chapter names do not exist, uses previous numbers system based off of page number. 
Resulting Fixes:
- "Extras" no longer show as a chapter new chapter number (eg Extra or Chapter 21.5)
- Chapters after extras appear with correct chapter numbers
- Some manga volumes are split into another entry and do not start on chapter 1, example:
Blue Sky Complex v01 (Ch 1-6) and Blue Sky Complex (7-19)
=> MyReadingManga Chapter Names Parsing

src/all/genkan/build.gradle, src/all/genkan/src/eu/kanade/tachiyomi/extension/all/genkan/Genkan.kt, src/all/genkan/src/eu/kanade/tachiyomi/extension/all/genkan/GenkanFactory.kt
The Genkan CMS updated and now has its own search function, but not all the sites using Genkan have updated.  I've shifted the sources to using their site's search where possible; still doing client-side search for 2 of the original sources.
Leviatan Scans has Spanish translated manga available again, so I've added that.  Although they're one of the sites that's updated, search is broken for the Spanish version; so for now the Spanish version gets searched client-side unlike the English version.
Reworded a couple comments.
=> Genkan search update

src/all/mangacards/build.gradle, src/all/mangacards/src/eu/kanade/tachiyomi/extension/all/mangacards/MangaCards.kt
Current extension is 404ing on both sites due to how the URL was managed before. This change fixes both of them.
=> MangaCards: URL assignment fix

src/en/mangarock/build.gradle, src/en/mangarock/src/eu/kanade/tachiyomi/extension/en/mangarock/MangaRock.kt
It's interesting, the previous push _does_ fix the delay issue for some manga, but not all.  I've reverted that change and I'm pushing a different one.  I've checked the latest 20-25 manga at different points the last few days with this change and they've all been good; so I think this might be the one.  The solution was easy to overlook, needed to capitalize a parameter for chapter requests.
=> MangaRock chapter delay fix 2

src/all/komga/build.gradle, src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/Komga.kt, src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/dto/Dto.kt
Komga has the ability to convert images on the fly, since Tachiyomi cannot read some formats like `tiff`, it will request Komga server to convert if the raw format is not supported.
=> [Komga] request converted image from server if format is not supported

src/en/readmangatoday/build.gradle, src/en/readmangatoday/src/eu/kanade/tachiyomi/extension/en/readmangatoday/Readmangatoday.kt
Some of their chapters are linking to images outside their domain which can trigger a captcha without the right header.
=> ReadMangaToday referer header

src/pt/mangasproject/build.gradle, src/pt/mangasproject/src/eu/kanade/tachiyomi/extension/pt/mangasproject/MangasProject.kt
Recently they started to use Cloudflare on one of the sites, so the extension are getting HTTP 503 errors. This PR should fix this.
=> Fix MangaLivre Cloudflare error

src/all/webtoons/build.gradle, src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/Webtoons.kt, src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/WebtoonsDefault.kt, src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/WebtoonsFactory.kt, src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/WebtoonsTranslate.kt, src/all/webtoons/src/eu/kanade/tachiyomi/extension/id/webtoons/WebtoonsIndonesian.kt, src/all/webtoons/src/eu/kanade/tachiyomi/extension/th/webtoons/WebtoonsThai.kt, src/all/webtoons/src/eu/kanade/tachiyomi/extension/zh/webtoons/WebtoonsChineseTraditional.kt
This adds more languages where webtoons has official comics:
- Chinese (Traditional)
- Indonesian
- Thai
Closes #1492
Note that Webtoons also has Chinese (Simplified) pages, but those go off into a separate host name, so I'm not touching that for now.
Also, as far as I can tell the French (unofficial translations) support is currently busted anyway; this PR does not fix it (since there's already quite a bit of changes here).  I might do a follow-up PR if that seems useful... though I note that there hasn't been an issue filed for it.
I'm not familiar with Kotlin (or Android development in general); please let me know if there is anything I can improve, I'd be happy to change things.
Thanks for the app and the various extensions!
=> all/webtoons: Add additonal languages

src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
- Fixes formatting in strings eg. Preserves new line characters, old method would just cause manga description to bunch up into single line making it hard to read.
- Removes nested BBCode instead of just outer BBCode
- Fixed html example in comment
- Fixes #1020
=> Improve MangaDex string sanitization; Fixes #1020

src/all/foolslide/build.gradle, src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/FoolSlideFactory.kt
Fixes One Time Scans.
I'll also note that I checked all of Foolslide's sources today to see if any others were broken and found Shoujo Hearts, Shoujo Sense, and Storm In Heaven had issues.  Those issues are on their end and may be temporary so I'm not removing them in this PR.  I'll check on them again in the future and fix or remove as warranted.
=> Foolslide - OneTimeScans update

src/all/myreadingmanga/build.gradle, src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt
Fixes #1557 
[Unhanded exception](https://kotlinlang.org/docs/reference/exceptions.html) [IOException from OKHTTPClient](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-call/execute/) is now taken care of. 
Added some [null safety](https://kotlinlang.org/docs/reference/null-safety.html) for filters due to IOException
Tested online
Tested offline, did not crash on my phone.
=> Fix MRM Filter IOException

src/all/webtoons/build.gradle, src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/Webtoons.kt, src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/WebtoonsFactory.kt, src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/WebtoonsTranslate.kt, src/all/webtoons/src/eu/kanade/tachiyomi/extension/fr/webtoons/WebtoonsFrench.kt
all/webtoons: update fan-translation languages
This reworks the Webtoons fan translation languages to actually work now, as well as add all the previously unlisted languages (we just had French before).
Fixes #1517
This includes so many languages, we might want to consider splitting it off into its own extension instead.  I'm happy to do that if it seems like a good idea.
=> Webtoons: Fan translations

src/en/mangahub/build.gradle, src/en/mangahub/src/eu/kanade/tachiyomi/extension/en/mangahub/Mangahub.kt
Sorry for the inconvenience, but while comparing Mangas between different extensions i noticed that the chapter numbers were missing. So i added them.
=> Small adjustment to show chapter number in chapter list

src/zh/hanhankuman/build.gradle, src/zh/hanhankuman/src/eu/kanade/tachiyomi/extension/zh/hanhankuman/HanhanKuman.kt
Fixes #1624 
Added back code in mangaDetailsParse which should fix the details and thumbnail on backup/restore as well as library update requests.
=> Hanhankuman Details Parse 

src/zh/manhuaren/build.gradle, src/zh/manhuaren/src/eu/kanade/tachiyomi/extension/zh/manhuaren/Manhuaren.kt
Some mangas' cover is replaced by default img, while the other optional img is available.
Here is a manga reponse example.
```
{
"response": {
"mangaName": "ANGEL PARA BELLUM",
"mangaCoverimageUrl": "http://mhfm5.tel.cdndm5.com/tag/category/nopic.jpg",
"mangaPicimageUrl": "http://mhfm4cnc.cdndm5.com/15/14963/14963_b.jpg",
}
```
=> Fixed manhuaren thumbnail error

src/pt/unionmangas/build.gradle, src/pt/unionmangas/src/eu/kanade/tachiyomi/extension/pt/unionmangas/UnionMangas.kt
Sometimes they change the home, updating the url to a new one. To avoid the detection of the extension, it's good that the requests made uses the correct referer url.
=> Update UnionMangas "Referer" header to the new home url

src/all/madara/build.gradle, src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Removed Kanjiku because their website no longer uses Madara.
Added nmanhwa.com.  Closes https://github.com/inorichi/tachiyomi-extensions/issues/1652
Removed the trailing slash from KomikGo's baseUrl so that it no longer 403s.
=> Madara - sources update

src/es/tumangaonline/build.gradle, src/es/tumangaonline/src/eu/kanade/tachiyomi/extension/es/tumangaonline/TuMangaOnline.kt
I wanted to fix the latest update bug first so I proposed the previous PR. However, all the duplicates bothered me so I wrote up a fix. It just took me a bit longer to code and validate. 
Fixes: Removes all the duplicate mangas due to how the site displays latest updates.
=> [Improvement] TuMangaOnline - Removed dups from latest updates

build.gradle, src/all/mangaplus/build.gradle, src/all/mangaplus/src/eu/kanade/tachiyomi/extension/all/mangaplus/MangaPlus.kt, src/all/mangaplus/src/eu/kanade/tachiyomi/extension/all/mangaplus/MangaPlusApi.kt, src/all/mangaplus/src/eu/kanade/tachiyomi/extension/all/mangaplus/MangaPlusFactory.kt
Currently, MangaPlus is a little slow because it uses Duktape to deserialize Protobuf and decode the pages of the chapter. This PR removes Duktape completely by replacing it with [kotlinx.serialization](https://github.com/Kotlin/kotlinx.serialization) and a native function to decode the images. Should fix the problem with the thumbnails not loading after some time too.
I had to add one `classpath` to the repository Gradle file, but I think this is not a problem.
**Edit:** The compile log will have some warnings about `@Optional`, but I couldn't make it work without it, since using a default value to make a property optional only works with Kotlin >= 1.3.30.
=> Add kotlinx.serialization to MangaPlus

src/es/tumangaonline/build.gradle, src/es/tumangaonline/src/eu/kanade/tachiyomi/extension/es/tumangaonline/TuMangaOnline.kt
Closes #1671 
Old: Chapter elements were only selecting one scanner. 
New: Each chapters are now separated per scanner.
Notice for users: Chapter numbers are now added allowing for users to skip read chapters if sorted by "By chapter number"
=> [Feature] TuMangaOnline - Choose Scans

src/all/myreadingmanga/build.gradle, src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt
Restored WPSolr Search for My Reading Manga
Continues work on #1354 
I finally found how you can retrieve paginated results for wpsolr's infinite scroll.  It is POSTed normally but the post request had `wpsolr_page=2` which made it an easy GET request. 
Code also takes into account the filters which are handled via different css selectors. 
- [Restored] WPSolr Search - faster results
- ["Fixed"] WPSolr Search Page - now returns all results
- [Fixed] Trim on title - fixed the extra space at the beginning of manga titles which had been bugging me
- [New] Moved latest manga to "Latest" button instead of browse. "Browse" now displays 'random' manga. 
Also, sorry for the mess of a differential. I moved some lines up and down and github didn't seem to like that. I added some notes for future …
=> [Improvement] My Reading Manga - Search

src/zh/dmzj/build.gradle, src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt
The original comic query failed, and adding a version parameter will fix it.
Example:
❎[http://v3api.dmzj.com/comic/comic_47626.json](http://v3api.dmzj.com/comic/comic_47626.json)                             
✅[http://v3api.dmzj.com/comic/comic_47626.json?version=2.7.019](http://v3api.dmzj.com/comic/comic_47626.json?version=2.7.019)
=> Fixed dmzj search error

src/all/mangaplus/build.gradle, src/all/mangaplus/src/eu/kanade/tachiyomi/extension/all/mangaplus/MangaPlus.kt, src/all/mangaplus/src/eu/kanade/tachiyomi/extension/all/mangaplus/MangaPlusApi.kt
The version used of Kotlinx Serialization has some issues when deserializing on KitKat devices, I don't know if it's related to the version of the lib and it's fixed in the newer versions of Kotlin. As a temporary solution, the old method of deserialize the MangaPlus API is used on devices running KitKat or a lower Android version.
Should close #1678.
=> Fix the crash in MangaPlus on KitKat devices

src/en/mangafree/build.gradle, src/en/mangafree/src/eu/kanade/tachiyomi/extension/en/mangafree/Mangafree.kt
Fixes #1704
~~Square brackets and some other characters are considered unsafe and really shouldn't be used ina url in general~~
Skimmed RFC 2396 for URI rules but didn't see anything particular. Either way, the URI parser is throwing an exception with square brackets so as a work around, we can pre-encode the brackets before sending it to setUrlWithoutDomain
=> [Fix] Mangafree - url with brackets

src/zh/dmzj/build.gradle, src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt
Fixes #1702 
The V3 API for Dmzj is reporting back "章节不存在" (Chapter does not exist)
I'm not sure how the api works. I'm also not sure if the api is having temporary issues or not. 
The javascript to load the chapters refers to `var request_chap_url = '/chapinfo/' + this.comic_id + '/' + this.chapter_id + '.html';` which is working more reliably and looks to return the same json file currently so I updated the page list request.
=> [Fix] Dmzj - api issues

src/all/mangadex/build.gradle, src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
Confirmed by MD staff
```
[4:01 PM] FlaminSarge: quick q: the 'eu' and 'eu2' server query parameter options are completely gone and we should use 'na' and 'na2' only now, right?
[4:01 PM] FlaminSarge: or 'row'
[4:07 PM] Plykiya ⭐: @FlaminSarge eu isn't gone
[4:07 PM] Plykiya ⭐: the na and eu options are merged because Path automatically directs your traffic to their closest cache server which is either in the NA or EU
[4:37 PM] FlaminSarge: Sorry, right, the query param values only accept 'na' or 'na2' or 'row' now though, right?
[4:38 PM] FlaminSarge: last I checked, using 'eu' or 'eu2' values didn't work
[4:45 PM] Holo: yesw
[4:53 PM] FlaminSarge: ty
```
=> [Mangadex] Remove eu/eu2 image server options and update strings to match current website options

src/all/mangabox/build.gradle, src/all/mangabox/src/eu/kanade/tachiyomi/extension/all/mangabox/MangaBox.kt
I think 7 of the 12 "latest" manga on mangakakalot is redirected to manganelo. 
This should set the manga url the same way as the chapter urls are set.
=> [Fix] Mangakakalot Redirect

src/zh/kuaikanmanhua/build.gradle, src/zh/kuaikanmanhua/src/eu/kanade/tachiyomi/extension/zh/kuaikanmanhua/Kuaikanmanhua.kt
Closes #1729 
Chapters links are currently a relative link so I removed setUrlWithoutDomain
I added a lock icon for locked chapters as well as a exception toast. 
Thank you @SnakeDoc83 for helping take a look too.
=> [Fix] Kuaikanmanhua - locked chapters

src/all/mangadex/build.gradle, src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
Adds ability to find all the manga from a group.  It works when you're not logged in too; so it's another way to find manga besides using ID (assuming you know which group TLed it).
=> MangaDex - group search

src/es/tumangaonline/build.gradle, src/es/tumangaonline/src/eu/kanade/tachiyomi/extension/es/tumangaonline/TuMangaOnline.kt
Addresses https://github.com/inorichi/tachiyomi/issues/2297
New:
Provides preference option to remove duplicate chapter entries by only adding first scanlator on list. 
To be fixed later:
Strings are in English, someone should translate them properly.
=> [Enhancement] TuMangaOnline De-dup Preference

src/all/mangabox/build.gradle, src/all/mangabox/src/eu/kanade/tachiyomi/extension/all/mangabox/MangaBox.kt
I'm not sure why mainline Tachi wasn't complaining and Tachi-EH did but here is the fix for `Did not find balanced marker at 'status'` when using mangabox in Tach-EH
=> [Fix] Mangabox - balanced marker at status

src/es/mangamx/build.gradle, src/es/mangamx/src/eu/kanade/tachiyomi/extension/es/mangamx/MangaMx.kt
#1756 
Changed Latest Updates from 'Latest Manga added to the site' to 'Latest Chapters added to the site'
Extension tries to remove duplicates but it only works per page. 
Still to do: genre filtering but I still need to learn a bit more on how the filters work and how to properly add them in.
=> [Change] Mangamx

src/all/madara/build.gradle, src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Fixes #1769
Allporncomic might still be using cloudflare but most of the major browser checking and ddos protections look to be turned off. 
Not sure why this edit works but it works on my test phone. I not even adding any headers.
=> [FIx] Allporncomic

src/all/madara/build.gradle, src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Second time to try to fix #1769
Error 503 + cloudflare server is assumed to be ddos protectoin with check.
Turns out, site is also running wordfence security (found out when I got temp banned). Possible with rate limiting. Turns out, wordfence also throws 503 errors which causes the cloudflare client to check for challenge url which doesn't exist. 
Added desktop user-agent to bypass the 503 since the website loads for my desktop browser. It was part of my testing the first time but it was working without it too so I got rid of it in my previous PR.
=> [Fix v2] AllPornComics

src/all/madara/build.gradle, src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
**ZinManga** https://github.com/inorichi/tachiyomi/issues/2335
Added Referrer to resolve 403 forbidden from images hosted by CDN
**AllPornComics** https://github.com/inorichi/tachiyomi-extensions/issues/1769
503 errors should have come from WordFence. However, due to also running though the cloudflare cdn, it triggered Tachiyomi's cloudflare bypass. Wordfence seems to be behaving now so, I reverted the changes. 
Draft pending continued testing against AllPornComics to ensure the fix actually sticks.
=> Madara Fixes, - revert AllPornComics, ZinManga fix

src/en/mangahere/build.gradle, src/en/mangahere/src/eu/kanade/tachiyomi/extension/en/mangahere/Mangahere.kt
Fixes #1808 
Checks if page is using webtoon viewer (ie chapter_bar.js)
Then de-obfuscates the script and pulls in url data.
=> [Fix] Mangahere - Parser for webtoon type 

src/all/nhentai/build.gradle, src/all/nhentai/src/eu/kanade/tachiyomi/extension/all/nhentai/NHentai.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/754 and https://github.com/inorichi/tachiyomi-extensions/issues/1711
I didn't add all the details that were asked for in #754, as some of it was superfluous.
For #1711 I made it a configurable option to display titles in full (as they were) or in a shorter form; the default is full titles.
=> NHentai update

src/all/foolslide/build.gradle, src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/FoolSlideFactory.kt
TsubasaSociety seems to be an image board now; so removing them.
Something's up with DKThias too, but it may be temporary so I'm leaving it for now.
=> Foolslide - remove TsubasaSociety, add HelveticaScans

src/zh/manhuadui/build.gradle, src/zh/manhuadui/src/eu/kanade/tachiyomi/extension/zh/manhuadui/Manhuadui.kt
Fixes #1836
Image failed because it was forbidden to hot link direct to `images.dmzj.com` server. 
Loads image though `https://mhcdn.manhuazj.com/showImage.php?url=` which is how the website normally works.
=> [Fix] Manhuadui

src/all/mangabox/build.gradle, src/all/mangabox/src/eu/kanade/tachiyomi/extension/all/mangabox/MangaBox.kt
Fixes #1844 
I hit an issue with the `convert_image_digi.mgicdn.com` on 10/13/2019 where tachi will not load the image correctly. I still can't tell what exactly is the problem is. A site such as Mangakakalot is referencing the `mgicdn.com` which in turn pulled from the `mrcdn.info` (manga rock?)
Because it will not load correctly from `convert_image_digi.mgicdn.com`, this attempts to remedy it by passing it to the `Images.weserv.nl` image cache which will work.
I'm not sure if it is a good idea or not but it does work.
=> [Patch] MangaBox - Change CDN 

src/en/tapastic/build.gradle, src/en/tapastic/src/eu/kanade/tachiyomi/extension/en/tapastic/Tapastic.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1852 and https://github.com/inorichi/tachiyomi-extensions/issues/1165
@superuser-does
Regarding #1165, I only changed Tapastic to Tapas for the extensions page.  It'll still appear as Tapastic in the catalog; changing it there could cause an issue for users who saved manga from Tapastic to their library.
=> Tapastic - chapter lock icon

src/all/madara/build.gradle, src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
The standalone toonily extension was presenting problems and was being reported in Discord. 
The site appears to be running Madara so I added it for now.
Tested it and it seems to be loading everything as expected.
Todo by anyone:
Clean up standalone extension after merge (and confirmation it works)
=> Move Toonily into Madara

src/es/tumangaonline/build.gradle, src/es/tumangaonline/src/eu/kanade/tachiyomi/extension/es/tumangaonline/TuMangaOnline.kt
This PR should be ready to pull pending any further changes from TMO. It has been a few days since their last (daily) change. We can still wait some more to see if anything changes... again. 
This should fix #1749
Current revisions:
- Revert pageListParse
- Chapter URL are no longer directly linked from manga page. Read button is an actual button with a scripted click action. This now pulls the chapter ID and requests viewer url via POST.
FAQ Reminder that needs to be posted: 
Since chapter URLs have been updated, the chapter lists in the library need to be pulled to refresh.
=> [Ready] TMO Update

src/en/webcomics/build.gradle, src/en/webcomics/src/eu/kanade/tachiyomi/extension/en/webcomics/Webcomics.kt
Source only allows 20 chapters per manga, after that they're locked to their own app.  Since they're unavailable to us, might as well not create chapters past 20.  Also added manga.status to details.
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1298
=> Webcomics: Limit to 20 chapters

src/all/mangabox/src/eu/kanade/tachiyomi/extension/all/mangabox/MangaBox.kt
In manga description:
replace __\<br\>__ tags with __'\n'__ (line break)
remove any other tags (such as __\<b\>__ or __\</b\>__ for example)
some descriptions start with __"[_manga title_] summary:"__, remove it as it adds nothing to the context
=> Mangakakalot description parsing

src/all/mangabox/build.gradle, src/all/mangabox/src/eu/kanade/tachiyomi/extension/all/mangabox/MangaBoxFactory.kt
Fixes Kakalot's filtered search (https://github.com/inorichi/tachiyomi-extensions/issues/1895), don't want to deal with Nelo right now.
Should be able to merge this along with https://github.com/inorichi/tachiyomi-extensions/pull/1893, right?
=> MangaBox - Kakalot search

src/en/guya/build.gradle, src/en/guya/src/eu/kanade/tachiyomi/extension/en/guya/Guya.kt
It seems like the latest changes to dev broke the preference screen for Guya, and causes the app to fail to launch. 
This fixes the problem.
=> Preference cast fix.

src/all/madara/build.gradle, src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1966 and https://github.com/inorichi/tachiyomi-extensions/issues/1967
Didn't remove ToonManga in case they stop forwarding/return to themselves in the near future; will remove if they don't.  Added the site they're forwarding to (wakamics) as its own source.
Removed Tritinia Scans--my understanding is that they will publish to MangaDex instead of their own site from now on.
=> Madara - add Wakamics, remove Tritinia

src/all/toomics/build.gradle, src/all/toomics/src/eu/kanade/tachiyomi/extension/all/toomics/ToomicsGlobal.kt
These end up having 'empty pagelist' errors as well
Ultimately the ext should figure out how to use the same requests that the Toomics native app uses, but that's for a later time
=> [Toomics] Filter out 'free in app' chapters

src/all/mangabox/build.gradle, src/all/mangabox/src/eu/kanade/tachiyomi/extension/all/mangabox/MangaBoxFactory.kt
Reported via discord 
Fixes #2000
The only examples I could find are Mangabat hosting the manga details page themselves but link to Nelo for the chapter / reader. I don't think there is a need to change anything else. 
Also added a quick comment to help explain what is going on.
=> Mangabat pagelist Empty

src/en/mangaowl/build.gradle, src/en/mangaowl/src/eu/kanade/tachiyomi/extension/en/mangaowl/MangaOwl.kt
Directed at fixing some chapter URLs causing an error 500.  Users experiencing that error should be directed to update and refresh any chapter list that generate that error.
Also, can close https://github.com/inorichi/tachiyomi-extensions/issues/1679.
=> MangaOwl - chapter URLs

src/en/mangarock/build.gradle, src/en/mangarock/src/eu/kanade/tachiyomi/extension/en/mangarock/MangaRock.kt
Changed P`age List Empty` error to `Manga Rock has shut down. Please migrate to another source` because people still are still asking us in Discord Support 💢
=> MangaRock - Update Error Message

src/all/ninemanga/build.gradle, src/all/ninemanga/src/eu/kanade/tachiyomi/extension/all/ninemanga/NineMangaFactory.kt
Fixes #2017
Ninemanga doesn't know which subdomain to give for en users. 
- Latest it uses www
- Popular it uses en
Now accounts and changes www.ninemanga.com to en.ninemanga.com
I don't know why it doesn't use setUrlWithoutDomain() but I didn't want to change too much.
=> NineMangaEn - Account for subdomain

src/ja/rawkuma/build.gradle, src/ja/rawkuma/src/eu/kanade/tachiyomi/extension/ja/rawkuma/Rawkuma.kt
Fixes #2061 
Pattern X is only part of API 24+ (Android 7)
X | Time zone | ISO 8601 time zone | -08; -0800; -08:00 | 24+
I removed the time zone because we are really looking for the date only. 
I added a try and catch just in case something changes.
Tested OK to ensure I didn't break anything.
=> Fix Rawkuma date parsing

src/all/mangadex/build.gradle, src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
Force network instead of using cache when getting manga info and chapter list for mangadex.
=> fix chapter list not reflecting blocked groups from mangadex

src/all/madara/build.gradle, src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
I didn't want to do this but people #2113 kept #2069 complaining #2029 !
This I feel will be my final "fix". 
Wordfence is a bit difficult to defeat partially because I don't know what they are doing that keeps triggering 503 forbidden and the help documentation only explains so much. (Though I guess I can install it myself to take a closer look)
- Uses latest Chrome user agent. De-randomized, because that isn't working anymore anyways. I keep thinking I dare them to block the standard chrome user agent but I know that isn't what will happen either way. 
- Adds refer back just in case
- Changes the cloudflare client to the normal client to stop throwing the cloudflare error.
=> Madara APC Fix

src/pt/hqnow/build.gradle, src/pt/hqnow/src/eu/kanade/tachiyomi/extension/pt/hqnow/HQNow.kt
The title of the letter filter is bad translated from English to Portuguese.
The current word, *carta*, means "a paper letter", and not "a letter from the alphabet", that would be *letra*.
This PR changes the word to the correct one.
=> Fix a wrong word on HQNow extension

src/all/madara/build.gradle, src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes #2040
Limitations:
- Region limited to BR only.
- Some covers are broken on source. Lazy loading loads a resized version but the main image itself is 403 Forbidden. This really should only affect older mangas I think. 
- Chapter upload date doesn't include a year so I didn't do anything with it. It will still pick up on relative time such as '5 hours ago'
=> [Madara] Add Yaoi Toshokan

src/en/mangahere/build.gradle, src/en/mangahere/src/eu/kanade/tachiyomi/extension/en/mangahere/Mangahere.kt
Fixes #2107 
Mangahere normally has a insert image for the mangazone app as the last page. However, it doesn't get inserted properly for the webtoon viewer type. 
The invalid last image is now bypassed by reducing the total images by 1. It should not affect actual pages that are important. 
Also, changed to https
=> Mangahere Update Page List for Webtoons

src/fr/japscan/build.gradle, src/fr/japscan/src/eu/kanade/tachiyomi/extension/fr/japscan/Japscan.kt
Fixes #2125 
I'm not totally sure what encoding measures that japscan has in place so I tried not to mess with it too much.
- The data url as part of the page list (options) are already an absolute url currently. (not sure what it was before.) Fixed it so there is no duplicate path interted. 
- Also fixed thumbnail urls which was broken for me because the img files were case sensitive for whatever reason.
=> Fix Japscan

src/zh/gufengmh/build.gradle, src/zh/gufengmh/src/eu/kanade/tachiyomi/extension/zh/gufengmh/Gufengmh.kt
Fixes #2140
I noticed it on the filter list but the path generated is `/search?keyword=query` while the site specifically requires `/search/?keyword=query`
=> Fix Gufeng Manhua Search

src/all/genkan/build.gradle, src/all/genkan/src/eu/kanade/tachiyomi/extension/all/genkan/GenkanFactory.kt
Also, removed KaguyaDex and KomiScans - both websites have been unreachable for quite a while.
=> Genkan - add Reaper Scans

src/zh/pufei/build.gradle, src/zh/pufei/src/eu/kanade/tachiyomi/extension/zh/pufei/Pufei.kt
Pufei's domain got updated. I noticed it when I was running logs and testing out why the search doesn't work. 
So, this fixes #2156
They are still redirecting pufei.net to the new one. I tried updating the imgage server but it broke more than I wanted to handle so I left it as is. Not sure when it will stop working if they let .net expire.
=> Pufei Domain Update

src/ru/libmanga/build.gradle, src/ru/libmanga/src/eu/kanade/tachiyomi/extension/ru/libmanga/LibManga.kt
Fixes #2173
Used vpn via Serbia
Title isn't actually part of "body" so I switched it to document and updated the selector 
Validated selector via try.jsoup.org and log.i
It does however return a Russian title rather than the English which is what they have on top of the manga page.
=> Fix MangaLib Title Fetch

src/zh/pufei/build.gradle, src/zh/pufei/src/eu/kanade/tachiyomi/extension/zh/pufei/Pufei.kt
Fixes #2182 
I thought it wasn't working when I tested it as I was working on the previous PR. 
Retesting it again, it seems to be working. 
Inspecting the webpage shows that it points to `http://res.img.220012.net/`
As inferred from the previous entry, `http://res.img.ipufei.com` also works but I decided to mirror what they have now via.
=> Pufei imgdomain

src/pt/unionmangas/build.gradle, src/pt/unionmangas/src/eu/kanade/tachiyomi/extension/pt/unionmangas/UnionMangas.kt
Change to `http` in UnionMangás since their `https` certificate expired and they didn't renewed it yet.
Should close #2200.
=> Fix CertPathValidatorException in Union Mangás

src/en/mangahasu/build.gradle, src/en/mangahasu/src/eu/kanade/tachiyomi/extension/en/mangahasu/Mangahasu.kt
Fixes #1548
Find and replace placeholder images on new chapters. 
MangaHasu is ripping from Mangadex. There are temporary urls that are encoded json file before the images are fully loaded onto the MangaHasu servers. These images are scrapped as "Loading". 
This PR now decodes the json file and replaces the "Loading" images similar to what normally happens in the browser.
=> MangaHasu - Fix Placeholder Images

src/en/holymanga/build.gradle, src/en/holymanga/src/eu/kanade/tachiyomi/extension/en/holymanga/HMangaFactory.kt
Hopefully closes #2263 
I was not able to reproduce the "No Results Found" error code but I did notice that there was a chain of redirects which causes an error bypassing cloudflare.
Example:
`https://heavenmanga.org` redirects to `http://ww7.heavenmanga.org` which then redirects to `http://ww8.heavenmanga.org` each triggering cloudflare checks again. 
Updated baseUrl and tested on dev and stable that basic functions were working.
=> Holy/Heaven Manga - Update baseUrl

src/all/webtoons/build.gradle, src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/Webtoons.kt
* can browse popular webtoons again
* can update webtoon chapter lists again
* can search for webtoons again
* version number updated
Webtoon implemented an age gate that interfered with scraping.
We now have to send a cookie with every request to make it work again.
I've used code from commit #1029 which fixed a similar issue.
Finding the problem, adapting the fix and testing it is what I did.
=> webtoon age gate fix

src/ar/mangaae/build.gradle, src/ar/mangaae/src/eu/kanade/tachiyomi/extension/ar/mangaae/MangaAe.kt
Change Log (from top to bottom)
- Added Rate Limiting and new headers as an attempt to address #1963. I think this reduces the risk and rate of a possible server side trigger that causes pages to be blocked. 
Popular
- Added pages to popular and fixed next page selector
- Changed Arabic names to English to make names uniform across the extension. Also helps if you wish to migrate to a different extension I think.
- Fixed broken thumbnails
Latest
- Fixed url selection #2268
Details
- Refactored while I was at it.
Chapter List
- Added a arabic Unicode marker to ensure all text is right to left due to mixed text (Some titles contain only numbers while some other contain arabic titles)
=> Refactor / Fix Manga.ae

src/all/mangadventure/build.gradle, src/all/mangadventure/src/eu/kanade/tachiyomi/extension/all/mangadventure/MangAdventure.kt, src/all/mangadventure/src/eu/kanade/tachiyomi/extension/all/mangadventure/MangAdventureExtensions.kt
MangAdventure introduced custom chapter titles (e.g. `Z={number}: {title}`) in `v0.6.4`.
The extension will now use that title and fall back to a generic format if it's not available.
This also fixes a bug in older versions of the API.
---
P.S. @SnakeDoc83 MangAdventure should be moved to the multi-source tab of your spreadsheet.
=> MangAdventure: support custom chapter titles

src/en/guya/AndroidManifest.xml, src/en/guya/build.gradle, src/en/guya/src/eu/kanade/tachiyomi/extension/en/guya/Guya.kt, src/en/guya/src/eu/kanade/tachiyomi/extension/en/guya/GuyaUrlActivity.kt
At the request of some users, added support for directly opening manga from the `https://guya.moe/read/manga/*` URL.
=> Guya: Add support for opening guya.moe titles directly in Tachiyomi

src/all/mangabox/build.gradle, src/all/mangabox/src/eu/kanade/tachiyomi/extension/all/mangabox/MangaBoxFactory.kt
Reported on Discord:
MangaFree doesn't support https 
`Unable to connect` / refused connection.
=> MangaFree - Remove https

src/en/kissmanga/build.gradle, src/en/kissmanga/src/eu/kanade/tachiyomi/extension/en/kissmanga/Kissmanga.kt
Covers were included in the tool tip info so we can add thumbnails to the initial manga load in popular / latest / search.
=> Kiss Manga - Add thumbnails to MangaFromElement

src/all/mangadex/build.gradle, src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
I needed this for filtering, plus you can see it as a way for user to tell the origin of a manga/comic/manhwa/thing
=> [MangaDex] Adding Manga language to list of genres

src/en/kissmanga/build.gradle, src/en/kissmanga/src/eu/kanade/tachiyomi/extension/en/kissmanga/Kissmanga.kt
A user on discord was asking if they can view trending titles instead of most popular. 
This enables the viewing of Trending Manga and New Manga lists via a filter select for Kiss Manga.
=> KissManga - Enable Trending / New Manga lists

src/all/ehentai/build.gradle, src/all/ehentai/src/eu/kanade/tachiyomi/extension/all/ehentai/EHentai.kt
Allows you to use the E-Hentai watched page to view a listing of your watched tags
- Requires you be logged in with webview
- Watched tags have have to be edited in webview or on a browser
- Power threshold is changed in the webview, in the E-Hentai Settings for your account
=> E-Hentai added Watched list

src/all/mangaplus/build.gradle, src/all/mangaplus/src/eu/kanade/tachiyomi/extension/all/mangaplus/MangaPlus.kt
- If the response has any error, display the message from the API in popular and latest;
- Use the response content type to build the new body;
- Update user agent string.
Regarding the thumbnail problem, I think it can't be fixed on the extension side because of the behavior of the MangaPlus backend. However, maybe some checks can be done in the app, I will open a issue on the main repo with the information and a possible solution.
=> Use error message from MangaPlus API

src/pt/mangasproject/build.gradle, src/pt/mangasproject/src/eu/kanade/tachiyomi/extension/pt/mangasproject/MangasProject.kt, src/pt/mangasproject/src/eu/kanade/tachiyomi/extension/pt/mangasproject/MangasProjectFactory.kt
MangasProject recently changed its name to "Leitor.net" and now only lists webtoons at the initial page, becoming into a "different website". To avoid confusion, I changed the old name and hardcoded the old generated id. 
Old titles like mangas in the library still work and can be accessed at the website through the direct URL or search, so a migration isn't really necessary. Is this a good approach, or it's better to only change the `name` and bump the `versionId`, forcing the users to migrate their library to MangaLivre?
=> Change MangasProject name to the new one

build.gradle, src/all/mangaplus/build.gradle, src/all/mangaplus/src/eu/kanade/tachiyomi/extension/all/mangaplus/MangaPlus.kt, src/all/mangaplus/src/eu/kanade/tachiyomi/extension/all/mangaplus/MangaPlusApi.kt
Update Kotlin's version to match the version used in the app (1.3.70) and the kotlinx.serialization lib.
The compiled MangaPlus apk was tested in Android 4.1 (stable), Android 5.0, 6.0 and 10.0 (stable and dev) and it's working fine with the deserialization from kotlinx.serialization.
On older devices (Android <= KitKat) the extension only works with the stable version because of some unknown incompatibility with Duktape 1.3.0 and Kotlin 1.3.70 related to the `require` function. Since the dev version isn't compatible anymore with those devices, it doesn't see to be a huge problem.
Should close #2512.
=> Update Kotlin and kotlinx.serialization version

src/all/madara/build.gradle, src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Shouldn't really change nothing since the title _should_ already be fetched when opening the latest/popular/search page but better safe than sorry.
=> Fixed title parsing for DisasterScans's mangaDetailsParse

src/en/mangahere/build.gradle, src/en/mangahere/src/eu/kanade/tachiyomi/extension/en/mangahere/Mangahere.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2573
Seems like Mangahere obfuscates their manga on their mobile subdomain now as well as the main site; so I reverted to the previous version of the extension.  I've tweaked it; so hopefully the problem with webtoons having a broken last image won't show itself again.
=> Mangahere - revert & tweak pages

src/ru/mangaonlinebiz/build.gradle, src/ru/mangaonlinebiz/src/eu/kanade/tachiyomi/extension/ru/mangaonlinebiz/Mangaonlinebiz.kt
The site rejected connections with a 404 error when using the old chrome user agent.
=> Mangaonlinebiz: Error 404

src/all/mangaplus/build.gradle, src/all/mangaplus/src/eu/kanade/tachiyomi/extension/all/mangaplus/MangaPlus.kt
Even if the extension already does the request with the high-resolution parameter, I thought it was a good idea to add preferences to allow users to set the resolution to low if they want, just like the MangaPlus app does. I added an option to disable the split double pages behavior too, but it doesn't work on all titles.
The preferences are separated by the language, so they can be changed separately.
=> Add preferences to MangaPlus

src/pt/mangahost/build.gradle, src/pt/mangahost/src/eu/kanade/tachiyomi/extension/pt/mangahost/MangaHost.kt
I also hardcoded the id because the name was missing an accent and the language wasn't specific. 
I will probably do this to the other Brazilian extensions too in another PR.
To those who update: Mangá Host is now under the *Português (Brasil)* category at *Sources*.
=> Update MangaHost user-agent

src/all/mangadex/AndroidManifest.xml, src/all/mangadex/build.gradle
While Google search results lead to mangadex.org websites,
other search engines such as Duckduckgo and Bing lead to
www.mangadex.org websites.
Changed extension manifest to handle www.mangadex.org
=> Added www Mangadex subdomain to open directly

src/pt/mangasproject/build.gradle, src/pt/mangasproject/src/eu/kanade/tachiyomi/extension/pt/mangasproject/MangasProject.kt, src/pt/mangasproject/src/eu/kanade/tachiyomi/extension/pt/mangasproject/MangasProjectFactory.kt
Also updated the language to `pt-BR`, hardcoding the previous `id`.
To those who update: 
- MangaLivre and Leitor.net are now under the *Português (Brasil)* category at *Sources*;
- To skip the chapters with the same number from other scanlators and prioritize the current scanlator during reading, make sure the *Sorting mode* selected is *By chapter number* at the chapter list three-dots menu.
=> Add missing chapters at MangasProject

src/all/madara/build.gradle, src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/Madara.kt
Closes #2650 
Fixes Earlymanga and at least one other source using xhr but may have to revisit and tweak this if other sources have different css or a different requestbody.
=> Madara - xhr chapters

src/all/madara/build.gradle, src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/Madara.kt, src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2653
Also: 
More Madara sources are using different attributes for thumbnail URLs.  I'd initially intended to fix sources as needed but I changed my mind and think a blanket approach will be better.
Updated Hiperdex's URL.
=> Madara - chapters, thumbnails

src/pt/unionmangas/build.gradle, src/pt/unionmangas/src/eu/kanade/tachiyomi/extension/pt/unionmangas/UnionMangas.kt
To those who update: Union Mangás is now under the *Português (Brasil)* category at *Sources*.
=> Update language and old manga url at Union Mangás

src/pt/mangahost/build.gradle, src/pt/mangahost/src/eu/kanade/tachiyomi/extension/pt/mangahost/MangaHost.kt
Also fix #2583 by changing the URLs in popular and latest to the same used in the search. 
Unfortunately, users will have to re-add their mangas in the library (or migrate to the same source) to update to the new URL used if they want that their library mangas are marked as added in the listing. The old URL still works though.
=> Fix thumbnails not showing at MangaHost

src/ko/mangashowme/build.gradle, src/ko/mangashowme/src/eu/kanade/tachiyomi/extension/ko/mangashowme/ManaMoa.kt
* Update BaseUrl
* Fix page list empty error
- It's unknown reason but query selector is not working so it will search whole documents.
* Remove `?quick` for fix issue with externally hosted images.
- It is still used on site, but it's working without that query param.
=> Update Manamoa extension for Minor fixes, v1.2.20

src/en/mangahere/build.gradle, src/en/mangahere/src/eu/kanade/tachiyomi/extension/en/mangahere/Mangahere.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2689
Applies logic that fixed mangahere's webtoons to manga as well.
=> Mangahere - fix pages

src/all/foolslide/build.gradle, src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/FoolSlideFactory.kt
Fixes #2768  
It seems like FoolSlide has a (rather barebones) API available, but it's mostly useful for chapter pages since you'd otherwise have to source an ID for the series. 
Technically, the overrides would work in the main `FoolSlide` class, but there are some edge cases where sites don't properly set their chapter numbers correctly, causing the call to fail. I haven't seen any chapters on JB that suffer from this, so I've kept the API usage localized to that extension.
=> JB page list fix.

src/all/mangabox/build.gradle, src/all/mangabox/src/eu/kanade/tachiyomi/extension/all/mangabox/MangaBox.kt, src/all/mangabox/src/eu/kanade/tachiyomi/extension/all/mangabox/MangaBoxFactory.kt
I'd been avoiding it because I thought it might cause confusion but I think at this point it's confusing people regardless.
Also:
* closes https://github.com/inorichi/tachiyomi-extensions/issues/2804
* scanlator field now shows chapter's host name; so if you're using kakalot but it's really hosted on nelo you'll see manganelo.com in the scanlator field.
* removed old Chapter Manga code (can always find it again later if necessary)
=> MangaBox - add Mangakakalots

src/en/readcomiconline/build.gradle, src/en/readcomiconline/src/eu/kanade/tachiyomi/extension/en/readcomiconline/Readcomiconline.kt
Also, images were being requested without headers; so that was probably less than helpful.  Hopefully closes https://github.com/inorichi/tachiyomi-extensions/issues/1500 and https://github.com/inorichi/tachiyomi-extensions/issues/1193
Removed author filter because it seems like the site doesn't have that option anymore, closes https://github.com/inorichi/tachiyomi-extensions/issues/1851
=> ReadComicOnline - refactor pageListParse

src/all/mangabox/build.gradle, src/all/mangabox/src/eu/kanade/tachiyomi/extension/all/mangabox/MangaBox.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2840
Also throws an exception message "Source URL has changed" when refreshing manga details or chapter list of a manga that Kakalot's made a new entry for.
=> MangaBox - redirect check, selectors

src/es/mangamx/build.gradle, src/es/mangamx/src/eu/kanade/tachiyomi/extension/es/mangamx/MangaMx.kt
Manga-mx.com uses Cloudflare.
Using the Cloudflare client makes it usable again.
=> MangaMx Cloudflare fix

CONTRIBUTING.md
Corrected "at the expensive of" to "at the expense of" in the contributing guidelines.
=> Resolving spelling error

src/en/mangahub/build.gradle, src/en/mangahub/src/eu/kanade/tachiyomi/extension/en/mangahub/Mangahub.kt
This fixes alternative names and labels like Hot or New being appended to the manga title.
=> Mangahub - fix title

src/en/tapastic/build.gradle, src/en/tapastic/src/eu/kanade/tachiyomi/extension/en/tapastic/Tapastic.kt
Users can change their configuration to show all chapters or only the ones that are free and currently available (not slated to release at a future date).
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3080
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1165
=> Tapas - filter future releases

src/all/madara/build.gradle, src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
It would seem that Hiperdex has changed from Hiperdex.com to Hiperdex.info (which has made the source unusable.
Fixes #3100
=> Change Hiperdex url

src/en/tapastic/build.gradle, src/en/tapastic/src/eu/kanade/tachiyomi/extension/en/tapastic/Tapastic.kt
To be honest, I can't be 100% sure this works. The URLs are being set now for paid chapters; so if a user logs in, has paid for the chapters, and sets the extension's preferences, in theory they may be able to read those locked chapters.  I'm not paying for chapters to verify though.
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3197
=> Tapas - refactor chapter list

src/pt/hipercool/build.gradle, src/pt/hipercool/src/eu/kanade/tachiyomi/extension/pt/hipercool/Hipercool.kt
The PR #3191 will cause an error with the removal of two `.toString()` calls in Hipercool, so I decided to refactor the extension and use proper methods to take some data from the chapter URL instead of using RegEx.
=> Refactor the HiperCool extension

src/all/mangadex/build.gradle, src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
Verified that the 'server' value that gets returned with 'saver=1' is `mangadex.org/data-saver/` and that it remains the default `mangadex.org/data/` with 'saver=0'
=> [Mangadex] Add Data saver option to ext preferences

src/all/foolslide/build.gradle, src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/FoolSlideFactory.kt
Closes #3373.
The PR #3230 changed the source URL to a wrong one that isn't a Foolslide instance.
=> Change BaixarHentai URL to the old one

src/en/madokami/build.gradle, src/en/madokami/src/eu/kanade/tachiyomi/extension/en/madokami/Madokami.kt
All minor changes. Added a more helpful error when encountering status code 401 directing users to extension settings, made latestUpdate functions throw unused Exceptions, and made a tiny correctness change for requesting manga details.
=> Madokami cleanup

src/all/mangaplus/build.gradle, src/all/mangaplus/src/eu/kanade/tachiyomi/extension/all/mangaplus/MangaPlus.kt, src/all/mangaplus/src/eu/kanade/tachiyomi/extension/all/mangaplus/MangaPlusApi.kt, src/all/mangaplus/src/eu/kanade/tachiyomi/extension/all/mangaplus/MangaPlusFactory.kt
- Possible fix to missing `viewCount` field error, now it has a default value;
- Change the source name to match the official service name, overriding the `id`;
- Change the way that authors are displayed to match the latest UI change in the preview version;
- Add missing `nonAppearanceInfo` field to Duktape parsing.
=> Minor fixes for MangaPlus extension

src/en/mangamutiny/build.gradle, src/en/mangamutiny/src/eu/kanade/tachiyomi/extension/en/mangamutiny/MangaMutiny.kt
Some thumbnails and manga descriptions aren't maintained by the website.
This results in avoidable errors. Fixed with this commit.
=> MangaMutiny - JsonNull fix

build.gradle, src/zh/manhuagui/build.gradle, src/zh/manhuagui/src/eu/kanade/tachiyomi/extension/zh/manhuagui/Manhuagui.kt
Manga thumbnail and R18+ manga issues mentioned in https://github.com/inorichi/tachiyomi-extensions/issues/3546, https://github.com/inorichi/tachiyomi-extensions/issues/1791, https://github.com/inorichi/tachiyomi-extensions/issues/1759, https://github.com/inorichi/tachiyomi-extensions/issues/1623 and https://github.com/inorichi/tachiyomi-extensions/issues/1441 are fixed. I also added PreferenceScreen for Simplified/Traditional Chinese version website switch and show R18+ content switch. But I still got ban IP issue sometimes, not sure it's cause by client bugs or Manhuagui's server policy.
=> Fix Manhuagui manga thumbnail, added ability to parse more manga details and view R18+ manga.

src/en/vizshonenjump/build.gradle, src/en/vizshonenjump/src/eu/kanade/tachiyomi/extension/en/vizshonenjump/VizShonenJump.kt
Previously the Viz thumbnails were getting set to a placeholder image in the static HTML rather than the actual thumbnail image that was placed once the page loaded through javascript. This has been fixed.
Resolves #3567.
=> Fix Viz thumbnails

src/all/myreadingmanga/build.gradle, src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt
Fixes page selector for My Reading Manga
--
My Reading Manga stopped working and it seems like they have stopped using the lazy loader extension. I think this happened before in the history of the site so I'm not sure if they are just updating the plugin or not. 
This is a quick page update to account for the current change so I'm not sure if you want to merge this yet. 
If you do, we can update it if and when the owners load a lazy loader plugin back onto the server.
=> MRM - Update Page Selector

src/all/mangaplus/build.gradle, src/all/mangaplus/src/eu/kanade/tachiyomi/extension/all/mangaplus/MangaPlus.kt
The old "High resolution" now is displayed as "Medium resolution" (value: "high") and links "High resolution" with the new added value: "super_high".
Also, set "High resolution" (super_high) as default.
=> Add "super_high" resolution to Mangaplus

src/all/myreadingmanga/build.gradle, src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3707
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3250
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2997
There's now a filter checkbox titled "Enforce language" set to true by default. While true, search results are from a single language; while false (unchecked) all languages will show up in results.
Regarding incorrect scanlator groups: it's actually too troublesome to correct for too little gain. I've removed it from chapter info and made it it part of the manga description instead.
Covers should work better on refresh/import.
=> MyReadingManga - some refactoring, added language filter

src/all/madara/build.gradle, src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/Madara.kt, src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt, src/all/wpcomics/build.gradle, src/all/wpcomics/src/eu/kanade/tachiyomi/extension/all/wpcomics/WPComicsFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3769
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3761
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3743
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3716
References https://github.com/inorichi/tachiyomi-extensions/issues/3759
* Adds ToonPoint and Manga-Scantrad
* Moves Manhua Plus from WP Comics to Madara
* Fixes Manga68
* Removes Plot Twist No Fansub (their old site doesn't work and the new one doesn't use Madara)
=> Madara - update sources, annex Manhua Plus from WP Comics

src/all/ehentai/build.gradle, src/all/ehentai/src/eu/kanade/tachiyomi/extension/all/ehentai/EHentai.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3802
Strict language enforcement is optional now, by default it's off. So while it's off, browse and search results should be what they were a version or two ago. It can be toggled in preferences if you want it always on/off or can be used as a filter in search if you want to change it for one-off searches\.
"Misc" tags are a more complete list now. Some tags may be ExHentai only, didn't bother filtering them out.
=> EHentai - add language preference

src/en/comicpunch/build.gradle, src/en/comicpunch/src/eu/kanade/tachiyomi/extension/en/comicpunch/Comicpunch.kt
Comicpunch removed the "div#chapterlist" element from their pages, and didn't have a consistent replacement looking across a few comics, so I just took it out in favor of just using li.chapter.
For pages, they are now stored as an array of urls within a script tag instead of being all loaded by default like before.
=> Comicpunch - fix chapters and pages not loading

src/all/wpcomics/build.gradle, src/all/wpcomics/src/eu/kanade/tachiyomi/extension/all/wpcomics/WPComicsFactory.kt
Fixes the search on ComicLatest as per https://github.com/inorichi/tachiyomi-extensions/pull/3790#issuecomment-660398990. Also, added the ability to search by author via a text filter. 
NOTE: author search must match the author's name exactly (case-insensitive).
=> Comic latest

src/pt/goldenmangas/build.gradle, src/pt/goldenmangas/src/eu/kanade/tachiyomi/extension/pt/goldenmangas/GoldenMangas.kt
Also adds `Accept` and `Accept-Language` to the headers. This should prevent in most cases the Cloudflare captcha page, if it appears, to get stuck in a loop.
Should close #3868.
=> Update GoldenMangas url

src/all/madara/build.gradle, src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes #3873.
Probably the images weren't loading because of the empty `Referer` header.
=> Fix pages not loading at YaoiToshokan

src/zh/manhuagui/build.gradle, src/zh/manhuagui/src/eu/kanade/tachiyomi/extension/zh/manhuagui/Manhuagui.kt
Removing the backslash to escape '\\}', which Android studio suggest to remove them as redundant will cause regexp error. Details in #3925, #3924. The weird thing is I can't reproduce this error in kotlin running on Windows JDK 8 and 11.
Also, fixed manga.genre format in mangaDetailsParse() to display multiple genre separately.
=> <Manhuagui>: <regexp syntax error> Add the backslashes to escape '\}' back.

src/pt/mangasproject/build.gradle, src/pt/mangasproject/src/eu/kanade/tachiyomi/extension/pt/mangasproject/MangasProject.kt
The check if the manga is licensed prevents the chapter list API from being called when it's not supposed, simulating the behavior of the website.
=> Fix unacessible chapters showing when the manga is licensed at LeitorNet

src/all/mangaplus/build.gradle, src/all/mangaplus/src/eu/kanade/tachiyomi/extension/all/mangaplus/MangaPlus.kt
Now the extension saves all the titles from the response in an internal list. 
With an additional interceptor, if the requested thumbnail is expired (returned `401` or `404`) it uses the saved title list (that contains all the titles from the service) to find and return the newer thumbnail URL with the most updated `key`, making the thumbnail load properly (at browse, latest, and search).
I tested on my physical device where all the mangas outside my library did have broken thumbnails, and all of them loaded and appeared again. :)
I also removed the Weserv usage.
=> Fix broken thumbnails after expiration time at MangaPlus

src/zh/manhuagui/AndroidManifest.xml, src/zh/manhuagui/build.gradle, src/zh/manhuagui/src/eu/kanade/tachiyomi/extension/zh/manhuagui/Manhuagui.kt, src/zh/manhuagui/src/eu/kanade/tachiyomi/extension/zh/manhuagui/ManhuaguiRateLimitInterceptor.kt, src/zh/manhuagui/src/eu/kanade/tachiyomi/extension/zh/manhuagui/ManhuaguiUrlActivity.kt
I'm getting IP ban by Manhuagui every time I update my library. So I separate the ratelimit for main website (with aggressive request limit) and image CDN and add preferences to config them.
=> <Manhuagui> Add ratelimit permits preferences and intent filter

src/en/mangamutiny/build.gradle, src/en/mangamutiny/src/eu/kanade/tachiyomi/extension/en/mangamutiny/MangaMutiny.kt
- fixed Genre parsing (website renamed "genres" to "tags" in their json responses)
- corrected chapter release year parsing
- increased manga list fetch size from 20 to 21 to make requests that are almost indistinguishable from requests the real website makes (only URI parameter order differs)
- split Genre filter into Genre and Format filter to be more in line with what the website offers
- updated Genre/Format filter content
- implemented new way to process URI query parameters (first collect them in a mutable list, then add them to the URI)
- added author/artist search (and prepared for scanlator search, although that feature doesn't work yet even on the website)
=> Multiple MangaMutiny fixes/additions

.travis/create-repo.sh, AndroidManifest.xml, CONTRIBUTING.md, common.gradle, src/all/nhentai/build.gradle
Works towards https://github.com/inorichi/tachiyomi/issues/1312
---
Extension is listed as NSFW:
```json
{
"name": "Tachiyomi: NHentai",
"pkg": "eu.kanade.tachiyomi.extension.all.nhentai",
"apk": "tachiyomi-all.nhentai-v1.2.27.apk",
"lang": "all",
"code": 27,
"version": "1.2.27",
"nsfw": 1
},
```
And example of non-flagged extension:
```json
{
"name": "Tachiyomi: Mangasee",
"pkg": "eu.kanade.tachiyomi.extension.en.mangasee",
"apk": "tachiyomi-en.mangasee-v1.2.12.apk",
"lang": "en",
"code": 12,
"version": "1.2.12",
"nsfw": 0
},
```
---
Tested locally on my Mac.
Note that you must install `bash` and GNU `grep` (i.e. `ggrep`) via homebrew to run the build scripts properly.
=> Add ability to flag extension as NSFW

annotations/src/main/kotlin/Nsfw.kt, common.gradle, src/all/madara/build.gradle, src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Allows more granular flagging within multi-source extensions.
App should be able to have different levels of managing NSFW sources, e.g.:
- Everything allowed
- Block loading sources annotated with `@Nsfw`, but still showing extensions flagged with `containsNsfw` within the extensions list; useful for things like Madara
- Block extensions flagged with `containsNsfw`, i.e. hidden from extensions list and block loading its sources even if installed
=> Add ability to flag individual sources as NSFW

src/en/guya/build.gradle, src/en/guya/src/eu/kanade/tachiyomi/extension/en/guya/GuyaUrlActivity.kt
The url fragments can have more than 3 items. 
Tested locally, confirmed working.
=> Fix guya URL activity.

src/ko/newtoki/build.gradle, src/ko/newtoki/src/eu/kanade/tachiyomi/extension/ko/newtoki/NewToki.kt
v1.2.13
====
* Fix page list empty issue on old mangas in `.net` domain
- This caused by chapter has 3 divs to access it. recent Chs are only have 2 div btw.
* Fix thumbnail on detail page.
-----
Hello, long time no see.
Manamoa is currently down. but seems... more like _taken down_ now.
I didn't managed korean extensions except for manamoa. Even created by myself
As i'm fan of manga and Manamoa was great korean translation source for it.
When i didn't managing this extension, many people who loves webtoon(manhwa, on `.com` domain) still maintaining this one.
But as there's many alternative sources about manga, the manga side is bit broken(The site not changed much... so it worked)
...
just in short word, For now, Manamoa is down, And I will maintain this extension again.
=> Fix issue with old manga on Newtoki's .net domain + thumbnails

src/all/myreadingmanga/build.gradle, src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt
I was having trouble bypassing the captcha in webview. 
This switches Headers.Builder() to super.headersBuilder() to inherit existing headers such as user agent.
=> MRM - Use super in headersbuilder

src/ko/newtoki/build.gradle, src/ko/newtoki/src/eu/kanade/tachiyomi/extension/ko/newtoki/NewToki.kt, src/ko/newtoki/src/eu/kanade/tachiyomi/extension/ko/newtoki/NewTokiFactory.kt
v1.2.14
=====
* Site name/domain changes
- ManaMoa merged into NewToki's manga side. calls ManaToki.
- Site wasn't not changed too hard so decided to keep old site ids.
* Fix issue with pages with optional \<p\> tags
* Search Filter on ManaToki side
- The site doesn't support title search with filter. It runs separately  
----
nah idea's new ui is too complicated to me
The site is very unstable on title name search now.
=> Update Newtoki Extension v1.2.14

src/en/mangafast/build.gradle, src/en/mangafast/src/eu/kanade/tachiyomi/extension/en/mangafast/MangaFast.kt
Fixes #4346
MangaFast introduced the concept of teaser chapters and placeholders for upcoming chapters. These do not have a proper date and previously led to a ParseException.
Ideally the extension would mark those chapters as teasers and in case of placeholders just skip them, but I couldn't think of a way to do so.
=> MangaFast: ignore unparseable dates

src/ko/newtoki/build.gradle, src/ko/newtoki/src/eu/kanade/tachiyomi/extension/ko/newtoki/NewToki.kt, src/ko/newtoki/src/eu/kanade/tachiyomi/extension/ko/newtoki/NewTokiFactory.kt
v1.2.15
=====
* Fix domain number again.
- It keeps jumping unusually.
* Initial ID support added for both side.
- The site search is *\*very\** unstable now so this would help.
- Note that ID is shares chapters too.
=> Update NewToki Extension v1.2.15

src/ko/newtoki/build.gradle, src/ko/newtoki/src/eu/kanade/tachiyomi/extension/ko/newtoki/NewToki.kt
Fix page list empty.
This will breaks old manga a bit but recent should ok.
=> Update NewToki Extension v1.2.18

src/all/komga/CHANGELOG.md, src/all/komga/build.gradle, src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/Komga.kt, src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/dto/Dto.kt
some collections could contain series with a pure String ID, but could not be deserialised properly, resulting in an empty list of collections in the filter panel
=> [Komga] fix for collections in filter not always working

src/all/lanraragi/build.gradle, src/all/lanraragi/src/eu/kanade/tachiyomi/extension/all/lanraragi/LANraragi.kt
Uses new search, extract, and thumbnail endpoints.
extract endpoint now uses POST instead of GET.
If an API key is provided it is base64 encoded and added to the headers.
Fixes #4278
=> LANraragi: Update to API 0.7.2

src/all/ninehentai/build.gradle, src/all/ninehentai/src/eu/kanade/tachiyomi/extension/all/ninehentai/NineHentai.kt
=> Update domain from 9hentai.com to .ru

src/all/mangaplus/build.gradle, src/all/mangaplus/src/eu/kanade/tachiyomi/extension/all/mangaplus/MangaPlus.kt, src/all/mangaplus/src/eu/kanade/tachiyomi/extension/all/mangaplus/MangaPlusApi.kt
Closes #4722.
The kotlinx.serialization now is only used if the device's Android version is at least Nougat, since the library eventually always have some problems with these devices.
I also have updated the kotlinx.serialization to the newer version available.
I have tested on Nougat (preview and stable) and Android 10 (preview).
=> Fix kotlinx.serialization issue on MANGA Plus

src/it/novelleleggere/build.gradle, src/it/novelleleggere/src/eu/kanade/tachiyomi/extension/it/novelleleggere/NovelleLeggere.kt
Small fix to pageListParse selector to ignore <noscript> img duplicate
=> NovelleLeggere - fixing duplicated page images

src/all/webtoons/build.gradle, src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/WebtoonsFactory.kt
- fix webtoon indonesia not appear in indonesia language, instead create another indonesia language
- replace hardcode date-format (indonesia)
*need to migrate after update, since the source from "fake" "indonesia" will disappear. "moved for the better future"
=> Webtoon - Indonesia update

src/all/webtoons/build.gradle, src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/WebtoonsFactory.kt
it seems normal dateFormat doesnt work in some cases(android/device/android lower than 10/other cause)
Closes #4992
=> Webtoon(ID) revert removed harcode date-parse

src/en/hentainexus/build.gradle, src/en/hentainexus/src/eu/kanade/tachiyomi/extension/en/hentainexus/HentaiNexus.kt
Reworked image loading functions to simply use the normal urls instead of deobfuscating a string. Now using same system as HentaiFox. Fixes https://github.com/inorichi/tachiyomi-extensions/issues/5022
Should probably be more maintanable now.
=> Fixed imageloading again

src/pt/tsukimangas/build.gradle, src/pt/tsukimangas/src/eu/kanade/tachiyomi/extension/pt/tsukimangas/TsukiMangas.kt
Closes #5050.
Existing mangas in library will have to be migrated (from Tsuki to Tsuki) to update the URL.
=> Update manga and API endpoints at Tsuki

src/en/dilbert/build.gradle, src/en/dilbert/src/eu/kanade/tachiyomi/extension/en/dilbert/Dilbert.kt
Closes #4634 
With the previous method "https" was added to the image url.
Now that method adds another "https" before the https of the url (they have probably updated their website) which makes the url invalid.
=> Dilbert: Fix (#4634)

CONTRIBUTING.md
additional info:
mangadex api gives time in epoch format but we are multiplying it by 1000
ref: https://github.com/inorichi/tachiyomi-extensions/blob/bb131790df4adfac5dd788eb1363fa30a3696f53/src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDex.kt#L540-L541
=> [CI SKIP] date_upload is in miliseconds

src/zh/wnacg/build.gradle, src/zh/wnacg/src/eu/kanade/tachiyomi/extension/zh/wnacg/wnacg.kt
Seems they reversed the data-original attribute to src
View previous PR #4489 
Closes #4369 
Closes #4388
=> Fix WNACH thumbnails not loading

src/all/eromuse/build.gradle, src/all/eromuse/src/eu/kanade/tachiyomi/extension/all/eromuse/EroMuse.kt, src/all/eromuse/src/eu/kanade/tachiyomi/extension/all/eromuse/EroMuseFactory.kt
> **TLDR**: (#5241) I was trying to add [this](https://comics.8muses.com/comics/album/Fakku-Comics/E-musu-Aki/Parallel-World-ErosSwine-Finale) to my library but was not able to since it was being parsed as a chapter of its [parent](https://comics.8muses.com/comics/album/Fakku-Comics/E-musu-Aki/). Seemed odd to me since the parent folder was acting more like an artist-filter instead of a manga by itself. This PR improves searching and other shit in the EroMuse extension.
The problems are described with examples here: #5237, #5238, #5241.
`VARIOUS_AUTHORS`: An album that holds `AUTHOR` albums, usually grouped by organization or source-specific collection scheme eg. [fakku](https://comics.8muses.com/comics/album/fakku-comics)
`ARTIST:` An album that holds `MANGA` albums made by an artist, …
=> Improve searching for EroMuse sources with support for nested albums

src/ko/newtoki/build.gradle, src/ko/newtoki/src/eu/kanade/tachiyomi/extension/ko/newtoki/ManaToki.kt, src/ko/newtoki/src/eu/kanade/tachiyomi/extension/ko/newtoki/NewToki.kt, src/ko/newtoki/src/eu/kanade/tachiyomi/extension/ko/newtoki/NewTokiFactory.kt
Mitigation about IP Ban by bunch of request on latest on manatoki.
--------------------------------------------------------------------------
RateLimit, And make default to not make bunch of request.
Split ManaToki into separate file as it became bigger.
More rate limit
-----------------
NewToki and ManaToki Shares IP bans.
Also when refresh the batch of mangas, It could be banned too. 
So rate limit on ChapterList and MangaDetail request too. (And apply both of them)
=> Update NewToki Extension to v1.2.19

src/all/webtoons/build.gradle, src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/WebtoonsFactory.kt
Adds Spanish and Spanish Translation to Webtoons extension.
Closes #5396
=> Add Spanish and Spanish Translation to Webtoons

src/en/doujins/build.gradle, src/en/doujins/src/eu/kanade/tachiyomi/extension/en/doujins/Doujins.kt
Fixes:
1. Chapter upload date not parsed for certain mangas that have requester details due to incorrect selector
2. Fetching latest page incorrectly uses local timezone instead of UTC
3. Tags not parsed for mangas from search or popular page
=> Various Doujins ext fixes

src/en/pururin/build.gradle, src/en/pururin/src/eu/kanade/tachiyomi/extension/en/pururin/Pururin.kt
1. Add support for collections i.e. multi-series mangas
2. Removes redundant information from description: title and tags
3. Adds other information to description: circle, category, character and language
4. Adds scanlator to manga attributes if available
=> Add support for collections and refactor manga description for Pururin ext

src/en/hentai2read/build.gradle, src/en/hentai2read/src/eu/kanade/tachiyomi/extension/en/hentai2read/Hentai2Read.kt
1. Adds alternative title to description (Japanese and other alt title)
2. Adds Parody, Page count, Characters and Language to description
=> Add more content to hentai2read ext manga description

src/id/komiku/build.gradle, src/id/komiku/src/eu/kanade/tachiyomi/extension/id/komiku/Komiku.kt
This update fixed problem on komiku that can't go into chapter when opened from searching. It seems that komiku.id change behavior of searching. Instead of page "cari" on the web, they use page "pustaka" now for manga list and also searching
=> Fix cannot open chapter after searching

src/all/lanraragi/build.gradle, src/all/lanraragi/src/eu/kanade/tachiyomi/extension/all/lanraragi/LANraragi.kt, src/all/lanraragi/src/eu/kanade/tachiyomi/extension/all/lanraragi/model/Category.kt
Filters and pagination manipulation.
Latest now works as intended with accompanying new preferences.
API usage change to use its metadata endpoint and preserve WebView.
Categories are fetched from the server on `init {}` in a similar fashion to Komga.
=> LANraragi: Filters, Latest, misc API.

src/all/lanraragi/build.gradle, src/all/lanraragi/src/eu/kanade/tachiyomi/extension/all/lanraragi/LANraragi.kt
It was possible to get a null into the function and the following split() did not like it.
=> LANraragi: Safer tag parsing.

src/zh/dmzj/build.gradle, src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt
1. Delete redundant url replace rule: https://github.com/tachiyomiorg/tachiyomi-extensions/pull/5502#issuecomment-764735616
2. Get HD comic images instead of compressed ones in v3api.
=> <zh-dmzj> Fix url replace rule and parse HD images in v3api.

src/en/doujins/build.gradle, src/en/doujins/src/eu/kanade/tachiyomi/extension/en/doujins/Doujins.kt
Premium content access via login is not yet supported for this extension. This fix excludes premium items from being included in search results.
=> Exclude premium items from search results

src/ar/gmanga/build.gradle, src/ar/gmanga/src/eu/kanade/tachiyomi/extension/ar/gmanga/Gmanga.kt, src/ar/gmanga/src/eu/kanade/tachiyomi/extension/ar/gmanga/GmangaCryptoUtils.kt
Fixes #5331
- Uses `android.util.Base64` now which is available for lower API levels (thanks to @alimamahmoud for reporting and for the suggested fix)
Reverts #5497
- The previous URL was still fine, just that items without thumbnails were not handled properly hence the `JSON Null` error. Changing to `/release` doesn't make it work either and will require different parsing logic. This reverts that PR and adds handling for items with `null` thumbnails.
=> Fix GManga Latest page error and crashing on older devices

src/fr/japscan/build.gradle, src/fr/japscan/src/eu/kanade/tachiyomi/extension/fr/japscan/Japscan.kt
The search on japscan is buggy (does not return any items anymore), adding a fallback to duckduckgo
=> Add fallback on search to duckduckgo

src/ru/libmanga/build.gradle, src/ru/libmanga/src/eu/kanade/tachiyomi/extension/ru/libmanga/LibManga.kt
When the manga was opened, the original name from the catalog changed to an alternate one.
=> [Ru]Fix Mangalib conflicting directory names and manga details (J2K)

src/pt/unionmangas/AndroidManifest.xml, src/pt/unionmangas/build.gradle, src/pt/unionmangas/src/eu/kanade/tachiyomi/extension/pt/unionmangas/UnionMangas.kt
Entries in the library with the old URL will keep working, but the users can migrate from Union to Union to update the URL too.
=> Update manga details URL at UnionMangás

src/zh/pufei/build.gradle, src/zh/pufei/src/eu/kanade/tachiyomi/extension/zh/pufei/Pufei.kt
- Fix some pages (closes #4576): the latest chapter for one of the examples in the issue (氪金玩家) doesn't work on the site either, but this PR does fix the other example (魔王大人氪金中).
- Fix covers in manga list: covers weren't set when parsing manga list, so there were additional network calls that caused some time before all covers load
- Fix some covers in manga details: host in cover URLs was replaced to `http://i.youzipi.net/` that worked only when URL already uses this host. When URL uses another host - covers were broken
- Show author
=> Pufei: fix some pages, fix some covers, show author

src/all/toomics/build.gradle, src/all/toomics/src/eu/kanade/tachiyomi/extension/all/toomics/ToomicsGlobal.kt
Closes #4959
- New links to popular and latest
- Fix thumbnails in browse
- Fix sometimes no chapters found due to `/ab/on` at the end that redirects to a chapter instead of manga page
- Don't filter out chapters that user already have read
- Fix chapter names displaying only number
- Show corresponding error when a chapter requires age confirmation
- Fix pages not loading
=> Toomics: various fixes

src/ko/newtoki/build.gradle, src/ko/newtoki/src/eu/kanade/tachiyomi/extension/ko/newtoki/ManaToki.kt, src/ko/newtoki/src/eu/kanade/tachiyomi/extension/ko/newtoki/NewToki.kt, src/ko/newtoki/src/eu/kanade/tachiyomi/extension/ko/newtoki/NewTokiFactory.kt
* Preference: Rate Limit Period added. (also closes #5934)
- Default is 2. can reduce to 1 or increase to 9 as you want.
- Since their system is bit weird. I didn't got ban on 1 sec, but #5934 says he got banned.
- By this change, Default Rate Limit is 1 request per 1 second.
* Specify a default sort filter's setting.
- Site says it's just default btw.
* Temp fix about uri parsing error (closes #5657)
- This was not extension fault. According to [RFC 3986](http://www.ietf.org/rfc/rfc3986.txt), Square bracket is not allowed on uri path.
=> Update NewToki extension to v1.2.21

src/en/keenspot/build.gradle, src/en/keenspot/src/eu/kanade/tachiyomi/extension/en/keenspot/TwoKinds.kt
Closes #5191
It **will** create orphaned downloads for those, who already downloaded. Those users will need to rename the folder by removing the colon and restart the app after this.
But, it will fix downloads for those, who couldn't download because of the colon, e.g. #5191.
=> Keenspot TwoKinds: Remove colon from source name to avoid downloading problems

src/id/komiku/build.gradle, src/id/komiku/src/eu/kanade/tachiyomi/extension/id/komiku/Komiku.kt
if manga title contains number, it can cause issue to tracking
=> Komiku: remove manga title in chapter name

src/fr/mangakawaii/build.gradle, src/fr/mangakawaii/src/eu/kanade/tachiyomi/extension/fr/mangakawaii/MangaKawaii.kt
- Fixes popular URL manga
- Fixed image selector isolate manga pages causing the download process to stall / fail 
Closes #5985
=> MangaKawaii: Basic function fixes

src/en/comicextra/build.gradle, src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt
Resolves #5947
- Switch to recursive fetching to ensure all pages are processed
=> ComicExtra: Recursively fetch chapters

src/en/readmanhwa/build.gradle, src/en/readmanhwa/src/eu/kanade/tachiyomi/extension/en/readmanhwa/ReadManhwa.kt
- Use popular for all time instead of week. Closes #5765. Why it didn't work before: the site itself doesn't have results for popular by week that was used by default in the extension. Why switching nsfw flag fixed it: changing filter caused to apply all parameters from filter, where order by date for all time is used by default.
- Remove repeated `order` parameter.
- Fix some warnings in lines 139-145
=> ReadManhwa: use popular for all time instead of week, minor changes

src/all/komga/CHANGELOG.md, src/all/komga/build.gradle, src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/Komga.kt, src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/dto/Dto.kt
This changes the way to browse collections. Before, one could select one or more collections to filter series, but that would show Series without respecting the collection's ordering.
Now the filter panel will show a dropdown list for collections, and only a single collection can be selected. The series shown will respect the collection's ordering.
---
This also adds a filter to choose searching for Series or Read Lists. If you choose Read Lists, it will show all read lists, and read lists can be browsed liked a series. They will display the list of books inside the read list, respecting the read list's ordering.
=> [Komga] browse read lists and collections

src/en/mangamutiny/build.gradle, src/en/mangamutiny/src/eu/kanade/tachiyomi/extension/en/mangamutiny/MangaMutiny.kt
- WebView now works (main page + pages of individual manga)
- changed baseUrl to https://mangamutiny.org and moved https://api.mangamutiny.org to different variable
(the extension still relies on the lightweight json responses from the API for everything that isn't WebView related - the baseUrl only had to be changed for WebView to work)
- fixed pagination bug (would previously skip 21 manga after the first 21 manga, now fixed)
- Internally reworked filters to make them compatible with the WebView changes (does not affect users in any way)
=> MangaMutiny: WebView + pagination fix

src/ru/libmanga/build.gradle, src/ru/libmanga/src/eu/kanade/tachiyomi/extension/ru/libmanga/LibManga.kt
Closes #5933
`response.isRedirect` didn't work for some reason and also there is a chance that it would redirect to correct manga page, so I did it with a selector
=> MangaLib: notify user when manga redirects to home page

src/en/mangamainac/build.gradle, src/en/mangamainac/src/eu/kanade/tachiyomi/extension/en/mangamainac/MangaMainac.kt
- filter unreleased chapters (the same as in #6050)
- update two URLs (old manga in library will still work with http or redirect)
No opened issues
Side note for future: `The Promised Neverland` and `The Quintessential Quintuplets` sites are down, I couldn't find new links to them and if they will remain like this for long time, they should be removed
=> MangaMainac: filter out latest chapter if it's not released yet, update URLs

src/all/mango/build.gradle, src/all/mango/src/eu/kanade/tachiyomi/extension/all/mango/Mango.kt
Would crash on startup if the address field is empty since it has zero length so you can't get a `.last()`.
=> Fixed crash on startup when host address is empty

src/en/mangalife/build.gradle, src/en/mangalife/src/eu/kanade/tachiyomi/extension/en/mangalife/MangaLife.kt
This PR changes how chapter number is shown in MangaLife
chapterRegex was taken from MangaSee extension code (which share most of their code already)
Have been using the extension for some time and its working fine
| before | after |
|----|---|
| "Chapter 0142" | "Chapter 142" |
| ![Screenshot_1614798631](https://user-images.githubusercontent.com/72807749/110000456-4f2eb100-7d39-11eb-86f5-3bef13f34f87.png) | ![Screenshot_1614803771](https://user-images.githubusercontent.com/72807749/110000460-50f87480-7d39-11eb-87b2-63cc43a34fbe.png) |
=> fix Mangalife chapter numbers

src/en/guya/build.gradle, src/en/guya/src/eu/kanade/tachiyomi/extension/en/guya/Guya.kt
The use-case is niche (especially since many of the proxied sites have Tachi extensions already), but we're hosting a Kaguya re-read event on the Kaguya Discord, and we'll be using our proxy to time the weekly releases [here](https://guya.moe/proxy/gist/Kaguya-Reread/). This PR adds support for the proxy using search with the schema of `proxy:<source>/<slug>`.
For example, `proxy:gist/Kaguya-Reread` for the above. Our proxy also supports Imgur, so, for example, `proxy:imgur/2FzJ0Y9` works. This might address #5631, but the functionality is rather nested.
=> Add support for Guya proxy.

src/all/lanraragi/build.gradle, src/all/lanraragi/src/eu/kanade/tachiyomi/extension/all/lanraragi/LANraragi.kt
- Adds a "Random" entry to popular's MangasPage, assuming nothing else prevents it.
- Clears an archive's new status on the server similar to two versions ago before moving to API endpoints.
- The web reader happened to be taking care of it
=> LANraragi: Random item, clear new status

CONTRIBUTING.md
for scaffold: 
If it's left empty, won't be picked up by git.
Just a small convenience util.
=> [SKIP CI] multiple changes

src/en/mangalife/build.gradle, src/en/mangalife/src/eu/kanade/tachiyomi/extension/en/mangalife/MangaLife.kt, src/en/mangasee/build.gradle, src/en/mangasee/src/eu/kanade/tachiyomi/extension/en/mangasee/Mangasee.kt
It won't work right now, but:
- Users will see why it doesn't work.
- It will work as soon as they stop blocking tachi (tested with current variable name). Here is the post where sites' owner tells about unblocking: https://mangasee123.com/discussion/post.php?id=9870704
=> MangaLife, MangaSee: revert temporary fixes, show error about blocking

src/en/mangamutiny/build.gradle, src/en/mangamutiny/src/eu/kanade/tachiyomi/extension/en/mangamutiny/MangaMutiny.kt
- Fix for #6149 (tested it with the Anilist tracker and chapters are tracked correctly with the changes of this PR)
- Sub-chapters (e.g. "1.0", "1.1", "1.2") are now recognizable by their chapter name
- closing some response bodies
Note: For mangas in the library users have to refresh the chapter lists once in order for the new chapter numbers to take effect. Performing a global update or updating the individual Manga Mutiny mangas should do the trick.
=> Manga mutiny: chapter number fix + closing responses

multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
the extensions was removed as per the scanlation site's request
Closes https://github.com/tachiyomiorg/tachiyomi-extensions/issues/6192
=> remove Gourmet Scans from Madara multisrc

multisrc/overrides/mangabox/mangairo/src/Mangairo.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangabox/MangaBoxGenerator.kt
- New search path. Closes #6202.
- Remove extra slash. It didn't cause any issues, but all links had 2 slashes after the domain.
=> Mangairo: new search path, remove extra slash

src/all/batoto/build.gradle, src/all/batoto/src/eu/kanade/tachiyomi/extension/all/batoto/BatoToFactory.kt
added en_us and unfiltered to language list
removed xh, hi and ku from language list
=> Updated Bato.to supported languages list

src/en/guya/AndroidManifest.xml, src/en/guya/build.gradle, src/en/guya/src/eu/kanade/tachiyomi/extension/en/guya/GuyaUrlActivity.kt
Adds intent filter for Guya proxy links, so one doesn't manually need to type for example `proxy:imgur/aigznZt`.
=> Add intent for Guya proxies

multisrc/overrides/wpmangastream/xcalibrscans/src/xCaliBRScans.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStreamGenerator.kt
- Fix pages, closes #6316.
- Use HTTPS instead of HTTP.
=> xCaliBR Scans: fix pages, use https

src/es/mangamx/build.gradle, src/es/mangamx/src/eu/kanade/tachiyomi/extension/es/mangamx/MangaMx.kt
Closes #6313.
Users need to clear database in advanced settings to reset broken covers.
=> MangaMx: fix covers

src/all/komga/CHANGELOG.md, src/all/komga/build.gradle, src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/Komga.kt
This will use the System DNS in the network client, effectively ignoring the DNS over HTTPS setting of Tachiyomi. DoH prevents reaching local IP addresses, since they cannot be resolved by the DNS.
Could also be used for Mango and Lanraragi.
=> [Komga] ignore dns over https

src/en/mangamutiny/build.gradle, src/en/mangamutiny/src/eu/kanade/tachiyomi/extension/en/mangamutiny/MangaMutiny.kt
- small change to make chapter numbers in chapter names lose trailing `.0`
- don't recreate the SimpleDateFormatter for every parsed chapter. Declaring and initializing it once is enough.
=> MangaMutiny: chapter number in chapter name improvement

src/fr/japanread/build.gradle, src/fr/japanread/src/eu/kanade/tachiyomi/extension/fr/japanread/Japanread.kt
* Fixed selectors not working that were copy/paste from another extension.
* Fixed search/latest next page
* Latest updates were latest added manga, replacing with latest manga with a chapter update
* Complete all available details for manga
* Complete all available details for chapters
=> Japanread: Fix issues + add more details to manga and chapters

src/all/batoto/src/eu/kanade/tachiyomi/extension/all/batoto/BatoTo.kt
CSS selector for release date was changed on bato.to
added scanlator support for bato.to 
Closes #6409
=> Bata.to fix date parsing and add scanlator support

multisrc/build.gradle.kts
As described here https://www.infoworld.com/article/2071275/when-runtime-exec---won-t.html under "Listing 4.2 BadExecJavac2.java" the limited buffer size of the standard input associated with the sub-process can cause problems with the Runtime exec method.
Consuming what the sub-process outputs allows for the process to finish (+ if you enable log level info you get some nice debug information).
I've tested this on my local machine (Linux), on the tachiyomi-extensions GitHub runner, improved upon it and tested it again on the tachiyomi-extensions GitHub runner and it worked fine.
What I can't test is how it behaves on Windows, it should be fine but if someone could check out my https://github.com/E3FxGaming/tachiyomi-extensions/tree/FixMultisourceGen branch on Windows and run `./gradlew …
=> Fix for the multi-sources not being generated properly

src/fr/japanread/build.gradle, src/fr/japanread/src/eu/kanade/tachiyomi/extension/fr/japanread/Japanread.kt
There was a mismatch between chapter number and chapter id, resulting in wrong chapter loaded.
It's a recently added source but I'm surprised no one noticed.
=> JapanRead: fix wrong chapter loaded

src/en/xkcd/build.gradle, src/en/xkcd/src/eu/kanade/tachiyomi/extension/en/xkcd/Xkcd.kt
closes #6370
Some xkcd comics tend to be interactive and can only be played in a regular browser
These cannot be loaded in the app and the reader loads indefinitely
Instead, we throw a text image with a message to open in browser
the div#comic img attribute will be null/empty in case of parsing interactive
comics and is then replaced with an image warning
uses [fakeimg.pl](https://fakeimg.pl/1500x2126/000000/ffffff/?text=To%20experience%20the%0Ainteractive%20version%20of%20this%20comic%0Aopen%20it%20in%20WebView/browser&font_size=42&font=museo) to generate image from text
Apk tested on 0.10.9 with examples from the linked issue 
| Screenshot |
|--|
| ![Screenshot_20210408-175049](https://user-images.githubusercontent.com/72807749/114025805-272ff180-9893-11eb-818a-ff85fc363e57.png) |
=> handle interactive xkcd comics

src/en/catmanga/build.gradle, src/en/catmanga/src/eu/kanade/tachiyomi/extension/en/catmanga/CatManga.kt
This prevents manga entries without any new chapter from getting bumped to the top of "Latest chapter" list when the library is updated.
=> CatManga: Remember currentTimeMillis when a chapter is found for the first time

src/all/mangaplus/build.gradle, src/all/mangaplus/src/eu/kanade/tachiyomi/extension/all/mangaplus/MangaPlus.kt, src/all/mangaplus/src/eu/kanade/tachiyomi/extension/all/mangaplus/MangaPlusApi.kt, src/all/mangaplus/src/eu/kanade/tachiyomi/extension/all/mangaplus/MangaPlusFactory.kt
MANGA Plus started supporting more languages recently, but their API doesn't return the information correctly.
This PR adds an initial support to basic filtering of the languages while their API doesn't get an update to handle this.
There are only 3 titles in Portuguese at the moment (One Piece, Spy x Family and Jujutsu Kaisen). These titles have the Portugal flag in the thumbnail, but the text of the translations are in Brazilian Portuguese.
I also added support to the titles in Thai language.
Closes #6503.
=> Add initial support to more languages at MangaPlus

src/pt/mangahost/build.gradle, src/pt/mangahost/src/eu/kanade/tachiyomi/extension/pt/mangahost/MangaHost.kt
I also updated the URL of the titles to avoid (for a while) the HTTP 403.
Entries in the library should still work, but users can migrate from MH to MH to update the URLs if they want too.
=> Update MH url (again)

src/pt/mangahost/build.gradle, src/pt/mangahost/src/eu/kanade/tachiyomi/extension/pt/mangahost/MangaHost.kt
I also changed the HTTP 403 error to be more explicit about the blocking.
As I said (in Portuguese) in #6537, let's see if the more severe rate limiting unloads the server a while.
If it's not the case, I will then submit a new PR to end this cat and mouse game.
Closes #6537.
=> Make rate limiting apply to all requests in MH

src/pt/unionmangas/build.gradle, src/pt/unionmangas/src/eu/kanade/tachiyomi/extension/pt/unionmangas/UnionMangas.kt
It seems I was right on #6623, and it's really a cat and mouse game now.
If you are reading this and use the extension, it's recommended to migrate to another source.
I updated the selectors one last time, and added a message about the blocking that will show when they change things.
When this happens, I will leave the extension with the blocking message for a while and then submit a new PR to remove it, since it's not worthy anymore to keep maintaining. The users can migrate to better sources.
=> Update 'UM' selectors (again) and add a blocking message

src/pt/mangahost/build.gradle, src/pt/mangahost/src/eu/kanade/tachiyomi/extension/pt/mangahost/MangaHost.kt
The source seems to be changing constantly the classes to break the extension too.
I updated the selectors to the most recent ones and added a blocking message that will show when they change them again.
Users should have migrated from this source already, but unfortunately some still use the extension.
It's not worthy to keep maintaining this extension anymore.
=> Update selectors and show a blocking message if no results found

src/en/mangapark/build.gradle, src/en/mangapark/src/eu/kanade/tachiyomi/extension/en/mangapark/MangaPark.kt
Site updated, they still have a copy of legacy interface on a secondary url, this is a stand in for a redoing the scraper, only a temporary measure. 
Closes #6721
=> Changed url for mangapark extension

src/all/komga/CHANGELOG.md, src/all/komga/build.gradle, src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/Komga.kt
The URL was not fully set in the `SManga` object, it did not contain the base URL. This was meant to handle URL change in the extension settings, but probably wouldn't have worked given Tachiyomi stores SManga locally. Because of that, restoring from a backup would generate some errors because URL would be missing `http` or `https`. This will not help people with existing library though, they would need to edit the backup file manually to fix it.
This also uses the newly introduced API endpoint to only get Series tags for filtering. Before it was showing also book tags, but filtering on those would not yield any results.
=> [Komga] fix restoring backup & tags in filter panel

src/en/vizshonenjump/build.gradle, src/en/vizshonenjump/src/eu/kanade/tachiyomi/extension/en/vizshonenjump/VizShonenJump.kt
Closes #6772.
The majority of chapters will now show the blank page at the start, and this is to prevent the behavior reported at #6772.
I also added the auth check request from the site when opening a locked chapter if the user is logged in, to prevent the users with the session expired or that don't have access to the locked chapters from trying to read them.
I can't really test if it's working with a subscriber account since I don't have one, but users probably will open an issue if something is not working as expected.
=> Fix missing pages at Viz

multisrc/overrides/madara/mangamitsu/src/MangaMitsu.kt, multisrc/overrides/madara/mangayami/src/MangaYami.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
PR #6802 wrongly put two English sources in the Spanish package in the overrides.
Will probably close #6814.
=> Fix wrong package in two sources at Madara

CONTRIBUTING.md
@hapylestat noticed in #3669 that tachiyomi extensions can be debugged with the debugger, by using `Attach debugger to Android Process` to attach to the running Tachiyomi instance.
The requirements to do so are looser than described in the issue; Tachiyomi doesn't need to be launched with a specific run configuration for this to work. 
I was able to validate that this with the Android emulator, but have yet to do so on a physical device.
I edited CONTRIBUTING.md to reflect this.
(I also clarified what the provided run configuration in the `Running` section actually does)
Closes #3669
=> Describe how to use debugger + Clarify Run Configuration

multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangareader/WPMangaReader.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangareader/WPMangaReaderGenerator.kt
Per [wordpress mangareader's changelog](https://themesia.com/mangareader-wordpress-theme/#changelog), it seems like search had been changed a bit after the filters were originally implemented in this extension. So it has been broken for a few months.
This pull request updates the filtering and also adds in some logic to dynamically fetch genres (which differ from site to site)
Aside:
It'd be dope if the Sources had a bit more support for dynamic filters -> tachiyomi eagerly fetches filters from sources, and the only way to get the view to update is seemingly to get the user to hit reset
Either delaying the initialization of filters until after an initial request (popular/latest) is made, or providing a callback that allows the source to force a redraw would go a long way to make this …
=> Fix wpmangareader filtering + Dynamically Fetch Genres

multisrc/overrides/wpmangareader/gsnation/src/GSNation.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangareader/WPMangaReaderGenerator.kt
GSNation overrode some methods which led to infinite recursion after the last wpmangareader update.
This pull request fixes that issue 
Closes #6968
=> Fix infinite recursion in GSNation extension

multisrc/overrides/wpmangareader/flamescans/src/FlameScans.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangareader/WPMangaReaderGenerator.kt
This pull request corrects flamescan.org's scheme to `https`.
=> Flame Scans: http -> https

multisrc/overrides/madara/neoxscanlator/src/NeoxScanlator.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
Reported by some users that sometimes the source changes the slug of the manga (I don't know if this is a measure to prevent 3rd party apps from accessing their content). Now, when this happens again, there will be a warning to inform the user to migrate the manga from the source to the same source to update the URL.
I also filtered the novels in pure text format, that the app does not support.
=> Add a warning when the manga URL changes in NS

multisrc/overrides/wpmangareader/default/AndroidManifest.xml, multisrc/overrides/wpmangareader/gsnation/src/GSNation.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangareader/WPMangaReader.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangareader/WPMangaReaderGenerator.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangareader/WPMangaReaderUrlActivity.kt, multisrc/src/main/java/generator/ThemeSourceGenerator.kt
A large portion of tachiyomi extensions are generated from templates, and the only way to currently set a non-default AndroidManifest.xml is to write an override for every single generated extension.
This pull request:
* Adds support for a default [AndroidManifest.xml](https://github.com/h-hyuuga/tachiyomi-extensions/blob/27a12e81addfa281678ca80157b39293cd2fbc59/multisrc/src/main/java/generator/ThemeSourceGenerator.kt#L94) for all extensions generated from a theme source
* [Modifies the default generated `build.gradle` to include useful manifestPlaceholders for building intents](https://github.com/h-hyuuga/tachiyomi-extensions/blob/27a12e81addfa281678ca80157b39293cd2fbc59/multisrc/src/main/java/generator/ThemeSourceGenerator.kt#L76)
* Implements deeplinking in `wpmangareader` as an …
=> Facilitate Deeplinking for multisrc extensions

src/all/mangadex/build.gradle, src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDexInterceptors.kt
Today, all report requests are denied by MD@H backend since the field doesn't match the required schema:
```Go
type reportRequest struct {
URL      string  `json:"url"`
Success  bool    `json:"success"`
Bytes    int     `json:"bytes"`
Duration float64 `json:"duration"` // milliseconds, can have decimal places
Cached   bool    `json:"cached"`
}
```
=> Use correct field name for MD@H report endpoint

src/en/hiveworks/build.gradle, src/en/hiveworks/src/eu/kanade/tachiyomi/extension/en/hiveworks/Hiveworks.kt
Witchy used to be broken on hiveworks, due to having a custom page for /comic/archive that uses a bunch of links instead of an `<option>` for each page (see https://www.witchycomic.com/comic/archive vs https://www.sleeplessdomain.com/comic/archive : the select control is missing).
=> Fix Witchy from HiveworksComic

multisrc/overrides/fmreader/heroscan/additional.gradle.kts, multisrc/overrides/fmreader/heroscan/src/HeroScan.kt, multisrc/overrides/fmreader/manhuascan/additional.gradle.kts, multisrc/overrides/fmreader/manhuascan/src/ManhuaScan.kt, multisrc/overrides/fmreader/manhwahot/additional.gradle.kts, multisrc/overrides/fmreader/manhwahot/src/ManhwaHot.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/fmreader/FMReader.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/fmreader/FMReaderGenerator.kt
alternate title: Play Cat and Mouse with HeroScan, ManhuaScan, and ManhwaHot
This pull request restores functionality to the aforementioned extensions and applies a harsh rate limiting limit.
Aside: There's no chance this fix survives the day. Once it breaks again, we'll probably have to declare them `won't fix`.
Closes #7055
Closes #7054
=> FMReader Fixes Pt.2: The Encryption Strikes Back

multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/genkan/GenkanGenerator.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/genkan/GenkanOriginalGenerator.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
I added a preference to choose the host server for Madara sources. If the preference is set to *Auto*, it will try the *default* then each server until it finds some pages (if possible).
There are probably some things to improve so don't hesitate to suggest if you have any idea.
Closes #6835
I also moved `Method Scans` to `GenkanOriginal`
=> Add host preference madara

src/all/komga/CHANGELOG.md, src/all/komga/build.gradle, src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/Komga.kt
Else a series with a single book in progress would not be shown. The same fix has been applied to the webui of Komga.
=> [Komga] search for `in progress` and `unread` when `unread only` filter is selected

multisrc/overrides/madara/neoxscanlator/src/NeoxScanlator.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
This source is very slow nowadays, and they are always changing the manga URLs, probably to block the app.
This PR fixes the WebView method of bypassing Cloudflare and also adds a more harsh rate limiting.
The fix probably will stop working soon, if it's really a cat and mouse game.
=> Attempt to bypass Cloudflare at NS

multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/guya/Guya.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/guya/GuyaGenerator.kt
Endpoints of both guya.moe and danke.moe, ends with a slash. This saved a http request.
=> Fix missing slash in api endpoint

multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/webtoons/Webtoons.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/webtoons/WebtoonsGenerator.kt
Some pages in the challenge category uses another HTML tag for the title and may not have the status. This behavior was making the extension throw a `NullPointerException` when using the `text()` method in `mangaDetailsParse`.
=> Fix Jsoup NPE at Webtoons

common-dependencies.gradle, src/all/mangaplus/build.gradle, src/all/mangaplus/src/eu/kanade/tachiyomi/extension/all/mangaplus/MangaPlusFactory.kt, src/pt/bruttal/build.gradle, src/pt/bruttal/src/eu/kanade/tachiyomi/extension/pt/bruttal/Bruttal.kt, src/pt/bruttal/src/eu/kanade/tachiyomi/extension/pt/bruttal/BruttalDto.kt, src/pt/hipercool/build.gradle, src/pt/hipercool/src/eu/kanade/tachiyomi/extension/pt/hipercool/Hipercool.kt, src/pt/hipercool/src/eu/kanade/tachiyomi/extension/pt/hipercool/HipercoolDto.kt, src/zh/dmzj/build.gradle
A test to check if the replacement of Gson + Kotson with kotlinx.serialization is already viable.
The idea is after the merge keep looking for a certain period at user reports about bugs or crashes, and if it's working fine, replace gradually all the usages of Gson + Kotson with kotlinx.serialization.
Both Json and ProtoBuf dependencies were added as `compileOnly` to `common-dependencies.gradle`.
Tested with `v0.10.12`, `v0.11.1` and `r3472`.
=> Replace Gson usage with kotlinx.serialization in some sources

src/en/mangamutiny/build.gradle, src/en/mangamutiny/src/eu/kanade/tachiyomi/extension/en/mangamutiny/MangaMutiny.kt, src/en/mangamutiny/src/eu/kanade/tachiyomi/extension/en/mangamutiny/MangaMutinySerialization.kt
With the changes of this pull request I'm getting rid of the GSON library for the MangaMutiny extension and instead use kotlinx.serialization (reason for this change is #7392).
The changes made with this pull request will not affect extension users.
I avoided adding data classes annotated with Serializable, since I did not want to introduce additional classes to the extension. DeserializationStrategy objects can be just as useful and don't require lots of instances at runtime.
=> MangaMutiny - Migration from Gson to kotlinx.serialization

src/zh/manhuagui/build.gradle, src/zh/manhuagui/src/eu/kanade/tachiyomi/extension/zh/manhuagui/Manhuagui.kt
Currently, even if choosing 1 request pre-second, there will be a high chance for Manhuagui to block ip address if you are checking 100+ manga from manhuagui. Change the interval to 10 seconds should be able to fix this issue.
=> Change Manhuagui's Main-Site Rate Limite Interval to 10 Seconds

multisrc/overrides/mmrcms/fallenangels/src/FallenAngels.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mmrcms/MMRCMSSources.kt
Problem:
it is difficult to know chapter numbers for Manga titles with long chapter names or manga names like (Destroy All Humankind. They Can’t Be Regenerated.)
Fix:
added a new override for the chapterListParse method for the FallenAngels source in MMRCMS Generator
Notes:
since the chapter URL is unchanged, downloads wouldn't be affected. Checked on a oneshot chapter I had kept downloaded and it worked fine after the change
Changes:
previously -> mangaName chapterNumber : chapterTitle
new          ->         Chapter chapterNumber : chapterTitle
Screenshots : 
| Before | After |
|----------|---------|
|![Screenshot_20210604-013513_TachiyomiSY](https://user-images.githubusercontent.com/72807749/120860868-fa067380-c5a3-11eb-840f-5d83517f12ca.png)  | …
=> Fix chapter names in FallenAngels

multisrc/overrides/mmrcms/fallenangels/src/FallenAngels.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mmrcms/MMRCMSSources.kt
missed this in #7469 because I overlooked it, my bad XD
| previously | new |
|---------------|-------|
| `d+`          | `[1-9]\d*(\.\d+)*` |
the regex should now get correct chapter numbers for better chapters names 
while I only saw examples like chapter 64.5, the regex should be able to handle 64.5.5 as well (even though I couldn't find it)
=> Fix regex for chapterNumber in FAScans

src/pt/tsukimangas/build.gradle, src/pt/tsukimangas/src/eu/kanade/tachiyomi/extension/pt/tsukimangas/TsukiMangas.kt
All HTTP requests to the image servers have now a harsher rate limiting, following the website request.
I also added a query parameter to hide the adult content in popular by default (can be re-enabled by filters).
=> Add a harsher rate limiting to image servers requests at Tsuki

src/en/hentaimimi/build.gradle, src/en/hentaimimi/src/eu/kanade/tachiyomi/extension/en/hentaimimi/HentaiMimi.kt
I've noticed some books could not be viewed due to them having unicode entities in page URLs, like this: `"uploads\/zip_files\/extracted\/\u201cFirst Step\u201d\/001.webp".`
The extension cuts extensions incorrectly everywhere, but instead it must cut only "\/" sequence.
Example of such book: https://hentaimimi.com/view/3
=> Hentaimimi fix

src/all/mangaplus/AndroidManifest.xml, src/all/mangaplus/build.gradle, src/all/mangaplus/src/eu/kanade/tachiyomi/extension/all/mangaplus/MangaPlus.kt, src/all/mangaplus/src/eu/kanade/tachiyomi/extension/all/mangaplus/MangaPlusUrlActivity.kt, src/pt/tsukimangas/AndroidManifest.xml, src/pt/tsukimangas/build.gradle, src/pt/tsukimangas/src/eu/kanade/tachiyomi/extension/pt/tsukimangas/TsukiMangas.kt, src/pt/tsukimangas/src/eu/kanade/tachiyomi/extension/pt/tsukimangas/TsukiMangasUrlActivity.kt
Both websites are single page applications, so Chrome doesn't prompt the open at dialog.
However, Android prompts the dialog when clicking in links through other apps or with `adb` as below.
```console
$ adb shell am start -d "https://tsukimangas.com/obra/5578/lingwu-emperor" -a android.intent.action.VIEW
Starting: Intent { act=android.intent.action.VIEW dat=https://tsukimangas.com/... }
$ adb shell am start -d "https://mangaplus.shueisha.co.jp/titles/100001" -a android.intent.action.VIEW
Starting: Intent { act=android.intent.action.VIEW dat=https://mangaplus.shueisha.co.jp/... }
```
=> Add deeplinking to MangaPlus and Tsuki

multisrc/overrides/madara/thefluffyhangoutgroup/src/TheFluffyHangoutGroup.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
=> [Madara] Fix dateformat for TheFluffyHangoutGroup

src/en/hentaimimi/build.gradle, src/en/hentaimimi/src/eu/kanade/tachiyomi/extension/en/hentaimimi/HentaiMimi.kt
The previous pull request #7574 didn't fix the slashes issue. I'm really sorry for submitting not working fix.
To fix my situation, I had to put my hands in Kotlin and figure out how to fix the parsing of the list of pages. It turns out that simple js arrays, such as a list of pages on their site, can be parsed as json, and you don't have to bother with handling escaped strings at all.
This time, I carefully checked and tested on a device that the changes worked, and additionally checked other special elements such as ?, #, @, /, [, ] too - all pages parsed without errors.
=> Hentaimimi proper fix

multisrc/overrides/nyahentai/default/AndroidManifest.xml, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/nyahentai/NyaHentai.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/nyahentai/NyaHentaiGenerator.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/nyahentai/NyaHentaiUrlActivity.kt
[Fix] tarUrl not initialized when using filter search
The tagUrl is not initialized and will never get initialized, resulting in the search page not been able to load more than one page. Fixed by rewrite the searchMangaRequest.
[Feat] Enable filter search for parody, character, artist, and group
[Feat] Enable sort by time or popularity search when not in a specific language.
[Feat] Add deeplink support
=> Rewrite NyaHentai Filter and add deeplink support

src/zh/jinmantiantang/AndroidManifest.xml, src/zh/jinmantiantang/build.gradle, src/zh/jinmantiantang/src/eu/kanade/tachiyomi/extension/zh/jinmantiantang/Jinmantiantang.kt, src/zh/jinmantiantang/src/eu/kanade/tachiyomi/extension/zh/jinmantiantang/JinmantiantangUrlActivity.kt
[Fix] Jingmantiantang's ownText is null during chapter loading
The old implementation is to use chapterArea to store wheather or
not the Manga requested is only single page or multi-chapter.
This, however, creates a big issue as the chapterArea can be changed
to multi-chapter in preveious Manga, and that information is carried
over to other Manga which might be single chapter.
The new implementation remove global value chapterArea and it helper
function determineChapterInfo.
Instead, the single-multi check is performed in chapterListParse, which
only happen once per manga update request, vs three times call of
determineChapterInfo.
[Fix] Change Author's CSS selector and enable multi-author listing
[Fix] Default manga status to Completed
As Jingmantiantang often do not mark manga as …
=> Fix Jingmantiantang's ownText is null and add deeplink support

src/all/comickfun/build.gradle, src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt, src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunSerialization.kt, src/all/genkanio/build.gradle, src/all/genkanio/src/eu/kanade/tachiyomi/extension/all/genkanio/GenkanIO.kt, src/en/catmanga/build.gradle, src/en/catmanga/src/eu/kanade/tachiyomi/extension/en/catmanga/CatManga.kt, src/ru/remanga/build.gradle, src/ru/remanga/src/eu/kanade/tachiyomi/extension/ru/remanga/Remanga.kt, src/ru/remanga/src/eu/kanade/tachiyomi/extension/ru/remanga/dto/Dto.kt
This pull request supports #7392, replacing the used json library with kotlinx.serialization
Sources : 
Musings:
* Debugging any non-trivial (de)serializers for kotlinx.serialization can be pretty annoying. The decoding error messages are somewhat obtuse.
=> Replace json library with kotlinx.serialization in multiple sources

src/all/mangadex/build.gradle, src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDex.kt
Addresses #7697 and #7678, albeit by just swallowing the error case.  The MangaDex team is aware of the root issue and have an issue logged to address the root cause.
=> Add in error handling to handle malformed responses from the aggregate endpoint

multisrc/overrides/wpmangareader/flamescans/src/FlameScans.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangareader/WPMangaReaderGenerator.kt
* Reduced request limit to 1 request / second
* Traffic from Tachiyomi is identified by the word "Tachiyomi" in the user agent.
=> Flame Scans: Harsher Rate Limit + Add Tachiyomi Identifier to User Agent

src/all/hitomi/build.gradle, src/all/hitomi/src/eu/kanade/tachiyomi/extension/all/hitomi/Hitomi.kt
[FIX] Remove hardcode image path condition
Rather than hardcoded conditions for determining image path's first subdomain,
the extension now dynamically load the condition by parsing the condition from
Hitomi.la's common.js. This should keep the cat and mouse chase a little bit longer.
[REFACTOR] Simplify regular expression for id extraction
=> [Hitomi.la] Remove hardcode image path condition

src/zh/dmzj/build.gradle, src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt
The new v4api doesn't work if using `nnv4api.dmzj.com` as api url, only `nnv4api.dmzj1.com` works. The `dmzj.com` version will always return an error message indicating `暂时无法观看` (with errno `3`) even if the manga is not blocked (i.e. can read directly from website).
The `dmzj1.com` domain is back online again, including its websites: https://www.dmzj1.com/ ([archive](https://web.archive.org/web/20210617223910/https://www.dmzj1.com/)) and https://manhua.dmzj1.com/ ([archive](https://web.archive.org/web/20210617224035/https://manhua.dmzj1.com/)). The previous issue (https://github.com/tachiyomiorg/tachiyomi-extensions/issues/7668) may be just a DNS misconfiguration incident. I only reverted change of v4api because it seems that other apis still work under `dmzj.com`, only v4api breaks.
=> zh-dmzj: replace dmzj.com with dmzj1.com for v4api only to make it work again

src/all/batoto/build.gradle, src/all/batoto/src/eu/kanade/tachiyomi/extension/all/batoto/BatoTo.kt, src/en/dynasty/build.gradle, src/en/dynasty/src/eu/kanade/tachiyomi/extension/en/dynasty/DynastyScans.kt, src/en/mangapark/build.gradle, src/en/mangapark/src/eu/kanade/tachiyomi/extension/en/mangapark/MangaPark.kt, src/en/readm/build.gradle, src/en/readm/src/eu/kanade/tachiyomi/extension/en/readm/ReadM.kt
This pull request supports #7392, replacing the used json library with kotlinx.serialization
=> Kotlinx.serialization migration for several sources

src/en/mangamiso/build.gradle, src/en/mangamiso/src/eu/kanade/tachiyomi/extension/en/mangamiso/MangaMiso.kt, src/en/mangamiso/src/eu/kanade/tachiyomi/extension/en/mangamiso/MangaMisoObjects.kt
I think MangaMiso slightly changed their internal API, as the name of one of the fields returned when doing a filter search originally was `totalResults`, but now it's just `total`.
I think that's the case, I hope I just didn't manage to miss testing that when initially creating the extension ¯\\\_(ツ)_/¯
This change meant that when filtering manga, only 1 page of results would be viewable.
This PR corrects the field name, so that multiple pages of results are returned when doing a search via Filters
=> Fix only one page of MangaMiso filter results being returned

src/zh/dmzj/build.gradle, src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/protobuf/V4apiComicDetailResponse.kt
`ChapterOrder` field of `ComicDetailChapterInfoResponse` may be missing in valid response, and is actually not used by the extension. Make it optional by specifying a default value.
The manga I tested with is: https://m.dmzj.com/info/49093.html
<details><summary>LogCat output when I'm investigationg why manga that are reabable on website still fallback</summary>
```
2021-06-28 23:36:03.210 20307-4819/? E/dmzj: v4api chapter list failed
kotlinx.serialization.MissingFieldException: Field 'ChapterOrder' is required for type with serial name 'eu.kanade.tachiyomi.extension.zh.dmzj.protobuf.ComicDetailChapterInfoResponse', but it was missing
at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:3)
at …
```
=> [zh-dmzj] Make ChapterOrder field optional

multisrc/overrides/wpmangastream/komikstation/src/KomikStation.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangareader/WPMangaReader.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangareader/WPMangaReaderGenerator.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStream.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStreamGenerator.kt
In a few cases, 'src' would be a literal SVG (a loading icon) rather than a URL to the page's image, which would work fine with 'src' but show up as an empty string for 'abs:src'.
xCaliBR was one such source. In its case, it would load the page list as a single empty page, instead of the correct page URLs, and would prevent the js-page-detection logic from populating the actual page list.
Tested xCaliBR, Komik Station, APairOf2 (as samples of each of the multisrc's that changed).
=> [WPMangaReader, WPMangaStream] Prevent pages that don't have abs:src from being added to page list

src/en/swordscomic/build.gradle, src/en/swordscomic/src/eu/kanade/tachiyomi/extension/en/swordscomic/SwordsComic.kt
Adds title text as a page to chapters in the Swords Comic source, similar to the current behavior of the xkcd source. 
Example of a generated title text page (from Swords DXI):
=> Add title text as a page to Swords Comic source

src/all/mangadex/build.gradle, src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDexHelper.kt
Being that this pull request has no issues to close, I will explain what the problem is.
After 5 mins, chapters being read from the MangaDex extension would fail to load images. This happened because after 5 mins, the extension would try to make sure the MD@H url was still correct.
But what would happen is that the cache wouldn't end up having the url in it, and would report a `504 Unsatisfiable Request` with an empty body. This would lead to the url to the image being incorrect. Why the cache would start dropping the data, I don't know.
This pull request does 2 things.
1) Don't force cache access if we know that the MD@H url should be valid.
2) If we end up with getting `504 Unsatisfiable Request`, retry and force a network request so that we can cache it.
=> Make MangaDex load images more consistently

src/all/komga/CHANGELOG.md, src/all/komga/build.gradle, src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/Komga.kt
This is a backward compatible change to prepare for the new version of Komga that will fix https://github.com/gotson/komga/issues/217
Books and series can appear as `Unavailable` when the files are not present anymore (like Plex). This version of the extension will filter out all those deleted series and books.
=> [Komga] filter deleted series and books

src/en/mangajar/build.gradle, src/en/mangajar/src/eu/kanade/tachiyomi/extension/en/mangajar/MangaJar.kt
Couldn't find a way to have the chapter list show all chapters, so overrode `fetchChapterList` to get the next page until there isn't a next page. A side effect is that full chapter names show up now.
=> MangaJar reads all pages of chapters and full chapter names

src/all/cubari/build.gradle, src/all/cubari/src/eu/kanade/tachiyomi/extension/all/cubari/Cubari.kt
Got recently changed with  #8126, altering it to make it Cubari Imgur source compatible.
Cubari API responses don't contain release_date information when the Cubari source is Imgur.
The minor change made with this commit makes the existence of the release_date json property for the parsing process optional.
Tested with https://cubari.moe/read/imgur/fE52z40/ as well as the Cubari Mangadex and Cubari Gist sources from the PR mentioned above.
Edit:
This PR now also contains a fix for when the volume in the json is set to null (won't be included in the chapter name anymore).
Was a problem e.g. with https://cubari.moe/read/mangadex/e83c326b-921b-45ff-bc0c-d667bbfe64cc/
Also cleaned up the chapter title concatenation (had some duplicate code for chapter names with and without volume numbers).
=> Cubari release_date fix + volume null fix

.github/scripts/create-repo.sh, .github/workflows/build_push.yml
Continues #6410
This is an rewritten version of the Tachidesk Inspector that ArMor PR'd back in April. It takes the suggestions of other contributors, such as:
- Puts the array of source information(such as name, lang, and id) inside the index.json as a item in the extensions object. 
- Deletes all Tachidesk specific code, only adding whats needed for the Inspector
- Puts the Inspector.jar in the runner-files so that it is not downloaded externally
Sample from index.json
```json
[
{
"name": "Tachiyomi: Cubari",
"pkg": "eu.kanade.tachiyomi.extension.all.cubari",
"apk": "tachiyomi-all.cubari-v1.2.9.apk",
"lang": "all",
"code": 9,
"version": "1.2.9",
"nsfw": 0,
"sources": [
{
"name": "Cubari",
"lang": "en",
"id": 6338219619148106000
},
{
"name": "Cubari",
"lang": "all",
"id": …
```
=> Inspect extensions to get source information

src/zh/copymanga/build.gradle, src/zh/copymanga/src/eu/kanade/tachiyomi/extension/zh/copymanga/CopyManga.kt
When we end up with a decrypt password of null (that is, there is no comic-specific decryption password), fall back to the default password. Previously, we ended up passing in null instead of a default password.
Also update the default password.
Fixes #9114
Checklist:
=> CopyManga: Fix missing decrypt password

src/ja/nicovideoseiga/build.gradle, src/ja/nicovideoseiga/src/eu/kanade/tachiyomi/extension/ja/nicovideoseiga/NicovideoSeiga.kt
When downloading NicovideoSeiga image, the saved file extension has become wrong type. This commit addresses the issue by fixing following errors.
- Images is determined the type by file header. The logic has wrongly assumed Byte.toInt() returns unsigned integer, but it actually returns signed value.
- The server returns application/octet-stream as Content-Type header. But the logic only worked when header is empty.
Checklist:
=> NicovideoSeiga: Fix file type handling.

multisrc/overrides/wpmangastream/infernalvoidscans/src/InfernalVoidScans.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStreamGenerator.kt
=> Infernal Void Scans: Fix page parsing

multisrc/overrides/madara/hscans/src/Hscans.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
=> Fix Hscans date parsing

src/vi/blogtruyen/build.gradle, src/vi/blogtruyen/src/eu/kanade/tachiyomi/extension/vi/blogtruyen/BlogTruyen.kt
=> BlogTruyen: Fix parse page list not return enough pages in some manga

multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangareader/WPMangaReader.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangareader/WPMangaReaderGenerator.kt
This pull request makes the WPMangaReader series type selector slightly more permissive.
This fixes series type selection for Flamescans
Checklist:
=> WPMangaReader: Update Series Type Selector

src/ja/mangaraw/build.gradle, src/ja/mangaraw/src/eu/kanade/tachiyomi/extension/ja/mangaraw/MangaRaw.kt, src/ja/mangaraw/src/eu/kanade/tachiyomi/extension/ja/mangaraw/MangaRawFactory.kt, src/ja/mangaraw/src/eu/kanade/tachiyomi/extension/ja/mangaraw/sources/Comick.kt, src/ja/mangaraw/src/eu/kanade/tachiyomi/extension/ja/mangaraw/sources/MangaPro.kt
Checklist:
Closes #11047 
Both Manga1000 and Manga1001 has been [DMCA'd and shut down by Shogakukan, Shueisha, Kadokawa and Kodansha](https://torrentfreak.com/major-manga-publishers-try-to-identify-operators-of-massive-pirate-sites-211211/). And judging from the news sources, Manga1002 might also soon be taken down. Plus it has a completely different layout from the old one. Not sure if it's even the same site, so I'm not going to spend time on that one.
comick.top and mangapro.top are the copycats (Not the same owner) of these two sites. They look the same visually but have slightly different html layout. It's also filled with clickjacking ads. **Highly not recommend viewing the site in WebView**
Users are required to migrate their library to the new sources.
=> Replace Manga1000/1001 with Comick and MangaPro

multisrc/overrides/madara/reaperscans/src/ReaperScansFactory.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
Checklist:
This PR aims to fix chapter names and dates in the ReaperScan En extension, which are currently broken and set to null.
=> Fix date and chapter name from ReaperScans EN

src/en/hentaifox/build.gradle, src/en/hentaifox/src/eu/kanade/tachiyomi/extension/en/hentaifox/HentaiFox.kt
=> Fix: hentaifox.com second page issue

multisrc/overrides/madara/manhwafull/src/Manhwafull.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
Closes https://github.com/tachiyomiorg/tachiyomi-extensions/issues/11602
Checklist:
=> fix: manhwafull pagination

src/en/irovedout/build.gradle, src/en/irovedout/src/eu/kanade/tachiyomi/extension/en/irovedout/IRovedOut.kt
Previous css selector expected the link to the next page, which doesn't exist on the last page.
Checklist:
=> I Roved Out: Fix loading last page

src/en/irovedout/build.gradle, src/en/irovedout/src/eu/kanade/tachiyomi/extension/en/irovedout/IRovedOut.kt
Fixes the extension not finding chapters.
Checklist:
=> Add www to irovedout URL

multisrc/overrides/madara/leviatanscans/src/LeviatanScansFactory.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
Not sure about the date locale for `LeviatanScansES` since both US and ES locales work for now. I assumed it's ES since the hours/days ago are in spanish
Checklist:
=> LeviatanScans: Fix dates, description and status

src/all/komga/CHANGELOG.md, src/all/komga/build.gradle, src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/Komga.kt, src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/dto/Dto.kt
Closes #12644
How the status is parsed:
- `ENDED` + Total book count is missing/more than current book count: `Completed`
- `ENDED` + Total book count is less then the current book count: `Publication Finished`
Need a minimum of Komga v0.113.0 to work properly.
Checklist:
=> Komga: Improve status parsing

multisrc/overrides/madara/leviatanscans/src/LeviatanScansFactory.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
The dates format changed again for the english website
Checklist:
=> Leviatan Scans: Fix dates format

multisrc/overrides/nepnep/mangasee/AndroidManifest.xml, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/nepnep/NepNepGenerator.kt
=> Fix a bug with mangasee intent filter

multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangathemesia/MangaThemesia.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangathemesia/MangaThemesiaGenerator.kt
This pull request modifies the seriesTypeSelector so that it properly detects the series type on several mangaThemesia sources (asura scans, alpha scans, etc..).
Checklist:
=> Fix seriesTypeSelector for some mangathymesia sources

lib/cryptoaes/src/main/java/eu/kanade/tachiyomi/lib/cryptoaes/CryptoAES.kt, src/all/comico/build.gradle, src/all/comico/src/eu/kanade/tachiyomi/extension/all/comico/Comico.kt
Replaced CryptoJS with javax.crypto. Also removed QuickJS Dependency.
Tested reading and downloads for various titles.
The `cryptoaes` lib has been modified, but the interface used by batoto and mangapark remains the same.
Checklist:
=> Comico: Replace CryptoJS with javax.crypto

src/all/comickfun/build.gradle, src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunFilters.kt
=> Comick.fun: fixed filter label misspelling

multisrc/overrides/madara/reaperscans/src/ReaperScansFactory.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
This pull request adds support for parsing the following metadata to ReaperScans: 
* Chapter Upload Date
* Series Type
* Cancellation Status 
Checklist:
**Note**: This pull request bumps the extension to the same version as #13781, assuming both PRs will be merged at the same time
=> Improve Reaper Scans metadata parsing

src/all/comickfun/build.gradle, src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunDto.kt
=> Added fallback if manga description is null

src/en/earlymanga/build.gradle, src/en/earlymanga/src/eu/kanade/tachiyomi/extension/en/earlymanga/EarlyManga.kt
Checklist:
Closes #13765 
Since the website now has a V2 version this PR just updates the source to their V1 website.
It may be important to rewrite the extension for the V2 website. I don't know if they will shut down the V1 in the future.
=> fix: EarlyManga update baseUrl

multisrc/overrides/madara/mangaleveling/src/MangaLeveling.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
=> manga leveling chapter name fix

src/all/kavita/CHANGELOG.md, src/all/kavita/build.gradle, src/all/kavita/src/eu/kanade/tachiyomi/extension/all/kavita/Kavita.kt
This PR fixes an error when downloading that was apparently brought up in the latest preview version (r5254 and previous).
Latest preview version does now call `pageListRequest`  which from my understanding it shouldn't if `fetchPageList` is overriden.
I updated the method to return a dummy request to the chapter page since this call apparently does nothing in this use case.
I'm open to discussion if an issue should be raised in the main repo. Meanwhile here's valid fix for now (works with latest stable as well).
Note that this error only happens when downloading chapters.
Checklist:
=> Kavita: Bugfix/expected url scheme

src/en/mangafreak/build.gradle, src/en/mangafreak/src/eu/kanade/tachiyomi/extension/en/mangafreak/Mangafreak.kt
=> Update mangafreak base url to the latest working version

src/en/rawmanga/build.gradle, src/en/rawmanga/src/eu/kanade/tachiyomi/extension/en/rawmanga/RawManga.kt
Closes #14471
Closes #14431 
Incorrect manga id caused app not to fetch chapter list correctly. Affected delimiter has been updated.
Checklist:
=> Raw-manga: Fix chapter list not fetched

src/en/madokami/build.gradle, src/en/madokami/src/eu/kanade/tachiyomi/extension/en/madokami/Madokami.kt
Fixes https://github.com/tachiyomiorg/tachiyomi-extensions/issues/10447
Checklist:
=> Madokami: fix encoding special characters in url 

src/en/madokami/build.gradle, src/en/madokami/src/eu/kanade/tachiyomi/extension/en/madokami/Madokami.kt
Fixes https://github.com/tachiyomiorg/tachiyomi-extensions/issues/15988
Checklist:
=> Madokami: Fix Manga details failed to load on deep subdirectory

multisrc/overrides/mangathemesia/mangaswat/src/MangaSwat.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangathemesia/MangaThemesiaGenerator.kt
Closes #16030
Looks to work fine after change.
Checklist:
=> update MangaSwat URL

src/en/vizshonenjump/AndroidManifest.xml, src/en/vizshonenjump/build.gradle, src/en/vizshonenjump/src/eu/kanade/tachiyomi/extension/en/vizshonenjump/VizShonenJump.kt, src/en/vizshonenjump/src/eu/kanade/tachiyomi/extension/en/vizshonenjump/VizUrlActivity.kt
Add URL intent to open series links (e.g. https://www.viz.com/shonenjump/chapters/kaiju-no-8) and chapter links (e.g. https://www.viz.com/shonenjump/kaiju-no-8-chapter-85/chapter/38004) in the extension.
Checklist:
=> [VizShonenJump] Add URL intent for series and chapter links

src/en/aurora/build.gradle, src/en/aurora/src/eu/kanade/tachiyomi/extension/en/aurora/Aurora.kt
An update to the comics page broke chapter loading, as the preview chapter did not have a link to use for the chapter overview.
I also saw that the ordering of the pages is wrong (which can manually be fixed by the end users, but that would have to be done for each new chapter).
Checklist:
=> Fix: page ordering & broken chapter loading

src/id/bacakomik/build.gradle, src/id/bacakomik/src/eu/kanade/tachiyomi/extension/id/bacakomik/BacaKomik.kt
I aleready tested
Closes : #16949
Checklist:
=> Fix BacaKomik no pages found

src/vi/hentaivn/build.gradle, src/vi/hentaivn/src/eu/kanade/tachiyomi/extension/vi/hentaivn/HentaiVN.kt
Fixes #17071. Cloudflare protection may be stricter for non-Vietnamese IPs.
Checklist:
=> Changed domain for hentaivn

src/en/latisbooks/build.gradle, src/en/latisbooks/src/eu/kanade/tachiyomi/extension/en/latisbooks/Latisbooks.kt
At some point recently (within the last week), latisbooks.com changed something about the site, likely a preprocessor update on their blog system. As a result, the extension was unable to find any pages. The first commit remedies this.
Additionally, I noticed that the cover art was completely broken, deciding not to load. As I use a custom art for my personal use, I'm not sure how long this has been a problem, but to remedy this I chose a cover piece from the comic to use as the unofficial official cover.
I want to note that this does not seem to be directly related to #16624, as the wording on that issue implies that the chapter list itself is not loadable. I had no issues with it loading during development, not during personal use for the past month and a half since that issue was …
=> latisbooks: fix page parsing, fix cover art

multisrc/overrides/mangathemesia/asurascans/src/AsuraScansEn.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangathemesia/MangaThemesiaGenerator.kt
Closes #17136.
I haven't tested it as I do not have Android Studio set up.
Checklist:
=> Update asurascans url to new one

multisrc/overrides/fmreader/kisslove/src/KissLove.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/fmreader/FMReaderGenerator.kt
=> fix some manga id parse problem

src/es/olympusscanlation/build.gradle, src/es/olympusscanlation/src/eu/kanade/tachiyomi/extension/es/olympusscanlation/OlympusScanlation.kt
Olympus Scan changed domain,
Closes https://github.com/tachiyomiorg/tachiyomi-extensions/issues/17431.
Checklist:
=> Update OlympusScanlation domain

multisrc/overrides/mmrcms/mangafr/src/MangaFR.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mmrcms/MMRCMSGenerator.kt
=> MangaFR: Fix chapterNames and mangaName while in manga details

multisrc/overrides/wpcomics/nettruyen/src/NetTruyen.kt, multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpcomics/WPComicsGenerator.kt
=> Update domain Nettruyen

src/zh/manwa/build.gradle, src/zh/manwa/src/eu/kanade/tachiyomi/extension/zh/manwa/Manwa.kt
For #16752
- when only showing 3 pages, throw Exception, to make download task fail;
- Add a new preference, when only showing 3 pages, auto clear cookies;
Checklist:
=> Fix: Manwa.me download and read only showing 3 pages

src/ko/navercomic/build.gradle, src/ko/navercomic/src/eu/kanade/tachiyomi/extension/ko/navercomic/NaverComicBase.kt
Closes #17966
Closes #17948
naver's API changed how author info was stored in the response
additionally they added a secondary `rest` flag for series that are on hiatus. previously those series would have the `finished` flag set to true instead
Checklist:
=> naver: fix author parsing and handle on hiatus status

src/all/tachidesk/build.gradle, src/all/tachidesk/src/eu/kanade/tachiyomi/extension/all/tachidesk/Tachidesk.kt
Add a huge timeout (2min), waiting for Suwayomi Tachidesk dev to fix the problem.
Checklist:
=> Suwayomi: Add timeout (2min) waiting for Suwayomi staff to fix the problem

src/all/comicfury/build.gradle, src/all/comicfury/src/eu/kanade/tachiyomi/extension/all/comicfury/ComicFury.kt
=> Fix Comic Fury extension search functionality

src/all/everiaclub/build.gradle, src/all/everiaclub/src/eu/kanade/tachiyomi/extension/all/everiaclub/EveriaClub.kt
=> fix(EveriaClub): update searchMangaSelector

src/zh/jinmantiantang/build.gradle, src/zh/jinmantiantang/src/eu/kanade/tachiyomi/extension/zh/jinmantiantang/Jinmantiantang.kt
Checklist:
The PR #18961 causes NullPointerException
Closes #19100
Closes #19058
=> Revert PR#18961 which causes multiple regressions

src/en/readcomiconline/build.gradle, src/en/readcomiconline/src/eu/kanade/tachiyomi/extension/en/readcomiconline/Readcomiconline.kt
I made a list to choose from the 2 servers in the settings.
I checked this feature by opening chapters in Webview in the reader (not with the WebView button in the manga screen with the list of chapters) and observed that the server changes accordingly and should close [#18853](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/18853)
Checklist:
=> Readcomiconline: Server preference added

src/en/readcomiconline/build.gradle, src/en/readcomiconline/src/eu/kanade/tachiyomi/extension/en/readcomiconline/Readcomiconline.kt
Closes [#14581](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/14581)
Additionally to the Publisher filter the issue wanted to have, I implemented Writer and Artist filter as well and the 4 sorting orders when one of the three is set.
I couldn't implement it sothat the new filters works with the tag and title search that was originally there, because when you want to search Publishers/Writers/Artists, you will have to go to this kind of an url: 
```https://readcomiconline.li/Publisher/DC-Comics/```,
which is varies from the original link: 
```https://readcomiconline.li/AdvanceSearch?comicName=&ig=&eg=41%2C&status=```
So the new filters is only activated the query and the genre tag filter is not set.
Also, when you set multiple of the new filters (e.g. Publisher = DC Comics, …
=> Readcomiconline: Added new filters

src/en/readcomiconline/build.gradle, src/en/readcomiconline/src/eu/kanade/tachiyomi/extension/en/readcomiconline/Readcomiconline.kt
Fixed the issue of my previous [PR](https://github.com/tachiyomiorg/tachiyomi-extensions/pull/19262) that only the first page of the source is loaded, where it should load more.
Checklist:
=> Readcomiconline: fixed small issue to the new filter

src/all/kavita/CHANGELOG.md, src/all/kavita/build.gradle, src/all/kavita/src/eu/kanade/tachiyomi/extension/all/kavita/Kavita.kt, src/all/kavita/src/eu/kanade/tachiyomi/extension/all/kavita/KavitaInt.kt
Fixed:
* Added missing null-check if smart-filter is not loaded (due to not being any in kavita instance)
* Added a more broad exception handler in fetch
An edge case that got past testing. Sorry for the inconvenience.
To be merged asap as it fixes search function.
Checklist:
=> [Kavita] Patch - Fix for null cast exception

src/en/solarandsundry/build.gradle, src/en/solarandsundry/src/eu/kanade/tachiyomi/extension/en/solarandsundry/SolarAndSundry.kt
Updates the [Solar and Sundry](https://sas.ewanb.me/) extension to use the new version of the API, and also includes a new image and description.
Checklist:
=> Update Solar and Sundry API

src/zh/picacomic/build.gradle, src/zh/picacomic/src/eu/kanade/tachiyomi/extension/zh/picacomic/Picacomic.kt
Closes #19434
Caused by #19400
Checklist:
I have no condition to test because the repo is too heavy, but it can work theoretically for its just a small change.
=> Picacomic: Fix json decoding error of non-ASCII chars (#19434)
