tachiyomiorg/tachiyomi-extensions

- src/all/eromuse/build.gradle
- src/all/eromuse/src/eu/kanade/tachiyomi/extension/all/eromuse/EroMuse.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4085
> EroMuse - fix missing chapters

- src/zh/dmzj/build.gradle
- src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt
#4086  Current chapterList's api is broken, and the v3api works now.
> dmzj chapterList's api changed

- src/all/myreadingmanga/build.gradle
- src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt
- src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingMangaFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4067
> MyReadingManga - fix titles, duplicate pages

- src/es/vcpvmp/build.gradle
- src/es/vcpvmp/src/eu/kanade/tachiyomi/extension/es/vcpvmp/VCPVMP.kt
- src/es/vcpvmp/src/eu/kanade/tachiyomi/extension/es/vcpvmp/VCPVMPFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4017
> VCPVMP - fix images and chapters

- src/all/fmreader/build.gradle
- src/all/fmreader/src/eu/kanade/tachiyomi/extension/all/fmreader/FMReader.kt
- src/all/fmreader/src/eu/kanade/tachiyomi/extension/all/fmreader/FMReaderFactory.kt
> Fix Epikmanga

- src/zh/jinmantiantang/build.gradle
- src/zh/jinmantiantang/src/eu/kanade/tachiyomi/extension/zh/jinmantiantang/Jinmantiantang.kt
When I had written my extension of 18comic, I found someone did the same thing, just 12h ahead of me. So I decided to merge my codes, which contained some new features.
> Refined codes and added new features

- src/en/dynasty/build.gradle
- src/en/dynasty/src/eu/kanade/tachiyomi/extension/en/dynasty/DynastyChapters.kt
- src/en/dynasty/src/eu/kanade/tachiyomi/extension/en/dynasty/DynastyScans.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4131
> Dynasty - fix date parsing

- src/zh/dmzj/build.gradle
- src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4132
> Dmzj - update page parsing

- src/zh/dmzj/build.gradle
- src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4141
> Dmzj - fallback to v3api for hidden chapters

- src/en/vizshonenjump/build.gradle
- src/en/vizshonenjump/src/eu/kanade/tachiyomi/extension/en/vizshonenjump/VizImageInterceptor.kt
- src/en/vizshonenjump/src/eu/kanade/tachiyomi/extension/en/vizshonenjump/VizShonenJump.kt
Closes #4149.
I had to change the Exif library because the AndroidX one does not provide correct access to some tags.
> Fix image decoding method at Viz Shonen Jump

- src/en/mangareader/build.gradle
- src/en/mangareader/src/eu/kanade/tachiyomi/extension/en/mangareader/MRP.kt
- src/en/mangareader/src/eu/kanade/tachiyomi/extension/en/mangareader/MRPFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4147
> MangaReader - update parsing

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/Madara.kt
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Also removed Indiancomicsonline, it's dead.
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4114
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4097
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4098
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4073
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4063
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4036
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4031
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4004
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3193
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4154
> Madara - add sources, fix some chapter lists

- src/ko/newtoki/build.gradle
- src/ko/newtoki/src/eu/kanade/tachiyomi/extension/ko/newtoki/NewToki.kt
- src/ko/newtoki/src/eu/kanade/tachiyomi/extension/ko/newtoki/NewTokiFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3794
> NewToki - fix pages

- src/en/mangaowl/build.gradle
- src/en/mangaowl/src/eu/kanade/tachiyomi/extension/en/mangaowl/MangaOwl.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4170
> MangaOwl - fix search

- src/zh/manhuadui/build.gradle
- src/zh/manhuadui/src/eu/kanade/tachiyomi/extension/zh/manhuadui/Manhuadui.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4193
> ManhuaDui - update decryption, follow redirects

- src/all/foolslide/build.gradle
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/FoolSlideFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4184
> FoolSlide - add Edens Zero

- src/all/mmrcms/build.gradle
- src/all/mmrcms/src/eu/kanade/tachiyomi/extension/all/mmrcms/MyMangaReaderCMSSource.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4165
> MMRCMS - refactor latest parsing, fix Mangas.pw

- src/all/myreadingmanga/build.gradle
- src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt
Always add the `referer` header to requests so that the website does not redirect some of the pages to https://i.imgur.com/h3QvV4j.gif. ☟
> Fix MyReadingManga not loading images correctly

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> MangaArabTeam source URL changed

- src/es/kumanga/build.gradle
- src/es/kumanga/src/eu/kanade/tachiyomi/extension/es/kumanga/Kumanga.kt
- src/es/lectormanga/AndroidManifest.xml
- src/es/lectormanga/build.gradle
- src/es/lectormanga/src/eu/kanade/tachiyomi/extension/es/lectormanga/LectorManga.kt
- src/es/lectormanga/src/eu/kanade/tachiyomi/extension/es/lectormanga/LectorMangaUrlActivity.kt
- src/es/plottwistnofansub/build.gradle
- src/es/plottwistnofansub/src/eu/kanade/tachiyomi/extension/es/plottwistnofansub/PlotTwistNoFansub.kt
- src/es/tmohentai/AndroidManifest.xml
- src/es/tmohentai/build.gradle
- src/es/tmohentai/src/eu/kanade/tachiyomi/extension/es/tmohentai/TMOHentai.kt
- src/es/tmohentai/src/eu/kanade/tachiyomi/extension/es/tmohentai/TMOHentaiUrlActivity.kt
- src/es/tumangaonline/AndroidManifest.xml
- src/es/tumangaonline/build.gradle
- src/es/tumangaonline/src/eu/kanade/tachiyomi/extension/es/tumangaonline/TuMangaOnline.kt
- src/es/tumangaonline/src/eu/kanade/tachiyomi/extension/es/tumangaonline/TuMangaOnlineUrlActivity.kt
> Fix Plot Twist no Fansub, Update LectorManga, TMOHentai and TMO

- src/all/webtoons/build.gradle
- src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/DongmanManhua.kt
- src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/Webtoons.kt
- src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/WebtoonsDefault.kt
- src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/WebtoonsFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4217
> Webtoons - add French webtoons

- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStream.kt
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStreamFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4221
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4222
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4195
> WP Mangastream - add Boosei and Mangakyo

- src/zh/jinmantiantang/build.gradle
- src/zh/jinmantiantang/src/eu/kanade/tachiyomi/extension/zh/jinmantiantang/Jinmantiantang.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4224
> Jinmantiantang - clean up, parse chapters with 500+ pages

- src/ru/risensteam/build.gradle
- src/ru/risensteam/src/eu/kanade/tachiyomi/extension/ru/risensteam/RisensTeam.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4167
Due to changes in their API old favorites won't be compatible and will need to be migrated after updating this extension.
> RisensTeam - update for their new API

- src/ko/jmana/build.gradle
- src/ko/jmana/src/eu/kanade/tachiyomi/extension/ko/jmana/JMana.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4271
> JMana - fix chapters and latest titles

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4253
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4264
> Madara - add AlianzaMarcial

- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDex.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4239
> MangaDex - add 2 tags

- src/pt/goldenmangas/build.gradle
- src/pt/goldenmangas/src/eu/kanade/tachiyomi/extension/pt/goldenmangas/GoldenMangas.kt
> Fix Golden Manga due to site redesign

- src/ru/libmanga/build.gradle
- src/ru/libmanga/src/eu/kanade/tachiyomi/extension/ru/libmanga/LibManga.kt
mangalib.me disable download chapters for unauth users. Revert last update
> [Ru] Libmanga. Revert changes from 19->20 update

- src/zh/onemanhua/build.gradle
- src/zh/onemanhua/src/eu/kanade/tachiyomi/extension/zh/onemanhua/Onemanhua.kt
> Fix ohmanhua decryption

- src/pt/mangahost/build.gradle
- src/pt/mangahost/src/eu/kanade/tachiyomi/extension/pt/mangahost/MangaHost.kt
> Fix covers not loading at MangáHost

- src/pt/goldenmangas/build.gradle
- src/pt/goldenmangas/src/eu/kanade/tachiyomi/extension/pt/goldenmangas/GoldenMangas.kt
> Revert GoldenMangás to previous design

- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStreamFactory.kt
> Update Komiktap : wpmangastream

- src/ko/newtoki/build.gradle
- src/ko/newtoki/src/eu/kanade/tachiyomi/extension/ko/newtoki/NewToki.kt
v1.2.17
=====
* Fix page load error due to source change
> Update Newtoki Extension v1.2.17

- src/ru/libmanga/build.gradle
- src/ru/libmanga/src/eu/kanade/tachiyomi/extension/ru/libmanga/LibManga.kt
> Fix mangalib.me manga pages

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> madara: Add olaoe.giize.com

- src/all/foolslide/build.gradle
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/FoolSlideFactory.kt
Jaimini's Box is dead and has removed their reader from the site.
> Remove Jaimini's Box

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStreamFactory.kt
Fixes #4368 and #4404 
First time contributing. Let me know if I need to fix anything.
> Move AsuraScans from Madara to WP MangaStream

- src/all/wpmangastream/build.gradle
Not sure if I should change extension's version, since I didn't actually change anything inside of it. And I didn't build/test it, but this shouldn't break anything, I think.
> Fix typo for WP MangaStream 

- src/pt/mangasproject/build.gradle
- src/pt/mangasproject/src/eu/kanade/tachiyomi/extension/pt/mangasproject/MangasProject.kt
- src/pt/mangasproject/src/eu/kanade/tachiyomi/extension/pt/mangasproject/MangasProjectFactory.kt
> Add Toonei

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/Madara.kt
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> Add FDM and Argos Scan

- src/zh/wnacg/build.gradle
- src/zh/wnacg/src/eu/kanade/tachiyomi/extension/zh/wnacg/wnacg.kt
> Fix wnacg thumbnails loading

- .github/runner-files/ci-gradle.properties
- .github/workflows/pr_build_check.yml
Based on https://github.com/inorichi/tachiyomi/pull/3891
> Cache Gradle dependencies for PR build check workflow

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Another update to Madara...
The site is really slow at the moment, but probably it will normalize after a while.
Closes #4523.
> Update Neox URL

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/Madara.kt
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
I apologize, I didn't saw these issues when I opened the previous PR, otherwise I would have submitted all the changes in just one.
Closes #4512.
Closes #4513.
> Add Projeto Scanlator and Hikari Scan

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> Update WordExcerpt URLs

- src/zh/onemanhua/build.gradle
- src/zh/onemanhua/src/eu/kanade/tachiyomi/extension/zh/onemanhua/Onemanhua.kt
Handle 2 new ways of processing images. Updated extension name
Fixes  #4539
> Fix Ohmanhua / COCOManhua

- .github/ISSUE_TEMPLATE/source_bug.md
- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/Madara.kt
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Sorry about the Update source_bug.md commit, it should be the same as before but it's the result of a rebase - not too sure how I should fix that (or if I even need to).
Closes #4462
Closes #4419
Closes #4418
Closes #4410
Closes #3803
Closes #4558
Closes #4532
Deleted luxyscans - doesn't seem to exist anymore, chrome tells me: luxyscans.com’s server IP address could not be found.
Manga Spark and Manga Starz - search needs to bypassed via webview (doing a search in webview brings the cloudflare page)
> Madara Updates 

- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStreamFactory.kt
> Add Silence Scan

- src/en/mangasee/build.gradle
- src/en/mangasee/src/eu/kanade/tachiyomi/extension/en/mangasee/Mangasee.kt
> Use scan status instead of published status

- src/all/hitomi/AndroidManifest.xml
- src/all/hitomi/build.gradle
- src/all/hitomi/src/eu/kanade/tachiyomi/extension/all/hitomi/Hitomi.kt
- src/all/hitomi/src/eu/kanade/tachiyomi/extension/all/hitomi/HitomiActivity.kt
> Add hitomi.la URL intent

- src/en/hentainexus/AndroidManifest.xml
- src/en/hentainexus/build.gradle
- src/en/hentainexus/src/eu/kanade/tachiyomi/extension/en/hentainexus/HentaiNexus.kt
- src/en/hentainexus/src/eu/kanade/tachiyomi/extension/en/hentainexus/HentaiNexusActivity.kt
> Add hentainexus URL intent

- src/en/hentai2read/AndroidManifest.xml
- src/en/hentai2read/build.gradle
- src/en/hentai2read/src/eu/kanade/tachiyomi/extension/en/hentai2read/Hentai2Read.kt
- src/en/hentai2read/src/eu/kanade/tachiyomi/extension/en/hentai2read/Hentai2ReadActivity.kt
> Add hentai2read URL intent

- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStream.kt
Closes #4593 
Closes #4461
Closes #4428
> Wpmangastream fixes

- src/en/mangalife/build.gradle
- src/en/mangalife/src/eu/kanade/tachiyomi/extension/en/mangalife/MangaLife.kt
- src/en/mangasee/build.gradle
- src/en/mangasee/src/eu/kanade/tachiyomi/extension/en/mangasee/Mangasee.kt
> Update Covers url for Mangalife and Mangasee

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes #4618.
0 results in https://wordexcerpt.com/team/webtoon
Maybe there should be a buffer period before merging to see if this is temporary? I don't know, I'm a simple man.
*build.gradle has been update - hooray!*
> Remove WordExcerpt 

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStreamFactory.kt
Move Shea Manga from Madara to WP MangaStream
> Move Shea Manga from Madara to WP MangaStream

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
add chapter timestamp on KlanKomik and AstralLibrary
> Update some Madara source chapter timestamp

- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStream.kt
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStreamFactory.kt
- add FlameScans Closes #4354
- update new Mangastream manga details 
- Fix chapter date on SheaManga and KomikAV
> Update WP MangaStream

- src/id/ngomik/build.gradle
- src/id/ngomik/src/eu/kanade/tachiyomi/extension/id/ngomik/Ngomik.kt
some chapter didn't show author and status properly
> Fix Ngomik manga detail

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes #4570.
Closes #4650.
Closes #4653.
> Fix Neox, add MangaTeca and YuriVerso

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/Madara.kt
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
- add RuyaManga Closes #4670
- add HimeraFansub Closes #4669 
- add MangaBaz Closes #4668
- add Manhuaga Closes #4666
- add MangaCultivator Closes #4660
- handle timestamp (min/hour/day) ago for turkish
> Madara Update

- src/all/komga/CHANGELOG.md
- src/all/komga/build.gradle
- src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/Komga.kt
use `book.metadata.releaseDate` or `book.fileLastModified` for chapter date instead of `book.lastModified`
> [Komga] fix chapter date display

- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStreamFactory.kt
> WP MangaStream add source

- src/all/emerald/build.gradle
- src/all/emerald/src/eu/kanade/tachiyomi/extension/all/emerald/Emerald.kt
- fix Emerald manga details Closes #4719
- fix Emerald last tag issue
- fix Emerald max 60 manga Closes #4721
> Emerald fix some bug

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
add NTSVoidScans Closes #4710
add ToonGod Closes #4711
add Hscans Closes #4726
add WebToonily Closes #4712
add MangaRoma Closes #4728
> Madara source update

- src/all/paprika/build.gradle
- src/all/paprika/src/eu/kanade/tachiyomi/extension/all/paprika/PaprikaFactory.kt
- add ReadMangaFox Closes #4680
- add MangaStream.Xyz Closes #4746
> Paprika add Sources

- src/all/foolslide/build.gradle
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/FoolSlideFactory.kt
> FoolSlide add Source

- src/pt/tsukimangas/build.gradle
- src/pt/tsukimangas/src/eu/kanade/tachiyomi/extension/pt/tsukimangas/TsukiMangas.kt
> Fix mangas not loading at Tsuki

- src/zh/jinmantiantang/build.gradle
- src/zh/jinmantiantang/src/eu/kanade/tachiyomi/extension/zh/jinmantiantang/Jinmantiantang.kt
Solve the problem that the pictures are arranged in reverse order after being segmented
> Solve the problem that the pictures are arranged in reverse order after being segmented

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
- add NekoBreaker Closes #4766
- add Manganelo.link Closes #4765
- add ApollComics Closes #4760
- add KisekiManga Closes #4756
- add FreeWebtoonCoins Closes #4755
> Madara add sources

- src/en/mangahub/build.gradle
- src/en/mangahub/src/eu/kanade/tachiyomi/extension/en/mangahub/Mangahub.kt
only shows result one result (first manga) from each site page
Closes #4799
> Mangahub fix search issue

- src/zh/jinmantiantang/build.gradle
- src/zh/jinmantiantang/src/eu/kanade/tachiyomi/extension/zh/jinmantiantang/Jinmantiantang.kt
> <Jinmantiantang>Optimize the algorithm to solve the position deviation when cutting pictures

- src/all/webtoons/build.gradle
- src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/WebtoonsDefault.kt
some title didnt shows chapter list as it should be
Closes #4786
> Webtoon fix some chapter list

- CONTRIBUTING.md
Since the removal of the "Browse" button, the descriptions don't make much sense at first impressions.
> Disambiguation of extension entry points.

- CONTRIBUTING.md
> better syntax highlighting for gradle snippets

- src/all/emerald/build.gradle
- src/all/emerald/src/eu/kanade/tachiyomi/extension/all/emerald/Emerald.kt
> Emerald fix old chapter

- src/en/thepropertyofhate/build.gradle
- src/en/thepropertyofhate/src/eu/kanade/tachiyomi/extension/en/thepropertyofhate/ThePropertyOfHate.kt
> The Property of Hate: chapters should be reversed!

- src/pt/mangahost/build.gradle
- src/pt/mangahost/src/eu/kanade/tachiyomi/extension/pt/mangahost/MangaHost.kt
> Update MangáHost url

- src/pt/mangayabu/build.gradle
- src/pt/mangayabu/src/eu/kanade/tachiyomi/extension/pt/mangayabu/MangaYabu.kt
> Update MangaYabu url

- src/es/zahard/build.gradle
- src/es/zahard/src/eu/kanade/tachiyomi/extension/es/zahard/Zahard.kt
> Zahard : moved to new domain

- src/es/zahard/build.gradle
- src/es/zahard/src/eu/kanade/tachiyomi/extension/es/zahard/Zahard.kt
> Zahard: latest updates implemented

- src/pt/unionmangas/AndroidManifest.xml
- src/pt/unionmangas/build.gradle
- src/pt/unionmangas/src/eu/kanade/tachiyomi/extension/pt/unionmangas/UnionMangas.kt
- src/pt/unionmangas/src/eu/kanade/tachiyomi/extension/pt/unionmangas/UnionMangasUrlActivity.kt
Also added the current source URL to Manifest.
> Fix wrong title in details parse at UnionMangás

- src/ar/teamx/build.gradle
- src/ar/teamx/src/eu/kanade/tachiyomi/extension/ar/teamx/TeamX.kt
TeamX fix no pages found 
Closes #4860
> TeamX fix no pages found

- src/en/readm/build.gradle
- src/en/readm/src/eu/kanade/tachiyomi/extension/en/readm/ReadM.kt
manga status not included(recently added)
Closes #4432
> ReadM fix manga Status

- src/ar/teamx/build.gradle
- src/ar/teamx/src/eu/kanade/tachiyomi/extension/ar/teamx/TeamX.kt
other page chapter list not listed
Closes #4864
> TeamX fix NextPage chapter list

- src/ru/remanga/build.gradle
- src/ru/remanga/src/eu/kanade/tachiyomi/extension/ru/remanga/Remanga.kt
> [Ru] Remanga. Fix default popular sorting. Fix encoding pages to png

- CONTRIBUTING.md
continues #4828
I can't push to that branch.
> [CI SKIP] Improve wording, manga details new info

- src/pt/tsukimangas/build.gradle
- src/pt/tsukimangas/src/eu/kanade/tachiyomi/extension/pt/tsukimangas/TsukiMangas.kt
> Fix chapter images not loading at Tsuki

- src/pt/mangasproject/build.gradle
- src/pt/mangasproject/src/eu/kanade/tachiyomi/extension/pt/mangasproject/MangasProject.kt
> Fix description in manga details at MangasProject

- src/pt/tsukimangas/build.gradle
- src/pt/tsukimangas/src/eu/kanade/tachiyomi/extension/pt/tsukimangas/TsukiMangas.kt
Let's see how long it keeps working this time...
> Fix chapter images not loading at Tsuki (again)

- src/zh/jinmantiantang/build.gradle
- src/zh/jinmantiantang/src/eu/kanade/tachiyomi/extension/zh/jinmantiantang/Jinmantiantang.kt
> URL update, the original URL was abandoned, resulting in mainland China users unable to link.

- src/en/mangareader/build.gradle
- src/en/mangareader/src/eu/kanade/tachiyomi/extension/en/mangareader/MRPFactory.kt
Their certificate expired a month ago (28 days ago to be exact) and they still didn't renew it. I guess it's time to switch protocols
> Mangapanda: Switch protocol from HTTPS to HTTP

- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStreamFactory.kt
> add WPMangaStream source

- src/all/wpcomics/build.gradle
- src/all/wpcomics/src/eu/kanade/tachiyomi/extension/all/wpcomics/WPComicsFactory.kt
Manhua ES chapter page contain other images
> WPComics fix ManhuaES bug

- src/id/komiku/build.gradle
- src/id/komiku/src/eu/kanade/tachiyomi/extension/id/komiku/Komiku.kt
fix Komiku chapter list
fix Komiku chapter TimeStamp
> Komiku fix chapter

- src/ru/libmanga/AndroidManifest.xml
- src/ru/libmanga/build.gradle
- src/ru/libmanga/src/eu/kanade/tachiyomi/extension/ru/libmanga/LibManga.kt
- src/ru/libmanga/src/eu/kanade/tachiyomi/extension/ru/libmanga/LibMangaActivity.kt
> [RU] Libmanga. Fix latest page. Add intent to mangalib.me

- src/en/mangalife/build.gradle
- src/en/mangalife/src/eu/kanade/tachiyomi/extension/en/mangalife/MangaLife.kt
- src/en/mangasee/build.gradle
- src/en/mangasee/src/eu/kanade/tachiyomi/extension/en/mangasee/Mangasee.kt
add isekai genre for Mangalife and Mangasee
Closes #4931
> Mangalife and Mangasee add genre

- src/pt/supermangas/build.gradle
- src/pt/supermangas/src/eu/kanade/tachiyomi/extension/pt/supermangas/SuperMangasGeneric.kt
- src/pt/supermangas/src/eu/kanade/tachiyomi/extension/pt/supermangas/source/SuperMangas.kt
> Fix search not working at Super Mangás

- src/en/mangaowl/build.gradle
- src/en/mangaowl/src/eu/kanade/tachiyomi/extension/en/mangaowl/MangaOwl.kt
url change Closes #4935
fix manga detail/info
> MangaOwl update

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Example: https://comickiba.com/manga/the-strongest-cheat-player/
> ComicKiba: fix pageListParse for some manga

- src/zh/manhuadui/build.gradle
- src/zh/manhuadui/src/eu/kanade/tachiyomi/extension/zh/manhuadui/Manhuadui.kt
Manhuadui: update site base url
Closes #4976
> Manhuadui: update site base url

- src/id/komiku/build.gradle
- src/id/komiku/src/eu/kanade/tachiyomi/extension/id/komiku/Komiku.kt
> fix Komiku chapter

- src/all/genkan/build.gradle
- src/all/genkan/src/eu/kanade/tachiyomi/extension/all/genkan/GenkanFactory.kt
KKJ Scans have now merged with Reaper Scans
> Remove KKJ Scans

- src/id/ngomik/build.gradle
- src/id/ngomik/src/eu/kanade/tachiyomi/extension/id/ngomik/Ngomik.kt
- Update baseUrl
- add timestamp to latest chapter
> Update Ngomik 

- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStream.kt
previous regex match other thing in some site
Closes #4771
> update WP MangaStream regex

- src/en/vizshonenjump/build.gradle
- src/en/vizshonenjump/src/eu/kanade/tachiyomi/extension/en/vizshonenjump/VizShonenJump.kt
> Add thumbnail to mangaDetailsParse at Viz

- src/all/fmreader/build.gradle
- src/all/fmreader/src/eu/kanade/tachiyomi/extension/all/fmreader/FMReader.kt
- src/all/fmreader/src/eu/kanade/tachiyomi/extension/all/fmreader/FMReaderFactory.kt
- remove ReadComicOnlineOrg Closes #4794
- add HeroScan Closes #4476
- fix manga description
> update FMReader 

- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStreamFactory.kt
> fix: remove tab that should be 4 spaces

- src/en/hentainexus/build.gradle
- src/en/hentainexus/src/eu/kanade/tachiyomi/extension/en/hentainexus/HentaiNexus.kt
Authored by: @MoistSac 
I simply copied the source he/she provided in https://github.com/inorichi/tachiyomi-extensions/issues/4938 and it works from testing.
Moist if you want me to change anything or remove the PR feel free to comment, I just wanted this fixed.
Fixes https://github.com/inorichi/tachiyomi-extensions/issues/4938
> Fixed imageloading 

- src/en/comicastle/build.gradle
- src/en/comicastle/src/eu/kanade/tachiyomi/extension/en/comicastle/Comicastle.kt
fix Comicastle page list only load 1 page
Closes #5045
> fix Comicastle page list

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
fix chibi manga issue … Closes #4342 
add Manhua SY source Closes #5049
fix nightComic error 400 Closes #5052
fix astral Library issue … Closes #5054
> update & fix Madara

- src/zh/copymanga/build.gradle
- src/zh/copymanga/src/eu/kanade/tachiyomi/extension/zh/copymanga/CopyManga.kt
for library gobal search
search manga title with the same text
添加标题的繁体转简体的设定选项
方便在Library中的搜索，
简体和繁体混在一起不太好搜索
> Add CopyManga Setting Change Title to Simplified Chinese Optionally

- src/all/genkan/build.gradle
- src/all/genkan/src/eu/kanade/tachiyomi/extension/all/genkan/GenkanFactory.kt
- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
removed krakenscans,friendlytranslations,funlist,ninjascans
Closes #4575
> Remove Dead Source

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> Update Neox URL (again)

- src/en/timelessleaf/build.gradle
- src/en/timelessleaf/src/eu/kanade/tachiyomi/extension/en/timelessleaf/TimelessLeaf.kt
add chapter timeStamp by taking it from url
> TimelessLeaf add chapter timeStamp

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStreamFactory.kt
from wpmangastream back to madara
Closes #5018
> move back bestManhua to madara

- src/id/komiku/build.gradle
- src/id/komiku/src/eu/kanade/tachiyomi/extension/id/komiku/Komiku.kt
change baseUrl Closes #4913
fix manga request
fix selector Closes #4927
fix manga cover
> fix Komiku

- src/id/bacamanga/build.gradle
- src/id/bacamanga/src/eu/kanade/tachiyomi/extension/id/bacamanga/BacaManga.kt
Fix and closes #2213 and #5036
This source cannot be merge with other using wp mangastream because they use custom code and obfuscation.
Date, chapters list and reader now are working fine.
PS: rot13 made me crazy :)
> Patch baca manga

- src/en/manhwamanga/build.gradle
- src/en/manhwamanga/src/eu/kanade/tachiyomi/extension/en/manhwamanga/ManhwaManga.kt
- src/zh/jinmantiantang/build.gradle
- src/zh/jinmantiantang/src/eu/kanade/tachiyomi/extension/zh/jinmantiantang/Jinmantiantang.kt
Fixes and closes #5095 and #5082
> Fix #5095 and #5082

- CONTRIBUTING.md
related to: https://github.com/inorichi/tachiyomi/issues/2089
> [CI SKIP] info about chapter upload date

- src/ru/libmanga/build.gradle
- src/ru/libmanga/src/eu/kanade/tachiyomi/extension/ru/libmanga/LibManga.kt
> [Ru] Mangalib. Fix 403 image without referer

- src/zh/jinmantiantang/build.gradle
- src/zh/jinmantiantang/src/eu/kanade/tachiyomi/extension/zh/jinmantiantang/Jinmantiantang.kt
1. Fix a bug that some mangas are always blocked
2. Fix a bug that there are always some missing lines in manga picture.
3. Fix a translation typo
> [Jinmantiantang] Fix unintended block bug and missing pixels bug

- src/en/readmanhwa/build.gradle
- src/en/readmanhwa/src/eu/kanade/tachiyomi/extension/en/readmanhwa/ReadManhwa.kt
> Readmanhwa.com enhanced search and filters - fix #4972

- src/ru/libmanga/build.gradle
- src/ru/libmanga/src/eu/kanade/tachiyomi/extension/ru/libmanga/LibManga.kt
Fix default server
Fix images not loading. Cause server require double slash after hostname
> [Ru]Mangalib. Fix images with double slash

- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStream.kt
when there is no chapter, ext throw "index 0 size 0" instead "no chapter found"
> fix wp mangastream no chapter issue

- src/all/wpmangareader/build.gradle
- src/all/wpmangareader/src/eu/kanade/tachiyomi/extension/all/wpmangareader/WPMangaReader.kt
- src/id/comicfx/build.gradle
- src/id/comicfx/src/eu/kanade/tachiyomi/extension/id/comicfx/ComicFx.kt
- src/id/manhuaid/build.gradle
- src/id/manhuaid/src/eu/kanade/tachiyomi/extension/id/manhuaid/ManhuaID.kt
fix latest chapter timestamp, error when there is no chapter
add latest chapter timestamp to manhuaID
> fix & add latest chapter timestamp

- src/en/timelessleaf/build.gradle
- src/en/timelessleaf/src/eu/kanade/tachiyomi/extension/en/timelessleaf/TimelessLeaf.kt
> Timelessleaf add manga description

- src/en/mangahasu/build.gradle
- src/en/mangahasu/src/eu/kanade/tachiyomi/extension/en/mangahasu/Mangahasu.kt
> fix mangahasu description

- src/all/wpmangareader/build.gradle
- src/all/wpmangareader/src/eu/kanade/tachiyomi/extension/all/wpmangareader/WPMangaReader.kt
- src/all/wpmangareader/src/eu/kanade/tachiyomi/extension/all/wpmangareader/WPMangaReaderFactory.kt
wp mangareader update their theme
Closes #5193
> update WP MangaReader

- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStreamFactory.kt
add ChiOtaku source
Closes #5181
> WP MangaStream add ChiOtaku

- src/id/komiku/build.gradle
- src/id/komiku/src/eu/kanade/tachiyomi/extension/id/komiku/Komiku.kt
Fixing Komiku extension and add filtering capability
> Fix can't load pages Komiku

- src/all/wpcomics/build.gradle
- src/all/wpcomics/src/eu/kanade/tachiyomi/extension/all/wpcomics/WPComicsFactory.kt
older chapter cant load image
Closes #5215
> fix wpComics - manhuaes page parse

- CONTRIBUTING.md
> [CI SKIP] URL intent filter

- src/en/naniscans/build.gradle
- src/en/naniscans/src/eu/kanade/tachiyomi/extension/en/naniscans/NaniScans.kt
> NaniScans: Fix 404 when loading chapters

- src/all/foolslide/build.gradle
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/HentaiCafe.kt
> Hentai cafe url fix

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> Update Neox URL (again x2)

- src/fr/scantrad/build.gradle
- src/fr/scantrad/src/eu/kanade/tachiyomi/extension/fr/scantrad/Scantrad.kt
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/5243
> baseUrl : "https://scantrad.fr" -> "https://scantrad.net"

- src/fr/scantrad/build.gradle
- src/fr/scantrad/src/eu/kanade/tachiyomi/extension/fr/scantrad/Scantrad.kt
Requests with default user-agent was being blocked.
Closes #5243
> Replace default blocked user-agent

- src/ru/remanga/build.gradle
- src/ru/remanga/src/eu/kanade/tachiyomi/extension/ru/remanga/Remanga.kt
Closes https://github.com/tachiyomiorg/tachiyomi-extensions/issues/5264
> Change User-Agent Remanga

- src/zh/jinmantiantang/build.gradle
- src/zh/jinmantiantang/src/eu/kanade/tachiyomi/extension/zh/jinmantiantang/Jinmantiantang.kt
Main work: Users now can add genres they don't like in preference panel, mangas match any one of genres will not show in result.
Others: changing thumbnail size to 4:3, and some code fix
> Achieve a genre filter at client end

- src/all/fmreader/build.gradle
- src/all/fmreader/src/eu/kanade/tachiyomi/extension/all/fmreader/FMReaderFactory.kt
changed baseUrl for RawLH 
issue #5290
> baseUrl: loveheaven.net -> lovehug.net (#5290)

- src/en/mangaowl/build.gradle
- src/en/mangaowl/src/eu/kanade/tachiyomi/extension/en/mangaowl/MangaOwl.kt
Fix search issue. Closes #5168 
The issue arises because it is now need to specify search_field on the search URL
> Fix search issue #5168

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
add NeatManga Closes #5249
add WarQueenScan Closes #5283
remove KnightNoScanlation Closes #5260
> madara add n remove source

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStreamFactory.kt
> move klanKomik from madara to wpMangastream

- src/all/wpcomics/build.gradle
- src/all/wpcomics/src/eu/kanade/tachiyomi/extension/all/wpcomics/WPComicsFactory.kt
> WpComics - manhuaes fix some page parse

- src/en/webnovel/build.gradle
- src/en/webnovel/src/eu/kanade/tachiyomi/extension/en/webnovel/Webnovel.kt
add lock icon for locked chapter
Closes #5296
> Webnovel.com add lock to chapter name

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/Madara.kt
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
- add arabic for parsing date
- make chapter new banner selector to value
- fix atikrost chapter name and time issue Closes #5262
- fix mangaArabTeam chapter time issue Closes #5277
- replace mangaKitsu with mangaCrimson Closes #5213
- fix astralLibrary reversed chapter order issue
> Madara fix n replace

- src/zh/onemanhua/build.gradle
- src/zh/onemanhua/src/eu/kanade/tachiyomi/extension/zh/onemanhua/Onemanhua.kt
> Added new Cocomanhua decryption key. Changed decryption logic to use a series of decryption keys

- src/tr/mangaship/build.gradle
- src/tr/mangaship/src/eu/kanade/tachiyomi/extension/tr/mangaship/MangaShip.kt
> fix mangaShip

- src/fr/mangakawaii/build.gradle
- src/fr/mangakawaii/src/eu/kanade/tachiyomi/extension/fr/mangakawaii/MangaKawaii.kt
fixed browse and latest not displaying correct or any results at all
closes issue #5284
> fix mangakawaii (#5284)

- src/ru/mangahub/build.gradle
- src/ru/mangahub/src/eu/kanade/tachiyomi/extension/ru/mangahub/Mangahub.kt
> [Ru]Mangahub. Update page list selector name

- src/fr/scantrad/build.gradle
- src/fr/scantrad/src/eu/kanade/tachiyomi/extension/fr/scantrad/Scantrad.kt
fixed scantrad blocking tachis user agent by randomizing it for now. guess they'll keep blocking so maybe we need to remove them
Closes #5322
> fix scantrad

- src/fr/mangakawaii/build.gradle
- src/fr/mangakawaii/src/eu/kanade/tachiyomi/extension/fr/mangakawaii/MangaKawaii.kt
tachi didn't get all chapters. had to change the place where to get it. forgot it the other day
Closes #5205
> Mangakawaii fix getting all chapters

- src/ar/gmanga/build.gradle
- src/ar/gmanga/src/eu/kanade/tachiyomi/extension/ar/gmanga/Gmanga.kt
> Fix gmanga bug when searching with text given empty filter list

- src/ko/toonkor/build.gradle
- src/ko/toonkor/src/eu/kanade/tachiyomi/extension/ko/toonkor/Toonkor.kt
> changed baseUrl: toonkor.ws -> tkor.cx

- src/all/fmreader/build.gradle
- src/all/fmreader/src/eu/kanade/tachiyomi/extension/all/fmreader/FMReader.kt
- src/all/fmreader/src/eu/kanade/tachiyomi/extension/all/fmreader/FMReaderFactory.kt
> FMReader - fix RawLH

- src/en/manhwamanga/build.gradle
- src/en/manhwamanga/src/eu/kanade/tachiyomi/extension/en/manhwamanga/ManhwaManga.kt
> change search url

- src/all/wpcomics/build.gradle
- src/all/wpcomics/src/eu/kanade/tachiyomi/extension/all/wpcomics/WPComics.kt
some source like mangasum need it to load chapter images
Closes #4284
> WPComics add headers

- src/all/fmreader/build.gradle
- src/all/fmreader/src/eu/kanade/tachiyomi/extension/all/fmreader/FMReader.kt
- src/all/fmreader/src/eu/kanade/tachiyomi/extension/all/fmreader/FMReaderFactory.kt
update FMReader for new theme
fix kissLove using new theme Closes #5299
clean thing after update factory
revert parseChapterDate to private
> update FMReader for new theme

- src/all/fmreader/build.gradle
- src/all/fmreader/src/eu/kanade/tachiyomi/extension/all/fmreader/FMReader.kt
> fix FMReader extra ghost chapter

- src/ru/remanga/build.gradle
- src/ru/remanga/src/eu/kanade/tachiyomi/extension/ru/remanga/Remanga.kt
> change title from en_name to rus_name

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> Madara remove source request

- src/zh/jinmantiantang/build.gradle
- src/zh/jinmantiantang/src/eu/kanade/tachiyomi/extension/zh/jinmantiantang/Jinmantiantang.kt
Update baseUrl for jinmantiantang,
Old baseUrl can't visit websites from mainland China.
> Update baseUrl for jinmantiantang

- src/ru/mangaclub/build.gradle
- src/ru/mangaclub/src/eu/kanade/tachiyomi/extension/ru/mangaclub/Mangaclub.kt
https://mangaclub.ru/ - site rework
> [Ru] Mangaclub. Site rework

- src/id/mangayu/build.gradle
- src/id/mangayu/src/eu/kanade/tachiyomi/extension/id/mangayu/MangaYu.kt
mangaYu tweaking their theme
Closes #5375
> fix mangaYu issue

- src/all/zbulu/build.gradle
- src/all/zbulu/src/eu/kanade/tachiyomi/extension/all/zbulu/ZbuluFactory.kt
> added bulumanga to zbulu

- src/en/earlymanga/build.gradle
- src/en/earlymanga/src/eu/kanade/tachiyomi/extension/en/earlymanga/EarlyManga.kt
> earlymanga add genre in manga details

- src/en/eggporncomics/build.gradle
- src/en/eggporncomics/src/eu/kanade/tachiyomi/extension/en/eggporncomics/Eggporncomics.kt
> <Eggporncomics>: fix showing popular

- src/all/comicake/build.gradle
- src/all/comicake/src/eu/kanade/tachiyomi/extension/all/comicake/ComiCakeFactory.kt
- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
added voidscans to madara. removed PTScans from ComicCake
Closes #5372
> add and remove sources

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> adding geceninlordu to madara

- src/all/wpcomics/build.gradle
- src/all/wpcomics/src/eu/kanade/tachiyomi/extension/all/wpcomics/WPComicsFactory.kt
A little hack to exclude raw mangas using selector.
Closes #5400
> Remove RAWs from Mangasum search

- src/all/batoto/build.gradle
- src/all/batoto/src/eu/kanade/tachiyomi/extension/all/batoto/BatoTo.kt
Fixes:
- Totally sort
- A-Z sort
- Genres
Adds:
- Z-A sort
- Status
- Origin
Removes:
- Stars (doesn't work)
- Styles (included in Genres)
- Demographic (included in Genres)
Closes #5399
> Fixes Bato.to Filtering

- src/all/wpcomics/build.gradle
- src/all/wpcomics/src/eu/kanade/tachiyomi/extension/all/wpcomics/WPComicsFactory.kt
> WP Comics add mangasum RAW

- src/all/webtoons/build.gradle
- src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/WebtoonsFactory.kt
Changed date format
Closes #5405
> Fixes Webtoons Spanish

- src/all/batoto/build.gradle
- src/all/batoto/src/eu/kanade/tachiyomi/extension/all/batoto/BatoTo.kt
Fixes Typo I made in previous fix
> Bato.to Typo fix

- src/ru/remanga/build.gradle
- src/ru/remanga/src/eu/kanade/tachiyomi/extension/ru/remanga/Remanga.kt
Fixes downloading manga with the same name to one folder
> remanga double name title

- src/all/zbulu/build.gradle
- src/all/zbulu/src/eu/kanade/tachiyomi/extension/all/zbulu/ZbuluFactory.kt
> fix bulu manga - chapter image issue

- src/es/kumanga/build.gradle
- src/es/kumanga/src/eu/kanade/tachiyomi/extension/es/kumanga/Kumanga.kt
Closes #5406 
Due to obfuscation the extension no longer worked.
The PageList also no longer worked due to obfuscation.
> Fix Kumanga (ES) mangas list and pages list not loading

- src/all/simplyhentai/build.gradle
- src/all/simplyhentai/src/eu/kanade/tachiyomi/extension/all/simplyhentai/SimplyHentai.kt
1. Parses manga upload date and assign as Chapter attribute
2. Sets default manga status as completed
> Add simply hentai ext chapter upload date

- src/it/novelleleggere/build.gradle
- src/it/novelleleggere/src/eu/kanade/tachiyomi/extension/it/novelleleggere/NovelleLeggere.kt
some chapter cant load images
Closes #5349
> fix novelle leggere chapter issue

- src/all/wpmangareader/build.gradle
- src/all/wpmangareader/src/eu/kanade/tachiyomi/extension/all/wpmangareader/WPMangaReaderFactory.kt
> WP MangaReader add TurkToon

- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStream.kt
> WP MangaStream fix manga details

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/Madara.kt
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes #5436 
Closes #5424 
Closes #5414
> adding new sources to madara

- src/all/webtoons/build.gradle
- src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/WebtoonsFactory.kt
> fix webtoon es parse date

- src/all/ninemanga/build.gradle
- src/all/ninemanga/src/eu/kanade/tachiyomi/extension/all/ninemanga/NineMangaFactory.kt
Closes #5439
dupes:
Closes #5446
Closes #5444
add more dupes here for easy mass close:
Closes #5455
Closes #5454
> ninemanga change to https

- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDex.kt
end chapter doesnt get "[END]" added to chapter name
> fix mangadex end chapter

- src/all/batoto/build.gradle
- src/all/batoto/src/eu/kanade/tachiyomi/extension/all/batoto/BatoToFactory.kt
> Add Nsfw flag to Bato.to

- src/ru/libmanga/build.gradle
- src/ru/libmanga/src/eu/kanade/tachiyomi/extension/ru/libmanga/LibManga.kt
> Fix Mangalib - getting chapters

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStreamFactory.kt
Closes #5457 
Closes #4890 
Closes #5469
> added 2 sources to madara

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> added 2 new sources to madara

- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStreamFactory.kt
their tweaked site return to default format
Closes #5482
> WP MangaStream fix westManga

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> madara fix arangScans

- src/ru/libmanga/build.gradle
- src/ru/libmanga/src/eu/kanade/tachiyomi/extension/ru/libmanga/LibManga.kt
> [RU] Mangalib. Fix loading cover and getting chapters

- src/ru/remanga/build.gradle
- src/ru/remanga/src/eu/kanade/tachiyomi/extension/ru/remanga/Remanga.kt
Closes #5489 
this fix could not last forever. guess they won't stop blocking tachi from now on
> fix remanga blocking tachi

- src/all/wpcomics/build.gradle
- src/all/wpcomics/src/eu/kanade/tachiyomi/extension/all/wpcomics/WPComicsFactory.kt
popular, latest, and search only show few manga (only page 1)
> WP Comics fix manhuaES paging issue

- src/all/hitomi/build.gradle
- src/all/hitomi/src/eu/kanade/tachiyomi/extension/all/hitomi/Hitomi.kt
> Fix hardcoded image subdomain

- src/zh/dmzj/build.gradle
- src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt
Closes #5501 
i fixed the urls for getting all info, but it seems like they didn't change the chapter urls on their site:
_should be images.dmzj1._
you can't read on the website either. so we have to wait until they change it. extension is ready tho
> <dmzj>: fix url

- src/all/wpcomics/build.gradle
- src/all/wpcomics/src/eu/kanade/tachiyomi/extension/all/wpcomics/WPComics.kt
- src/all/wpcomics/src/eu/kanade/tachiyomi/extension/all/wpcomics/WPComicsFactory.kt
fix manga genre
fix manga description (some manga doesnt show desc)
> WP Comics fix manhuaES manga detail

- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDex.kt
see title
dex ext was throwing many 429s. neko changed requests per sec to 1, so i did the same for the ext
> change rate limiting from 4 requests/sec to 1 r/s

- src/zh/qiximh/build.gradle
- src/zh/qiximh/src/eu/kanade/tachiyomi/extension/zh/qiximh/Qiximh.kt
changed baseUrl: http://qiximh.com/ -> http://qiximh1.com/
Closes #5503
> <qiximanhua>: fixed baseUrl

- src/ru/nudemoon/build.gradle
- src/ru/nudemoon/src/eu/kanade/tachiyomi/extension/ru/nudemoon/Nudemoon.kt
> [RU] Nude-Moon. Changing domain name

- src/ru/allhentai/build.gradle
- src/ru/allhentai/src/eu/kanade/tachiyomi/extension/ru/allhentai/AllHentai.kt
> [RU] AllHentai. Fixed loading images

- src/ru/libmanga/build.gradle
- src/ru/libmanga/src/eu/kanade/tachiyomi/extension/ru/libmanga/LibManga.kt
This commit removes the chapter list limitation. This limitation made it difficult to obtain a complete list of chapters, since it received a list of chapters only for the first translator.
> [RU] Mangalib. Fixed getting chapters(1+ translators)

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/Madara.kt
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> added vanguardbun and clovermanga to madara

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> fix tritiniascans

- src/ru/desu/build.gradle
- src/ru/desu/src/eu/kanade/tachiyomi/extension/ru/desu/Desu.kt
- src/ru/remanga/build.gradle
- src/ru/remanga/src/eu/kanade/tachiyomi/extension/ru/remanga/Remanga.kt
Closes https://github.com/tachiyomiorg/tachiyomi-extensions/issues/5511
> Redirect from api Remanga and Desu (open in browser)

- src/all/luscious/build.gradle
- src/all/luscious/src/eu/kanade/tachiyomi/extension/all/luscious/Luscious.kt
> Fix page order not following site's default content specific ordering

- src/all/wpmangastream/build.gradle
arkon sama forgot to update it #5525
https://github.com/tachiyomiorg/tachiyomi-extensions/commit/514374f13a29958d9c9c6c2a7fd0ee3746e93f23
> wpmangastream build.gradle

- src/ru/remanga/build.gradle
- src/ru/remanga/src/eu/kanade/tachiyomi/extension/ru/remanga/Remanga.kt
- src/ru/remanga/src/eu/kanade/tachiyomi/extension/ru/remanga/dto/Dto.kt
> Remanga chapter number x.x.x format

- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDex.kt
> [Mangadex] Exclude thumbnail downloads from rate limiting

- src/fr/mangakawaii/build.gradle
- src/fr/mangakawaii/src/eu/kanade/tachiyomi/extension/fr/mangakawaii/MangaKawaii.kt
Fix empty page on mangakawaii extension. Link to issue 5518
Closes # 5518
> Issue 5518 : <Mangakawaii [FR]>: <No page found on any manga>

- src/all/komga/CHANGELOG.md
- src/all/komga/build.gradle
- src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/Komga.kt
- src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/dto/Dto.kt
- display Series summary from books if no summary exists for Series. closes gotson/komga#391
- display Series authors. closes #5481
> [Komga] Display book aggregated data on Series screen

- src/ru/remanga/build.gradle
- src/ru/remanga/src/eu/kanade/tachiyomi/extension/ru/remanga/Remanga.kt
Fix chapter number for remanga
> [Ru]Remanga. Fix chapter number

- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStream.kt
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStreamFactory.kt
fix mangakyo and westmanga manga details issue
> WP Mangastream fix issue

- src/fr/scantrad/build.gradle
- src/fr/scantrad/src/eu/kanade/tachiyomi/extension/fr/scantrad/Scantrad.kt
try triple randomizer 
Closes #5560
> Scantrad user agent

- src/all/foolslide/build.gradle
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/FoolSlide.kt
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/FoolSlideFactory.kt
change url
add manga details for italian
ignore case sensitive for regex
Closes #5561
> Foolslide phoenixscans

- src/fr/scantrad/build.gradle
- src/fr/scantrad/src/eu/kanade/tachiyomi/extension/fr/scantrad/Scantrad.kt
try hexa random that will/should be close to/similar if use pc/normal
> scantrad useragent2

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes #5530 
Closes #5539 
Closes #5554  
Closes #5564  
Closes #5559
> add new sources to madara

- src/zh/copymanga/build.gradle
- src/zh/copymanga/src/eu/kanade/tachiyomi/extension/zh/copymanga/CopyManga.kt
> copymanga: fix crash on low android sdk level

- src/fr/scantrad/build.gradle
- src/fr/scantrad/src/eu/kanade/tachiyomi/extension/fr/scantrad/Scantrad.kt
look like the random int only called once and being used again causing repeated number
> scantrad userAgent3

- src/en/latisbooks/build.gradle
- src/en/latisbooks/src/eu/kanade/tachiyomi/extension/en/latisbooks/Latisbooks.kt
adds upload date and annotates nsfw
no related issue
> Latisbooks add upload date to chapters

- src/en/vizshonenjump/build.gradle
- src/en/vizshonenjump/src/eu/kanade/tachiyomi/extension/en/vizshonenjump/VizImageInterceptor.kt
- src/en/vizshonenjump/src/eu/kanade/tachiyomi/extension/en/vizshonenjump/VizShonenJump.kt
> Fix exception when there is no description or key at VIZ

- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStreamFactory.kt
change flame scans to their new site Closes #5588
add MangaIndonesia source Closes #5180
> WP MangaStream add source & change url

- src/en/mangamutiny/AndroidManifest.xml
- src/en/mangamutiny/build.gradle
- src/en/mangamutiny/src/eu/kanade/tachiyomi/extension/en/mangamutiny/MangaMutiny.kt
- src/en/mangamutiny/src/eu/kanade/tachiyomi/extension/en/mangamutiny/MangaMutinyUrlActivity.kt
- Fixing an artist NullPointer exception
- Can now open manga from the mangamutiny.org website in the Tachiyomi app
> MangaMutiny bugfix + link handler

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
timestamp not showing in pm scans 
add Raw Mangas Closes #5619
add SiXiang Scans Closes #5597
> Open Madara PR

- src/zh/dmzj/AndroidManifest.xml
- src/zh/dmzj/build.gradle
- src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt
- src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/DmzjUrlActivity.kt
1. Add fallback api to fetch hidden manga, can close #5599 and #4286 now.
2. Add URL intent filter.
> [zh-dmzj]Add fallback api to fetch hidden manga and URL intent filter.

- src/all/genkan/build.gradle
- src/all/genkan/src/eu/kanade/tachiyomi/extension/all/genkan/Genkan.kt
timestamp longer than 1 year shows as current year
> fix genkan year timestamp

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
madara fix bestmanhua no page bug
Closes #5632
> madara fix bestmanhua no page bug

- src/all/foolslide/build.gradle
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/FoolSlideFactory.kt
> FoolSlide remove dokiFansubs

- src/en/mangasee/build.gradle
- src/en/mangasee/src/eu/kanade/tachiyomi/extension/en/mangasee/Mangasee.kt
some chapter cant load properly, because some chapter url cant load with extra 0
Closes #5636
> fix mangasee some chapter cant load

- src/fr/mangakawaii/build.gradle
- src/fr/mangakawaii/src/eu/kanade/tachiyomi/extension/fr/mangakawaii/MangaKawaii.kt
> fix mangakawaii pages doesnt load

- src/en/readcomiconline/build.gradle
- src/en/readcomiconline/src/eu/kanade/tachiyomi/extension/en/readcomiconline/Readcomiconline.kt
Tested on my phone where the issue happens - seems to work fine
> ReadComicOnline: change user-agent (closes #5612)

- src/fr/mangakawaii/build.gradle
- src/fr/mangakawaii/src/eu/kanade/tachiyomi/extension/fr/mangakawaii/MangaKawaii.kt
> fix mangakawaii pages - season 3

- src/en/earlymanga/build.gradle
- src/en/earlymanga/src/eu/kanade/tachiyomi/extension/en/earlymanga/EarlyManga.kt
> EarlyManga: new URL domain .org

- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStreamFactory.kt
> wp MangaStream add ResetScans

- src/en/tsumino/build.gradle
- src/en/tsumino/src/eu/kanade/tachiyomi/extension/en/tsumino/Tsumino.kt
- src/en/tsumino/src/eu/kanade/tachiyomi/extension/en/tsumino/TsuminoUtils.kt
> Tsumino: Parse tags into in-app tags instead of description

- multisrc/overrides/src/madara/bestmanhua/BestManhua.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> remove BestManhua's override

- src/all/fmreader/build.gradle
- src/all/fmreader/src/eu/kanade/tachiyomi/extension/all/fmreader/FMReader.kt
> RawLH: fix pages showing loading gif

- common-dependencies.gradle
- common.gradle
> fixes main method running from android studio for multisrc

- .github/workflows/build_pull_request.yml
- .github/workflows/build_push.yml
- multisrc/build.gradle.kts
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/ThemeSourceGenerator.kt
- simplifies running the generators
- `AndroidManifest.xml` override support for #5667
> improve tasks, support AndroidManifest override

- src/fr/mangakawaii/build.gradle
- src/fr/mangakawaii/src/eu/kanade/tachiyomi/extension/fr/mangakawaii/MangaKawaii.kt
> mangakawaii fix pages 4

- src/all/fmreader/build.gradle
- src/all/fmreader/src/eu/kanade/tachiyomi/extension/all/fmreader/FMReader.kt
- src/all/fmreader/src/eu/kanade/tachiyomi/extension/all/fmreader/FMReaderFactory.kt
KissLove: Fix loading gif instead of pages (closes #5704)
Manga-TR: Fix user agent, the site says to change browser with current user agent (no opened issue)
> FMReader: fix KissLove and Manga-TR

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/eromuse/EroMuseGenerator.kt
> Missing nsfw directives

- src/es/doujinyang/build.gradle
- src/es/doujinyang/src/eu/kanade/tachiyomi/extension/es/doujinyang/DoujinYang.kt
> Doujin-Yang: new URL

- multisrc/overrides/madara/hunterfansub/src/HunterFansub.kt
- multisrc/overrides/madara/ichirinnohanayuri/src/IchirinNoHanaYuri.kt
- multisrc/overrides/madara/justforfun/src/JustForFun.kt
- multisrc/overrides/madara/klikmanga/src/KlikManga.kt
- multisrc/overrides/madara/kombatch/src/Kombatch.kt
> fix packages

- src/zh/manhuadui/build.gradle
- src/zh/manhuadui/src/eu/kanade/tachiyomi/extension/zh/manhuadui/Manhuadui.kt
- New base URL and image server
- Remove decryption, the site doesn't use it anymore
- Minor fixes: chapter name, regex, image URL
Closes #5726
> Manhuadui: new URL, remove decryption and other changes

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> fix void scans

- multisrc/overrides/madara/clovermanga/src/CloverManga.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> fix clover manga url

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
need restart app after update
Closes #5768
> fix webnovel.live shadowing webnovel.com

- src/vi/hentaivn/build.gradle
- src/vi/hentaivn/src/eu/kanade/tachiyomi/extension/vi/hentaivn/HentaiVN.kt
> HentaiVN: fix covers and no results

- src/en/rainofsnow/build.gradle
- src/en/rainofsnow/src/eu/kanade/tachiyomi/extension/en/rainofsnow/RainOfSnow.kt
> fixed missing css selector Rain of snow

- src/vi/hentaivn/build.gradle
- src/vi/hentaivn/src/eu/kanade/tachiyomi/extension/vi/hentaivn/HentaiVN.kt
> HentaiVN: fix search, show more useful errors

- src/pt/mangasproject/build.gradle
- src/pt/mangasproject/src/eu/kanade/tachiyomi/extension/pt/mangasproject/MangasProject.kt
- src/pt/mangasproject/src/eu/kanade/tachiyomi/extension/pt/mangasproject/MangasProjectFactory.kt
> Temporary fix Cloudflare bypassing in Leitor.net

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/paprika/PaprikaGenerator.kt
> add source MangaHere.today

- src/pt/tsukimangas/build.gradle
- src/pt/tsukimangas/src/eu/kanade/tachiyomi/extension/pt/tsukimangas/TsukiMangas.kt
> Fix JSON error when title is null at Tsuki

- src/en/mangakatana/build.gradle
- src/en/mangakatana/src/eu/kanade/tachiyomi/extension/en/mangakatana/MangaKatana.kt
> Mangakatana: fix search when found only one manga

- multisrc/overrides/madara/manga347/src/Manga347.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> fix manga347 page issue

- src/en/rainofsnow/build.gradle
- src/en/rainofsnow/src/eu/kanade/tachiyomi/extension/en/rainofsnow/RainOfSnow.kt
> fix rainOfSnow revese chapter

- multisrc/overrides/madara/manwhaclub/src/ManwhaClub.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
Requested by Ichigo Kurosaki on Discord.
> fix manhwa.club's name

- multisrc/overrides/fmreader/manhwasmut/src/ManhwaSmut.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/fmreader/FMReaderGenerator.kt
> Manhwasmut

- src/en/earlymanga/build.gradle
- src/en/earlymanga/src/eu/kanade/tachiyomi/extension/en/earlymanga/EarlyManga.kt
> earlyManga add header & fix pages

- src/all/ninehentai/build.gradle
- src/all/ninehentai/src/eu/kanade/tachiyomi/extension/all/ninehentai/NineHentai.kt
> NineHentai: fix galleries with broken last page

- src/all/hitomi/build.gradle
- src/all/hitomi/src/eu/kanade/tachiyomi/extension/all/hitomi/Hitomi.kt
js script on the site also does toLowerCase for some reason, so I just did the same
Closes #4816
> Hitomi.la: fix search when using upper case

- src/en/earlymanga/build.gradle
- src/en/earlymanga/src/eu/kanade/tachiyomi/extension/en/earlymanga/EarlyManga.kt
> fix earlymanga chapter page & clean chapter name

- src/vi/hentaivn/build.gradle
- src/vi/hentaivn/src/eu/kanade/tachiyomi/extension/vi/hentaivn/HentaiVN.kt
> HentaiVN: maybe fix cloudflare issue

- src/fr/scantrad/build.gradle
- src/fr/scantrad/src/eu/kanade/tachiyomi/extension/fr/scantrad/Scantrad.kt
> Remove referer header causing a 403 HTTP error

- common.gradle
> Disable unused AGP features

- multisrc/overrides/wpmangastream/mangaraworg/src/MangaRawOrg.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStreamGenerator.kt
> fix mangaraw.org dupe class name

- src/fr/scantrad/build.gradle
- src/fr/scantrad/src/eu/kanade/tachiyomi/extension/fr/scantrad/Scantrad.kt
> Generate a totally random user-agent

- src/fr/scantrad/build.gradle
- src/fr/scantrad/src/eu/kanade/tachiyomi/extension/fr/scantrad/Scantrad.kt
> Add header accept-language

- src/fr/scantrad/build.gradle
- src/fr/scantrad/src/eu/kanade/tachiyomi/extension/fr/scantrad/Scantrad.kt
Bypass 403 attempt 4523 :laughing:
> Use a common user-agent

- src/fr/mangakawaii/build.gradle
- src/fr/mangakawaii/src/eu/kanade/tachiyomi/extension/fr/mangakawaii/MangaKawaii.kt
> fix MangaKawaii chapter list

- src/ko/newtoki/build.gradle
- src/ko/newtoki/src/eu/kanade/tachiyomi/extension/ko/newtoki/ManaToki.kt
- src/ko/newtoki/src/eu/kanade/tachiyomi/extension/ko/newtoki/NewToki.kt
- src/ko/newtoki/src/eu/kanade/tachiyomi/extension/ko/newtoki/NewTokiFactory.kt
* Better RateLimit
* New Search filter for ManaToki.
> Update Newtoki Extension to v1.2.20

- multisrc/overrides/madara/shieldmanga/additional.gradle.kts
- multisrc/overrides/madara/shieldmanga/src/ShieldManga.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> add rate limiter to Shield Manga

- src/ru/remanga/build.gradle
- src/ru/remanga/src/eu/kanade/tachiyomi/extension/ru/remanga/Remanga.kt
Users complain about loading images and app crush. Remove merge part of image
Closes https://github.com/tachiyomiorg/tachiyomi/issues/4515
> [Ru]Remanga. Fix issue with merging part of image

- src/en/mangajar/build.gradle
- src/en/mangajar/src/eu/kanade/tachiyomi/extension/en/mangajar/MangaJar.kt
> fix mangajar pages issue

- multisrc/overrides/madara/manga347/src/Manga347.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> fix Manga347 pages

- multisrc/overrides/madara/mangacrimson/src/MangaCrimson.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> remove Manga Crimson source

- src/pt/mangasproject/build.gradle
- src/pt/mangasproject/src/eu/kanade/tachiyomi/extension/pt/mangasproject/MangasProject.kt
> Increase rate limiting in MangásProject

- src/pt/tsukimangas/build.gradle
- src/pt/tsukimangas/src/eu/kanade/tachiyomi/extension/pt/tsukimangas/TsukiMangas.kt
I also changed the rate limiting, it should now prevent the HTTP 429 errors that some users reported on Discord.
> Change chapter list API endpoint at Tsuki

- src/pt/supermangas/build.gradle
- src/pt/supermangas/src/eu/kanade/tachiyomi/extension/pt/supermangas/SuperMangasGeneric.kt
- src/pt/supermangas/src/eu/kanade/tachiyomi/extension/pt/supermangas/source/SuperMangas.kt
> Temporary fix images not loading at SuperMangás

- src/pt/mangahost/build.gradle
- src/pt/mangahost/src/eu/kanade/tachiyomi/extension/pt/mangahost/MangaHost.kt
> Update MangáHost url and add a harsh rate limiting

- src/ja/senmanga/build.gradle
- src/ja/senmanga/src/eu/kanade/tachiyomi/extension/ja/senmanga/SenManga.kt
Closes #5977
- Update selectors
- Utilize Time tag for exact dates
> Fixes to Sen-Manga

- src/en/mangafast/build.gradle
- src/en/mangafast/src/eu/kanade/tachiyomi/extension/en/mangafast/MangaFast.kt
> MangaFast: fix thumbnails

- multisrc/overrides/madara/dreammanga/src/DreamManga.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> DreamManga: change url, fix chapter timestamp

- src/th/nekopost/build.gradle
- src/th/nekopost/src/eu/kanade/tachiyomi/extension/th/nekopost/Nekopost.kt
> Nekopost: new file server url

- src/en/hentai2read/build.gradle
- src/en/hentai2read/src/eu/kanade/tachiyomi/extension/en/hentai2read/Hentai2Read.kt
> Hentai2Read: Fix id search

- src/es/tumangaonline/build.gradle
- src/es/tumangaonline/src/eu/kanade/tachiyomi/extension/es/tumangaonline/TuMangaOnline.kt
> TuMangaOnline: add rate limit

- multisrc/overrides/wpmangareader/hikariscan/src/HikariScan.kt
- multisrc/overrides/wpmangareader/sekaikomik/src/Sekaikomik.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangareader/WPMangaReaderGenerator.kt
- Adds Hikari Scan / Pt 2 Closes #5925 
- Adds Sekaikomik / Closes #4645
> WPMangaReader Updates

- src/all/komga/CHANGELOG.md
- src/all/komga/build.gradle
- src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/Komga.kt
> [Komga] filter by authors

- multisrc/overrides/wpmangareader/ngomik/src/Ngomik.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangareader/WPMangaReader.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangareader/WPMangaReaderGenerator.kt
- Fixes page URLs / Closes #6023
- Removed unnecessary Ngomik override
- Incremented version code
> [WPMangaReader] Theme Update - Fixes Pagination 

- multisrc/overrides/madara/mangaus/src/MangaUS.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
- Adds pageListParseSelector to override / Closes #6036
> [Madara] MangaUS - Fix Pages

- src/en/tcbscans/build.gradle
- src/en/tcbscans/src/eu/kanade/tachiyomi/extension/en/tcbscans/TCBScans.kt
Couldn't find a way to check it without actually opening a chapter, so I've added one more network call
Closes #5608
> TCBScans: filter out latest chapter if it's not released yet

- multisrc/overrides/madara/manhuaplus/src/ManhuaPlus.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> ManhuaPlus: fix pages issue

- multisrc/overrides/madara/mangasorigines/src/MangasOrigines.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> [Madara] Mangas Origines - New Source

- src/ja/mangaraw/build.gradle
- src/ja/mangaraw/src/eu/kanade/tachiyomi/extension/ja/mangaraw/MangaRaw.kt
Closes #5928
Closes #5941
Also fixed a warning
> MangaRaw: add referer to fix images

- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDexFactory.kt
> [Mangadex] add language for chapters with out specified language

- src/all/komga/CHANGELOG.md
- src/all/komga/build.gradle
- src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/Komga.kt
This is a maintenance release to help fix 2 issues:
- exception catching while building filter list (#6074)
- error logs while loading filter values (#6047)
> [KOMGA] add logs and try/catch

- src/en/guya/build.gradle
- src/en/guya/src/eu/kanade/tachiyomi/extension/en/guya/Guya.kt
Some small improvements that should fix some inconsistencies with the scanlator cache.
There's some blocking IO here, but it shouldn't ever be called (unless the IO-scheduled call fails and/or guya.moe dies).
> Update networking functions in Guya.

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangabox/MangaBoxGenerator.kt
- src/all/imhentai/build.gradle
- src/all/imhentai/src/eu/kanade/tachiyomi/extension/all/imhentai/IMHentai.kt
> Update Imhentai domain

- src/zh/manhuagui/build.gradle
- src/zh/manhuagui/src/eu/kanade/tachiyomi/extension/zh/manhuagui/Manhuagui.kt
Add preference to use official mirror URL.
> [ZH-Manhuagui] Add preference to use official mirror URL.

- multisrc/overrides/madara/neoxscanlator/src/NeoxScanlator.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
Update NeoxScanlator URL conform mentioned in #6100
> Update NeoxScanlator URL

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangareader/WPMangaReaderGenerator.kt
> moved geceninLordu from madara to wpmangareader

- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDex.kt
changed the rate limit of mangadex extension to 2/sec
> Mangadex: changed rate limit to 2/sec

- src/en/mangalife/build.gradle
- src/en/mangalife/src/eu/kanade/tachiyomi/extension/en/mangalife/MangaLife.kt
> fix chapter url suffix location

- multisrc/overrides/mangabox/mangabat/src/Mangabat.kt
- multisrc/overrides/mangabox/mangairo/src/Mangairo.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangabox/MangaBoxGenerator.kt
> Finish mangairo and mangabat changes 

- CONTRIBUTING.md
> [SKIP CI] improve wording

- src/en/mangalife/build.gradle
- src/en/mangalife/src/eu/kanade/tachiyomi/extension/en/mangalife/MangaLife.kt
- src/en/mangasee/build.gradle
- src/en/mangasee/src/eu/kanade/tachiyomi/extension/en/mangasee/Mangasee.kt
Closes #6136 (MangaSee)
Closes #6138 (MangaLife)
> MangaSee, MangaLife: fix pages again, add rate limiting

- multisrc/overrides/mangabox/mangabat/src/Mangabat.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangabox/MangaBoxGenerator.kt
Built and tested - it works fine now
Closes #4557
> MangaBat: fix URL for real this time

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStreamGenerator.kt
> removed komiktap from mangastream

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/genkan/GenkanGenerator.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/genkan/GenkanOriginalGenerator.kt
> LynxScans: move to the new Genkan to fix search

- multisrc/overrides/madara/hiperdex/src/Hiperdex.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> Hiperdex: add 18+ tag

- src/pt/supermangas/build.gradle
- src/pt/supermangas/src/eu/kanade/tachiyomi/extension/pt/supermangas/SuperMangasGeneric.kt
- src/pt/supermangas/src/eu/kanade/tachiyomi/extension/pt/supermangas/source/SuperHentais.kt
- src/pt/supermangas/src/eu/kanade/tachiyomi/extension/pt/supermangas/source/SuperMangas.kt
> Fix missing response at SuperMangas

- multisrc/overrides/madara/aloalivn/src/Aloalivn.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> Aloalivn: fix pages issue

- src/en/rainofsnow/build.gradle
- src/en/rainofsnow/src/eu/kanade/tachiyomi/extension/en/rainofsnow/RainOfSnow.kt
> RainOfSnow: fix duplicate entries, add chapter timestamp

- src/all/vinnieVeritas/build.gradle
- src/all/vinnieVeritas/src/eu/kanade/tachiyomi/extension/all/vinnieVeritas/vinnieVeritas.kt
in the shower rn so I can't test this but I think it'll work w/e
> CCC webcomic: support multi-image chapters

- src/en/mangalife/build.gradle
- src/en/mangalife/src/eu/kanade/tachiyomi/extension/en/mangalife/MangaLife.kt
- src/en/mangasee/build.gradle
- src/en/mangasee/src/eu/kanade/tachiyomi/extension/en/mangasee/Mangasee.kt
> Fix MangaLife and MangaSee

- multisrc/overrides/madara/manhuaes/src/ManhuaES.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> ManhuaES: fix chapter empty in some manga

- multisrc/overrides/wpmangastream/komikcast/src/KomikCast.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStreamGenerator.kt
<strike>need to fix the chapter list maybe with regex which i dont know much LOL</strike>
*update i fix it
Closes #6212
> KomikCast: fix website redesign

- multisrc/overrides/madara/leviatanscans/src/LeviatanScansFactory.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/genkan/GenkanGenerator.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> Moved LeviatanScans & SleepingKnightScans to Madara

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> LeviatanScans & SleepingKnightScans: update  ext version

- src/id/bacakomik/build.gradle
- src/id/bacakomik/src/eu/kanade/tachiyomi/extension/id/bacakomik/Bacakomik.kt
> Bacakomik: fix empty pages 

- CONTRIBUTING.md
> [SKIP CI] fix grammar

- src/fr/mangakawaii/build.gradle
- src/fr/mangakawaii/src/eu/kanade/tachiyomi/extension/fr/mangakawaii/MangaKawaii.kt
Closes #6046 but more like fix #6132
> MangaKawaii: fix page issue

- multisrc/overrides/madara/manhuaes/src/ManhuaES.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
fix page selector Closes #6264
clean some import
> ManhuaES: fix page issue in some chapter

- src/en/guya/AndroidManifest.xml
- src/en/guya/build.gradle
- src/en/guya/src/eu/kanade/tachiyomi/extension/en/guya/GuyaUrlActivity.kt
Add so Imgur links can be opened in Tachi via Guya proxy
> Imgur intent filter for Guya

- multisrc/overrides/wpmangareader/sekaikomik/src/Sekaikomik.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangareader/WPMangaReaderGenerator.kt
> <SekaiKomik>: change baseUrl

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
Closes #6279 
was mangarawr - is manhwa.live
the site is still in its BETA. changes can happen
> <Mangarawr>: change baseUrl and name

- src/fr/mangakawaii/build.gradle
- src/fr/mangakawaii/src/eu/kanade/tachiyomi/extension/fr/mangakawaii/MangaKawaii.kt
Closes #6296
make it encoded so they do some work to see the selector LOL
> MangaKawaii: fix empty pages

- src/en/earlymanga/build.gradle
- src/en/earlymanga/src/eu/kanade/tachiyomi/extension/en/earlymanga/EarlyManga.kt
make the selector string need to be decoded first before looking 
fix load latest next page
> EarlyManga: fix chapter list, fix latest load more

- src/es/lectormanga/build.gradle
- src/es/lectormanga/src/eu/kanade/tachiyomi/extension/es/lectormanga/LectorManga.kt
- src/es/tmohentai/build.gradle
- src/es/tmohentai/src/eu/kanade/tachiyomi/extension/es/tmohentai/TMOHentai.kt
- src/es/tumangaonline/build.gradle
- src/es/tumangaonline/src/eu/kanade/tachiyomi/extension/es/tumangaonline/TuMangaOnline.kt
**TMO:**
**LectorTMO:**
**TMOHentai:**
> Update TMO, LectorTMO & TMOHentai

- src/es/lectormanga/build.gradle
- src/es/lectormanga/src/eu/kanade/tachiyomi/extension/es/lectormanga/LectorManga.kt
- src/es/mangamx/build.gradle
- src/es/mangamx/src/eu/kanade/tachiyomi/extension/es/mangamx/MangaMx.kt
- src/es/tumangaonline/build.gradle
- src/es/tumangaonline/src/eu/kanade/tachiyomi/extension/es/tumangaonline/TuMangaOnline.kt
**LectorManga**
**TuMangaOnline**
**MangaMx**
> Fix LectorManga HTTP error 403, Add MangaMx genre filter and config screen

- src/all/cubari/build.gradle
- src/all/cubari/src/eu/kanade/tachiyomi/extension/all/cubari/Cubari.kt
- src/all/cubari/src/eu/kanade/tachiyomi/extension/all/cubari/CubariFactory.kt
- src/en/guya/AndroidManifest.xml
- src/en/guya/build.gradle
- src/en/guya/src/eu/kanade/tachiyomi/extension/en/guya/GuyaUrlActivity.kt
Just slowly migrating proxy things over from Guya to Cubari.
Also, added some small QoL improvements to improve Cubari's discoverability and error messages.
> Migrate Guya proxy to Cubari, QoL updates to Cubari.

- src/fr/scanmanga/build.gradle
- src/fr/scanmanga/src/eu/kanade/tachiyomi/extension/fr/scanmanga/ScanManga.kt
* Better maintainability of the json parsing
* Add genre and status when coming from search
* Correctly split different authors
> ScanManga: small improvements

- src/en/mangafast/build.gradle
- src/en/mangafast/src/eu/kanade/tachiyomi/extension/en/mangafast/MangaFast.kt
> MangaFast: various fixes

- multisrc/overrides/madara/aloalivn/src/Aloalivn.kt
- multisrc/overrides/madara/manga347/src/Manga347.kt
- multisrc/overrides/madara/mangagreat/src/MangaGreat.kt
- multisrc/overrides/madara/mangarave/src/MangaRave.kt
- multisrc/overrides/madara/manhuafast/src/ManhuaFast.kt
- multisrc/overrides/madara/manhuaplus/src/ManhuaPlus.kt
- multisrc/overrides/madara/manhuaus/src/ManhuaUS.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
update madara factory chapter page selector
add manga1st source Closes #6215
fix mangarave chapter timestamp
> Update factory code, Manga1st: add source, MangaRave: fix date

- multisrc/overrides/madara/shinzoo/src/Shinzoo.kt
- multisrc/overrides/madara/shinzooscan/src/ShinzooScan.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> change name and language code

- multisrc/overrides/wpmangastream/komikcast/src/KomikCast.kt
- multisrc/overrides/wpmangastream/silencescan/src/SilenceScan.kt
- multisrc/overrides/wpmangastream/westmanga/src/WestManga.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStream.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStreamGenerator.kt
add series type(manga/manhwa/manhua/other) thinggy to genre for some source
> Update WPMangaStream factory code: add series type to genre

- multisrc/overrides/fmreader/ksgroupscans/src/KSGroupScans.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/fmreader/FMReaderGenerator.kt
> KSGroupScans: add source

- src/fr/mangakawaii/build.gradle
- src/fr/mangakawaii/src/eu/kanade/tachiyomi/extension/fr/mangakawaii/MangaKawaii.kt
I tried fixing #6360 with no success.
However, I fixed some issues with cover loading and made some clean up, so I'm at least submitting them.
> MangaKawaii: Improve cover loading + clean up

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/nepnep/NepNep.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/nepnep/NepNepGenerator.kt
- src/id/komiku/build.gradle
- src/id/komiku/src/eu/kanade/tachiyomi/extension/id/komiku/Komiku.kt
- src/id/maidmanga/build.gradle
- src/id/maidmanga/src/eu/kanade/tachiyomi/extension/id/maidmanga/MaidManga.kt
- src/id/manhuaid/build.gradle
- src/id/manhuaid/src/eu/kanade/tachiyomi/extension/id/manhuaid/ManhuaID.kt
add series type(manga/manhwa/manhua/other) thinggy to genre
> Add series type to genre for: MangaSee, MangaLife, Komiku, Maid, ManhuaID

- src/all/lanraragi/build.gradle
- src/all/lanraragi/src/eu/kanade/tachiyomi/extension/all/lanraragi/LANraragi.kt
- Fixes categories not appearing from large responses 
- Random item visibility no longer reliant on a clean server DB
- Smaller improvements
- Fixes #6341
> LANraragi: Category, Random, and DNS fixes

- multisrc/overrides/wpmangastream/komikgo/src/KomikGO.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStreamGenerator.kt
Ran into a issue with a wip extension tester and identified it wasn't my fault(surprisingly). This should fix the extension not being able to be loaded in Tachiyomi
> Fix KomicGO loading

- src/ru/comx/build.gradle
- src/ru/comx/src/eu/kanade/tachiyomi/extension/ru/comx/ComX.kt
> [Ru] ComX. Fix images

- multisrc/overrides/madara/voidscans/src/Voidscans.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> Removed Voidscans, Added Cervo Scanlator

- src/all/batoto/build.gradle
I forgot to update the version number on Pull request #6419
> Forgot to update version number of bato.to

- src/all/webtoons/build.gradle
- src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/Webtoons.kt
Should fix Webtoons not working for EU users
Reported in #6417 and #6394
> Webtoons Fix for EU users

- src/es/vcpvmp/build.gradle
- src/es/vcpvmp/src/eu/kanade/tachiyomi/extension/es/vcpvmp/VCPVMPFactory.kt
Fixed IllegalArgumentException when saving thumbnail and when loading chapter images.
> Fixed VMP thumbnails and chapters not loading

- src/all/batoto/build.gradle
- src/all/batoto/src/eu/kanade/tachiyomi/extension/all/batoto/BatoTo.kt
- src/all/batoto/src/eu/kanade/tachiyomi/extension/all/batoto/BatoToFactory.kt
Filters out not wanted languages: Problem returns no results if the is none of the selected language on the first page.
Also fixes not parsing seconds for date giving chapters that where released less that 1 min ago no release date.
Closes #6201
> Bato.to improved language filter

- multisrc/overrides/madara/mangadiyari/src/MangaDiyari.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> change baseUrl & add override for date

- multisrc/overrides/webtoons/webtoons/src/WebtoonsFactory.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/webtoons/WebtoonsGenerator.kt
> Small fix for webtoons backward compabilty

- multisrc/overrides/foolslide/helveticascans/src/HelveticaScans.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/foolslide/FoolSlideGenerator.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> removed void scans and helvetica scans

- src/en/silentmangaaudition/build.gradle
- src/en/silentmangaaudition/src/eu/kanade/tachiyomi/extension/en/silentmangaaudition/ExtensionData.kt
- src/en/silentmangaaudition/src/eu/kanade/tachiyomi/extension/en/silentmangaaudition/SilentMangaAudition.kt
> Add SMA-14 to SilentMangaAudition

- multisrc/overrides/mangasproject/leitornet/src/LeitorNet.kt
- multisrc/overrides/mangasproject/mangalivre/src/MangaLivre.kt
- multisrc/overrides/mangasproject/toonei/src/Toonei.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangasproject/MangasProject.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangasproject/MangasProjectGenerator.kt
Just as a side note, #6475 can be closed since it's not an extension issue.
> Make HTTP errors explicit in API calls at MangasProject

- src/pt/mangahost/build.gradle
- src/pt/mangahost/src/eu/kanade/tachiyomi/extension/pt/mangahost/MangaHost.kt
> Update MH url

- src/fr/scanmanga/build.gradle
- src/fr/scanmanga/src/eu/kanade/tachiyomi/extension/fr/scanmanga/ScanManga.kt
> ScanManga: add scanlators to chapter list

- src/fr/mangakawaii/build.gradle
- src/fr/mangakawaii/src/eu/kanade/tachiyomi/extension/fr/mangakawaii/MangaKawaii.kt
> MangaKawaii: add scanlator

- src/fr/japanread/build.gradle
- src/fr/japanread/src/eu/kanade/tachiyomi/extension/fr/japanread/Japanread.kt
> Japanread: fix empty search

- build.gradle
- buildSrc/build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
> Update Gradle and AGP, remove jcenter

- src/ru/libmanga/build.gradle
- src/ru/libmanga/src/eu/kanade/tachiyomi/extension/ru/libmanga/LibManga.kt
> MangaLib: Fix licensing and 18+ status, changing sorting settings

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
- add series type(manga/manhwa/manhua/other) thinggy to genre(s)
- add tag(s) to genre(s)
- remove author & artist name if the name is "Updating"
- add alternative name to manga description
> Madara: update manga info

- src/en/readcomiconline/build.gradle
- src/en/readcomiconline/src/eu/kanade/tachiyomi/extension/en/readcomiconline/Readcomiconline.kt
Updated domain from .to to .li and added Sports and Music to filter
Closes #6515
> ReadComicOnline: update domain and add new filter options

- src/en/rainofsnow/build.gradle
- src/en/rainofsnow/src/eu/kanade/tachiyomi/extension/en/rainofsnow/RainOfSnow.kt
website change things
Closes #6526
> RainOfSnow: fix issue 

- multisrc/overrides/madara/shieldmanga/src/ShieldManga.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> ShieldManga: fix chapter & page issue

- multisrc/overrides/madara/manhuaplus/src/ManhuaPlus.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
fix page issue for some chapter
Closes #6535
> ManhuaPlus: fix page issue

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/luscious/Luscious.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/luscious/LusciousGenerator.kt
The image server that Tachiyomi was using return 403 Forbidden, so I set it to use a different image server this results in a lower image resolution on Luscious extensions.
Close #6551
> Luscious fix images not loading

- src/pt/mangayabu/build.gradle
- src/pt/mangayabu/src/eu/kanade/tachiyomi/extension/pt/mangayabu/MangaYabu.kt
> Update MY! selectors

- src/it/mangaworld/build.gradle
- src/it/mangaworld/src/eu/kanade/tachiyomi/extension/it/mangaworld/Mangaworld.kt
> Updated the Mangaworld domain

- multisrc/overrides/wpmangareader/sekaikomik/src/Sekaikomik.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangareader/WPMangaReaderGenerator.kt
> <sekaikomik> change baseUrl

- src/en/multporn/build.gradle
- src/en/multporn/src/eu/kanade/tachiyomi/extension/en/multporn/Multporn.kt
> change search query parameter

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt
> add french to ongoing and completed status

- src/zh/copymanga/build.gradle
- src/zh/copymanga/src/eu/kanade/tachiyomi/extension/zh/copymanga/CopyManga.kt
close #6584 
P.S. May fix it (for my situation), but need more test in different networks.
> copymanga: fix manga image load problem

- src/pt/unionmangas/build.gradle
- src/pt/unionmangas/src/eu/kanade/tachiyomi/extension/pt/unionmangas/UnionMangas.kt
> Temporary fix 'UM' Cloudflare loop

- src/ru/remanga/build.gradle
- src/ru/remanga/src/eu/kanade/tachiyomi/extension/ru/remanga/Remanga.kt
- src/ru/remanga/src/eu/kanade/tachiyomi/extension/ru/remanga/dto/Dto.kt
Remanga add single pixels pages without reason. Remove it
> [Ru]Remanga. Fix single pixel pages

- src/ru/libmanga/build.gradle
- src/ru/libmanga/src/eu/kanade/tachiyomi/extension/ru/libmanga/LibManga.kt
Additionally removed a non-working filter.
closes #6609
> MangaLib: Show the scanlator as a team / Paid chapters hidden

- src/pt/unionmangas/build.gradle
- src/pt/unionmangas/src/eu/kanade/tachiyomi/extension/pt/unionmangas/UnionMangas.kt
I think that maybe the cat and mouse game started with this source too.
For precaution, I updated the rate limiting to be more harsh.
Closes #6622 for now.
> Update 'UM' selectors

- src/pt/hqdragon/build.gradle
- src/pt/hqdragon/src/eu/kanade/tachiyomi/extension/pt/hqdragon/HQDragon.kt
Looking at the source code, it seems that the site is from the same owners of Union Mangás.
Since it's the same case, and we are in a cat and mouse game with this source too, I added the blocking message.
If you can, when this PR gets merged, please add this source (HQ Dragon) to the "Too Difficult to maintain" section on #3475.
> Update 'HD' selectors and add blocking message

- src/en/mangapill/build.gradle
- src/en/mangapill/src/eu/kanade/tachiyomi/extension/en/mangapill/MangaPill.kt
Closes #6616 
Closes #6603 
Closes #6597 
Closes #6594
> <mangapill>: fix search + browse + filter

- multisrc/overrides/madara/fukushuunoyuusha/src/FukushuuNoYuusha.kt
- multisrc/overrides/madara/littlemonsterscan/src/LittleMonsterScan.kt
- multisrc/overrides/madara/pornwha/src/Pornwha.kt
- multisrc/overrides/madara/randomscan/src/RandomScan.kt
- multisrc/overrides/madara/threequeensscanlator/src/ThreeQueensScanlator.kt
- multisrc/overrides/madara/winterscan/src/WinterScan.kt
- multisrc/overrides/madara/wonderland/src/Wonderland.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
Adding new sources mentioned in the PRs below:
Closes #6513 
Closes #6538 
Closes #6629 
Closes #6636 
Closes #6639 
Closes #6641
> Adding news sources

- src/en/mangafast/build.gradle
- src/en/mangafast/src/eu/kanade/tachiyomi/extension/en/mangafast/MangaFast.kt
Fixes:
- filter out not released chapters
- fix title having non-title text on it
> MangaFast fixes

- src/fr/scantrad/build.gradle
- src/fr/scantrad/src/eu/kanade/tachiyomi/extension/fr/scantrad/Scantrad.kt
`Scantrad` released a new version of their website so I updated the extension. And I changed the user-agent to a mobile one, I don't know if they will block it too or not.
> scantrad : maj new version + modify user-agent

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/luscious/Luscious.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/luscious/LusciousGenerator.kt
Changes:
- Moved manga details parsing to API
- added more filters
- changed from one chapter per album to one chapter per page due to albums getting updated with new pages constantly
Closes  #6642
> Luscious various fixes and updates

- src/pt/tsukimangas/build.gradle
- src/pt/tsukimangas/src/eu/kanade/tachiyomi/extension/pt/tsukimangas/TsukiMangas.kt
> Update JSON property in popular at Tsuki

- multisrc/overrides/wpmangastream/sektedoujin/src/SekteDoujin.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStreamGenerator.kt
> <sektedoujin>: move sektedoujin from madara to wpmangastream

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/luscious/Luscious.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/luscious/LusciousGenerator.kt
Added:
- Option for Merging all pages into one Chapter (Fix problem mentioned in comments of #6701)
- Option to select resolution (added in case a situation like  #6551 happens again)
> Added Preferences Screen to Luscious

- src/id/komiku/build.gradle
- src/id/komiku/src/eu/kanade/tachiyomi/extension/id/komiku/Komiku.kt
> Komiku: fix chapter image

- multisrc/overrides/wpmangastream/xcalibrscans/src/xCaliBRScans.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStreamGenerator.kt
> xCaliBRScans: fix pages issue

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/fmreader/FMReader.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/fmreader/FMReaderGenerator.kt
> Fix ManhuaScan and HeroScan

- src/all/mangaplus/build.gradle
- src/all/mangaplus/src/eu/kanade/tachiyomi/extension/all/mangaplus/MangaPlus.kt
- src/all/mangaplus/src/eu/kanade/tachiyomi/extension/all/mangaplus/MangaPlusApi.kt
Updated `kotlinx-serialization-protobuf` from `1.0.1` to `1.2.0`.
Tested with `r3328` and `v0.10.12`, it's working fine.
> Update kotlinx-serialization-protobuf to match Kotlin version at MangaPlus

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangasproject/MangasProject.kt
- src/ja/shonenjumpplus/src/eu/kanade/tachiyomi/extension/ja/shonenjumpplus/ShonenJumpPlus.kt
- src/pt/bruttal/src/eu/kanade/tachiyomi/extension/pt/bruttal/Bruttal.kt
- src/pt/centraldemangas/src/eu/kanade/tachiyomi/extension/pt/centraldemangas/CentralDeMangas.kt
- src/pt/hipercool/src/eu/kanade/tachiyomi/extension/pt/hipercool/Hipercool.kt
- src/pt/hqnow/src/eu/kanade/tachiyomi/extension/pt/hqnow/HQNow.kt
- src/pt/mangatube/src/eu/kanade/tachiyomi/extension/pt/mangatube/MangaTube.kt
- src/pt/mundohentai/src/eu/kanade/tachiyomi/extension/pt/mundohentai/MundoHentai.kt
- src/pt/mundomangakun/src/eu/kanade/tachiyomi/extension/pt/mundomangakun/MundoMangaKun.kt
- src/pt/socialcomics/src/eu/kanade/tachiyomi/extension/pt/socialcomics/SocialComics.kt
- src/pt/tsukimangas/src/eu/kanade/tachiyomi/extension/pt/tsukimangas/TsukiMangas.kt
- src/pt/unionmangas/src/eu/kanade/tachiyomi/extension/pt/unionmangas/UnionMangas.kt
It shouldn't change anything to the users, so I don't bumped the `extVersionCode` of the extensions.
If it's better to bump them, just let me know.
> Remove JsonParser deprecation warning in some sources

- src/fr/kangaryu/build.gradle
There was a fix of the extension here, but he forgot to update the version
https://github.com/tachiyomiorg/tachiyomi-extensions/pull/6680
> Kangaryu version++

- src/all/cubari/build.gradle
- src/all/cubari/src/eu/kanade/tachiyomi/extension/all/cubari/Cubari.kt
Was trying to get JSONobject instead of string so the Series had problem updating.
> Cubari QoL Patch

- src/en/vizshonenjump/build.gradle
- src/en/vizshonenjump/src/eu/kanade/tachiyomi/extension/en/vizshonenjump/VizShonenJump.kt
Should close two issues reported by @spoutn1k at #6771.
> Fix JSON error when loading chapter at Viz

- src/all/cubari/build.gradle
- src/all/cubari/src/eu/kanade/tachiyomi/extension/all/cubari/Cubari.kt
Volume defaults to "Uncategorized" so if volume is "Uncategorized" don't show volume.
> Cubari QoL Update

- src/zh/kuaikanmanhua/build.gradle
- src/zh/kuaikanmanhua/src/eu/kanade/tachiyomi/extension/zh/kuaikanmanhua/Kuaikanmanhua.kt
Converted the old KKMH extension from ParsedHttpSource to HttpSource
Currently there's a bug where it is impossible to scroll to a previous chapter, but I believe it's caused by the very short images that KKMH provides messing with the webtoon viewer, as there is no issue going backwards when using other readers
Closes #3335
Closes #6665
> Fixed Kuaikanmanhua extension

- src/pt/taosect/build.gradle
- src/pt/taosect/src/eu/kanade/tachiyomi/extension/pt/taosect/TaoSect.kt
> Fix cover not loading at TS

- src/en/patchfriday/build.gradle
- src/en/patchfriday/src/eu/kanade/tachiyomi/extension/en/patchfriday/PatchFriday.kt
Fixes:
- Chapter title
- chapter number
- sets upload date to current date as it does not have upload dates
- set status to ongoing
- Changes chapters parsing
> Patchfriday various updates and fixes 

- multisrc/overrides/madara/mangafenix/src/MangaFenix.kt
- multisrc/overrides/madara/mangamitsu/src/MangaMitsu.kt
- multisrc/overrides/madara/mangayami/src/MangaYami.kt
- multisrc/overrides/madara/traduccionesamistosas/src/TraduccionesAmistosas.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
Closes #4939
Closes #6729
Closes #6487
> Adding news sources in Madara

- src/fr/japanread/build.gradle
- src/fr/japanread/src/eu/kanade/tachiyomi/extension/fr/japanread/Japanread.kt
In b13ccc27ecb301416e3b54949b4033da00297c1c "popular" filter was replaced by "most recent".
Reverting to original working version.
> Japanread: fix popular

- src/fr/japanread/build.gradle
- src/fr/japanread/src/eu/kanade/tachiyomi/extension/fr/japanread/Japanread.kt
Just added some filters to Japanread (strongly inspired by `Tapas` extension)
> Add filters Japanread (fr)

- src/en/dynasty/AndroidManifest.xml
- src/en/dynasty/build.gradle
- src/en/dynasty/src/eu/kanade/tachiyomi/extension/en/dynasty/DynastyAnthologies.kt
- src/en/dynasty/src/eu/kanade/tachiyomi/extension/en/dynasty/DynastyChapters.kt
- src/en/dynasty/src/eu/kanade/tachiyomi/extension/en/dynasty/DynastyDoujins.kt
- src/en/dynasty/src/eu/kanade/tachiyomi/extension/en/dynasty/DynastyIssues.kt
- src/en/dynasty/src/eu/kanade/tachiyomi/extension/en/dynasty/DynastyScans.kt
- src/en/dynasty/src/eu/kanade/tachiyomi/extension/en/dynasty/DynastySeries.kt
- src/en/dynasty/src/eu/kanade/tachiyomi/extension/en/dynasty/DynastyUrlActivity.kt
- src/zh/kuaikanmanhua/AndroidManifest.xml
- src/zh/kuaikanmanhua/build.gradle
- src/zh/kuaikanmanhua/src/eu/kanade/tachiyomi/extension/zh/kuaikanmanhua/Kuaikanmanhua.kt
- src/zh/kuaikanmanhua/src/eu/kanade/tachiyomi/extension/zh/kuaikanmanhua/KuaikanmanhuaUrlActivity.kt
> Added Url intents for DynastyScans and Kuaikanmanhua

- multisrc/overrides/luscious/luscious/src/LusciousFactory.kt
- multisrc/overrides/luscious/lusciousapi/src/LusciousAPIFactory.kt
- multisrc/overrides/luscious/lusciousmembers/src/LusciousMembersFactory.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/luscious/Luscious.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/luscious/LusciousGenerator.kt
Changelog:
- Added Page Sort setting
- Removed & Fixed some Filter option
- Changed Tag filter to text input
- minor code clean up
- Changed default Image resolution to Large as original seems to have regular outages
- Added unfiltered language
- Made filter by year update always to the current year
Note: When having problems with images loading try switching the image resolution, they are all hosted on different servers
Note2: When having issues with loading chapter list try turning on Merged Chapters
> Luscious some updates and fixes

- multisrc/overrides/mangacatalog/readfairytailedenszeromangaonline/src/ReadFairyTailEdensZeroMangaOnline.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangacatalog/MangaCatalogGenerator.kt
> MangaCatlouge FairyTail small update

- multisrc/overrides/mangacatalog/readnarutoborutosamurai8mangaonline/src/ReadNarutoBorutoSamurai8MangaOnline.kt
- multisrc/overrides/mangacatalog/readnoblessemanhwaonline/src/ReadNoblesseManhwaOnline.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangacatalog/MangaCatalog.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangacatalog/MangaCatalogGenerator.kt
> MangaCataloug Added Search function

- core/build.gradle.kts
- src/zh/manhuadui/build.gradle
- src/zh/manhuadui/src/eu/kanade/tachiyomi/extension/zh/manhuadui/Manhuadui.kt
> remove duplicate slash

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/luscious/Luscious.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/luscious/LusciousGenerator.kt
Note: I have no android 8 devices to test this on
Closes #6840
> Luscious android 8 support fix

- multisrc/overrides/madara/fudidoscanlator/src/FudidoScanlator.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> Add a new source to Madara

- multisrc/overrides/nyahentai/ddhentai/src/DDHentaiFactory.kt
- multisrc/overrides/nyahentai/ddhentaia/src/DDHentaiAFactory.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/nyahentai/NyaHentaiGenerator.kt
> Added DDHentai

- multisrc/overrides/madara/tsundokutraducoes/src/TsundokuTraducoes.kt
- multisrc/overrides/webtoons/webtoonstranslate/src/WebtoonsTranslateFactory.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/webtoons/WebtoonsTranslateGenerator.kt
> Replace pt-br usages with pt-BR in Madara and Webtoons

- multisrc/overrides/mangacatalog/readattackontitanshingekinokyojinmanga/src/ReadAttackOnTitanShingekiNoKyojinManga.kt
- multisrc/overrides/mangacatalog/readbokunoheroacademiamyheroacademiamanga/src/ReadBokuNoHeroAcademiaMyHeroAcademiaManga.kt
- multisrc/overrides/mangacatalog/readdragonballsuperchoumangaonline/src/ReadDragonBallSuperChouMangaOnline.kt
- multisrc/overrides/mangacatalog/readnanatsunotaizai7deadlysinsmangaonline/src/ReadNanatsuNoTaizai7DeadlySinsMangaOnline.kt
- multisrc/overrides/mangacatalog/readnarutoborutosamurai8mangaonline/src/ReadNarutoBorutoSamurai8MangaOnline.kt
- multisrc/overrides/mangacatalog/readsololevelingmangamanhwaonline/src/ReadSoloLevelingMangaManhwaOnline.kt
- multisrc/overrides/mangacatalog/readtowerofgodmanhwamangaonline/src/ReadTowerOfGodManhwaMangaOnline.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangacatalog/MangaCatalogGenerator.kt
replace `/` with ` ` in extension name to fix invalid download folder names
Closes #6612
Closes #6454
> Mangacataloug fixes

- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDexHelper.kt
I can't read json, evidently.
Closes #6903
> [Mangadex] Fix authorMap being empty

- src/all/genkanio/build.gradle
- src/all/genkanio/src/eu/kanade/tachiyomi/extension/all/genkanio/GenkanIO.kt
This pull requests restores search functionality to the Genkan.io extension, which broke after a site change
Closes #6915
> Fix search for genkan io

- src/ru/mangapoisk/build.gradle
- src/ru/mangapoisk/src/eu/kanade/tachiyomi/extension/ru/mangapoisk/MangaPoisk.kt
https://mangapoisk.ru/manga/vanpanchmen/chaptersList - with pagination for now. Fix it
> [Ru]Mangapoisk. Fix pagination on page list

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> Add Comicdom

- multisrc/overrides/wpmangareader/luminousscans/src/LuminousScans.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangareader/WPMangaReaderGenerator.kt
Closes #6956 
Closes #6901 
Closes #6425
> Add Luminous Scans, Davey Scans, and Skull Scans to wpmangareader

- src/all/batoto/build.gradle
- src/all/batoto/src/eu/kanade/tachiyomi/extension/all/batoto/BatoTo.kt
> <bato.to> getting the correct tags now

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/luscious/Luscious.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/luscious/LusciousGenerator.kt
Changes:
- Added Uploader filter
- Added Favourite filter
- Fixed  webview from showing API instead of manga page
Closes #6979
> Luscious new filters

- src/ar/gmanga/build.gradle
- src/ar/gmanga/src/eu/kanade/tachiyomi/extension/ar/gmanga/Gmanga.kt
The code might not be the best since I am not a Kotlin developer but I tried my best :)
Closes #6852
> ar: gmanga: Fix index error while fetching chapters list

- src/ru/libmanga/build.gradle
- src/ru/libmanga/src/eu/kanade/tachiyomi/extension/ru/libmanga/LibManga.kt
> MangaLib: Show domain warning as toast

- multisrc/overrides/wpmangareader/yugenmangas/src/YugenMangas.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangareader/WPMangaReaderGenerator.kt
Adds YugenMangas to wpmangareader
Closes #7008
> WPMangaReader: Add yugenmangas

- src/all/ninehentai/build.gradle
- src/all/ninehentai/src/eu/kanade/tachiyomi/extension/all/ninehentai/NineHentai.kt
> Update 9hentai site url.

- src/en/homeheroscans/AndroidManifest.xml
- src/en/homeheroscans/build.gradle
- src/en/homeheroscans/src/eu/kanade/tachiyomi/extension/en/homeheroscans/HomeHeroScans.kt
- src/en/homeheroscans/src/eu/kanade/tachiyomi/extension/en/homeheroscans/HomeHeroScansUrlActivity.kt
This pull request:
* Fixes a bug where it was impossible launch webview for manga
* Enables deeplinking to manga
> Home Hero Scans: Add support for deeplinking + fix bug where webview wouldn't launch

- src/en/vizshonenjump/build.gradle
- src/en/vizshonenjump/src/eu/kanade/tachiyomi/extension/en/vizshonenjump/VizShonenJump.kt
The issue tachiyomiorg/tachiyomi#5083 has a good point, so I added a rate limiting to the Viz extension.
> Add rate limiting to Viz

- multisrc/overrides/webtoons/webtoons/AndroidManifest.xml
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/webtoons/Webtoons.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/webtoons/WebtoonsGenerator.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/webtoons/WebtoonsUrlActivity.kt
This pull request add search by url (`url:https://webtoons/en/...`) + deep linking to webtoons source
> Webtoons: Add Search By Url + Deeplinking

- src/ru/libmanga/build.gradle
- src/ru/libmanga/src/eu/kanade/tachiyomi/extension/ru/libmanga/LibManga.kt
Closes #5716 - https://github.com/tachiyomiorg/tachiyomi-extensions/pull/6896
> MangaLib: Fixed sorting by translator

- src/pt/tsukimangas/build.gradle
- src/pt/tsukimangas/src/eu/kanade/tachiyomi/extension/pt/tsukimangas/TsukiMangas.kt
> Add more filters to Tsuki

- .github/workflows/issue_closer.yml
arkon/issue-closer-action#29 Must be merged first
> Added extensions that will not be added back to issue autocloser

- .github/workflows/issue_closer.yml
> Added two commas that I forgot

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt
Added Adult content filter to Madara extensions.
This is a minor addition to Madara, so it should probably be merged together with a more major update to Madara.
Did not increase gradle version due to this.
> Madara: Added Filter for Adult Content

- src/pt/goldenmangas/build.gradle
- src/pt/goldenmangas/src/eu/kanade/tachiyomi/extension/pt/goldenmangas/GoldenMangas.kt
Probably the source will not like this and there's a chance of a cat and mouse game starting to happen.
As a precaution I modified the rate limiting to be more harsh.
Closes #4958.
> Fix Cloudflare loop in GM

- .github/workflows/issue_closer.yml
> [SKIP CI] Added caseIgnore to relevant tasks

- src/all/batoto/build.gradle
- src/all/batoto/src/eu/kanade/tachiyomi/extension/all/batoto/BatoTo.kt
Disable Letter matching filter to fixsearch not working
Closes #7120
> Bato.to: Search Fix for #7120

- .github/workflows/issue_closer.yml
Hope I didn't forget something this time
> fixed ignorecase and added heroscan, manhuascan, and manhwahot to list

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/luscious/Luscious.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/luscious/LusciousGenerator.kt
Changelog:
- Added date to chapters
- Added Selection filter
Note:
I have no idea how many more filters there are on Luscious if some knows some that I'm still missing in the extension it would be nice if they could tell me so that I can add them.
> Luscious: Added date and filter

- src/ru/libmanga/build.gradle
- src/ru/libmanga/src/eu/kanade/tachiyomi/extension/ru/libmanga/LibManga.kt
- src/ru/remanga/build.gradle
- src/ru/remanga/src/eu/kanade/tachiyomi/extension/ru/remanga/Remanga.kt
- src/ru/remanga/src/eu/kanade/tachiyomi/extension/ru/remanga/dto/Dto.kt
> [RU] Remanga & Libmanga add rate/score

- src/fr/japscan/build.gradle
- src/fr/japscan/src/eu/kanade/tachiyomi/extension/fr/japscan/Japscan.kt
> Fix japscan baseUrl

- .github/workflows/issue_moderator.yml
Needs to wait the tachiyomiorg/issue-moderator-action#1 to be merged and get a release before merging this one.
> [SKIP CI] Add issue moderator action

- src/ru/allhentai/build.gradle
- src/ru/allhentai/src/eu/kanade/tachiyomi/extension/ru/allhentai/AllHentai.kt
- src/ru/libmanga/build.gradle
- src/ru/libmanga/src/eu/kanade/tachiyomi/extension/ru/libmanga/LibManga.kt
- src/ru/mintmanga/build.gradle
- src/ru/mintmanga/src/eu/kanade/tachiyomi/extension/ru/mintmanga/Mintmanga.kt
- src/ru/readmanga/build.gradle
- src/ru/readmanga/src/eu/kanade/tachiyomi/extension/ru/readmanga/Readmanga.kt
- src/ru/remanga/build.gradle
- src/ru/remanga/src/eu/kanade/tachiyomi/extension/ru/remanga/Remanga.kt
> [RU] Readmanga & Mintmanga add rate/score and fixes

- src/all/batoto/build.gradle
- src/all/batoto/src/eu/kanade/tachiyomi/extension/all/batoto/BatoTo.kt
> Bato.To: Fix infinitiy search

- multisrc/overrides/wpmangastream/asurascans/src/AsuraScans.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStreamGenerator.kt
This should hopefully fix any issues with people running into timeouts and 404s
> Asura fixes

- src/ru/desu/build.gradle
- src/ru/desu/src/eu/kanade/tachiyomi/extension/ru/desu/Desu.kt
> [RU]Desu Rus+Alttitle Rate

- src/all/mango/build.gradle
- src/all/mango/src/eu/kanade/tachiyomi/extension/all/mango/Mango.kt
> Mango: Add chapter numbers

- src/fr/japscan/build.gradle
- src/fr/japscan/src/eu/kanade/tachiyomi/extension/fr/japscan/Japscan.kt
> Fix japscan intercept url

- src/en/rainofsnow/build.gradle
- src/en/rainofsnow/src/eu/kanade/tachiyomi/extension/en/rainofsnow/RainOfSnow.kt
> RainOfSnow: add rate limit 2/s

- multisrc/overrides/wpmangastream/komikcast/src/KomikCast.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStreamGenerator.kt
try lessen cloudflare issue
use google.com referer
> KomikCast: add header (user agent, referer)

- src/id/komiku/build.gradle
- src/id/komiku/src/eu/kanade/tachiyomi/extension/id/komiku/Komiku.kt
> Komiku: fix chapter page

- src/zh/jinmantiantang/build.gradle
- src/zh/jinmantiantang/src/eu/kanade/tachiyomi/extension/zh/jinmantiantang/Jinmantiantang.kt
Closes #7090 
last pr seems nothing to change.
> fix: <Jinmantiantang>: <Error 429 when updating library>

- src/ru/mintmanga/build.gradle
- src/ru/mintmanga/src/eu/kanade/tachiyomi/extension/ru/mintmanga/Mintmanga.kt
- src/ru/readmanga/build.gradle
- src/ru/readmanga/src/eu/kanade/tachiyomi/extension/ru/readmanga/Readmanga.kt
Continuation this https://github.com/tachiyomiorg/tachiyomi-extensions/commit/620a1ea6f9800ba51d7218fac76049e6e974e833
> [RU]Readmanga & Mintmanga add Age tags

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
The PR was causing an uncaught exception, crashing tachiyomi, so reverting it until a fix can be found
> Revert Madara Host Preference

- src/es/vcpvmp/build.gradle
- src/es/vcpvmp/src/eu/kanade/tachiyomi/extension/es/vcpvmp/VCPVMPFactory.kt
> Fixed VCP selectors

- multisrc/overrides/mangabox/mangakakalot/src/Mangakakalot.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangabox/MangaBoxGenerator.kt
> mangakakalot: fix fetching dates and sorting

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
Closes #7182 
Closes #7183 
Closes #7184
> add MangaTuli, FreeManga, and Yaoi Manga

- src/es/tumangaonline/build.gradle
- src/es/tumangaonline/src/eu/kanade/tachiyomi/extension/es/tumangaonline/TuMangaOnline.kt
Fixed error 403 in tumangaonline extension
Closes #6888
> Fix error 403 Tumangaonline

- src/en/homeheroscans/build.gradle
- src/en/homeheroscans/src/eu/kanade/tachiyomi/extension/en/homeheroscans/HomeHeroScans.kt
> Home Hero Scans Fix HTTP Error 500

- multisrc/overrides/wpmangastream/komikcast/src/KomikCast.kt
- multisrc/overrides/wpmangastream/sektekomik/src/SekteKomik.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStreamGenerator.kt
Closes #6955 Closes #7279
Closes #7245
> KomikCast, SekteKomik: fix thumbnail issue

- multisrc/overrides/wpmangareader/sekaikomik/src/Sekaikomik.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangareader/WPMangaReaderGenerator.kt
> Sekaikomik change base url

- src/en/mangahasu/build.gradle
- src/en/mangahasu/src/eu/kanade/tachiyomi/extension/en/mangahasu/Mangahasu.kt
> Update MangaHasu Base Url.

- .github/workflows/issue_closer.yml
> [SKIP CI] Added KnightNoScanlation and AhStudios to autocloser

- src/fr/mangakawaii/build.gradle
- src/fr/mangakawaii/src/eu/kanade/tachiyomi/extension/fr/mangakawaii/MangaKawaii.kt
> MangaKawaii: URL changed. Fix #7030

- src/zh/dmzj/build.gradle
- src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt
- src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/protobuf/V4apiComicDetailResponse.kt
- src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/utils/RSA.kt
Almost same as PR #7343, I made some mistake with git and closed that PR. 🤣
Protobuf deserialization library has changed to kotlinx.serialization now.
> [ZH-dmzj] Move some logic to use dmzj's new v4api, fix #6858

- multisrc/overrides/madara/cutiepie/src/CutiePie.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
url changed from https://cutiepie.ga/ to https://cutiepie.moe/
Closes #7353
> fix [cutiepie]: update url

- src/zh/copymanga/build.gradle
- src/zh/copymanga/src/eu/kanade/tachiyomi/extension/zh/copymanga/CopyManga.kt
This website has 2 kind of cdn.For some people, one of the cdn can load images faster than the other, or vice versa.So add a preference to change image cdn will help a lot.
Thanks @ckn4
Closed #6649
> copymanga: add a preference to change image cdn

- multisrc/overrides/mangasproject/leitornet/src/LeitorNet.kt
- multisrc/overrides/mangasproject/mangalivre/src/MangaLivre.kt
- multisrc/overrides/mangasproject/toonei/src/Toonei.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangasproject/MangasProject.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangasproject/MangasProjectDto.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangasproject/MangasProjectGenerator.kt
- multisrc/src/main/java/generator/ThemeSourceGenerator.kt
- src/en/vizshonenjump/build.gradle
- src/en/vizshonenjump/src/eu/kanade/tachiyomi/extension/en/vizshonenjump/VizShonenJump.kt
- src/pt/hqnow/build.gradle
- src/pt/hqnow/src/eu/kanade/tachiyomi/extension/pt/hqnow/HQNow.kt
- src/pt/hqnow/src/eu/kanade/tachiyomi/extension/pt/hqnow/HQNowDto.kt
- src/pt/mangatube/build.gradle
- src/pt/mangatube/src/eu/kanade/tachiyomi/extension/pt/mangatube/MangaTube.kt
- src/pt/mangatube/src/eu/kanade/tachiyomi/extension/pt/mangatube/MangaTubeDto.kt
- src/pt/muitomanga/build.gradle
- src/pt/muitomanga/src/eu/kanade/tachiyomi/extension/pt/muitomanga/MuitoManga.kt
- src/pt/muitomanga/src/eu/kanade/tachiyomi/extension/pt/muitomanga/MuitoMangaDto.kt
- src/pt/mundomangakun/build.gradle
- src/pt/mundomangakun/src/eu/kanade/tachiyomi/extension/pt/mundomangakun/MundoMangaKun.kt
- src/pt/opex/build.gradle
- src/pt/opex/src/eu/kanade/tachiyomi/extension/pt/opex/OnePieceEx.kt
- src/pt/tsukimangas/build.gradle
- src/pt/tsukimangas/src/eu/kanade/tachiyomi/extension/pt/tsukimangas/TsukiMangas.kt
- src/pt/tsukimangas/src/eu/kanade/tachiyomi/extension/pt/tsukimangas/TsukiMangasDto.kt
I also added `kotlinx.serialization` plugin to `multisrc`.
> Add kotlinx.serialization to more sources

- src/all/cubari/build.gradle
- src/all/cubari/src/eu/kanade/tachiyomi/extension/all/cubari/Cubari.kt
> Fix proxy method not working on Cubari

- multisrc/overrides/madara/ichirinnohanayuri/src/IchirinNoHanaYuri.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> Temporary fix blocking for a source and add a message about it

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStream.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStreamGenerator.kt
> Fix duplicate images at WpMangaStream sources

- src/en/mangajar/build.gradle
- src/en/mangajar/src/eu/kanade/tachiyomi/extension/en/mangajar/MangaJar.kt
Changes the JSoup selectors
Closes #7390
> Fix MangaJar page list parsing

- multisrc/overrides/wpmangareader/flamescans/src/FlameScans.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangareader/WPMangaReaderGenerator.kt
Changed it to 2 since they have reported on increased server loads from
Tachi. Hopefully this eases it out else they might request for the extension
to be removed
> Increase ratelimit for FlameScans

- src/en/catmanga/build.gradle
- src/en/catmanga/src/eu/kanade/tachiyomi/extension/en/catmanga/CatManga.kt
One endpoint for all operations except for fetching pages. Should be faster when refreshing library.
> CatManga QoL improvements

- multisrc/overrides/madara/leviatanscans/src/LeviatanScansFactory.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> Fixed Leviatanscans Spanish

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> remove manganelo.link from madara

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/nepnep/NepNep.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/nepnep/NepNepGenerator.kt
> add / to referrer url

- multisrc/overrides/wpmangastream/komikstation/src/KomikStation.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStreamGenerator.kt
> KomikStation: fix chapter page

- src/ru/libmanga/build.gradle
- src/ru/libmanga/src/eu/kanade/tachiyomi/extension/ru/libmanga/LibManga.kt
Fix empty content-length header image
> [Ru]Libmanga. Fix empty content-length image

- src/all/mangapark/build.gradle
- src/all/mangapark/src/eu/kanade/tachiyomi/extension/all/mangapark/MangaPark.kt
Well I basically forgot to Response -> Json -> JsonElement -> Jsoup for getting Chapter list.
> MangaPark v3 Fixes 2.0

- src/all/mangapark/build.gradle
- src/all/mangapark/src/eu/kanade/tachiyomi/extension/all/mangapark/MangaPark.kt
If this doesn't fix it I hope someone will take over.
> MangaPark v3 Fix 3.0

- multisrc/overrides/luscious/luscious/src/LusciousFactory.kt
- multisrc/overrides/luscious/lusciousapi/src/LusciousAPIFactory.kt
- multisrc/overrides/luscious/lusciousmembers/src/LusciousMembersFactory.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/luscious/Luscious.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/luscious/LusciousGenerator.kt
- src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunFactory.kt
- src/all/ehentai/build.gradle
- src/all/ehentai/src/eu/kanade/tachiyomi/extension/all/ehentai/EHFactory.kt
- src/all/ehentai/src/eu/kanade/tachiyomi/extension/all/ehentai/EHentai.kt
- src/all/hentaihand/build.gradle
- src/all/hentaihand/src/eu/kanade/tachiyomi/extension/all/hentaihand/HentaiHand.kt
- src/all/hentaihand/src/eu/kanade/tachiyomi/extension/all/hentaihand/HentaiHandFactory.kt
- src/all/mangatoon/build.gradle
- src/all/mangatoon/src/eu/kanade/tachiyomi/extension/all/mangatoon/MangaToonFactory.kt
- src/all/ninemanga/build.gradle
- src/all/ninemanga/src/eu/kanade/tachiyomi/extension/all/ninemanga/NineManga.kt
- src/all/ninemanga/src/eu/kanade/tachiyomi/extension/all/ninemanga/NineMangaFactory.kt
- src/all/simplyhentai/build.gradle
- src/all/simplyhentai/src/eu/kanade/tachiyomi/extension/all/simplyhentai/SimplyHentai.kt
- src/all/simplyhentai/src/eu/kanade/tachiyomi/extension/all/simplyhentai/SimplyHentaiFactory.kt
Closes #6601.
Closes #6960.
Closes #6962.
> Fix wrong language code in some extensions

- multisrc/overrides/madara/default/AndroidManifest.xml
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraUrlActivity.kt
Sorry missed this 2 files in previous PR.
> Added 2 fiels that i missed to commit in previous pr (#7570)

- src/all/mangapark/build.gradle
- src/all/mangapark/src/eu/kanade/tachiyomi/extension/all/mangapark/MangaPark.kt
- src/all/mangapark/src/eu/kanade/tachiyomi/extension/all/mangapark/MangaParkFactory.kt
Closes #4803 (since thumbnails loads fine now).
Closes #6726 (extension already uses v3).
Closes #7561.
Closes #7576.
> Fix broken search and chapter images at MP

- multisrc/overrides/mangabox/mangakakalot/src/Mangakakalot.kt
- multisrc/overrides/mangabox/mangakakalots/src/Mangakakalots.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangabox/MangaBoxGenerator.kt
> [Mangabox] Revert Mangakakalot dateformat, add Mangakakalots dateformat

- src/en/wecomics/build.gradle
- src/en/wecomics/src/eu/kanade/tachiyomi/extension/en/wecomics/WeComics.kt
Closes #7162 
Linking related issue after opening this PR.
> WeComics: Update logic and error message for paid chapters.

- src/zh/pufei/build.gradle
- src/zh/pufei/src/eu/kanade/tachiyomi/extension/zh/pufei/Pufei.kt
> pufei: fix not showing description

- src/all/hitomi/build.gradle
- src/all/hitomi/src/eu/kanade/tachiyomi/extension/all/hitomi/Hitomi.kt
- src/en/homeheroscans/build.gradle
- src/en/homeheroscans/src/eu/kanade/tachiyomi/extension/en/homeheroscans/HomeHeroScans.kt
- src/en/honkaiimpact3/build.gradle
- src/en/honkaiimpact3/src/eu/kanade/tachiyomi/extension/en/honkaiimpact/Honkaiimpact.kt
- src/en/mangadog/build.gradle
- src/en/mangadog/src/eu/kanade/tachiyomi/extension/en/mangadog/Mangadog.kt
- src/en/mangahasu/build.gradle
- src/en/mangahasu/src/eu/kanade/tachiyomi/extension/en/mangahasu/Mangahasu.kt
- src/es/kumanga/build.gradle
- src/es/kumanga/src/eu/kanade/tachiyomi/extension/es/kumanga/Kumanga.kt
- src/es/mangamx/build.gradle
- src/es/mangamx/src/eu/kanade/tachiyomi/extension/es/mangamx/MangaMx.kt
- src/fr/japanread/build.gradle
- src/fr/japanread/src/eu/kanade/tachiyomi/extension/fr/japanread/Japanread.kt
- src/fr/japscan/build.gradle
- src/fr/japscan/src/eu/kanade/tachiyomi/extension/fr/japscan/Japscan.kt
- src/fr/scanmanga/build.gradle
- src/fr/scanmanga/src/eu/kanade/tachiyomi/extension/fr/scanmanga/ScanManga.kt
- src/it/digitalteam/build.gradle
- src/it/digitalteam/src/eu/kanade/tachiyomi/extension/it/digitalteam/DigitalTeam.kt
- src/ru/mangahub/build.gradle
- src/ru/mangahub/src/eu/kanade/tachiyomi/extension/ru/mangahub/Mangahub.kt
- src/zh/bh3/build.gradle
- src/zh/bh3/src/eu/kanade/tachiyomi/extension/zh/bh3/BH3.kt
- src/zh/qimiaomh/build.gradle
- src/zh/qimiaomh/src/eu/kanade/tachiyomi/extension/zh/qimiaomh/Qimiaomh.kt
Replace the usages of Gson's `JsonParser` by kotlinx.serialization as per #7392.
> Replace JsonParser with kotlinx.serialization in some extensions

- src/all/hitomi/AndroidManifest.xml
- src/all/hitomi/build.gradle
- src/all/hitomi/src/eu/kanade/tachiyomi/extension/all/hitomi/Hitomi.kt
- src/all/hitomi/src/eu/kanade/tachiyomi/extension/all/hitomi/HitomiActivity.kt
- src/all/hitomi/src/eu/kanade/tachiyomi/extension/all/hitomi/HitomiDto.kt
- src/all/hitomi/src/eu/kanade/tachiyomi/extension/all/hitomi/HitomiNozomi.kt
[FIX] Update image url path logic
Closes #7639
Closes #5830
[FEAT] Add Filter for searching with popularity support
Closes #7086
Closes #6095
[FIX] Replace the used json library with kotlinx.serialization
Per #7392
[FIX] Deeplink now support all type and can actually display result
[FEAT] Add common word detection to avoid large search result
Closes #6061
Closes #7224
> [hitomi.la] Update image url path logic and implement filter

- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDexInterceptors.kt
> Remove last Gson usage at MangaDex

- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDex.kt
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDexHelper.kt
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/dto/AggregateDto.kt
add checks to the uploaded chapters in order to determine if the (publication) completed manga has been fully scanlated
> Implement Completed and Cancelled statuses

- src/all/comickfun/build.gradle
- src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
- src/en/catmanga/build.gradle
- src/ru/remanga/build.gradle
- src/ru/remanga/src/eu/kanade/tachiyomi/extension/ru/remanga/dto/Dto.kt
This pull request fixes some bugs introduced by #7407 
Closes #7679
> Bugfixes for #7407

- src/zh/dmzj/build.gradle
- src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt
replace dmzj1.com with dmzj.com because dmzj1.com deprecated
Closes #7668
> [zh-dmzj] Fix url issue

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangasproject/MangasProject.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangasproject/MangasProjectDto.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangasproject/MangasProjectGenerator.kt
The extension will also show the error message from the API response if it exists.
> Fix chapters from some titles not loading at MP

- multisrc/overrides/madara/hiperdex/src/Hiperdex.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> Fix Hiperdex url

- src/pt/tsukimangas/build.gradle
- src/pt/tsukimangas/src/eu/kanade/tachiyomi/extension/pt/tsukimangas/TsukiMangas.kt
- src/pt/tsukimangas/src/eu/kanade/tachiyomi/extension/pt/tsukimangas/TsukiMangasDto.kt
Users are now required to log in at the website to read the titles.
This PR adds support to login through extension preferences.
> Add support to login at Tsuki

- src/pt/tsukimangas/build.gradle
- src/pt/tsukimangas/src/eu/kanade/tachiyomi/extension/pt/tsukimangas/TsukiMangas.kt
Apparently some users are confused on where are the settings, so now the message explicitly says "extension settings" :harold:
> Rewrite some error messages at Tsuki to make them more clear

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
This was fixed in #7696 just needed a version increase to work on Manhuas.net
Closes  #7739
> Manhuas.net fix

- src/fr/scantradunion/build.gradle
- src/fr/scantradunion/src/eu/kanade/tachiyomi/extension/fr/scantradunion/ScantradUnion.kt
> Fix ScranTradUnion duplicate pages (#7694)

- src/ru/mangabook/build.gradle
- src/ru/mangabook/src/eu/kanade/tachiyomi/extension/ru/mangabook/MangaBook.kt
- src/ru/mangapoisk/build.gradle
- src/ru/mangapoisk/src/eu/kanade/tachiyomi/extension/ru/mangapoisk/MangaPoisk.kt
+MangaBook rare but existing altname
> Add page teg [RU] MangaPoisk & MangaBook

- src/es/inmanga/build.gradle
- src/es/inmanga/src/eu/kanade/tachiyomi/extension/es/inmanga/InManga.kt
- src/es/inmanga/src/eu/kanade/tachiyomi/extension/es/inmanga/InMangaResultDto.kt
- src/es/mangamx/build.gradle
- src/es/mangamx/src/eu/kanade/tachiyomi/extension/es/mangamx/MangaMx.kt
- src/es/mangamx/src/eu/kanade/tachiyomi/extension/es/mangamx/ResponseDto.kt
> Fix InManga pages not load & MangaMx search

- multisrc/overrides/genkan/lynxscans/src/LynxScans.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/genkan/GenkanGenerator.kt
> Fixes LynxScans

- src/zh/wnacg/build.gradle
- src/zh/wnacg/src/eu/kanade/tachiyomi/extension/zh/wnacg/wnacg.kt
> WNACG: Fixes search

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> MGKomik: Updated URL

- src/en/mangadoom/build.gradle
- src/en/mangadoom/src/eu/kanade/tachiyomi/extension/en/mangadoom/MangaDoom.kt
> MangaDoom: Fixes chapterListParse

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangadventure/MangAdventureGenerator.kt
> Add Helvetica Scans

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> Add Ancient Empire Scan

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangareader/WPMangaReaderGenerator.kt
> Add Patatescans and Fusion Scanlation

- multisrc/overrides/fmreader/saytruyen/src/SayTruyen.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/fmreader/FMReaderGenerator.kt
> Update Say Truyen URL

- src/zh/dmzj/build.gradle
- src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt
use muwai.com for v4apiUrl & v3ChapterApiUrl & imageCDNUrl
> [zh-dmzj]use muwai.com instead of dmzj.com

- src/ru/mangahub/build.gradle
- src/ru/mangahub/src/eu/kanade/tachiyomi/extension/ru/mangahub/Mangahub.kt
Fix manga image in detail view
> [Ru]Mangahub. Fix detail thumbnail

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangabox/MangaBox.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangabox/MangaBoxGenerator.kt
> [Mangabox] Separate authors with commas

- src/zh/dmzj/AndroidManifest.xml
- src/zh/dmzj/build.gradle
Add intents for muwai.com and remove intents of dmzj1.com.
> [zh-Dmzj]Add intents for muwai.com

- multisrc/overrides/wpmangastream/worldromancetranslation/src/WorldRomanceTranslation.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStreamGenerator.kt
parsing from chapter url Closes #7831
> WorldRomanceTranslation: fix chapter name

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> Update Siyahmelek URL

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> XuN Scans: change url in generator

- src/zh/copymanga/build.gradle
- src/zh/copymanga/src/eu/kanade/tachiyomi/extension/zh/copymanga/CopyManga.kt
Use search api from h5 app,because old api has broken.
Close https://github.com/tachiyomiorg/tachiyomi-extensions/issues/7868
pick from https://github.com/ckn4/tachiyomi-extensions/commit/ed7ec49bdf8ec67c8cb2bd648250b2efec1c5a02
Thanks @ckn4 !
> [zh-copymanga]Fix search

- src/en/mangapill/build.gradle
- src/en/mangapill/src/eu/kanade/tachiyomi/extension/en/mangapill/MangaPill.kt
> MangaPill: Update for new site layout

- multisrc/overrides/madara/leviatanscans/src/LeviatanScansFactory.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
Use chapter name as chapter number
> Add support for mangas with seasons

- .github/workflows/issue_moderator.yml
> [skip ci] Update issue-moderator-action to v1.1

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/source_bug.yml
- .github/ISSUE_TEMPLATE/source_request.yml
Greatest update this repository has seen for the past hour 😤 
- Emojifies the issue template list in `config.yml`. 🙏🏻
- Rewrites the description for Source information used in `source_bug.yml`.
- Adds quotes to the examples used in `source_request.yml`.
> Minor tweaks to the issue forms

- multisrc/overrides/genkan/lynxscans/src/LynxScans.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/genkan/GenkanGenerator.kt
> Fixed typo in LynxScans source name

- src/en/bilibilicomics/build.gradle
- src/en/bilibilicomics/src/eu/kanade/tachiyomi/extension/en/bilibilicomics/BilibiliComics.kt
- src/en/bilibilicomics/src/eu/kanade/tachiyomi/extension/en/bilibilicomics/BilibiliComicsUrlActivity.kt
- src/en/bilibilicomics/src/eu/kanade/tachiyomi/extension/en/bilibilicomics/BilibiliDto.kt
1. Add Url Intent
2. Implement Latest from Update Schedule
Closes #7646
> Bilibili Comics Update

- multisrc/overrides/madara/setsuscans/src/SetsuScans.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> Setsu Scans: Harsher Rate Limit + Tachiyomi in User Agent

- src/all/comickfun/build.gradle
- src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunSerialization.kt
> Comick.fun: Fix parsing issue for nullable chapter numbers

- src/all/mangapark/build.gradle
- src/all/mangapark/src/eu/kanade/tachiyomi/extension/all/mangapark/MangaPark.kt
> MangaPark v3 Genre Search Fix

- multisrc/overrides/wpmangareader/flamescans/src/FlameScans.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangareader/WPMangaReaderGenerator.kt
> Flamescans fix

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mmrcms/MMRCMS.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mmrcms/MMRCMSSources.kt
This is a simple workaround
Fixes #7154
> Mangaspw fix

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/fmreader/FMReader.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/fmreader/FMReaderGenerator.kt
Tested with KSGroupScans and LHTranslation.
> [FMReader] Comma-separate author list

- src/en/mangakatana/src/eu/kanade/tachiyomi/extension/en/mangakatana/MangaKatana.kt
> [MangaKatana] Add server preference, alt names in description, and comma-separate author list

- src/pt/taosect/build.gradle
- src/pt/taosect/src/eu/kanade/tachiyomi/extension/pt/taosect/TaoSect.kt
> Fix missing chapters at TS

- src/en/comicextra/build.gradle
- src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt
> ComicExtra Fix chapter date and URL

- multisrc/overrides/wpmangareader/flamescans/src/FlameScans.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangareader/WPMangaReaderGenerator.kt
> Fix missing half of the page at FS

- multisrc/overrides/wpmangareader/fusionscanlation/additional.gradle.kts
- multisrc/overrides/wpmangareader/fusionscanlation/src/FusionScanlation.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangareader/WPMangaReaderGenerator.kt
> fusion scanlation: add rate limit and dates

- src/en/mangafreak/build.gradle
- src/en/mangafreak/src/eu/kanade/tachiyomi/extension/en/mangafreak/Mangafreak.kt
> mangafreak: fix status and titles

- multisrc/overrides/madara/mangaweebs/src/MangaWeebs.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> mangaweebs: remove parts so chapters will show up again

- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MDConstants.kt
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDex.kt
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDexFilters.kt
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDexHelper.kt
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/dto/ChapterDto.kt
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/dto/MangaDto.kt
closes #8018, #8017, #8015, #8011
also fixed a bug where deeplink wasn't ignoring users contentRating settings
> MangaDex fix deeplinking, parsing, clean up dto's, add latest chapter

- multisrc/overrides/madara/neoxscanlator/src/NeoxScanlator.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
Some manga are giving timeout at the moment because their website is really slow.
Closes #8039.
> Update NS to their new URL (again)

- multisrc/overrides/wpmangastream/asurascans/src/AsuraScans.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStreamGenerator.kt
Fix Asura Scans stuck downloads by always ignoring the "stolen from Asura Scans" image.
Closes #7486
> Fix Asura Scans downloads

- multisrc/overrides/wpmangastream/asurascans/src/AsuraScans.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStreamGenerator.kt
I'm trying to be nice, don't bully scanlators, let's make the request/second a little bit lower.
> [AsuraScans] make the rate limit is bit lower

- multisrc/overrides/wpmangastream/asurascans/src/AsuraScans.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStreamGenerator.kt
> asura scans: add tachiyomi to UA

- src/en/mangaowl/build.gradle
- src/en/mangaowl/src/eu/kanade/tachiyomi/extension/en/mangaowl/MangaOwl.kt
_sorry if I didn't caught it on my last PR_
> mangaowl: fix single page only showing when using text search & filter

- src/all/cubari/build.gradle
- src/all/cubari/src/eu/kanade/tachiyomi/extension/all/cubari/Cubari.kt
closes #8076
Not sure if this is the best way to fix, but tested with
https://cubari.moe/read/mangadex/e83c326b-921b-45ff-bc0c-d667bbfe64cc/
https://cubari.moe/read/mangadex/e78a489b-6632-4d61-b00b-5206f5b8b22b/
https://cubari.moe/read/mangadex/9cc3be97-91c6-4ed7-ad28-dd396699ea87/
https://cubari.moe/read/gist/OPM/
> fix cubari upload date

- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDex.kt
> Fix latest mangadex order, and missing manga, and follows users default content rating

- src/ru/remanga/build.gradle
- src/ru/remanga/src/eu/kanade/tachiyomi/extension/ru/remanga/Remanga.kt
Fix urls like this: 
```
{
"id": 21221493,
"link": "/api/functions/images/21221493.jpg",
"page": 4,
"height": 2746,
"width": 800,
"count_comments": 0
}
```
> Fix links without http/https in ru-remanga

- src/pt/tsukimangas/build.gradle
- src/pt/tsukimangas/src/eu/kanade/tachiyomi/extension/pt/tsukimangas/TsukiMangas.kt
- src/pt/tsukimangas/src/eu/kanade/tachiyomi/extension/pt/tsukimangas/TsukiMangasDto.kt
> Distinguish between novels and manga in Tsuki

- src/en/purplecress/AndroidManifest.xml
- src/en/purplecress/build.gradle
- src/en/purplecress/src/eu/kanade/tachiyomi/extension/en/purplecress/PurpleCress.kt
- src/en/purplecress/src/eu/kanade/tachiyomi/extension/en/purplecress/PurpleCressURLActivity.kt
* Add search function to Purple Cress source
* Add deeplinking to Purple Cress for both chapter and series links (both open series page in Tachiyomi)
> Purple Cress: Add search and deeplinking

- src/es/lectormanga/build.gradle
- src/es/lectormanga/src/eu/kanade/tachiyomi/extension/es/lectormanga/LectorManga.kt
> A fix for the Scanlator Tag.

- multisrc/overrides/madara/dreamunionscan/src/DreamUnionScan.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
Sorry about opening a new PR, the last one got merged before the person opened the issue request.
Closes #8187.
> Add a new source to Madara (again)

- src/en/mangakatana/build.gradle
> [MangaKatana] Bump version for #7972

- multisrc/overrides/wpcomics/nettruyen/src/NetTruyen.kt
- multisrc/overrides/wpcomics/nhattruyen/src/NhatTruyen.kt
- multisrc/overrides/wpcomics/truyenchon/src/TruyenChon.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpcomics/WPComicsGenerator.kt
Update header in these sources.
Related issues:
#8071
> update Nettruyen, TruyenChon, Nhattruyen header.

- src/ru/henchan/build.gradle
- src/ru/henchan/src/eu/kanade/tachiyomi/extension/ru/henchan/Henchan.kt
> BaseURL Update

- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDex.kt
> Filtered comikey chapters

- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDexFilters.kt
Checklist:
- [*] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [*] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [*] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [*] Annotated `Source` or `SourceFactory` classes with `@Nsfw` when appropriate
- [*] Added the `containsNsfw = true` flag in `build.gradle` when appropriate
- [*] Have not changed source names
- [*] Have explicitly kept the `versionId` if a source's name or language were changed
> [Mangadex] Changed default sort to most follows from alphabetical

- src/it/mangaworld/build.gradle
- src/it/mangaworld/src/eu/kanade/tachiyomi/extension/it/mangaworld/Mangaworld.kt
Changed all domain from mangaworld.io to mangaworld.in
Changed extVersionCode from 4 to 5
If anyone can test it I would appreciate it.
First time coding with android resource, but I've only change this 2 file.
The Issue is related at #9291 
And I don't know if #9294 was resolved or not, soo i did it again
Checklist:
> MangaWorld Domain Changing

- src/ru/libmanga/build.gradle
- src/ru/libmanga/src/eu/kanade/tachiyomi/extension/ru/libmanga/LibManga.kt
Add fourth option in MangaLib settings for changing between English - Russian name in cover
> [RU]MangaLib: add new option for changing cover language

- src/zh/copymanga/build.gradle
- src/zh/copymanga/src/eu/kanade/tachiyomi/extension/zh/copymanga/CopyManga.kt
> Update copymanga mainlandcdn domains 

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangareader/WPMangaReaderGenerator.kt
> Fix PMScans URL

- multisrc/overrides/wpmangareader/kiryuu/src/Kiryuu.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangareader/WPMangaReaderGenerator.kt
> Kiryuu: Fix cover thumbnail blank (not loaded)

- multisrc/overrides/guya/magicaltranslators/src/MagicalTranslators.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/guya/GuyaGenerator.kt
> Magical Translators: add Spanish language

- src/en/hiveworks/build.gradle
- src/en/hiveworks/src/eu/kanade/tachiyomi/extension/en/hiveworks/Hiveworks.kt
This works towards #3153
Would also close #3930 - but it has closed already due to age.
Checklist:
> Add support for http://sssscomic.com/

- src/zh/jinmantiantang/build.gradle
- src/zh/jinmantiantang/src/eu/kanade/tachiyomi/extension/zh/jinmantiantang/Jinmantiantang.kt
> fix: jinmantiantang no pages found

- multisrc/overrides/madara/mmscans/src/MMScans.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
Closes https://github.com/tachiyomiorg/tachiyomi-extensions/issues/11716
Checklist:
> fix: mmscans theme change

- src/zh/zerobyw/build.gradle
- src/zh/zerobyw/src/eu/kanade/tachiyomi/extension/zh/zerobyw/Zerobyw.kt
> Zerobyw: Update baseUrl

- multisrc/overrides/wpmangastream/komikcast/src/KomikCast.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStreamGenerator.kt
> Komik Cast - Fix match result return null (not found)

- src/all/kavita/CHANGELOG.md
- src/all/kavita/build.gradle
- src/all/kavita/src/eu/kanade/tachiyomi/extension/all/kavita/Kavita.kt
- src/all/kavita/src/eu/kanade/tachiyomi/extension/all/kavita/dto/MetadataDto.kt
Changed:
- Ignore DOH
- Added `Item added` sort
- Last Updates button now filters `Item Added`
Checklist:
> Kavita: Ignore DOH and new sort option

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/nepnep/NepNep.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/nepnep/NepNepGenerator.kt
> Nepnep: Parse new statuses

- src/all/batoto/build.gradle
- src/all/batoto/src/eu/kanade/tachiyomi/extension/all/batoto/BatoTo.kt
> BATO.TO: Change default popular sort by `Most Views Totally`

- multisrc/overrides/wpcomics/nettruyen/src/NetTruyen.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpcomics/WPComics.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpcomics/WPComicsGenerator.kt
- src/vi/hentaivn/build.gradle
- src/vi/hentaivn/src/eu/kanade/tachiyomi/extension/vi/hentaivn/HentaiVN.kt
> Change domain NetTruyen and HentaiVN

- multisrc/overrides/nepnep/mangasee/AndroidManifest.xml
- multisrc/overrides/nepnep/mangasee/src/MangaSee.kt
- multisrc/overrides/nepnep/mangasee/src/MangaseeUrlActivity.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/nepnep/NepNepGenerator.kt
> Mangasee: Add intent filter

- multisrc/overrides/madara/empirewebtoon/src/EmpireWebtoon.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> Empire Webtoon: Add option to change BaseURL

- src/all/kavita/CHANGELOG.md
- src/all/kavita/build.gradle
- src/all/kavita/src/eu/kanade/tachiyomi/extension/all/kavita/Kavita.kt
> Kavita: Fix Init property title not initialized

- src/vi/truyenqq/build.gradle
- src/vi/truyenqq/src/eu/kanade/tachiyomi/extension/vi/truyenqq/TruyenQQ.kt
> Fix TruyenQQ popular and search request

- src/all/kavita/CHANGELOG.md
- src/all/kavita/build.gradle
- src/all/kavita/src/eu/kanade/tachiyomi/extension/all/kavita/Kavita.kt
- src/all/kavita/src/eu/kanade/tachiyomi/extension/all/kavita/KavitaConstants.kt
- src/all/kavita/src/eu/kanade/tachiyomi/extension/all/kavita/dto/MangaDto.kt
- src/all/kavita/src/eu/kanade/tachiyomi/extension/all/kavita/dto/MetadataDto.kt
- Removed some hacks to make search work as a proper filter
- Added and removed filters
- Updated how the extension will interpret volumes as chapters (encoding to allow volume tracking)
Checklist:
> Kavita: Filter and search update

- multisrc/overrides/madara/mangasorigines/src/MangasOrigines.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> Mangas Origines: Fix manga details

- multisrc/overrides/madara/azora/src/Azora.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> Updates Azora url

- src/tr/mangaship/build.gradle
- src/tr/mangaship/src/eu/kanade/tachiyomi/extension/tr/mangaship/MangaShip.kt
> Update MangaShip baseUrl

- multisrc/overrides/mangacatalog/readattackontitanshingekinokyojinmanga/src/ReadAttackOnTitanShingekiNoKyojinManga.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangacatalog/MangaCatalogGenerator.kt
> fixes #13734

- src/en/reaperscans/build.gradle
- src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt
> Fix broken source

- src/all/ehentai/build.gradle
- src/all/ehentai/src/eu/kanade/tachiyomi/extension/all/ehentai/EHentai.kt
Closes #14276
Checklist:
- [ -] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ -] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ -] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ -] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ -] Have not changed source names
- [ -] Have explicitly kept the `id` if a source's name or language were changed
- [ -] Have tested the modifications by compiling and running the extension through Android Studio
> Fix for #14276

- multisrc/overrides/mangathemesia/flamescans/src/FlameScans.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangathemesia/MangaThemesiaGenerator.kt
> FlameScans: Fix permanent url logic

- src/zh/zerobyw/build.gradle
- src/zh/zerobyw/src/eu/kanade/tachiyomi/extension/zh/zerobyw/Zerobyw.kt
Close #14430
Checklist:
- [] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [] Added the `isNsfw = true` flag in `build.gradle` when appropriate
> Update base URL zerobyw

- src/all/kavita/CHANGELOG.md
- src/all/kavita/build.gradle
- src/all/kavita/src/eu/kanade/tachiyomi/extension/all/kavita/Kavita.kt
> Kavita: Add pdf support

- multisrc/overrides/wpcomics/nettruyen/src/NetTruyen.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpcomics/WPComicsGenerator.kt
> Nettruyen URL Update

- multisrc/overrides/fmreader/welovemangaone/src/WeLoveMangaOne.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/fmreader/FMReaderGenerator.kt
> Add WeLoveMangaOne.

- multisrc/overrides/mangaraw/mangarawru/src/MangaRawRU.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangaraw/MangaRawGenerator.kt
> Add MangaRawRU.

- multisrc/overrides/mangaraw/mangarawru/src/ImageListParser.kt
- multisrc/overrides/mangaraw/mangarawru/src/MangaRawRU.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangaraw/MangaRawGenerator.kt
> MangaRawRU: fix page order

- multisrc/overrides/mangathemesia/constellarscans/src/ConstellarScans.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangathemesia/MangaThemesiaGenerator.kt
> fix page list

- multisrc/overrides/madara/hiperdex/src/Hiperdex.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
Sigh. Closes #15120 
Checklist:
> Update Hiperdex domain

- multisrc/overrides/madara/drakescans/src/DrakeScans.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> Fix Drake Scans wrong chapter release date

- src/zh/jinmantiantang/build.gradle
- src/zh/jinmantiantang/src/eu/kanade/tachiyomi/extension/zh/jinmantiantang/ScrambledImageInterceptor.kt
> Jinman Tiantang: update image descrambler

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangahub/MangaHub.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangahub/MangaHubGenerator.kt
> MangaHub: Patch extension

- src/all/tachidesk/build.gradle
- src/all/tachidesk/src/eu/kanade/tachiyomi/extension/all/tachidesk/Tachidesk.kt
> Tachidesk (Suwayomi): Implement search

- src/ru/comx/build.gradle
- src/ru/comx/src/eu/kanade/tachiyomi/extension/ru/comx/ComX.kt
Cleanup for
#15877
Check my stuff for errors, first time with kotlin, first time doing stuff on github, kindof scarry.
Checklist:
> [RU]ComX: Crossover-events handle, chapter naming cleanup

- multisrc/overrides/wpcomics/nettruyen/src/NetTruyen.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpcomics/WPComicsGenerator.kt
> nettruyen domain change

- src/en/hiveworks/build.gradle
- src/en/hiveworks/src/eu/kanade/tachiyomi/extension/en/hiveworks/Hiveworks.kt
> Hiveworks on hiatus support

- src/vi/hentaivn/src/eu/kanade/tachiyomi/extension/vi/hentaivn/HentaiVN.kt
> chore: update HentaiVN domain to mirror domain

- src/all/tachidesk/build.gradle
- src/all/tachidesk/src/eu/kanade/tachiyomi/extension/all/tachidesk/Dto.kt
- src/all/tachidesk/src/eu/kanade/tachiyomi/extension/all/tachidesk/Tachidesk.kt
QoL features for the Tachidesk extension. Pagination in particular drastically improves performance; app no longer slows down when fetching a library with hundreds of manga and/or high-res thumbnails.
Checklist:
> Suwayomi (Tachidesk): Implement pagination, sorting, tag-based filtering

- src/it/shingekinoshoujo/build.gradle
- src/it/shingekinoshoujo/src/eu/kanade/tachiyomi/extension/it/shingekinoshoujo/ShingekiNoShoujo.kt
Changed url
Fixed the code for the new site
I checked and there isn't any Issue related to this extension. 
Checklist:
> Fixed ShingekiNoShoujo

- multisrc/overrides/mangathemesia/manhwalist/src/ManhwaList.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangathemesia/MangaThemesiaGenerator.kt
> change base url manhwalist

- src/en/questionablecontent/build.gradle
- src/en/questionablecontent/src/eu/kanade/tachiyomi/extension/en/questionablecontent/QuestionableContent.kt
> Add Author's Notes To QuestionableContent

- src/fr/japanread/build.gradle
- src/fr/japanread/src/eu/kanade/tachiyomi/extension/fr/japanread/BentoManga.kt
Checklist:
Exclude the `component-chapter-title` containing `style="display:none"` which is not related to the series we're loading.
> Bentomanga fix chapters 

- multisrc/overrides/webtoons/webtoons/src/WebtoonsSrc.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/webtoons/WebtoonsGenerator.kt
> Fix CSS selectors for Author's Notes in Webtoons

- src/vi/hentaivn/build.gradle
- src/vi/hentaivn/src/eu/kanade/tachiyomi/extension/vi/hentaivn/HentaiVN.kt
> Hentaivn Fix bug "error 404 views chapter" 

- src/fr/furyosquad/build.gradle
- src/fr/furyosquad/src/eu/kanade/tachiyomi/extension/fr/furyosquad/FuryoSquad.kt
Checklist:
Closes #17358 
Closes #17357
> Change URL for Furyosquad

- multisrc/overrides/madara/hentaicube/src/HentaiCB.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> Update domain HentaiCB

- multisrc/overrides/wpcomics/nhattruyen/src/NhatTruyen.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpcomics/WPComicsGenerator.kt
> Update domain Nhattruyen

- multisrc/overrides/mangathemesia/animatedglitchedscans/src/AnimatedGlitchedScans.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangathemesia/MangaThemesiaGenerator.kt
> update Animated Glitched Scans domain

- multisrc/overrides/multichan/henchan/src/HenChan.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/multichan/ChanGenerator.kt
> [RU] Henchan - Change url and latest uri, update genres

- src/all/pixiv/build.gradle
- src/all/pixiv/src/eu/kanade/tachiyomi/extension/all/pixiv/Pixiv.kt
- src/all/pixiv/src/eu/kanade/tachiyomi/extension/all/pixiv/PixivTypes.kt
> Pixiv: fix chapter numbers and series details

- multisrc/overrides/webtoons/webtoons/src/WebtoonsFactory.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/webtoons/Webtoons.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/webtoons/WebtoonsGenerator.kt
> Webtoons: Fix cover and french status

- multisrc/overrides/mangathemesia/asurascans/src/AsuraScansEn.kt
- multisrc/overrides/mangathemesia/manhwafreak/src/ManhwaFreak.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangathemesia/MangaThemesia.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangathemesia/MangaThemesiaGenerator.kt
- Added cancelled status to multisrc. Didn't think it was worth to update all extensions
- ManhwaFreak: fix relative dates
- AsuraScans: fix search
Closes #18003
Checklist:
> MangaThemesia: AsuraScansEn search and ManhwaFreak dates

- src/ru/mangapoisk/build.gradle
- src/ru/mangapoisk/src/eu/kanade/tachiyomi/extension/ru/mangapoisk/MangaPoisk.kt
> [RU]MangaPoisk LICENSED notify deleted chapters

- src/en/nineanime/build.gradle
- src/en/nineanime/src/eu/kanade/tachiyomi/extension/en/nineanime/NineAnime.kt
> NineAnime: fix chapter pages

- multisrc/overrides/madara/mangalionz/src/MangaLionz.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> Updatre the Url for the overied mandra "mangalionz"

- src/ru/remanga/build.gradle
- src/ru/remanga/src/eu/kanade/tachiyomi/extension/ru/remanga/Remanga.kt
> [RU]Remanga filter only the last non-purchased chapters

- src/id/komikindoid/build.gradle
- src/id/komikindoid/src/eu/kanade/tachiyomi/extension/id/komikindoid/KomikIndoID.kt
- fix series status
- add other genre, series type
- add alternative name
Checklist:
> KomikIndoID: fix & add series info

- src/ru/comx/build.gradle
- src/ru/comx/src/eu/kanade/tachiyomi/extension/ru/comx/ComX.kt
> [RU]ComX fix cover & change titles lang

- src/en/comicextra/build.gradle
- src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt
> ComicExtra: Update URL

- multisrc/overrides/madara/mangarolls/src/MangaRolls.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> MangaRolls: Update URL

- multisrc/overrides/mangathemesia/sushiscan/src/SushiScan.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangathemesia/MangaThemesiaGenerator.kt
> Sushi-Scan: Add rate limit

- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/senkuro/Dto.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/senkuro/Senkuro.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/senkuro/SenkuroGenerator.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/senkuro/SenkuroQueries.kt
> [RU]Senkuro date_upload createdAt

- src/th/nekopost/build.gradle
- src/th/nekopost/src/eu/kanade/tachiyomi/extension/th/nekopost/Nekopost.kt
- src/th/nekopost/src/eu/kanade/tachiyomi/extension/th/nekopost/model/RawProjectSearchSummary.kt
fix Nekopost search HTTP error 520
Checklist:
> Nekopost extension: Search fix (HTTP error 520)

- src/all/comickfun/AndroidManifest.xml
- src/all/comickfun/build.gradle
- src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
Apparently the reason for the recent domain-hopping is [they're looking for an Ad Network](https://old.reddit.com/r/ComicK/comments/18dmf7l/is_everything_alright/kcj6q6n/), but I need *muh* deeplinks
Checklist:
> [Comick] New TLD

- multisrc/overrides/wpcomics/nettruyen/src/NetTruyen.kt
- multisrc/overrides/wpcomics/nhattruyen/src/NhatTruyen.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpcomics/WPComicsGenerator.kt
> (multisrc/WPComic) Update domain Nettruyen & Nhattruyen

- multisrc/overrides/mymangacms/truyentranhlh/src/TruyenTranhLH.kt
- multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mymangacms/MyMangaCMSGenerator.kt
> (Mutilsrc/mymangacms) Update domain truyentranhlh

- src/id/bacakomik/build.gradle
- src/id/bacakomik/src/eu/kanade/tachiyomi/extension/id/bacakomik/BacaKomik.kt
- fix image issue
- clean series info code
- add artist name
- tweak ratelimit
Closes #19454
Checklist:
> BacaKomik: fix img issue, clean series info, add artist
