tachiyomiorg/tachiyomi-extensions

- it-mangaeden/build.gradle
- it-mangaeden/src/eu/kanade/tachiyomi/extension/it/mangaeden/Mangaeden.kt
- settings.gradle
I take this opportunity to ask a question.
I think I'm going to write also mangaeden(en) and perveden extensions, since the structure is basically the same.
The question is, since perveden is an hentai website, do you still want the extension to be in this repo or not?
> Added mangaeden(it) extension

- src/en/readcomiconline/build.gradle
- src/en/readcomiconline/src/eu/kanade/tachiyomi/extension/en/readcomiconline/Readcomiconline.kt
copied kissmanga, fixed few things that were different
> Add ReadComicOnline

- src/en/mangazuki/build.gradle
- src/en/mangazuki/src/eu/kanade/tachiyomi/extension/en/mangazuki/Mangazuki.kt
- src/en/webtoons/build.gradle
- src/en/webtoons/src/eu/kanade/tachiyomi/extension/en/webtoons/Webtoons.kt
Add Webtoon.com source
Add mangazuki.co source (fixes #48 )
> Add webtoons.com and Mangazuki.co (#48)

- src/en/mangapark/src/eu/kanade/tachiyomi/extension/en/mangapark/MangaPark.kt
This PR contains two bug fixes for the MangaPark source:
- Fix broken date parsing for some chapters
- Fix the next page selector selecting the wrong elements when searching
(This resulted in "No results found" messages when moving between pages)
Resolves #61, #82
> Fix various bugs in MangaPark source

- src/en/readcomictv/build.gradle
- src/en/readcomictv/src/eu/kanade/tachiyomi/extension/en/readcomictv/Readcomictv.kt
> Fix readcomicstv

- src/en/mangastream/build.gradle
- src/en/mangastream/src/eu/kanade/tachiyomi/extension/en/mangastream/Mangastream.kt
As always, if there's some shitty code that can be more beautifully displayed tell me. And if doing so many calls to fetch the covers from MAL is something undesired I can remove it (it takes a bit to get them, too). #76
> Add Mangastream (closes #76)

- src/it/hentaifantasy/build.gradle
- src/it/hentaifantasy/src/eu/kanade/tachiyomi/extension/it/hentaifantasy/HentaiFantasy.kt
This is the first of two extensions requested in #91.
> Add HentaiFantasy (hentaifantasy.it) source. Closes #91 (1/2)

- src/it/hastareader/build.gradle
- src/it/hastareader/src/eu/kanade/tachiyomi/extension/it/hastareader/HastaReader.kt
This is the second of two extensions requested in #91.
> Add HastaReader (hastareader.com) source. Closes #91 (2/2)

- src/en/mangago/src/eu/kanade/tachiyomi/extension/en/mangago/Mangago.kt
Lol at Mangago's obfuscation attempts. Look at the title bar URL when you start reading any manga: http://www.mangago.me/read-manga/01_monkey/mf/v01/c001.1/
Resolves #88
> Fix Mangago reader

- src/en/mangacow/build.gradle
- src/en/mangacow/src/eu/kanade/tachiyomi/extension/en/mangacow/Mangacow.kt
> Add Mangacow (mngcow.co) source.

- src/en/merakiscans/build.gradle
- src/en/merakiscans/src/eu/kanade/tachiyomi/extension/en/merakiscans/MerakiScans.kt
> Add MerakiScans (merakiscans.com) source.

- src/en/mangahere/build.gradle
- src/en/mangahere/src/eu/kanade/tachiyomi/extension/en/mangahere/Mangahere.kt
updated to match internal source
> MangaHere update

- src/en/kissmanga/build.gradle
- src/en/kissmanga/src/eu/kanade/tachiyomi/extension/en/kissmanga/Kissmanga.kt
updated to match internal source
> kissmanga update

- src/ru/mangachan/build.gradle
- src/ru/mangachan/src/eu/kanade/tachiyomi/extension/ru/mangachan/Mangachan.kt
updated to match internal source
> mangachan update

- src/en/readmangatoday/build.gradle
- src/en/readmangatoday/src/eu/kanade/tachiyomi/extension/en/readmangatoday/Readmangatoday.kt
- src/ru/readmanga/build.gradle
updated to match internal source
> ReadMangaToday

- src/ru/mintmanga/build.gradle
- src/ru/mintmanga/src/eu/kanade/tachiyomi/extension/ru/mintmanga/Mintmanga.kt
- src/ru/readmanga/build.gradle
- src/ru/readmanga/src/eu/kanade/tachiyomi/extension/ru/readmanga/Readmanga.kt
pulled in changes from internal source to external source here.
> update mint/readmanga 

- src/en/mangafox/build.gradle
- src/en/mangafox/src/eu/kanade/tachiyomi/extension/en/mangafox/Mangafox.kt
updated to match internal source in tachiyomi app (actually matching Flats pull request #1119 in main app)
> update mangafox  external source

- src/ru/mintmanga/build.gradle
- src/ru/mintmanga/src/eu/kanade/tachiyomi/extension/ru/mintmanga/Mintmanga.kt
- src/ru/readmanga/build.gradle
- src/ru/readmanga/src/eu/kanade/tachiyomi/extension/ru/readmanga/Readmanga.kt
Sync with [#1192](https://github.com/inorichi/tachiyomi/pull/1192)
>  Add referer to readmanga/mintmanga requests header

- src/en/dynasty/build.gradle
- src/en/dynasty/src/eu/kanade/tachiyomi/extension/en/dynasty/DynastyAnthologies.kt
- src/en/dynasty/src/eu/kanade/tachiyomi/extension/en/dynasty/DynastyDoujins.kt
- src/en/dynasty/src/eu/kanade/tachiyomi/extension/en/dynasty/DynastyIssues.kt
- src/en/dynasty/src/eu/kanade/tachiyomi/extension/en/dynasty/DynastyScans.kt
- src/en/dynasty/src/eu/kanade/tachiyomi/extension/en/dynasty/DynastySeries.kt
can close #75 
took ThePreviousOnes base code and fixed all the issues mentioned in the review and comments
> Added dynasty scans with fixes

- src/ru/mangachan/build.gradle
- src/ru/mangachan/src/eu/kanade/tachiyomi/extension/ru/mangachan/Mangachan.kt
Copy of https://github.com/inorichi/tachiyomi/pull/1138
> Add mangachan features

- src/en/dynasty/build.gradle
- src/en/dynasty/src/eu/kanade/tachiyomi/extension/en/dynasty/DynastyScans.kt
#162
Thanks @sharedkestrel for all the details made it super easy to debug
> Fixed DynastyScans page list issue

- src/en/readmangatoday/build.gradle
- src/en/readmangatoday/src/eu/kanade/tachiyomi/extension/en/readmangatoday/Readmangatoday.kt
https://github.com/inorichi/tachiyomi/issues/1199
> fix readmangatoday search issue

- src/en/mangadex/build.gradle
- src/en/mangadex/src/eu/kanade/tachiyomi/extension/en/mangadex/Mangadex.kt
Added mangadex #161. Their site is still developing so pagination, language selection, genres etc are missing for now.  Probably will break as they keep adding features but i'll keep an eye out for issues
> add mangadex

- src/en/mangapark/build.gradle
- src/en/mangapark/src/eu/kanade/tachiyomi/extension/en/mangapark/MangaPark.kt
> Fix MangaPark image URLs and some code cleanup

- src/en/mangastream/build.gradle
- src/en/mangastream/src/eu/kanade/tachiyomi/extension/en/mangastream/Mangastream.kt
Mangastream made a couple of changes which broke latest updates and this PR fixes that.
> Fix mangastream's latest updates

- src/en/readmangatoday/build.gradle
- src/en/readmangatoday/src/eu/kanade/tachiyomi/extension/en/readmangatoday/Readmangatoday.kt
fix genre tags to be delimited correctly
> ReadMangaToday genre tag fix

- src/en/mangadex/build.gradle
- src/en/mangadex/src/eu/kanade/tachiyomi/extension/en/mangadex/Mangadex.kt
fix genre tags
add genre filter when searching
added paging for browse
> Update changes for mangadex

- src/en/mangadex/build.gradle
- src/en/mangadex/src/eu/kanade/tachiyomi/extension/en/mangadex/Mangadex.kt
- added paging for latest
- added ability in search to choose by letter, also added paging for this variation
- added cookie to view all manga including adult
@inorichi this is good now
> Mangadex updates

- src/en/readcomiconline/src/eu/kanade/tachiyomi/extension/en/readcomiconline/Readcomiconline.kt
> Fix readcomiconline paging and adjust to pull HQ images

- src/ja/senmanga/build.gradle
- src/ja/senmanga/src/eu/kanade/tachiyomi/extension/ja/senmanga/SenManga.kt
> Fix Senmanga

- src/en/readcomiconline/build.gradle
@inorichi forgot to adjust build.gradle on last pull request
> readcomiconline build.gradle adjustment

- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
> R18 during search option for Mangadex fixed chapter date

- src/en/xkcd/build.gradle
- src/en/xkcd/src/eu/kanade/tachiyomi/extension/en/xkcd/Xkcd.kt
#52
@j2ghz  couple things
1.  Do you know a better url i can use for the cover? 
2.  I can't currently thing of a way to see the alt text for each "chapter".   As extensions are only able to pass in urls to images  for a page.
> added xkcd

- src/en/xkcd/build.gradle
- src/en/xkcd/src/eu/kanade/tachiyomi/extension/en/xkcd/Xkcd.kt
> pull hd images for later comics xkcd

- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
adjusted paging of chapters -> #227
adjusted url to new .org
> Mangadex fixes

- src/en/dynasty/build.gradle
- src/en/dynasty/src/eu/kanade/tachiyomi/extension/en/dynasty/DynastyChapters.kt
- src/en/dynasty/src/eu/kanade/tachiyomi/extension/en/dynasty/DynastyScans.kt
fix duplicate genre tags
give default cover for chapters which allows covers to be set 
#226
> Dynasty Scans fixes

- src/en/dynasty/build.gradle
- src/en/dynasty/src/eu/kanade/tachiyomi/extension/en/dynasty/DynastyChapters.kt
> dynasty scans fix

- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
fixed bug with json for manga that were added pre id only url
> mandex fixes

- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
added dash for chapter name when there is title
> mangadex added - back in dont hate me :)

- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
switch to json changed date and caused future chapters to show again
> Mangadex future chapter fix

- src/en/mangarock/build.gradle
- src/en/mangarock/src/eu/kanade/tachiyomi/extension/en/mangarock/MangaRock.kt
- Make completed filter into a tristate filter
- Sort chapters in descending order to match how the website shows them
> Manga Rock fixes

- src/ru/desu/build.gradle
- src/ru/desu/src/eu/kanade/tachiyomi/extension/ru/desu/Desu.kt
> desu: Fix statuses

- src/zh/dmzj/build.gradle
- src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt
Dmzj is banning okhttp UA now...
> Dmzj: set UA

- src/all/foolslide/build.gradle
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/en/foolslide/FoolSlide.kt
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/en/foolslide/FoolSlideFactory.kt
Add more FoolSlide sources
Fix spacing in FoolSlide extension name
Fix Jaiminibox chapter dates
Fixes #283
Fixes #288 
Fixes #261
> FoolSlide enchancements

- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
> fix mangadex search and search paging

- src/all/foolslide/build.gradle
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/en/foolslide/FoolSlide.kt
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/en/foolslide/FoolSlideFactory.kt
> Fix FoolSlide dates

- src/all/foolslide/build.gradle
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/en/foolslide/FoolSlideFactory.kt
> Add NANI? SCANS to FoolSlide

- src/en/mangago/build.gradle
- src/en/mangago/src/eu/kanade/tachiyomi/extension/en/mangago/Mangago.kt
This should work. All creds to @bboyz269
> Fix mangago

- src/ru/mintmanga/build.gradle
- src/ru/mintmanga/src/eu/kanade/tachiyomi/extension/ru/mintmanga/Mintmanga.kt
- src/ru/readmanga/build.gradle
- src/ru/readmanga/src/eu/kanade/tachiyomi/extension/ru/readmanga/Readmanga.kt
https://github.com/inorichi/tachiyomi/pull/1459
> Update date selector and chapter number recognition for readmanga/mintmanga

- src/en/webtoons/build.gradle
- src/en/webtoons/src/eu/kanade/tachiyomi/extension/en/webtoons/Webtoons.kt
Removed the not-so-popular search filter. Now the search returns the results from the Webtoon and Discover sections together.
> webtoons: remove search filter and add mixed search

- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
missing null check was causing manga details not to parse when there are no chapters
> mangadex no chapter fix

- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
mangadex: fix completed and [END] being added mistakenly on manga with only 1 chapter labelled chapter number 0
fixes #380
> [END] tag fix

- src/en/readcomiconline/build.gradle
- src/en/readcomiconline/src/eu/kanade/tachiyomi/extension/en/readcomiconline/Readcomiconline.kt
Without this, the POST gets a 302 that doesn't send the search terms
> [ReadComicOnline] Switch to https so searching works

- src/ru/desu/build.gradle
- src/ru/desu/src/eu/kanade/tachiyomi/extension/ru/desu/Desu.kt
> Update Desu Source. Add genres and improve paging

- src/all/myreadingmanga/build.gradle
- src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt
> fix myreadingmanga showing next as chapter

- src/en/readcomictv/build.gradle
- src/en/readcomictv/src/eu/kanade/tachiyomi/extension/en/readcomictv/Readcomictv.kt
> Update readcomics for readcomics.io

- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
fix status not showing completed, when last chapter was not selected language
> fix status not showing completed, when cancelled status on mangadex.

- build.gradle
Although we might want to update both to 1.2.60.
> Update Kotlin to match main Tachiyomi app

- common.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
- src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt
- src/all/nhentai/src/eu/kanade/tachiyomi/extension/all/nhentai/NHentai.kt
- src/en/dynasty/src/eu/kanade/tachiyomi/extension/en/dynasty/DynastyScans.kt
- src/en/hentai2read/src/eu/kanade/tachiyomi/extension/en/hentai2read/Hentai2Read.kt
- src/en/mangacow/src/eu/kanade/tachiyomi/extension/en/mangacow/Mangacow.kt
- src/en/mangaeden/src/eu/kanade/tachiyomi/extension/en/mangaeden/Mangaeden.kt
- src/en/mangazuki/src/eu/kanade/tachiyomi/extension/en/mangazuki/Mangazuki.kt
- src/en/perveden/src/eu/kanade/tachiyomi/extension/en/perveden/Perveden.kt
- src/en/readcomiconline/src/eu/kanade/tachiyomi/extension/en/readcomiconline/Readcomiconline.kt
- src/en/shoujosense/src/en/kanade/tachiyomi/extension/en/shoujosense/ShoujoSense.kt
- src/en/webtoons/src/eu/kanade/tachiyomi/extension/en/webtoons/Webtoons.kt
- src/it/hentaifantasy/src/eu/kanade/tachiyomi/extension/it/hentaifantasy/HentaiFantasy.kt
- src/it/mangaeden/src/eu/kanade/tachiyomi/extension/it/mangaeden/Mangaeden.kt
- src/it/perveden/src/eu/kanade/tachiyomi/extension/it/perveden/Perveden.kt
- src/pt/unionmangas/src/eu/kanade/tachiyomi/extension/pt/unionmangas/UnionMangas.kt
- src/vi/truyentranhlh/src/eu/kanade/tachiyomi/extension/vi/truyentranhlh/Truyentranhlh.kt
To match what's in the main repo.
> Update common dependencies

- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
Nothing actually functional, just minor code cleanup.
> Minor edits

- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
cf. https://github.com/inorichi/tachiyomi/issues/1576
> Fix searching with only genres in MangaDex (closes #444)

- src/ru/mintmanga/build.gradle
- src/ru/mintmanga/src/eu/kanade/tachiyomi/extension/ru/mintmanga/Mintmanga.kt
- src/ru/readmanga/build.gradle
- src/ru/readmanga/src/eu/kanade/tachiyomi/extension/ru/readmanga/Readmanga.kt
https://github.com/inorichi/tachiyomi/pull/1607
> Add categories for readmanga/mintmanga

- src/all/mmrcms/build.gradle
- src/all/mmrcms/src/eu/kanade/tachiyomi/extension/all/mmrcms/MyMangaReaderCMSSource.kt
> fix covers

- src/ru/selfmanga/build.gradle
- src/ru/selfmanga/src/eu/kanade/tachiyomi/extension/ru/selfmanga/Selfmanga.kt
> Add sources Selfmanga.ru

- src/en/mangahasu/build.gradle
- src/en/mangahasu/src/eu/kanade/tachiyomi/extension/en/mangahasu/Mangahasu.kt
> Add new source mangahasu

- src/en/mangasee/src/eu/kanade/tachiyomi/extension/en/mangasee/Mangasee.kt
not updating gradle since i just want this for a potential next release.
> switch to base url

- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
> mangadex add sorting

- src/all/myreadingmanga/build.gradle
- src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt
> fix myreadingmanga

- src/all/myreadingmanga/build.gradle
- src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt
> fix images again for myreadingmanga

- src/en/kissmanga/build.gradle
- src/en/kissmanga/src/eu/kanade/tachiyomi/extension/en/kissmanga/Kissmanga.kt
> add Isekai for kissmanga and fix genre search bug

- src/all/myreadingmanga/build.gradle
- src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt
fixes #551 for realz this time
> myreadingmanga fix again

- src/all/wpmanga/build.gradle
- src/all/wpmanga/src/eu/kanade/tachiyomi/extension/all/wpmanga/WpManga.kt
> fix zeroscans

- src/ru/mintmanga/build.gradle
- src/ru/mintmanga/src/eu/kanade/tachiyomi/extension/ru/mintmanga/Mintmanga.kt
- src/ru/readmanga/build.gradle
- src/ru/readmanga/src/eu/kanade/tachiyomi/extension/ru/readmanga/Readmanga.kt
https://github.com/inorichi/tachiyomi/pull/1665
> Fix potential NPE at cover image selector (readmanga/mintmanga)

- src/ru/mangahub/build.gradle
- src/ru/mangahub/src/eu/kanade/tachiyomi/extension/ru/mangahub/Mangahub.kt
> Mangahub: Page fix

- src/all/myreadingmanga/build.gradle
- src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt
Fixes #566, changed MyReadingManga CSS selector
> Fixes MyReadingManga

- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
> support Oneshot for mangadex

- src/all/myreadingmanga/build.gradle
- src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt
Fixes #588, tried some mangas and everything seems to be working
> Fixes MyReadingManga selector once again

- src/ja/rawlh/build.gradle
- src/ja/rawlh/src/eu/kanade/tachiyomi/extension/ja/rawlh/Rawlh.kt
Issue was mentioned on Discord.
> Fix RawLH chapters selector

- src/ja/rawlh/build.gradle
- src/ja/rawlh/src/eu/kanade/tachiyomi/extension/ja/rawlh/Rawlh.kt
Chapter dates have been broken for quite some time, this fixes it.
> Fix chapter dates for RawLH

- src/en/mangarock/build.gradle
- src/en/mangarock/src/eu/kanade/tachiyomi/extension/en/mangarock/MangaRock.kt
> Update Manga Rock API version

- src/all/foolslide/build.gradle
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/en/foolslide/FoolSlideFactory.kt
Added and tested LupiTeam's FoolSlide
> Added LupiTeam's FoolSlide

- src/all/myreadingmanga/build.gradle
- src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt
> mrm adjust for manga that dont have language in url

- src/fr/japscan/build.gradle
- src/fr/japscan/src/eu/kanade/tachiyomi/extension/fr/japscan/Japscan.kt
> Update Japscan URL

- src/all/foolslide/build.gradle
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/en/foolslide/FoolSlideFactory.kt
Dot.tk stolen our domain, so we changed it again
> Changed LupiTeam's domain

- src/en/merakiscans/build.gradle
- src/en/merakiscans/src/eu/kanade/tachiyomi/extension/en/merakiscans/MerakiScans.kt
Everything is fixed now, unless there's some weird dependency I'm forgetting. I can successfully get it working on my device. 
@CarlosEsco This should be good to merge. I've tested everything, but if you want to double check that would be great.
> [Final] MerakiScans #694

- src/en/merakiscans/src/eu/kanade/tachiyomi/extension/en/merakiscans/MerakiScans.kt
If this don't work, I'm actually braindead.
Please travis-sama.
> [Meraki] 3rd time's the charm.

- src/all/comicake/build.gradle
- src/all/comicake/src/eu/kanade/tachiyomi/extension/en/comicake/ComiCake.kt
- src/all/comicake/src/eu/kanade/tachiyomi/extension/en/comicake/ComiCakeFactory.kt
- src/all/foolslide/build.gradle
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/en/foolslide/FoolSlideFactory.kt
Adds support for sites using ComiCake. All essentials work
> Add ComiCake support

- src/pt/mangalivre/build.gradle
- src/pt/mangalivre/src/eu/kanade/tachiyomi/extension/pt/mangalivre/MangaLivre.kt
- src/pt/mangasproject/build.gradle
- src/pt/mangasproject/src/eu/kanade/tachiyomi/extension/pt/mangasproject/MangasProject.kt
- src/pt/unionmangas/build.gradle
- src/pt/unionmangas/src/eu/kanade/tachiyomi/extension/pt/unionmangas/UnionMangas.kt
Some fixes for the brazilian sources.
- Fix wrong date parsing in chapter list in both MangasProject and MangaLivre;
- Fix indentation of `MangasProject.kt` and `MangasLivre.kt`;
- Fix latest releases not working in UnionMangas (closes #658);
- UnionMangas now use https.
> Fixes for brazilian sources

- src/all/nhentai/build.gradle
- src/all/nhentai/src/eu/kanade/tachiyomi/extension/all/nhentai/NHentai.kt
Added the baseurl to the mangadetailsrequest function in the nhentai extension to view the manga properly when opened in the browser
> [nhentai] fix open in browser issue (closes issue #709)

- src/ru/mintmanga/build.gradle
- src/ru/mintmanga/src/eu/kanade/tachiyomi/extension/ru/mintmanga/Mintmanga.kt
- src/ru/readmanga/build.gradle
- src/ru/readmanga/src/eu/kanade/tachiyomi/extension/ru/readmanga/Readmanga.kt
On this sites date format has two variants now -_-
> Added new date format for readmanga/mintmanga

- src/pt/mangalivre/build.gradle
- src/pt/mangalivre/src/eu/kanade/tachiyomi/extension/pt/mangalivre/MangaLivre.kt
- src/pt/mangasproject/build.gradle
- src/pt/mangasproject/src/eu/kanade/tachiyomi/extension/pt/mangasproject/MangasProject.kt
- Fix missing dates for chapters released "today" and "yesterday";
- Fix missing author and artist in completed mangas;
- Add missing scanlators when there's more than one.
> Fixes for MangasProject and MangaLivre

- src/en/arcrelight/src/eu/kanade/tachiyomi/extension/en/arcrelight/ARFilters.kt
Category was missing from list 
category found at:
https://arc-relight.site/reader/comic-trailer/
> Added Category/Genre ("Jubilee")

- src/ko/mangashowme/build.gradle
- src/ko/mangashowme/src/eu/kanade/tachiyomi/extension/ko/mangashowme/MSMFilters.kt
- src/ko/mangashowme/src/eu/kanade/tachiyomi/extension/ko/mangashowme/MSMImageDecoder.kt
- src/ko/mangashowme/src/eu/kanade/tachiyomi/extension/ko/mangashowme/MangaShowMe.kt
This codes has long history which may dirty.
> Add MangaShow.Me (Korean source)

- src/ko/jmana/build.gradle
- src/ko/jmana/src/eu/kanade/tachiyomi/extension/ko/jmana/JMana.kt
It's just new korean manga source.
> Add JMana (Korean Source)

- src/ru/libmanga/build.gradle
- src/ru/libmanga/src/eu/kanade/tachiyomi/extension/ru/libmanga/LibMangaFactory.kt
Manga has been transferred to MangaLib
> Remove YaoiLib as site has "Site is closed indefinitely" notice

- src/ru/libmanga/src/eu/kanade/tachiyomi/extension/ru/libmanga/LibMangaFactory.kt
> Fix build error due to not-deleted code on previous commit.

- src/ko/newtoki/build.gradle
- src/ko/newtoki/src/eu/kanade/tachiyomi/extension/ko/newtoki/NewToki.kt
Pagination was my mistake. Sorry.
> NewToki: Better Date handling, Fix popular request pagination

- src/ja/rawQQ/build.gradle
- src/ja/rawQQ/src/eu/kanade/tachiyomi/extension/ja/rawqq/Rawqq.kt
- src/ja/rawlh/build.gradle
- src/ja/rawlh/src/eu/kanade/tachiyomi/extension/ja/rawlh/Rawlh.kt
rawlh has `years ago`<br/>rawQQ is not confirmed but predicted from pattern.
> Support years ago in raw sites.

- src/ru/acomics/src/eu/kanade/tachiyomi/extension/ru/acomics/Acomics.kt
> AComics some fixes

- src/ko/jmana/build.gradle
- src/ko/jmana/src/eu/kanade/tachiyomi/extension/ko/jmana/JMana.kt
- src/ko/mangashowme/build.gradle
- src/ko/mangashowme/src/eu/kanade/tachiyomi/extension/ko/mangashowme/MSMImageDecoder.kt
- src/ko/mangashowme/src/eu/kanade/tachiyomi/extension/ko/mangashowme/MangaShowMe.kt
fix #854 + JMana: support uploaded date.
-----
JMana: They're using `iframe` tag to hide elements in (normal) accessible url.
MSM: Replace old url to new url (implement site's client-side script)
> Update extensions due to sites update.

- src/all/myreadingmanga/build.gradle
- src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt
- src/id/neumanga/src/eu/kanade/tachiyomi/extension/id/neumanga/Neumanga.kt
> [indonesian] neumanga source

- src/fr/japscan/build.gradle
- src/fr/japscan/src/eu/kanade/tachiyomi/extension/fr/japscan/Japscan.kt
- src/ko/jmana/build.gradle
- src/ko/jmana/src/eu/kanade/tachiyomi/extension/ko/jmana/JMana.kt
- src/ko/mangashowme/build.gradle
- src/ko/mangashowme/src/eu/kanade/tachiyomi/extension/ko/mangashowme/MangaShowMe.kt
- src/ko/newtoki/build.gradle
- src/ko/newtoki/src/eu/kanade/tachiyomi/extension/ko/newtoki/NewToki.kt
Japscans: fix #888 + https://github.com/inorichi/tachiyomi-extensions/issues/888#issuecomment-471766017
Others: update domains.
> Update extensions to fix issues

- src/ru/henchan/build.gradle
- src/ru/henchan/src/eu/kanade/tachiyomi/extension/ru/henchan/Henchan.kt
> Henchan.me - fix search

- src/fr/japscan/build.gradle
- src/fr/japscan/src/eu/kanade/tachiyomi/extension/fr/japscan/Japscan.kt
Based on @Peuuuur-Noel's comment in #931.
> Japscan: use proper request method in interceptor (fixes #931)

- src/en/manganelo/build.gradle
- src/en/manganelo/src/eu/kanade/tachiyomi/extension/en/manganelo/Manganelo.kt
Same fixes as MangaKakalot in #883.
> Fix MangaNelo (fixes #915)

- src/es/ikuhentai/src/eu/kanade/tachiyomi/extension/es/ikuhentai/Ikuhentai.kt
- src/id/komikgo/src/eu/kanade/tachiyomi/extension/id/komikgo/Komikgo.kt
- src/vi/blogtruyen/src/eu/kanade/tachiyomi/extension/vi/blogtruyen/Blogtruyen.kt
- src/vi/iutruyentranh/src/eu/kanade/tachiyomi/extension/vi/iutruyentranh/Iutruyentranh.kt
Doesn't really warrant actual releases for the extensions though.
> Remove logging statements

- src/vi/academyvn/build.gradle
- src/vi/academyvn/src/eu/kanade/tachiyomi/extension/vi/academyvn/HocVienTruyenTranh.kt
- src/vi/blogtruyen/build.gradle
- src/vi/blogtruyen/src/eu/kanade/tachiyomi/extension/vi/blogtruyen/BlogTruyen.kt
- src/vi/iutruyentranh/build.gradle
- src/vi/iutruyentranh/src/eu/kanade/tachiyomi/extension/vi/iutruyentranh/IuTruyenTranh.kt
- src/vi/truyentranhlh/build.gradle
- src/vi/truyentranhlh/src/eu/kanade/tachiyomi/extension/vi/truyentranhlh/TruyenTranhLH.kt
- Fix genre all VI sources
- Fix image parse error on TruyenTranhLH
- Rename all VI sources class
- Updated from old to new url
> Try to fix error and update old source

- src/all/nhentai/build.gradle
- src/all/nhentai/src/eu/kanade/tachiyomi/extension/all/nhentai/NHentai.kt
Addresses #938 
Also includes general refactoring to remove some redundancy and janky URL building for search.
> NHentai: fetch thumbnails directly from page response, add version to user agent

- src/vi/academyvn/build.gradle
- src/vi/academyvn/src/eu/kanade/tachiyomi/extension/vi/academyvn/HocVienTruyenTranh.kt
- src/vi/blogtruyen/build.gradle
- src/vi/blogtruyen/src/eu/kanade/tachiyomi/extension/vi/blogtruyen/BlogTruyen.kt
- src/vi/truyentranhlh/build.gradle
- src/vi/truyentranhlh/src/eu/kanade/tachiyomi/extension/vi/truyentranhlh/TruyenTranhLH.kt
Known bug: 403 error with mangas store in "https://cdn.lhmanga.com"
> Fix TruyenTranhLH, HocVienTruyenTranh, BlogTruyen small issues

- src/all/ninehentai/build.gradle
- src/all/ninehentai/src/eu/kanade/tachiyomi/extension/all/ninehentai/NineHentai.kt
> [ninehentai] convert JSON string to map

- src/all/ehentai/build.gradle
- src/all/ehentai/src/eu/kanade/tachiyomi/extension/all/ehentai/EHentai.kt
- src/all/ehentai/src/eu/kanade/tachiyomi/extension/all/ehentai/ExGalleryMetadata.kt
Doesn't include any of the extra ExHentai stuff.
From https://github.com/ilwaz/TachiyomiEH.
> Port E-Hentai from ilwaz/TachiyomiEH (closes #960)

- src/ko/jmana/build.gradle
- src/ko/jmana/src/eu/kanade/tachiyomi/extension/ko/jmana/JMana.kt
- src/ko/mangashowme/build.gradle
- src/ko/mangashowme/src/eu/kanade/tachiyomi/extension/ko/mangashowme/MSMFilters.kt
- src/ko/mangashowme/src/eu/kanade/tachiyomi/extension/ko/mangashowme/MSMImageDecoder.kt
- src/ko/mangashowme/src/eu/kanade/tachiyomi/extension/ko/mangashowme/MangaShowMe.kt
- src/ko/newtoki/build.gradle
- src/ko/newtoki/src/eu/kanade/tachiyomi/extension/ko/newtoki/NewToki.kt
All of Korean Extensions except ManhwaHand: Update domain. (Fix #961 for S.Korea users)
------
MSM: Re-branded to ManaMoa
JMana, NewToki: Support Latest
> Update Korean extensions

- src/en/webtoons/build.gradle
- src/en/webtoons/src/eu/kanade/tachiyomi/extension/en/webtoons/Webtoons.kt
Chapter cache needs to be cleared.
> Indicate if Webtoon chapter has music (closes #769)

- src/ko/mangashowme/build.gradle
- src/ko/mangashowme/src/eu/kanade/tachiyomi/extension/ko/mangashowme/MSMImageDecoder.kt
- src/ko/mangashowme/src/eu/kanade/tachiyomi/extension/ko/mangashowme/MangaShowMe.kt
I just no-mind that name change causing soooo many problems. So i reverted it.
(Shows `Source not installed`, Just Trying to use old methods if app not fully reloaded)
+ Little improves
> Revert name changes and etcs... in MSM extension.

- src/en/manhwahentai/build.gradle
- src/en/manhwahentai/src/eu/kanade/tachiyomi/extension/en/manhwahentai/Manhwahentai.kt
The Description of manga included shows show due to selection of complete div
> ManhwaHentai Manga Description (show more fix)

- src/all/foolslide/src/eu/kanade/tachiyomi/extension/en/foolslide/FoolSlide.kt
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/en/foolslide/FoolSlideFactory.kt
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/en/foolslide/HentaiCafe.kt
Why use foolslide if you are going to change up 90% of the UI? \**sigh*\*
Fixes #628.
> Add HentaiCafe

- src/all/ehentai/build.gradle
- src/all/ehentai/src/eu/kanade/tachiyomi/extension/all/ehentai/EHentai.kt
https://github.com/ilwaz/TachiyomiEH/compare/af1195aaf3d1e1271ee9c697b57b84d141d3bd8f...a9ecfd59fa71bb22a20c965cfb36fddc35e5324e#diff-38623e27ff84b67842f6dafccd22ab42
> Backport E-Hentai fixes from ilwaz/TachiyomiEH (closes #1003)

- src/ko/manhwahand/build.gradle
- src/ko/manhwahand/src/eu/kanade/tachiyomi/extension/ko/manhwahand/Manhwahand.kt
Show more is added due to selection of `div` rather then `p`
> (Show More) in description

- src/en/mangahere/build.gradle
- src/en/mangahere/src/eu/kanade/tachiyomi/extension/en/mangahere/Mangahere.kt
> MangaHere fix

- src/en/mangazuki/build.gradle
- src/en/mangazuki/src/eu/kanade/tachiyomi/extension/en/mangazuki/Mangazuki.kt
- src/en/questionablecontent/src/eu/kanade/tachiyomi/extension/en/questionablecontent/QuestionableContent.kt
- src/en/xkcd/src/eu/kanade/tachiyomi/extension/en/xkcd/Xkcd.kt
Didn't bump the other extensions since there isn't any functional changes.
> MangaZuki: return empty list for search (fixes #1034)

- lib/preference-stub/src/main/java/android/support/v7/preference/DialogPreference.java
- lib/preference-stub/src/main/java/android/support/v7/preference/EditTextPreference.java
- lib/preference-stub/src/main/java/android/support/v7/preference/ListPreference.java
- lib/preference-stub/src/main/java/android/support/v7/preference/Preference.java
- src/ko/mangashowme/build.gradle
- src/ko/mangashowme/src/eu/kanade/tachiyomi/extension/ko/mangashowme/MSMFilters.kt
- src/ko/mangashowme/src/eu/kanade/tachiyomi/extension/ko/mangashowme/MangaShowMe.kt
MSM
----
* Update filter.
* Fix tags
* Fix image fetch due to site changes (v4 -> v11)
* Add BaseUrl Override for site domain changes.
- Korean sources are change domain every 1-2 weeks due to internet censorship.
- For this update, I change some codes on `preference-stub`
Preference-stub
----
* Re-arrange some stubs to correct class.
- Some of `Preference` stubs are located in `ListPreference`. I just move to `Preference` class.
* Add EditTextPreference
- For this, I add some codes about dialog in `DialogPreference`.
Thus this update cause a bug in another extension that uses preference.
ps. There's no compile error.
> Update MSM Extension.

- src/en/mangarock/build.gradle
- src/en/mangarock/src/eu/kanade/tachiyomi/extension/en/mangarock/MangaRock.kt
Not entirely sure if it fixes it 100%, but it at least worked for Solo Leveling on my end?
> Potentially address missing MangaRock chapters (closes #1083)

- lib/ratelimit/build.gradle
- lib/ratelimit/src/main/AndroidManifest.xml
- lib/ratelimit/src/main/java/eu/kanade/tachiyomi/lib/ratelimit/RateLimitInterceptor.kt
- settings.gradle
- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
Figured this will need to be reusable across extensions.
Might also be worth moving into a separate project and publish to Maven?
> Move rate limit interceptor logic to module

- src/pt/mangahost/build.gradle
- src/pt/mangahost/src/eu/kanade/tachiyomi/extension/pt/mangahost/MangaHost.kt
Change MangaHost url to the [new one](https://mangahosted.com).
> Update MangaHost url

- src/ru/mintmanga/build.gradle
- src/ru/mintmanga/src/eu/kanade/tachiyomi/extension/ru/mintmanga/Mintmanga.kt
- src/ru/readmanga/build.gradle
- src/ru/readmanga/src/eu/kanade/tachiyomi/extension/ru/readmanga/Readmanga.kt
Fix chapters selector when chapter list has volume cover and add ratelimit for requests
> Readmanga: ratelimit and chapters selector

- src/all/foolslide/src/eu/kanade/tachiyomi/extension/en/foolslide/FoolSlideFactory.kt
Hatigarm's Active domain is "http://hatigarmscans.net"
> Update Foolslide (Hatigarm)

- lib/duktape-stub/src/com/squareup/duktape/Duktape.java
- src/es/tumangaonline/build.gradle
- src/es/tumangaonline/src/eu/kanade/tachiyomi/extension/es/tumangaonline/TuMangaOnline.kt
Yesterday they used canvas so I used Duktape, but now they returned it to how it was. So Duktape it's no longer necessary.
> Fix TMO, again. #1166

- src/fr/japscan/build.gradle
- src/fr/japscan/src/eu/kanade/tachiyomi/extension/fr/japscan/Japscan.kt
> Update scrambled images on webtoon

- src/en/renascans/build.gradle
- src/en/renascans/src/eu/kanade/tachiyomi/extension/en/renascans/Renascans.kt
Apparently when the Renascans extension went up, it had the wrong display name; so fixed that.  Also, I figured out how to use their site's search; so using that instead of searching client-side.
> Renascans fix and update

- src/en/mangasee/build.gradle
- src/en/mangasee/src/eu/kanade/tachiyomi/extension/en/mangasee/Mangasee.kt
> Fix Mangasee browsing

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/Madara.kt
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Added two new sources to Madara. :)
> Madara: Refactor and added new sources

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/Madara.kt
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes #1279 
I'm not sure if these names are appropriate for the three sites since they all share the same original name. :/ 
mangazuki.club also contains both Korean and Japanese raws so I'm not sure which of the two to classify it as.
> Madara: Added Multiple Sources

- src/all/foolslide/build.gradle
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/en/foolslide/FoolSlideFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1291
> ShoujoHearts added to Foolslide

- src/en/mangarock/build.gradle
- src/en/mangarock/src/eu/kanade/tachiyomi/extension/en/mangarock/MangaRock.kt
Fixes https://github.com/inorichi/tachiyomi-extensions/issues/1307
> Mangarock pageListParse to v2

- src/id/komikcast/build.gradle
- src/id/komikcast/src/eu/kanade/tachiyomi/extension/id/komikcast/Komikcast.kt
some manga have unknown description
> Komikcast: Fix description parsing issue

- src/vi/blogtruyen/build.gradle
- src/vi/blogtruyen/src/eu/kanade/tachiyomi/extension/vi/blogtruyen/BlogTruyen.kt
- src/vi/hentaivn/build.gradle
- src/vi/hentaivn/src/eu/kanade/tachiyomi/extension/vi/hentaivn/HentaiVN.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1138
> Fix Blogtruyen , Hentaivn

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes: 
https://github.com/inorichi/tachiyomi-extensions/issues/1327
https://github.com/inorichi/tachiyomi-extensions/issues/1326
As I commented in the code, Tritinia's website has a search function but it doesn't seem to work currently, so doing it client-side.  Can always go back to relying on their search in the future if they fix it.
> Madara (add Zinmanga, fix Tritinia)

- src/pt/unionmangas/build.gradle
- src/pt/unionmangas/src/eu/kanade/tachiyomi/extension/pt/unionmangas/UnionMangas.kt
Changes the `Referer` header and rewrites some parts of the code. Potentially will fix #1324.
> Improvements for UnionMangás

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/Madara.kt
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
* Workaround for chapters not found on Mangazuki's linked titles
* Add genre on manga description
* Disable search for wuxia
Add Filters
* Search by Artist / Author
* Search by Year
* Sort by Status
* Order by
> Madara: Rework search filters and some improvements

- src/all/myreadingmanga/build.gradle
- src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt
Fixed:
-Author (or should it be the artist? or both?)
-Description
-Status
Noticed that the description wasn't pulling when available. While I was at it, I added fixed author and added additional status function.
I do apologize as since this is a different pull request / fixes a different issue from my other request, how I should increment the build numbers? Please let me know if it needs to be changed. (Maintainers can edit) 
Thank you,
happywillow0
> MyReadingManga Manga Details parse update

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> Adding Toomics.me

- src/ru/nudemoon/build.gradle
- src/ru/nudemoon/src/eu/kanade/tachiyomi/extension/ru/nudemoon/Nudemoon.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1395
> Nude-moon fix

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1396 and https://github.com/inorichi/tachiyomi-extensions/issues/1377
> Madara (1st Kiss fix)

- src/en/guya/build.gradle
- src/en/guya/src/eu/kanade/tachiyomi/extension/en/guya/Guya.kt
I changed endpoint for scanlator cache, and fixed the caching issue with chapter pageLists after changing the scanlator preference.
> Quality of life improvements for the Guya extension.

- src/en/guya/build.gradle
- src/en/guya/src/eu/kanade/tachiyomi/extension/en/guya/Guya.kt
Added some safety to the extension init so doesn't take down the entire app if the API call fails. 
It's sub-optimal to catch all exceptions, but at least it won't crash the app if it's not just JSONException that gets thrown.
> Fail the fetch without crashing the entire app, also added fallback behaviour.

- src/en/heavenmanga/build.gradle
- src/en/heavenmanga/src/eu/kanade/tachiyomi/extension/en/heavenmanga/Heavenmanga.kt
Now mangas with lengthy chapters that are paginated should display all chapters.
Added Genre and Author filters(according to the website, invalid authors will display mangas by all authors)
> Fixes #1263

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> Manhwahentai.site

- src/en/mangarock/build.gradle
- src/en/mangarock/src/eu/kanade/tachiyomi/extension/en/mangarock/MangaRock.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1199
> MangaRock chapter delay fix

- src/en/lhtranslation/build.gradle
- src/en/lhtranslation/src/eu/kanade/tachiyomi/extension/en/lhtranslation/LHTranslation.kt
Site must have changed at some point--popular, latest, and search are all currently only returning the first page.  This fixes that.
> LHTranslation more pages

- src/ru/mangahub/build.gradle
- src/ru/mangahub/src/eu/kanade/tachiyomi/extension/ru/mangahub/Mangahub.kt
Fix update for site mangahub.ru
> Mangahub site update

- src/all/mangacards/build.gradle
- src/all/mangacards/src/eu/kanade/tachiyomi/extension/all/mangacards/MangaCardsFactory.kt
> MangaCards (add source Inept Bastards)

- src/fr/mangakawaii/build.gradle
- src/fr/mangakawaii/src/eu/kanade/tachiyomi/extension/fr/mangakawaii/MangaKawaiiSource.kt
> Mangakawaii: Fix #1455

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
They've changed names and domain.
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1465
> Madara (replace Mangalike with MangaKomi)

- src/en/heavenmanga/build.gradle
- src/en/heavenmanga/src/eu/kanade/tachiyomi/extension/en/heavenmanga/Heavenmanga.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1461
They've changed URLs twice since an issue was opened; I've updated baseUrl to what they're using currently.
> Heavenmanga date parse fix

- src/en/mangakakalot/build.gradle
- src/en/mangakakalot/src/eu/kanade/tachiyomi/extension/en/mangakakalot/Mangakakalot.kt
> MangaKakalot: Add comics filtering

- src/zh/dmzj/build.gradle
- src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1445 and https://github.com/inorichi/tachiyomi-extensions/issues/1472
> Dmzj update

- src/en/mangareader/build.gradle
- src/en/mangareader/src/eu/kanade/tachiyomi/extension/en/mangareader/MRPFactory.kt
- src/en/mangareader/src/eu/kanade/tachiyomi/extension/en/mangareader/Mangareader.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1456
Made Mangareader a factory to add Mangapanda.  Mangapanda is owned by Mangareader so I don't think there's a need to change the package name or move it to all at this point.  Also made a couple tweaks since I had it open.
> Mangareader (add Mangapanda)

- src/en/mangakakalot/build.gradle
- src/en/mangakakalot/src/eu/kanade/tachiyomi/extension/en/mangakakalot/Mangakakalot.kt
> Mangakakalot: replicate query normalization

- src/all/ninemanga/build.gradle
- src/all/ninemanga/src/eu/kanade/tachiyomi/extension/all/ninemanga/NineMangaFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1243
> NineMangaIt date parse fix

- src/es/doujinhentai/build.gradle
- src/es/doujinhentai/src/eu/kanade/tachiyomi/extension/es/doujinhentai/DoujinHentai.kt
Partially addresses #1152
- Adds latest (although the site seems to show the same thing for latest/popular)
- Fixes search
Doesn't add genres.
> DoujinHentai: fix search

- src/ja/rawdevart/build.gradle
- src/ja/rawdevart/src/eu/kanade/tachiyomi/extension/ja/rawdevart/Rawdevart.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1480
> Rawdevart update

- src/en/readmangatoday/build.gradle
- src/en/readmangatoday/src/eu/kanade/tachiyomi/extension/en/readmangatoday/Readmangatoday.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1485
Fixed the issue with chapters, added getting thumbnails for popularMangaRequest, made a few tweaks to get rid of some warnings.
> ReadMangaToday update

- src/en/toonily/build.gradle
- src/en/toonily/src/eu/kanade/tachiyomi/extension/en/toonily/Toonily.kt
> Toonily: Update search filters

- src/all/mangadventure/AndroidManifest.xml
- src/all/mangadventure/build.gradle
- src/all/mangadventure/src/eu/kanade/tachiyomi/extension/all/mangadventure/MangAdventure.kt
- src/all/mangadventure/src/eu/kanade/tachiyomi/extension/all/mangadventure/MangAdventureActivity.kt
- src/all/mangadventure/src/eu/kanade/tachiyomi/extension/all/mangadventure/MangAdventureExtensions.kt
- src/all/mangadventure/src/eu/kanade/tachiyomi/extension/all/mangadventure/MangAdventureFactory.kt
This PR allows users to open `/reader/{slug}` URLs within Tachiyomi.
It also updates the Arc-Relight source to use the new domain.
> Add search intent to MangAdventure

- src/all/genkan/build.gradle
- src/all/genkan/src/eu/kanade/tachiyomi/extension/all/genkan/GenkanFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1491
> Add WoweScans to Genkan

- CONTRIBUTING.md
Let's do our part to keep kids out of w3schools ;-).
> CONTRIBUTING.md: Add links for learners

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Fixed an issue with WuxiaWorld.
It seems that Toomics.me was in Madara previously and had switched to using manwahentai.site; they've changed back.
Added manwahentai.me.
> Madara - WuxiaWorld fix

- src/ja/rawlh/build.gradle
- src/ja/rawlh/src/eu/kanade/tachiyomi/extension/ja/rawlh/Rawlh.kt
Fix #1501
Fyi, when i updating code they just changed chapter img url mechanism.
this is latest changes on the site.
> RawLH: Update page list parse

- src/pt/hqdragon/build.gradle
- src/pt/hqdragon/src/eu/kanade/tachiyomi/extension/pt/hqdragon/HQDragon.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1341
Just needs icons
> HQDragon - new extension

- src/ja/rawlh/build.gradle
- src/ja/rawlh/src/eu/kanade/tachiyomi/extension/ja/rawlh/Rawlh.kt
* Change some selectors on manga details parse
* Fix manga genres, description (on some titles), and status
* Update page list parse again
* Remove unused
> RawLH: Update extension

- src/pt/goldenmangas/build.gradle
- src/pt/goldenmangas/src/eu/kanade/tachiyomi/extension/pt/goldenmangas/GoldenMangas.kt
> Fix duplicate pages in chapters in Golden Mangas

- src/all/foolslide/build.gradle
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/HentaiCafe.kt
* Fix genres and artist parsing
* Set status as completed
* Set chapters number to 1
> FoolSlide: Update Hentai Cafe

- src/pt/yesmangas/build.gradle
- src/pt/yesmangas/src/eu/kanade/tachiyomi/extension/pt/yesmangas/YesMangas.kt
Potentially will fix the main error reported in #support at Discord.
- Update the url.
- Add more info in manga details.
- Fix thumbnail not showing in latest.
- Update User-Agent.
> Fix the HTTP 403 errors in YES Mangás and other things

- src/en/toonily/build.gradle
- src/en/toonily/src/eu/kanade/tachiyomi/extension/en/toonily/Toonily.kt
> Toonily: Update chapter date parsing

- src/en/tsumino/build.gradle
- src/en/tsumino/src/eu/kanade/tachiyomi/extension/en/tsumino/Tsumino.kt
- src/en/tsumino/src/eu/kanade/tachiyomi/extension/en/tsumino/TsuminoUtils.kt
Filters code taken from NerdNumber9/TachiyomiEH
> Tsumino: Refactor and add search filters

- src/all/foolslide/build.gradle
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/HentaiCafe.kt
* They changed path url
* First choice on tag filters is always ignored
> FoolSlide: Update Hentai Cafe filters

- src/all/mangadex/build.gradle
Looks like it was missed on the previous PR, https://github.com/inorichi/tachiyomi-extensions/pull/1537
> Mangadex version bump

- src/fr/japscan/build.gradle
- src/fr/japscan/src/eu/kanade/tachiyomi/extension/fr/japscan/Japscan.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1526
> Japscan domain change

- src/all/foolslide/build.gradle
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/FoolSlideFactory.kt
- src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt
Third times a charm to fix #1543
Confirmed code from @SnakeDoc83 works and is better than mine. 
Also included is a minor enhancement that adds the scanlator group to the chapter list.
> MRM Fix Thumbnail on restore

- src/id/maidmanga/build.gradle
- src/id/maidmanga/src/eu/kanade/tachiyomi/extension/id/maidmanga/MaidManga.kt
- src/id/pecintakomik/build.gradle
- src/id/pecintakomik/src/eu/kanade/tachiyomi/extension/id/pecintakomik/PecintaKomik.kt
* PK: Fix latestupdate parse
* MM: Add date for latest chapter
* PK/MM: Refactor
> Update Maid Manga and Pecinta Komik

- src/ko/newtoki/build.gradle
- src/ko/newtoki/src/eu/kanade/tachiyomi/extension/ko/newtoki/NewTokiFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1563
> Newtoki url change

- src/zh/tohomh123/build.gradle
- src/zh/tohomh123/src/eu/kanade/tachiyomi/extension/zh/tohomh123/Tohomh.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1560
> Tohomh123 pageListParse selector

- src/id/pecintakomik/build.gradle
- src/id/pecintakomik/src/eu/kanade/tachiyomi/extension/id/pecintakomik/PecintaKomik.kt
fix bugs blank retry each image
> fix pecintakomik.net

- src/id/komikcast/build.gradle
- src/id/komikcast/src/eu/kanade/tachiyomi/extension/id/komikcast/Komikcast.kt
add custom header when load image from i0.wp.com
> fix load image from i0.wp.com komikcast

- src/en/comicextra/build.gradle
- src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt
Might help with https://github.com/inorichi/tachiyomi-extensions/issues/1579
> ComicExtra image parsing

- src/all/genkan/build.gradle
- src/all/genkan/src/eu/kanade/tachiyomi/extension/all/genkan/Genkan.kt
Fixes an issue with thumbnails and pages not loading due to the CMS shifting to using relative URLs.
> Genkan - relative URLs

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Fixes WuxiaWorld popular and latest.  Changed search so that it should return webcomics only (instead of webcomics and novels).
Removed Toomics.me because they're forwarding to a different site again.
> Madara - WuxiaWorld update

- src/all/ninehentai/build.gradle
- src/all/ninehentai/src/eu/kanade/tachiyomi/extension/all/ninehentai/NineHentai.kt
> Fix typo in NineHentai

- src/all/genkan/build.gradle
- src/all/genkan/src/eu/kanade/tachiyomi/extension/all/genkan/Genkan.kt
- src/en/mangahasu/build.gradle
- src/en/mangahasu/src/eu/kanade/tachiyomi/extension/en/mangahasu/Mangahasu.kt
> Genkan/MangaHasu: pass headers with GET requests

- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/meta_request.md
- .github/ISSUE_TEMPLATE/source_bug.md
- .github/ISSUE_TEMPLATE/source_request.md
Add templates for issues to make it easier to report issues.
__Might need significant help from reviewers to polish the templates.__
> Issue templates

- src/zh/hanhankuman/build.gradle
- src/zh/hanhankuman/src/eu/kanade/tachiyomi/extension/zh/hanhankuman/HanhanKuman.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1621
> HanhanKuman thumbnails

- src/all/ninemanga/build.gradle
- src/all/ninemanga/src/eu/kanade/tachiyomi/extension/all/ninemanga/NineManga.kt
- src/all/ninemanga/src/eu/kanade/tachiyomi/extension/all/ninemanga/NineMangaFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1614
Something else I noticed is that searching for a title with an apostrophe returns results for some languages but not others.  It's not a parsing issue but a request issue with the website.  I tried encoding it but that doesn't help; so instead I'm changing the query for the languages that have this issue.
> Ninemanga fixes

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Updated domain name to new one and display date of uploaded chapter
> Madara(TritiniaScans: updated domain name and captured date)

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> wuxiaworld

- src/pt/saikaiscan/build.gradle
- src/pt/saikaiscan/src/eu/kanade/tachiyomi/extension/pt/saikaiscan/SaikaiScan.kt
A specific manga had the author parsed wrong, this PR should fix it.
> Fix manga details parsing in SaikaiScan and refactor the code

- src/zh/manhuadb/build.gradle
- src/zh/manhuadb/src/eu/kanade/tachiyomi/extension/zh/manhuadb/ManhuaDB.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1649
> ManhuaDB refactor

- src/all/foolslide/build.gradle
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/FoolSlideFactory.kt
Helvetica's website has been gone for almost 2 months.
ShoujoSense removed their reader.
ShoujoSense hasn't added anything in 6 months and their reader is inaccessible.
> Foolslide - remove HelveticaScans, ShoujoSense, ShoujoHearts

- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
If you're logged in and have the correct permissions, you should now be able to read certain manga that gave a 451 error.  If you're not logged in or don't have the correct permissions, hopefully the error message makes things clear on what to do.  Closes https://github.com/inorichi/tachiyomi-extensions/issues/1576 as best as it can be.
Also cleaned up a few warnings from Android Studio.
> MangaDex - 451 handling

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1660 and https://github.com/inorichi/tachiyomi-extensions/issues/1661
> Madara - add manhwa18.net

- src/es/tumangaonline/build.gradle
- src/es/tumangaonline/src/eu/kanade/tachiyomi/extension/es/tumangaonline/TuMangaOnline.kt
Fixed the latest manga url
fixes #1662
> [Update] TuMangaOnline

- src/ru/nudemoon/build.gradle
- src/ru/nudemoon/src/eu/kanade/tachiyomi/extension/ru/nudemoon/Nudemoon.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1659
> Nudemoon update

- src/fr/scantrad/build.gradle
- src/fr/scantrad/src/eu/kanade/tachiyomi/extension/fr/scantrad/Scantrad.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1674
> Scantrad - double pages fix

- src/zh/manhuaren/build.gradle
- src/zh/manhuaren/src/eu/kanade/tachiyomi/extension/zh/manhuaren/Manhuaren.kt
Quality of life improvement: Identify locked chapters behind a paywall.
> [QOL] Manhuaren - Identify locked chapters

- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStream.kt
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStreamFactory.kt
Closes #1664 
Adds SekteKomik into factory. 
There is more work to be done as some manga details are being parsed incorrectly but all the important stuff was tested to work including Latest / Browse, Manga Title / Cover, chapter list and page list.
> [Add] WPMangaStream - SekteKomik

- src/en/mangahub/build.gradle
- src/en/mangahub/src/eu/kanade/tachiyomi/extension/en/mangahub/Mangahub.kt
Fixed some parsing bugs in chapter dates and chapter list.
> [Mangahub.io] Fix some parsing bugs

- src/fr/japscan/build.gradle
- src/fr/japscan/src/eu/kanade/tachiyomi/extension/fr/japscan/Japscan.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1618
> Japscan search

- src/all/mmrcms/build.gradle
- src/all/mmrcms/src/eu/kanade/tachiyomi/extension/all/mmrcms/MyMangaReaderCMSSource.kt
Fix #1687 
Cloudflare checks for (requires?) for headers. 
Added headers to each GET.
> [Fix] MMRCMS - Add Headers

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes #1699 
Manhwa18 removed / moved to FMReader
> [Add] Indiancomicsonline (Hindi)

- src/all/fmreader/build.gradle
- src/all/fmreader/src/eu/kanade/tachiyomi/extension/all/fmreader/FMReader.kt
- src/all/fmreader/src/eu/kanade/tachiyomi/extension/all/fmreader/FMReaderFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1703
Merge after/with https://github.com/inorichi/tachiyomi-extensions/pull/1701
> FMReader - add Manhwa18.net

- src/ko/jmana/build.gradle
- src/ko/jmana/src/eu/kanade/tachiyomi/extension/ko/jmana/JMana.kt
> Jmana update

- src/en/pururin/build.gradle
- src/en/pururin/src/eu/kanade/tachiyomi/extension/en/pururin/PuruRin.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1689
> Pururin refactor

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes #1730 
401 on post method, realized that we can override it like the others.
> [Add] Adonis Fansub

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/Madara.kt
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1734 and https://github.com/inorichi/tachiyomi-extensions/issues/1719
Also added GetManhwa.  They changed their domain and site breaking the current extension.  Their site is now fully compatible with Madara; so adding it here instead of fixing its extension.
> Madara - genre search, add 3 sources

- src/fr/scantrad/build.gradle
- src/fr/scantrad/src/eu/kanade/tachiyomi/extension/fr/scantrad/Scantrad.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1739
> Scantrad update

- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
It's not working perfectly.  There's still something I'm trying to figure out, but this at least fixes the issue of regular searches not working for some people.
> MangaDex - group search 2

- src/all/komga/build.gradle
- src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/Komga.kt
- src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/dto/Dto.kt
Libraries depend on each server, and can be dynamic. Retrieving once at startup seems the best option, but i am happy to get feedback in case there is a better option!
> [Komga] add filters by library

- src/es/tumangaonline/build.gradle
- src/es/tumangaonline/src/eu/kanade/tachiyomi/extension/es/tumangaonline/TuMangaOnline.kt
> [Fix] TMO - Updates page parsing

- src/all/boommanga/build.gradle
- src/all/boommanga/src/eu/kanade/tachiyomi/extension/all/boommanga/BoomManga.kt
fixes a issue comment on #1629 
I misinterpreted jsoup selectors where scripts contain data and not "text"
> [Fix] BoomFactory - Next page selector

- src/all/komga/build.gradle
- src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/Komga.kt
Use OkHttpClient Authenticator instead of always adding credentials in headers
> [Komga] better handling of authentication

- src/en/mangahub/build.gradle
- src/en/mangahub/src/eu/kanade/tachiyomi/extension/en/mangahub/Mangahub.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1766
> Mangahub - parse images from JSON

- src/en/dragonball_multiverse/build.gradle
- src/en/dragonball_multiverse/src/eu/kanade/tachiyomi/extension/en/dragonball_multiverse/DbMultiverse.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1776
> DB Multiverse update

- src/ko/newtoki/build.gradle
- src/ko/newtoki/src/eu/kanade/tachiyomi/extension/ko/newtoki/NewTokiFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1775
> NewToki domain update

- src/es/mangamx/build.gradle
- src/es/mangamx/src/eu/kanade/tachiyomi/extension/es/mangamx/MangaMx.kt
Closes #1756
This should complete the request.
> Mangamx - Add Filters

- src/all/mangatensei/build.gradle
- src/all/mangatensei/src/eu/kanade/tachiyomi/extension/all/mangatensei/Mangatensei.kt
- src/all/mangatensei/src/eu/kanade/tachiyomi/extension/all/mangatensei/MangatenseiFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/728 and https://github.com/inorichi/tachiyomi-extensions/issues/450
> Mangatensei - add Mangawindow and Bato.to

- src/all/webtoons/build.gradle
- src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/WebtoonsFactory.kt
- src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/WebtoonsTranslate.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/471
I remember this being implemented not too long ago; I checked it out today and found some problems.  This fixes the issues I found, cleans up a little, and adds search.
> Webtoons - Translations refactor

- src/all/myreadingmanga/build.gradle
- src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt
Reported on discord although I see it sometimes myself. 
Fixes a null error thrown on the off chance a search result doesn't have a cover.
> [Fix] My Reading Manga - fix for no cover

- src/de/wiemanga/build.gradle
- src/de/wiemanga/src/eu/kanade/tachiyomi/extension/de/wiemanga/WieManga.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/624
> Wiemanga refactor

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/Madara.kt
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Rather than fixing the extension, I'm adding it to Madara with genre search added as well.
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1814 and https://github.com/inorichi/tachiyomi-extensions/issues/1152
Also, removed Mangakomi: it's been dead for more than 3 weeks and they recently deleted their FB page too.
> Madara - add DoujinHentai

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1820
> Madara - add Azora

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/Madara.kt
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1825
Also fixed an omission for Azora.
> Madara - add Hunter Fansub

- src/all/webtoons/build.gradle
- src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/Webtoons.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/458
Edit: ~~Forgot to check something, don't merge yet.~~ Nevermind, all good.
> Webtoons - browse full catalog

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/Madara.kt
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1840
Modified `searchMangaNextPageSelector` so it doesn't need to be overridden as often.
Refactored `parseRelativeDate` because I was trying to figure something out.
> Madara - add MangaArabTeam, refactor

- src/ru/comx/build.gradle
- src/ru/comx/src/eu/kanade/tachiyomi/extension/ru/comx/ComX.kt
> Comx. Fix download some chapter and avoiding antibot feature

- src/ru/mintmanga/build.gradle
- src/ru/mintmanga/src/eu/kanade/tachiyomi/extension/ru/mintmanga/Mintmanga.kt
- src/ru/readmanga/build.gradle
- src/ru/readmanga/src/eu/kanade/tachiyomi/extension/ru/readmanga/Readmanga.kt
Remove manga title from chapter name. Help with readability chapter name and save/share single page of chapter.
@Taumer Review pls.
> Fix long names in manga names. Readmanga/Mintmanga

- src/es/mangamx/build.gradle
- src/es/mangamx/src/eu/kanade/tachiyomi/extension/es/mangamx/MangaMx.kt
- src/es/mangamx/src/eu/kanade/tachiyomi/extension/es/mangamx/MangaMxFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1787
The two sites seem affiliated; so I built upon the current extension.
Title queries don't seem to work on doujin-yang (seems like an issue on their end) but filtered search does.
> MangaMx - add Doujin-Yang

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/Madara.kt
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Other updates includes fixing thumbnails and some manga for AoC; better chapter lists for Chibi Manga; and some date parsing.
> Madara - add Night Comic, other updates

- src/ru/mangahub/build.gradle
- src/ru/mangahub/src/eu/kanade/tachiyomi/extension/ru/mangahub/Mangahub.kt
> Fix mangahub.ru search

- src/ru/libmanga/build.gradle
- src/ru/libmanga/src/eu/kanade/tachiyomi/extension/ru/libmanga/LibManga.kt
> Add licensed status for manga

- src/all/genkan/build.gradle
- src/all/genkan/src/eu/kanade/tachiyomi/extension/all/genkan/Genkan.kt
- src/all/genkan/src/eu/kanade/tachiyomi/extension/all/genkan/GenkanFactory.kt
- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Removes ZeroScans from Madara and adds to Genkan.  Closes https://github.com/inorichi/tachiyomi-extensions/issues/1866
Fiddled with Genkan a little since I had it open.
> Move ZeroScans

- src/en/mangatown/build.gradle
- src/en/mangatown/src/eu/kanade/tachiyomi/extension/en/mangatown/Mangatown.kt
Changed some date stuff because of site changes.  Tidied some other stuff up.
> Mangatown update

- src/es/lectormanga/build.gradle
- src/es/lectormanga/src/eu/kanade/tachiyomi/extension/es/lectormanga/LectorManga.kt
Lector updated the code because it is the same people who run TMO. This should also apply the changes that is needed.
> [Ready] Reader Manga / TMO sister update

- src/all/mangabox/build.gradle
- src/all/mangabox/src/eu/kanade/tachiyomi/extension/all/mangabox/MangaBox.kt
- src/all/mangabox/src/eu/kanade/tachiyomi/extension/all/mangabox/MangaBoxFactory.kt
Kakalot and Nelo were broken due to changes to Nelo's site..  Fixed and condensed some other stuff as well.
> MangaBox update

- src/all/fmreader/build.gradle
- src/all/fmreader/src/eu/kanade/tachiyomi/extension/all/fmreader/FMReader.kt
- src/all/fmreader/src/eu/kanade/tachiyomi/extension/all/fmreader/FMReaderFactory.kt
Added MangaBorn, closes https://github.com/inorichi/tachiyomi-extensions/issues/1890.
Removed MangaLeer, it points to a different site.
Fixes for Comicastle and RCO.
> FMReader update

- src/all/mangacards/build.gradle
- src/all/mangacards/src/eu/kanade/tachiyomi/extension/all/mangacards/MangaCards.kt
A user on discord was getting a date parse error, which it didn't seem like they should be, but hopefully this helps them.  Simplified some other stuff while I was looking at it.
> MangaCards update

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1912
> Madara - add Plot Twist No Fansub

- src/ja/senmanga/build.gradle
- src/ja/senmanga/src/eu/kanade/tachiyomi/extension/ja/senmanga/SenManga.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1907
> Senmanga update

- lib/extension/build.gradle
- lib/extension/src/main/AndroidManifest.xml
- lib/extension/src/main/java/eu/kanade/tachiyomi/network/NetworkHelper.kt
- lib/extension/src/main/java/eu/kanade/tachiyomi/network/OkHttpExtensions.kt
- lib/extension/src/main/java/eu/kanade/tachiyomi/network/Requests.kt
- lib/extension/src/main/java/eu/kanade/tachiyomi/source/CatalogueSource.kt
- lib/extension/src/main/java/eu/kanade/tachiyomi/source/Source.kt
- lib/extension/src/main/java/eu/kanade/tachiyomi/source/SourceFactory.kt
- lib/extension/src/main/java/eu/kanade/tachiyomi/source/model/Filter.kt
- lib/extension/src/main/java/eu/kanade/tachiyomi/source/model/FilterList.kt
- lib/extension/src/main/java/eu/kanade/tachiyomi/source/model/MangasPage.kt
- lib/extension/src/main/java/eu/kanade/tachiyomi/source/model/Page.kt
- lib/extension/src/main/java/eu/kanade/tachiyomi/source/model/SChapter.kt
- lib/extension/src/main/java/eu/kanade/tachiyomi/source/model/SManga.kt
- lib/extension/src/main/java/eu/kanade/tachiyomi/source/online/HttpSource.kt
- lib/extension/src/main/java/eu/kanade/tachiyomi/source/online/ParsedHttpSource.kt
- lib/extension/src/main/java/eu/kanade/tachiyomi/util/JsoupExtensions.kt
- settings.gradle
Basically copying http://github.com/inorichi/tachiyomi-extensions-lib to directly build extensions with it rather than versioning/publishing to Bintray.
> Add tachiyomi-extensions-lib as module

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> Adding Kissmanga.in

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Fixes #1918 
Attempts to bypass WordFence Advanced Blocking via user-agent by semi-randomizing a common user agent.
> APC Wordfence Bypass

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> Madara - readd MangaKomi

- src/all/foolslide/build.gradle
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/FoolSlideFactory.kt
> FoolSlide - Add Kirishima Fansub

- src/en/dynasty/build.gradle
- src/en/dynasty/src/eu/kanade/tachiyomi/extension/en/dynasty/DynastyDoujins.kt
- src/en/dynasty/src/eu/kanade/tachiyomi/extension/en/dynasty/DynastyScans.kt
> Dynasty Doujins fixes

- src/ru/mintmanga/build.gradle
- src/ru/mintmanga/src/eu/kanade/tachiyomi/extension/ru/mintmanga/Mintmanga.kt
> Mintmanga.com change domain to mintmanga.live

- src/en/dilbert/build.gradle
- src/en/dilbert/src/eu/kanade/tachiyomi/extension/en/dilbert/Dilbert.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1956
> Dilbert fix

- src/all/mangabox/build.gradle
- src/all/mangabox/src/eu/kanade/tachiyomi/extension/all/mangabox/MangaBox.kt
fix applies to tachiEH and other forks with updated deps.
I tested it dw.
> mangabox: fix alt titles included in title

- src/all/myreadingmanga/build.gradle
- src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt
Cloudflare protection broke current implementation of filters. 
Re-coded the filter section to use network.client. Now checks if page to see if it is the home page or the cloudflare page. 
Tested under different scenarios, no issues with startup or crashing as far as I can tell:
- Offline: returns Error getting filters
- Cloudflare: returns error stating user needs to load "Latest" and restart app
- (After CF): Filters working.
> MRM - Filter Update

- src/all/fmreader/build.gradle
- src/all/fmreader/src/eu/kanade/tachiyomi/extension/all/fmreader/FMReaderFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1973 (they mistitled their issue)
> FMReader - manhwa18 referer

- lib/preference-stub/src/main/java/androidx/preference/DialogPreference.java
- lib/preference-stub/src/main/java/androidx/preference/EditTextPreference.java
- lib/preference-stub/src/main/java/androidx/preference/ListPreference.java
- lib/preference-stub/src/main/java/androidx/preference/Preference.java
- lib/preference-stub/src/main/java/androidx/preference/PreferenceScreen.java
- lib/preference-stub/src/main/java/eu/kanade/tachiyomi/source/ConfigurableSource.java
- src/all/komga/build.gradle
- src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/Komga.kt
- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
- src/all/nhentai/build.gradle
- src/all/nhentai/src/eu/kanade/tachiyomi/extension/all/nhentai/NHentai.kt
- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStream.kt
- src/en/guya/build.gradle
- src/en/guya/src/eu/kanade/tachiyomi/extension/en/guya/Guya.kt
- src/en/mangakisa/build.gradle
- src/en/mangakisa/src/eu/kanade/tachiyomi/extension/en/mangakisa/MangaKisa.kt
- src/es/lectormanga/build.gradle
- src/es/lectormanga/src/eu/kanade/tachiyomi/extension/es/lectormanga/LectorManga.kt
- src/es/tumangaonline/build.gradle
- src/es/tumangaonline/src/eu/kanade/tachiyomi/extension/es/tumangaonline/TuMangaOnline.kt
- src/ko/mangashowme/build.gradle
- src/ko/mangashowme/src/eu/kanade/tachiyomi/extension/ko/mangashowme/MangaShowMe.kt
- src/ko/newtoki/build.gradle
- src/ko/newtoki/src/eu/kanade/tachiyomi/extension/ko/newtoki/NewToki.kt
- src/ru/libmanga/build.gradle
- src/ru/libmanga/src/eu/kanade/tachiyomi/extension/ru/libmanga/LibManga.kt
- src/ru/mangaonlinebiz/build.gradle
Related change in main app to use AndroidX: https://github.com/inorichi/tachiyomi/pull/2424
> Add support for AndroidX preferences

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- src/all/mangaplus/build.gradle
Annoyingly the serialization library requires 1.3.60.
> Update Gradle and Kotlin

- src/all/mangabox/build.gradle
- src/all/mangabox/src/eu/kanade/tachiyomi/extension/all/mangabox/MangaBox.kt
fixes a mistake (I made) in 45ca32d by not using __.toRegex()__
> fix 45ca32d

- src/all/mmrcms/build.gradle
- src/all/mmrcms/src/eu/kanade/tachiyomi/extension/all/mmrcms/MyMangaReaderCMSSource.kt
Fixes a parsing issue present in the dev build and Tachi's forks.  Also fixes a thumbnail issue for comicspace.
> MMRCMS parsing fix

- src/fr/scantrad/build.gradle
- src/fr/scantrad/src/eu/kanade/tachiyomi/extension/fr/scantrad/Scantrad.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1982
> Scantrad - date parsing fix

- src/ko/mangashowme/build.gradle
- src/ko/mangashowme/src/eu/kanade/tachiyomi/extension/ko/mangashowme/MSMFilters.kt
- src/ko/mangashowme/src/eu/kanade/tachiyomi/extension/ko/mangashowme/MSMImageUrlHandler.kt
- src/ko/mangashowme/src/eu/kanade/tachiyomi/extension/ko/mangashowme/MangaShowMe.kt
v1.2.15
-------
* Clean up codes.
* Fix nullable issue.
* Reduce Minimum image size for request error handling.
* Update description codes.
* Temp fix for parser failure on certain manga
- Raw `<` and `>` (no escape) causes error on jsoup?
* Update domain.
> Update ManaMoa extension

- src/en/dynasty/build.gradle
- src/en/dynasty/src/eu/kanade/tachiyomi/extension/en/dynasty/DynastyScans.kt
- src/en/mangaeden/build.gradle
- src/en/mangaeden/src/eu/kanade/tachiyomi/extension/en/mangaeden/Mangaeden.kt
- src/en/vgperson/build.gradle
- src/en/vgperson/src/eu/kanade/tachiyomi/extension/en/vgperson/Vgperson.kt
- src/it/hentaifantasy/build.gradle
- src/it/hentaifantasy/src/eu/kanade/tachiyomi/extension/it/hentaifantasy/HentaiFantasy.kt
- src/it/mangaeden/build.gradle
- src/it/mangaeden/src/eu/kanade/tachiyomi/extension/it/mangaeden/Mangaeden.kt
- src/ru/mintmanga/build.gradle
- src/ru/mintmanga/src/eu/kanade/tachiyomi/extension/ru/mintmanga/Mintmanga.kt
- src/ru/readmanga/build.gradle
- src/ru/readmanga/src/eu/kanade/tachiyomi/extension/ru/readmanga/Readmanga.kt
All of these sources are now serving their content over https.
> Several https updates

- src/all/mangabox/build.gradle
- src/all/mangabox/src/eu/kanade/tachiyomi/extension/all/mangabox/MangaBoxFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1987
> MangaBox - MangaOnl update

- src/en/explosm/build.gradle
- src/en/explosm/src/eu/kanade/tachiyomi/extension/en/explosm/Explosm.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1998
> Explosm - chapter dates

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Fixes #1995 due to a CDN update on source.
> 1st Kiss cdnUrl Update

- src/all/mangacards/build.gradle
- src/all/mangacards/src/eu/kanade/tachiyomi/extension/all/mangacards/MangaCards.kt
So we can get covers on import.
> MangaCards - details thumbnail

- src/en/sleepypandascans/build.gradle
- src/en/sleepypandascans/src/eu/kanade/tachiyomi/extension/en/sleepypandascans/SleepyPandaScans.kt
Needed to get covers on import for this one too, cleaned up some of my old work while I was at it.
> SleepyPandaScans refactor

- src/en/readcomiconline/build.gradle
- src/en/readcomiconline/src/eu/kanade/tachiyomi/extension/en/readcomiconline/Readcomiconline.kt
Closes #1976
I'm not set up to build Android X yet but I think it is right. Hope the check passes.
> ReadComicOnline - Adds Quality Preference

- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
since most old chapters are working with .cc.  Pushing the extension
> mangadex url change to .cc

- src/es/tumangaonline/build.gradle
- src/es/tumangaonline/src/eu/kanade/tachiyomi/extension/es/tumangaonline/TuMangaOnline.kt
Fixes #2011 
They removed lazy loading again but kept a bunch of anti-scraping images which are filtered out.
> TMO Update

- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
> mangadex filter out mangaplus chapters since it can't open them

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> Madara APC Update

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
I thought I looked into it before but I guess I overlooked it. 
Thanks SnakeDoc83 for reminding me. 
Actually uses a random number generator rather than just changing numbers based on the date. 
I don't know if this will do the trick long term or not. I just feel bad for pushing out so many updates.
> Madara - APC Random

- src/en/mangalife/build.gradle
- src/en/mangalife/src/eu/kanade/tachiyomi/extension/en/mangalife/mangalife.kt
Mangalife has started to obfuscate their code. 
They now fetch the server host name for the manga.
I don't think I can update it any more if it gets any more convoluted than this
> MangaLife - Fetch Host

- src/en/mangalife/build.gradle
- src/en/mangalife/src/eu/kanade/tachiyomi/extension/en/mangalife/mangalife.kt
What do you know, they didn't like the new method. 
They changed it back again. 
Closes #2044
~~Pending Check~~ Rebuilt and checked, should be working.
> Revert "MangaLife - Fetch Host"

- src/ja/rawdevart/build.gradle
- src/ja/rawdevart/src/eu/kanade/tachiyomi/extension/ja/rawdevart/Rawdevart.kt
> Rawdevart pageListParse update

- src/en/merakiscans/build.gradle
- src/en/merakiscans/src/eu/kanade/tachiyomi/extension/en/merakiscans/MerakiScans.kt
I think adding `Locale.US` should fix https://github.com/inorichi/tachiyomi-extensions/issues/2052.  Dates were showing up for me already; so I'm guessing that's the issue.  Cleaned up some other stuff while I had it open.
> MerakiScans update

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Madara Updates
I realized I should roll this into one PR since they both are Madara
- 1stKiss changed their CDN back. Added Referer to all headers instead of cdn only. 
- Adds Teabeer Comics
> Madara - Fix 1stkiss, Add TeabeerComics

- src/all/foolslide/build.gradle
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/HentaiCafe.kt
> FoolSlide - HCafe update

- src/ru/henchan/build.gradle
- src/ru/henchan/src/eu/kanade/tachiyomi/extension/ru/henchan/Henchan.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1923
> Henchan - thumbnails

- src/ja/rawkuma/build.gradle
- src/ja/rawkuma/src/eu/kanade/tachiyomi/extension/ja/rawkuma/Rawkuma.kt
Change the date parsing because the try and catch doesn't actually catch the right exception. 
Bypassed the time zone by grabbing the text date.
> Rawkuma - Date Fix v2

- src/all/foolslide/build.gradle
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/FoolSlideFactory.kt
> [Add] Foolslide PowerManga

- src/vi/truyenqq/build.gradle
- src/vi/truyenqq/src/eu/kanade/tachiyomi/extension/vi/truyenqq/TruyenQQ.kt
*sigh*
Forgot to add the thumbnail_url in mangadetails
> TruyenQQ - details thumbnail_url

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Some cleanup too removing trailing slashes from baseUrls and an unneeded import.
> Madara - add KingzManga, fix mangazuki.online

- src/all/foolslide/build.gradle
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/FoolSlideFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/537
> Foolside - add Baixar Hentai

- src/all/webtoons/build.gradle
- src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/DongmanManhua.kt
- src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/Webtoons.kt
- src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/WebtoonsFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/752
> Webtoons - add Dongman Manhua

- src/es/tumangaonline/build.gradle
- src/es/tumangaonline/src/eu/kanade/tachiyomi/extension/es/tumangaonline/TuMangaOnline.kt
Another day, another update. 
I always feel like it is targeted towards us but I know it is more likely towards Ninemanga and other aggregation sites .
> TMO Updates

- src/pt/mangasproject/build.gradle
- src/pt/mangasproject/src/eu/kanade/tachiyomi/extension/pt/mangasproject/MangasProject.kt
> Fix MangasProject token error

- src/vi/hentaivn/build.gradle
- src/vi/hentaivn/src/eu/kanade/tachiyomi/extension/vi/hentaivn/HentaiVN.kt
User on discord had an issue probably caused by the `.first()` in `mangaDetailsParse()`.
> HentaiVN update

- src/en/guya/build.gradle
- src/en/guya/src/eu/kanade/tachiyomi/extension/en/guya/Guya.kt
We show up in the library updates now, yay!
> Add date upload field to Guya.

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> Madara Add GoldenManga, Mangalek

- src/es/tumangaonline/build.gradle
- src/es/tumangaonline/src/eu/kanade/tachiyomi/extension/es/tumangaonline/TuMangaOnline.kt
Forgot to update get builder on my update 
Sorry
> TMO - Missed edit

- src/all/foolslide/build.gradle
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/FoolSlide.kt
Fixes #2145 
Not sure why there is a tomorrow but adds tomorrow
Cannot confirm this actually works. The text already changed to "today".
Can confirm I didn't break anything as far as I'm aware.
> FIx Foolslide Date

- src/en/readcomiconline/build.gradle
- src/en/readcomiconline/src/eu/kanade/tachiyomi/extension/en/readcomiconline/Readcomiconline.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2148
> ReadComicOnline - latest updates fix

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2150
Also:
Removed N Manhwa - site's been dead for more than a month.
Removed ToonManga - Site's been forwarding to Wakamics (also in Madara) for more than 3 weeks.
> Madara - add Astral Library

- src/es/lectormanga/build.gradle
- src/es/lectormanga/src/eu/kanade/tachiyomi/extension/es/lectormanga/LectorManga.kt
- src/es/tumangaonline/build.gradle
- src/es/tumangaonline/src/eu/kanade/tachiyomi/extension/es/tumangaonline/TuMangaOnline.kt
TMO and Lector broke. 
Use NineMangaES in the meantime.
> TMO / Lector Update

- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStreamFactory.kt
Closes #2144
This adds the basics of MangaSwat to WPManga
Basics such as browse, latest, reading tested and should work. 
Sorry to @arifr007 for creating a (potential) merge conflict
> [Add] MangaSwat (WP Manga)

- src/all/fmreader/build.gradle
- src/all/fmreader/src/eu/kanade/tachiyomi/extension/all/fmreader/FMReaderFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2161
Removed MangaWeek because the site's been unreachable for more than a month.
> FMReader - RawLH fix

- lib/preference-stub/src/main/java/android/support/v7/preference/CheckBoxPreference.java
- lib/preference-stub/src/main/java/android/support/v7/preference/Preference.java
- lib/preference-stub/src/main/java/android/support/v7/preference/TwoStatePreference.java
- lib/preference-stub/src/main/java/androidx/preference/CheckBoxPreference.java
- lib/preference-stub/src/main/java/androidx/preference/Preference.java
- lib/preference-stub/src/main/java/androidx/preference/TwoStatePreference.java
- src/ko/mangashowme/build.gradle
- src/ko/mangashowme/src/eu/kanade/tachiyomi/extension/ko/mangashowme/MSMImageDecoder.kt
- src/ko/mangashowme/src/eu/kanade/tachiyomi/extension/ko/mangashowme/MangaShowMe.kt
preference-stubs
-------------------
* Add `TwoStatePreference`
* Add `CheckBoxPreference`
Manamoa
-----------
* Code clean up.
* Simplify decoder by using kotlin functions.
* Add Experimental, Unstable feature: New domain auto fetcher 
- Requires Android Nougat or newer as it needs Java 8's `CompletableFuture`
- Using main thread black magic 🤷‍♂ 
- It will causes a freeze when enter Manamoa Browse first time on each time app launched
> Update Preference Stubs & Update Manamoa extension

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> Madara - add Novel France

- src/en/mangahub/build.gradle
- src/en/mangahub/src/eu/kanade/tachiyomi/extension/en/mangahub/Mangahub.kt
Source made some small changes.
> Mangahub - pages fix

- src/ar/teamx/build.gradle
- src/ar/teamx/src/eu/kanade/tachiyomi/extension/ar/teamx/TeamX.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2171
> Team X - src to data-src

- src/es/lectormanga/build.gradle
- src/es/lectormanga/src/eu/kanade/tachiyomi/extension/es/lectormanga/LectorManga.kt
- src/es/tumangaonline/build.gradle
- src/es/tumangaonline/src/eu/kanade/tachiyomi/extension/es/tumangaonline/TuMangaOnline.kt
They implemented the dummy image code into Lector and in the process, broke the selectors / div classes
Lector
TMO
> Update TMO / Lector

- src/es/lectormanga/build.gradle
- src/es/lectormanga/src/eu/kanade/tachiyomi/extension/es/lectormanga/LectorManga.kt
- src/es/tumangaonline/build.gradle
- src/es/tumangaonline/src/eu/kanade/tachiyomi/extension/es/tumangaonline/TuMangaOnline.kt
Further fixes to keep up to date with TMO and Lector.
Updated time method to emulate website methods.
> Fix TMO / Lector

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes #2186 
Temporarily fixes #2177 as well with user agent update.
> [Add] Madara - Klik Manga [ID]

- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStreamFactory.kt
Addresses #2180
Checks headers for sucuri bypass (similar to cloudflare). 
If not bypassed, prompts user to open webview. This attempts to replace error "no results found".
> Add MangaSwat Warning

- src/all/komga/build.gradle
- src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/Komga.kt
- src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/dto/Dto.kt
- use the metadata title for series
- ability to filter on series status
> [Komga] series metadata

- src/id/mangashiro/build.gradle
- src/id/mangashiro/src/eu/kanade/tachiyomi/extension/id/mangashiro/Mangashiro.kt
Closes #2198
This source can be moved into WPMangaStream but I didn't feel like doing that work yet.
> Mangashiro Update URL

- src/all/myreadingmanga/build.gradle
- src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt
Website changed how the description block was coded
> MRM - Update Description

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> [Add] Madara - Miracle Scans

- src/pt/mangasproject/build.gradle
- src/pt/mangasproject/src/eu/kanade/tachiyomi/extension/pt/mangasproject/MangasProject.kt
- src/pt/mangasproject/src/eu/kanade/tachiyomi/extension/pt/mangasproject/MangasProjectFactory.kt
Update the url to the new one since the redirection from the old one is blocking the Cloudflare bypassing on the main app.
> Update MangaLivre url

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> [Add] Madara - Manhuas.net

- src/pt/unionmangas/build.gradle
- src/pt/unionmangas/src/eu/kanade/tachiyomi/extension/pt/unionmangas/UnionMangas.kt
They updated their domain name. 
This also fixes the latest not working as reported on Discord.
> Update Union Mangás URL

- src/ru/libmanga/build.gradle
- src/ru/libmanga/src/eu/kanade/tachiyomi/extension/ru/libmanga/LibManga.kt
Updated Latest Thumbnail URL.  App was not processing relative url correctly.
Update Manga Details Title to use Romaji - Closes #2203
> Update LibManga 

- src/fr/japscan/build.gradle
- src/fr/japscan/src/eu/kanade/tachiyomi/extension/fr/japscan/Japscan.kt
Workaround for #2222
Related / Alternative to #2214
> Japscan Browse via Filters

- src/all/genkan/build.gradle
- src/all/genkan/src/eu/kanade/tachiyomi/extension/all/genkan/GenkanFactory.kt
> Adding the nonames

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> [Add] Madara -  EarlyManga, MangaLaw

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
#2265 
- Add MangaTx (en) 
Closes #2262 
- Add ATM-Subs (fr) 
Closes #2253
- Add OnManga (en) 
- Add Manga Action (ar) 
- Add Niji Translations (ar)
> Add Madara Sources

- src/fr/scantrad/build.gradle
- src/fr/scantrad/src/eu/kanade/tachiyomi/extension/fr/scantrad/Scantrad.kt
- Latest looked wrong so I fixed the selectors
- Updated page list selector 
Somehow doesn't fix #2239
Issue only happens in stable (Tested Dev and J2k) and I haven't figured out why
> Fix ScanTrad 

- src/fr/japscan/build.gradle
- src/fr/japscan/src/eu/kanade/tachiyomi/extension/fr/japscan/Japscan.kt
Use Duck Duck Go to search within JapScan
> Add Search to JapScan

- src/ru/mintmanga/build.gradle
- src/ru/mintmanga/src/eu/kanade/tachiyomi/extension/ru/mintmanga/Mintmanga.kt
- src/ru/readmanga/build.gradle
- src/ru/readmanga/src/eu/kanade/tachiyomi/extension/ru/readmanga/Readmanga.kt
- src/ru/selfmanga/build.gradle
- src/ru/selfmanga/src/eu/kanade/tachiyomi/extension/ru/selfmanga/Selfmanga.kt
Fix broken extension after site update
> Fix readmanga like sites with new composition of url

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes #2298
Closes #2310
Actually changes are:
- Removing an extra `/` in NijiTranslations
- Add Ichirin No Hana Yuri
- Add Lilly Manga
Sorry about github differential going crazy over line changes. I can resubmit without the reformat if you want.
> Madara - Add Ichirin No Hana Yuri / Lilly Manga

- src/all/myreadingmanga/build.gradle
- src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt
Tried to improve filter code by utilizing existing network calls. That didn't work. 
Found out that they changed part of the website and categories broke. 
Fixed categories and additional additional new filters found on website. 
Also ran the default code reformat in Android Studio to clean up some of my code.
> Update MRM Filter Code

- src/ru/libmanga/build.gradle
- src/ru/libmanga/src/eu/kanade/tachiyomi/extension/ru/libmanga/LibManga.kt
Remove manual settings for configure image sever, because of large community report of doesn't working chapters in main(default) server
> [ru-mangalib] Realtime calculate of image server

- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
Adds a check for the login button during a search call and if exists, throws a message to login. 
Would this be useful?
> Add warning to Mangadex search

- src/all/myreadingmanga/build.gradle
- src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt
I broke the filters with the last update. 
- Re-organized code 
-- Popular, Latest, Search, Details, Chapters, Pages, Filters
- Fixed / Updated filters. 
-- No longer attempts to parse filter on startup. 
-- Now waits until user enters browse and bypasses cloudflare captcha.
> Fix MRM Filters

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
- Add MangaBob #2312
- Fixes #2325 EarlyManga 
- Update APC UserAgent
> Madara Updates

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
🐇 🐇 🐇 🐇 🐇 🐇 🐇 
Closes #2334 
Closes #2312
> Madara - Add 365Manga, Disaster Scans

- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
It seems like the login check / message I added is being cached.
This adds the cache control to ensure the network is checked to see if anything changed.
> Mangadex - Use Network

- src/en/existentialcomics/build.gradle
- src/en/existentialcomics/src/eu/kanade/tachiyomi/extension/en/existentialcomics/ExistentialComics.kt
> ExistentialComics = Fix Chapter list

- src/es/lectormanga/build.gradle
- src/es/lectormanga/src/eu/kanade/tachiyomi/extension/es/lectormanga/LectorManga.kt
10 Character change
It was supposed to be only 3 characters originally but there was a few more updates to bloat the differential.
- Fix SimpleDateFormat Patterns
- FIx Unsafe use of a nullable receiver of type Date?
- Update userAgent while I'm at it
> ReadeManga Update

- src/en/mangaowl/build.gradle
- src/en/mangaowl/src/eu/kanade/tachiyomi/extension/en/mangaowl/MangaOwl.kt
> MangaOwl - Update Selectors

- src/ru/mintmanga/build.gradle
- src/ru/mintmanga/src/eu/kanade/tachiyomi/extension/ru/mintmanga/Mintmanga.kt
Change of a domain name since the old was blocked by russian authorities.
https://mintmanga.com/news/show_smena_domena_na_mintmanga_com
> Mintmanga: Domain Name Change

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
More 🐰 . We're up to 67 sources in Madara alone. 
Though I haven't been checking if any of them have went down as fast as they pop up. 
Anyways, 
Closes #2361 
Closes #2349
> Add MangaKiss, MangaDods

- src/ru/mintmanga/build.gradle
- src/ru/mintmanga/src/eu/kanade/tachiyomi/extension/ru/mintmanga/Mintmanga.kt
The site has restored the old domain. The new domain (.com) redirects to the old.
> Mintmanga: Domain

- src/all/ehentai/build.gradle
- src/all/ehentai/src/eu/kanade/tachiyomi/extension/all/ehentai/EHentai.kt
Simple thing I missed when I made it at first, thought the UriFilter only fired if it was checked
> E-Hentai WatchedList checkbox fix

- src/en/tapastic/build.gradle
- src/en/tapastic/src/eu/kanade/tachiyomi/extension/en/tapastic/Tapastic.kt
> Tapas Re-write

- src/all/mangabox/build.gradle
- src/all/mangabox/src/eu/kanade/tachiyomi/extension/all/mangabox/MangaBoxFactory.kt
Fixes #2398
Updated selectors to match current site
Also disables chapter manga due to chapter outage (unable to read chapters)
> Fix MangaBat

- src/all/mmrcms/src/eu/kanade/tachiyomi/extension/all/mmrcms/Generator.kt
I forgot to actually update the generator. 
This update doesn't include a apk update because the actual "factory" had already been updated.
> Update MMRCMS Generator.kt

- src/es/doujinyang/build.gradle
- src/es/doujinyang/src/eu/kanade/tachiyomi/extension/es/doujinyang/DoujinYang.kt
Due to coding changes I made in Manga-MX, the factory broke. 
I took the Doujin-Yang code and split it off into it's own extension. 
Icons needed
> Split Doujin-Yang

- src/en/mangahasu/build.gradle
- src/en/mangahasu/src/eu/kanade/tachiyomi/extension/en/mangahasu/Mangahasu.kt
- Fixes #2236 thumbnail hotlink protection
- Formatted code / optimized imports
> MangaHasu - Add Header Referer

- src/ar/teamx/build.gradle
- src/ar/teamx/src/eu/kanade/tachiyomi/extension/ar/teamx/TeamX.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2431
> Team-X - fix images

- src/en/xkcd/build.gradle
- src/en/xkcd/src/eu/kanade/tachiyomi/extension/en/xkcd/Xkcd.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2385
> xkcd - parse image from html

- src/all/nhentai/build.gradle
- src/all/nhentai/src/eu/kanade/tachiyomi/extension/all/nhentai/NHentai.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2181
> NHentai - sort filter

- src/fr/japscan/build.gradle
- src/fr/japscan/src/eu/kanade/tachiyomi/extension/fr/japscan/Japscan.kt
Closes #2445
- Update to use internal search
- Fix code warnings
- Reformat code
- Optimize imports
> Japscan - Update Search

- src/en/tapastic/build.gradle
- src/en/tapastic/src/eu/kanade/tachiyomi/extension/en/tapastic/Tapastic.kt
> Tapas - use data-src

- src/all/mangatensei/build.gradle
- src/all/mangatensei/src/eu/kanade/tachiyomi/extension/all/mangatensei/Mangatensei.kt
> Mangatensei - use abs:src

- src/en/hiveworks/build.gradle
- src/en/hiveworks/src/eu/kanade/tachiyomi/extension/en/hiveworks/Hiveworks.kt
Closes #2454 
This took longer than I wanted but I think this is some nice work. 
- Optimize imports
- Reorganize code
- Hide known incompatible comics
- Add local search
- Add proper Manga Details
- Changed page list selector
- Add site specific pages (SMBC for now)
- Add additional filters
- Add custom error codes
- Other misc code edits
> Improve Hiveworks

- src/all/komga/build.gradle
- src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/Komga.kt
- src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/dto/Dto.kt
use book metadata (introduced in Komga `0.22.0`)
> [Komga] use Book metadata

- src/en/hiveworks/build.gradle
- src/en/hiveworks/src/eu/kanade/tachiyomi/extension/en/hiveworks/Hiveworks.kt
- Better supports Check Please Comic
> Hiveworks - Add Chapter Filtering

- src/all/mmrcms/build.gradle
- src/all/mmrcms/src/eu/kanade/tachiyomi/extension/all/mmrcms/MyMangaReaderCMSSource.kt
Fixes https://github.com/inorichi/tachiyomi/issues/2742
- Fix Selector
> MMRCMS - Read Comics Online

- src/vi/blogtruyen/build.gradle
- src/vi/blogtruyen/src/eu/kanade/tachiyomi/extension/vi/blogtruyen/BlogTruyen.kt
> Blog truyen - Thumbnail Fix

- src/vi/hentaivn/build.gradle
- src/vi/hentaivn/src/eu/kanade/tachiyomi/extension/vi/hentaivn/HentaiVN.kt
Part of #2468
- Move Referer to main headers
> HentaiVN - Thumbnail Fix

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> [Madara] DisasterScans: Fix manga title not appearing; add MangaWOW + MangaStream

- src/en/hiveworks/build.gradle
- src/en/hiveworks/src/eu/kanade/tachiyomi/extension/en/hiveworks/Hiveworks.kt
According to [kotlin reference](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/first.html), if no such element is found for the given predicate, a  `NoSuchElementException` exception is thrown.  This exception is now caught. 
- Fixes #2465 
- Adds Original, Kids, and Completed comic lists to filters. These comics however do not get "details" updates.
> Hive Works - Manga not found

- src/all/mangabox/build.gradle
- src/all/mangabox/src/eu/kanade/tachiyomi/extension/all/mangabox/MangaBoxFactory.kt
> Remove Kono-Basho

- src/vi/academyvn/build.gradle
- src/vi/academyvn/src/eu/kanade/tachiyomi/extension/vi/academyvn/HocVienTruyenTranh.kt
> [HocVienTruyenTranh] Fix (half of) #2468

- src/ar/mangaae/build.gradle
- src/ar/mangaae/src/eu/kanade/tachiyomi/extension/ar/mangaae/MangaAe.kt
- Fixes #2483 url replacement 
- Reformat Code
- Optimize Imports
> MangaAE - Fix Chapter URL

- src/vi/academyvn/build.gradle
- src/vi/academyvn/src/eu/kanade/tachiyomi/extension/vi/academyvn/HocVienTruyenTranh.kt
- Change imgheader to global Refer (fixes #2482)
- Made IDE recommended code changes
- Reformat code
- Optimize Imports
> HocVienTruyenTranh - Fix Referer

- src/zh/pufei/build.gradle
- src/zh/pufei/src/eu/kanade/tachiyomi/extension/zh/pufei/Pufei.kt
It took me longer than I wanted but I figured it out.
Fixes #2480
I also don't know what is going on with the "patches" but I didn't feel like figuring it out either so I left the rest of the extension alone.
> Pufei - Add Content Type Interceptor

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> Add Neox Scanlator and Manga Lord

- src/en/kissmanga/build.gradle
- src/en/kissmanga/src/eu/kanade/tachiyomi/extension/en/kissmanga/Kissmanga.kt
KissManga started returning an empty response to our request. 
Updating the user agent fixed it for me in my testing. They likely are blocking the old agent.
> KissManga - Upgrade User-Agent

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2490
> Madara - add PornComix

- src/en/kissmanga/build.gradle
- src/en/kissmanga/src/eu/kanade/tachiyomi/extension/en/kissmanga/Kissmanga.kt
This may fare a bit better but nothing I can do for users are already IP banned.
> KissManga - Update UA #2

- src/en/oglaf/build.gradle
- src/en/oglaf/src/eu/kanade/tachiyomi/extension/en/oglaf/Oglaf.kt
Search keeps on going forever, this fixes that.
> Oglaf - change empty observable

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/Madara.kt
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2524
> Madara - fix 1stkiss thumbnails

- src/en/tapastic/build.gradle
- src/en/tapastic/src/eu/kanade/tachiyomi/extension/en/tapastic/Tapastic.kt
Opps, Seems I missed the thumbnail url in the details section.
Fixes #2543
> Tapas - Add Thumbnail to Details

- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangadexDescription.kt
closes #2540
instead of the system language it matches the language of the extension you are using
ran ktlint on mangadex class
descriptions cleaned up depending on internal language
main code is cleanDescription.  Not pretty but it works
> Mangadex description cleanup

- src/en/hentai2read/build.gradle
- src/en/hentai2read/src/eu/kanade/tachiyomi/extension/en/hentai2read/Hentai2Read.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2558
> Hentai2Read - update browse & latest

- src/vi/blogtruyen/build.gradle
- src/vi/blogtruyen/src/eu/kanade/tachiyomi/extension/vi/blogtruyen/BlogTruyen.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2567
> BlogTruyen - fix search

- src/all/foolslide/build.gradle
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/FoolSlide.kt
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/FoolSlideFactory.kt
DKThias has been unusable for months, World Three and AkaiYuhiMun at least 1 month.
> Foolslide - remove 3 sources, improve thumbnails

- src/all/mangabox/build.gradle
- src/all/mangabox/src/eu/kanade/tachiyomi/extension/all/mangabox/MangaBox.kt
- src/all/mangabox/src/eu/kanade/tachiyomi/extension/all/mangabox/MangaBoxFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2584
Can't really combine filters for this source; so only adding genre filters.
> MangaBox - MangaOnl genre filter

- src/zh/bh3/build.gradle
- src/zh/bh3/src/eu/kanade/tachiyomi/extension/zh/bh3/BH3.kt
> BH3 - Update Manga URL Selector

- src/all/mmrcms/build.gradle
- src/all/mmrcms/src/eu/kanade/tachiyomi/extension/all/mmrcms/MyMangaReaderCMSSource.kt
Fixes #2610
White Cloud Pavilion has a long base URL which setUrlWithoutDomain don't handle properly. 
https://www.whitecloudpavilion.com/manga/free
> MMRCMS - Update Latest URL

- src/en/mangasee/build.gradle
- src/en/mangasee/src/eu/kanade/tachiyomi/extension/en/mangasee/Mangasee.kt
Also cleaned up some small things Android Studio likes to point out.
> Mangasee - parse thumbnails on browse

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Adds #2622 Manga68, ManhuaBox
Closes #2626 RaiderScans
Closes #2623 PojokManga
Couldn't get MangaZone.cc working
> Madara - Add Websites

- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStream.kt
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStreamFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2600 and https://github.com/inorichi/tachiyomi-extensions/issues/2624
Sort of closes https://github.com/inorichi/tachiyomi-extensions/issues/1900.  There's still the standalone version of Komikcast that has this issue, but it's fixed for the version in this extension.
> WPMangaStream - add Manga Raw

- src/all/fmreader/build.gradle
- src/all/fmreader/src/eu/kanade/tachiyomi/extension/all/fmreader/FMReader.kt
- src/all/fmreader/src/eu/kanade/tachiyomi/extension/all/fmreader/FMReaderFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2627
Removed AiLoveManga because it appears to no longer host manga.
> FMReader - add SayTruyen

- src/pt/mangasproject/build.gradle
- src/pt/mangasproject/src/eu/kanade/tachiyomi/extension/pt/mangasproject/MangasProject.kt
I forgot to fix this issue in the last PR.
> Fix "Open in WebView" not working at MangasProject

- src/all/mmrcms/build.gradle
- src/all/mmrcms/src/eu/kanade/tachiyomi/extension/all/mmrcms/MyMangaReaderCMSSource.kt
Also fixes an issue with the onma source.
> MMRCMS - fewer dupes in latest

- src/all/genkan/build.gradle
- src/all/genkan/src/eu/kanade/tachiyomi/extension/all/genkan/GenkanFactory.kt
**Website link:** https://methodscans.com/home
> Added Method Scans

- src/all/wpcomics/build.gradle
- src/all/wpcomics/src/eu/kanade/tachiyomi/extension/all/wpcomics/WPComics.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2660
> WP-Comics - fix double pages

- src/es/lectormanga/build.gradle
- src/es/lectormanga/src/eu/kanade/tachiyomi/extension/es/lectormanga/LectorManga.kt
- src/es/tmohentai/build.gradle
- src/es/tmohentai/src/eu/kanade/tachiyomi/extension/es/tmohentai/TMOHentai.kt
- src/es/tumangaonline/build.gradle
- src/es/tumangaonline/src/eu/kanade/tachiyomi/extension/es/tumangaonline/TuMangaOnline.kt
- Update filters (TuMangaOnline, LectorManga & TMOHentai).
- Update latest URL to prevent server ban caused by too many requests: [screenshot](https://1.bp.blogspot.com/-vwaQebBe5F4/XpQbxZDX6wI/AAAAAAAA4ko/_dJI5shbbJEl8PmYVb_N0s4uhJJ7QM-VwCLcBGAsYHQ/s1600/Screen%2BShot%2B2020-04-09%2Bat%2B00.04.09.png) (TuMangaOnline & LectorManga).
> Update TuMangaOnline, LectorManga & TMOHentai

- src/ru/nudemoon/build.gradle
- src/ru/nudemoon/src/eu/kanade/tachiyomi/extension/ru/nudemoon/Nudemoon.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2658
> Nudemoon - fix pages

- src/vi/truyenqq/build.gradle
- src/vi/truyenqq/src/eu/kanade/tachiyomi/extension/vi/truyenqq/TruyenQQ.kt
> TruyenQQ - add referer header

- src/all/mangaplus/build.gradle
- src/all/mangaplus/src/eu/kanade/tachiyomi/extension/all/mangaplus/MangaPlus.kt
Although the site doesn't properly work on WebView, at least for me, users may want to see the site in the browser to check if it's working sometimes.
Also added correct `Referer` header to requests.
> Fix "Open in WebView" wrong URL at MangaPlus

- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStream.kt
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStreamFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2677
> WP Mangastream - refactor, fixes

- src/fr/mangakawaii/build.gradle
- src/fr/mangakawaii/src/eu/kanade/tachiyomi/extension/fr/mangakawaii/MangaKawaii.kt
Seems to close https://github.com/inorichi/tachiyomi-extensions/issues/2665
> Mangakawaii - change user-agent

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2687
> Madara - add Top Manhua

- src/all/wpcomics/build.gradle
- src/all/wpcomics/src/eu/kanade/tachiyomi/extension/all/wpcomics/WPComics.kt
- src/all/wpcomics/src/eu/kanade/tachiyomi/extension/all/wpcomics/WPComicsFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2679
> WP Comics - add xoxcomics

- src/all/webtoons/build.gradle
- src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/Webtoons.kt
- src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/WebtoonsDefault.kt
- src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/WebtoonsFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2682
> Webtoons - add locale cookie

- src/en/readmangatoday/build.gradle
- src/en/readmangatoday/src/eu/kanade/tachiyomi/extension/en/readmangatoday/Readmangatoday.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2695
> ReadMangaToday - fix pages

- src/all/mangabox/build.gradle
- src/all/mangabox/src/eu/kanade/tachiyomi/extension/all/mangabox/MangaBoxFactory.kt
Mangafree's domain is up for sale; so I guess they're done.
Reworked MangaOnl's genre search to be applicable to other sources.
> MangaBox - genre search, remove mangafree

- src/fr/mangakawaii/build.gradle
- src/fr/mangakawaii/src/eu/kanade/tachiyomi/extension/fr/mangakawaii/MangaKawaii.kt
URl change from search to search2/
> [BUG][fr-mangakawaii] fix the url to make  manga search

- src/all/komga/build.gradle
- src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/Komga.kt
- src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/KomgaFactory.kt
while waiting for https://github.com/inorichi/tachiyomi/pull/2196 this should suffice for most users
> [Komga] use SourceFactory to have multiple Komga servers (3 for the moment)

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Should close https://github.com/inorichi/tachiyomi-extensions/issues/2705
> Add manytoon.club

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2727
> Add ManhuaUS

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Fixes https://github.com/inorichi/tachiyomi-extensions/issues/2735
> Change NightComic to https

- src/en/kissmanga/build.gradle
- src/en/kissmanga/src/eu/kanade/tachiyomi/extension/en/kissmanga/Kissmanga.kt
Updated the User-Agent to fix ```Please turn JavaScript on and reload the page.```
> Update Kissmanga User-Agent

- src/en/kissmanga/build.gradle
- src/en/kissmanga/src/eu/kanade/tachiyomi/extension/en/kissmanga/Kissmanga.kt
The suffix hasn't changed since my last pull request so feel free to wait on this pull request.
I've tested it with https://gist.github.com/i404788/a1a53c1c2d269de989551515b44dfb94
The previous solutions didn't work with the test program, however this does seem to work.
>  Fix "Page List Empty" with Randomized Suffix (KissManga)

- src/all/ninemanga/build.gradle
- src/all/ninemanga/src/eu/kanade/tachiyomi/extension/all/ninemanga/NineMangaFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2754
> NineMangaFr headers

- src/all/toomics/build.gradle
- src/all/toomics/src/eu/kanade/tachiyomi/extension/all/toomics/ToomicsGlobal.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2750
> Toomics - fixes

- src/en/hentai2read/build.gradle
- src/en/hentai2read/src/eu/kanade/tachiyomi/extension/en/hentai2read/Hentai2Read.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1684
> Hentai2Rread - add search sorting

- src/en/hentaifox/build.gradle
- src/en/hentaifox/src/eu/kanade/tachiyomi/extension/en/hentaifox/HentaiFox.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2676
> HentaiFox - fix genre search pages

- src/all/foolslide/build.gradle
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/FoolSlide.kt
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/FoolSlideFactory.kt
> Foolslide - add HNI-Scantrad

- src/en/tsumino/AndroidManifest.xml
- src/en/tsumino/build.gradle
- src/en/tsumino/src/eu/kanade/tachiyomi/extension/en/tsumino/Tsumino.kt
- src/en/tsumino/src/eu/kanade/tachiyomi/extension/en/tsumino/TsuminoUrlActivity.kt
> Tsumino - Implement Url Intent and fix sort by newest

- src/all/wpcomics/build.gradle
- src/all/wpcomics/src/eu/kanade/tachiyomi/extension/all/wpcomics/WPComics.kt
- src/all/wpcomics/src/eu/kanade/tachiyomi/extension/all/wpcomics/WPComicsFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2693
Plus catalog fixes for ManhuaEs and more dates for MangaSum.
> WP Comics - fixes

- src/all/foolslide/build.gradle
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/FoolSlide.kt
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/FoolSlideFactory.kt
Via discord: OP of the previous HNI-Scantrad request had intended to ask for the English version but they provided the wrong link.  This covers what they actually wanted.
> Foolslide - add English HNI-Scantrad

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/Madara.kt
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> Madara - fix Hiperdex, add 2 tr sources

- src/es/heavenmanga/build.gradle
- src/es/heavenmanga/src/eu/kanade/tachiyomi/extension/es/heavenmanga/HeavenManga.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2432
Site's a bit broken but it's usable I guess.
> Heavenmanga - updates

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
- src/all/mangadventure/build.gradle
- src/all/mangadventure/src/eu/kanade/tachiyomi/extension/all/mangadventure/MangAdventure.kt
- src/all/mangadventure/src/eu/kanade/tachiyomi/extension/all/mangadventure/MangAdventureActivity.kt
- src/all/mangadventure/src/eu/kanade/tachiyomi/extension/all/mangadventure/MangAdventureExtensions.kt
- src/all/mangadventure/src/eu/kanade/tachiyomi/extension/all/mangadventure/MangAdventureFactory.kt
Also, improve some of the MangAdventure extension code.
> Move Decadence Scans to Madara

- src/ar/mangaae/build.gradle
- src/ar/mangaae/src/eu/kanade/tachiyomi/extension/ar/mangaae/MangaAe.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2820
> MangaAe - fix latest

- src/all/wpcomics/build.gradle
- src/all/wpcomics/src/eu/kanade/tachiyomi/extension/all/wpcomics/WPComics.kt
- src/all/wpcomics/src/eu/kanade/tachiyomi/extension/all/wpcomics/WPComicsFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2813
> WP Comics - add NhatTruyen

- src/all/fmreader/build.gradle
- src/all/fmreader/src/eu/kanade/tachiyomi/extension/all/fmreader/FMReaderFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2830, closes https://github.com/inorichi/tachiyomi-extensions/issues/2807
> FMReader - HanaScan, MangaTR fixes

- src/id/mangakyo/build.gradle
- src/id/mangakyo/src/eu/kanade/tachiyomi/extension/id/mangakyo/Mangakyo.kt
> Mangakyo - domain change

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2839
> Madara - ManhuaUS chapter order

- src/en/oglaf/build.gradle
- src/en/oglaf/src/eu/kanade/tachiyomi/extension/en/oglaf/Oglaf.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2572
> Oglaf - fix pages

- src/tr/serimanga/build.gradle
- src/tr/serimanga/src/eu/kanade/tachiyomi/extension/tr/serimanga/SeriManga.kt
Had the query hardcoded instead of using the query variable, my bad😅
Fixes https://github.com/inorichi/tachiyomi-extensions/issues/2853
> Fixed SeriManga search

- src/en/hentai2read/build.gradle
- src/en/hentai2read/src/eu/kanade/tachiyomi/extension/en/hentai2read/Hentai2Read.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2837
Previous method caused some results to not show up.  This method adds another call but it's kind of unavoidable.
> Hentai2Read - more search changes

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2843
> Madara - MangaKomi dates

- src/all/fmreader/build.gradle
- src/all/fmreader/src/eu/kanade/tachiyomi/extension/all/fmreader/FMReader.kt
- src/all/fmreader/src/eu/kanade/tachiyomi/extension/all/fmreader/FMReaderFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2842
> FMReader - fix thumbnails, headers

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Somehow forgot to add that line in my previous PR.
> Add MangaStein to list of sources

- src/tr/serimanga/build.gradle
- src/tr/serimanga/src/eu/kanade/tachiyomi/extension/tr/serimanga/SeriManga.kt
Fixes https://github.com/inorichi/tachiyomi-extensions/issues/2856
> SeriManga: Get chapters from following pages

- src/all/foolslide/build.gradle
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/FoolSlideFactory.kt
- src/all/noisemanga/build.gradle
- src/all/noisemanga/src/eu/kanade/tachiyomi/extension/all/noisemanga/NoiseManga.kt
- src/all/noisemanga/src/eu/kanade/tachiyomi/extension/all/noisemanga/NoiseMangaFactory.kt
- src/all/toomics/build.gradle
- src/all/toomics/src/eu/kanade/tachiyomi/extension/all/toomics/ToomicsFactory.kt
- src/all/toomics/src/eu/kanade/tachiyomi/extension/all/toomics/ToomicsGlobal.kt
- src/pt/animaregia/build.gradle
- src/pt/animaregia/src/eu/kanade/tachiyomi/extension/pt/animaregia/AnimaRegia.kt
- src/pt/centraldemangas/build.gradle
- src/pt/centraldemangas/src/eu/kanade/tachiyomi/extension/pt/centraldemangas/CentralDeMangas.kt
- src/pt/goldenmangas/build.gradle
- src/pt/goldenmangas/src/eu/kanade/tachiyomi/extension/pt/goldenmangas/GoldenMangas.kt
- src/pt/hipercool/build.gradle
- src/pt/hipercool/src/eu/kanade/tachiyomi/extension/pt/hipercool/Hipercool.kt
- src/pt/mangayabu/build.gradle
- src/pt/mangayabu/src/eu/kanade/tachiyomi/extension/pt/mangayabu/MangaYabu.kt
- src/pt/saikaiscan/build.gradle
- src/pt/saikaiscan/src/eu/kanade/tachiyomi/extension/pt/saikaiscan/SaikaiScan.kt
- src/pt/yesmangas/build.gradle
- src/pt/yesmangas/src/eu/kanade/tachiyomi/extension/pt/yesmangas/YesMangas.kt
- src/pt/zinnes/build.gradle
- src/pt/zinnes/src/eu/kanade/tachiyomi/extension/pt/zinnes/Zinnes.kt
> Update language in Brazilian sources

- src/fr/mangakawaii/build.gradle
- src/fr/mangakawaii/src/eu/kanade/tachiyomi/extension/fr/mangakawaii/MangaKawaii.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2879
> Mangakawaii - request header

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2872, closes https://github.com/inorichi/tachiyomi-extensions/issues/2882
> Madara - add MangaRockTeam

- src/all/foolslide/build.gradle
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/FoolSlide.kt
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/FoolSlideFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2700
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2887
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2890
> Foolslide - add Phoenix Scans, GTO, Kangaryu

- src/all/fmreader/build.gradle
- src/all/fmreader/src/eu/kanade/tachiyomi/extension/all/fmreader/FMReader.kt
- src/all/fmreader/src/eu/kanade/tachiyomi/extension/all/fmreader/FMReaderFactory.kt
Partly closes https://github.com/inorichi/tachiyomi-extensions/issues/2875
> FMReader - add Epik Manga

- src/all/foolslide/build.gradle
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/FoolSlideFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2906
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2905
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2904
> FoolSlide - add 3 Italian sources

- src/all/fmreader/build.gradle
- src/all/fmreader/src/eu/kanade/tachiyomi/extension/all/fmreader/FMReaderFactory.kt
It no longer fits in, making it a separate extension.
Also fixes https://github.com/inorichi/tachiyomi-extensions/issues/2914
> FMReader - remove TruyenTranhLH

- src/en/hentai2read/build.gradle
- src/en/hentai2read/src/eu/kanade/tachiyomi/extension/en/hentai2read/Hentai2Read.kt
> Hentai2Read - fix additional search pages

- src/all/genkan/build.gradle
- src/all/genkan/src/eu/kanade/tachiyomi/extension/all/genkan/GenkanFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2939
> Genkan - add SKScans

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/Madara.kt
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2934
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2894
Fully closes https://github.com/inorichi/tachiyomi-extensions/issues/2875
> Madara - add mixedmanga, manhuasworld, araznovel

- src/all/foolslide/build.gradle
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/FoolSlideFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2935
> FoolSlide - add customizable instance

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/Madara.kt
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2940
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2945
> Madara - add Manga Byte

- src/ar/mangaae/build.gradle
- src/ar/mangaae/src/eu/kanade/tachiyomi/extension/ar/mangaae/MangaAe.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2963
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2957
> MangaAe - update domain name

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2965
> Madara - add Manhwa Raw

- src/all/foolslide/build.gradle
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/FoolSlideFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2960
> FoolSlide - add Tortuga Ceviri

- src/tr/MangaDenizi/build.gradle
- src/tr/MangaDenizi/src/eu/kanade/tachiyomi/extension/tr/mangadenizi/MangaDenizi.kt
Should fix https://github.com/inorichi/tachiyomi-extensions/issues/2983
> Fixes to MangaDenizi

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> Add GuncelManga to Madara

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Was missing a comma in the list. Merged Just before I fixed, rip.
> Missing comma

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/Madara.kt
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3000
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2999
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2980
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2979
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1924
> Madara - update sources

- src/fr/mangakawaii/build.gradle
- src/fr/mangakawaii/src/eu/kanade/tachiyomi/extension/fr/mangakawaii/MangaKawaii.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3005
> Mangakawaii - fix search

- src/all/ninehentai/build.gradle
- src/all/ninehentai/src/eu/kanade/tachiyomi/extension/all/ninehentai/NHTags.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3010
> NineHentai - sort tags

- src/all/foolslide/build.gradle
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/FoolSlide.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3020
> Foolslide - cleaner details

- src/en/readmanhwa/build.gradle
- src/en/readmanhwa/src/eu/kanade/tachiyomi/extension/en/readmanhwa/ReadManhwa.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3008
Webview won't fully load the details page, users have to use "open in browser" from the webview if they want to see the actual page. Browse was even worse; so I didn't bother keeping it in after I tested.
> ReadManhwa - add filters

- src/fr/mangakawaii/build.gradle
- src/fr/mangakawaii/src/eu/kanade/tachiyomi/extension/fr/mangakawaii/MangaKawaii.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3023
> Mangakawaii - tweak chapter_number

- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStream.kt
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStreamFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3038
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2711
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2877
> WP Mangastream - refactor, add Sekte Doujin

- src/all/mangabox/build.gradle
- src/all/mangabox/src/eu/kanade/tachiyomi/extension/all/mangabox/MangaBox.kt
- src/all/mangabox/src/eu/kanade/tachiyomi/extension/all/mangabox/MangaBoxFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3045
> MangaBox - referer headers

- src/all/ninemanga/build.gradle
- src/all/ninemanga/src/eu/kanade/tachiyomi/extension/all/ninemanga/NineManga.kt
- src/all/ninemanga/src/eu/kanade/tachiyomi/extension/all/ninemanga/NineMangaFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3046
> NineManga - adjust headers

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/Madara.kt
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3047
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3040
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3036
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3014
> Madara - add 1st Kiss Manhua, Hero Manhua, Martial Scans

- src/pt/unionmangas/build.gradle
- src/pt/unionmangas/src/eu/kanade/tachiyomi/extension/pt/unionmangas/UnionMangas.kt
- src/pt/unionmangas/src/eu/kanade/tachiyomi/extension/pt/unionmangas/UnionMangasUrlActivity.kt
Closes #3050.
I also rewrote the URL intent handling methods in a better way.
> Fix some chapters not loading at Union Mangás

- src/zh/onemanhua/build.gradle
- src/zh/onemanhua/src/eu/kanade/tachiyomi/extension/zh/onemanhua/Onemanhua.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3022
> OneManhua - now OhManhua

- src/zh/onemanhua/build.gradle
- src/zh/onemanhua/src/eu/kanade/tachiyomi/extension/zh/onemanhua/Onemanhua.kt
Mixed up my inputs when I generated the id, sorry about that.
> OhManhua - correct id

- src/all/boommanga/src/eu/kanade/tachiyomi/extension/all/boommanga/BoomMangaFactory.kt
- src/all/ehentai/src/eu/kanade/tachiyomi/extension/all/ehentai/EHentai.kt
- src/all/ehentai/src/eu/kanade/tachiyomi/extension/all/ehentai/MetadataCopier.kt
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/FoolSlide.kt
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/FoolSlideFactory.kt
- src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/Komga.kt
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangadexDescription.kt
- src/all/mangatensei/src/eu/kanade/tachiyomi/extension/all/mangatensei/Mangatensei.kt
- src/all/mmrcms/src/eu/kanade/tachiyomi/extension/all/mmrcms/Generator.kt
- src/all/mmrcms/src/eu/kanade/tachiyomi/extension/all/mmrcms/MyMangaReaderCMSSources.kt
- src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt
- src/all/ninehentai/src/eu/kanade/tachiyomi/extension/all/ninehentai/NineHentai.kt
- src/all/toomics/src/eu/kanade/tachiyomi/extension/all/toomics/ToomicsGlobal.kt
- src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/WebtoonsFactory.kt
The lint monster is aptly satisfied. For now.
> Corrected a bunch of lints in "all"

- src/pt/goldenmangas/build.gradle
- src/pt/goldenmangas/src/eu/kanade/tachiyomi/extension/pt/goldenmangas/GoldenMangas.kt
> Fix wrong title parsing at Golden Mangás

- src/all/fmreader/build.gradle
- src/all/fmreader/src/eu/kanade/tachiyomi/extension/all/fmreader/FMReaderFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3081
> FMReader - add ManhuaScan

- src/all/comicake/build.gradle
- src/all/comicake/src/eu/kanade/tachiyomi/extension/all/comicake/ComiCake.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3077
Can't guess a manga's actual webpage from manga.url; so we have this here instead.
> Comicake - show webpage on open in webview

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3063
> Madara - add MangaYosh

- src/all/foolslide/build.gradle
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/FoolSlideFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3068
> Foolslide - add Rama

- src/en/mangalife/build.gradle
- src/en/mangalife/src/eu/kanade/tachiyomi/extension/en/mangalife/MangaLife.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3098
> MangaLife - fix chapters

- src/pt/mangayabu/build.gradle
- src/pt/mangayabu/src/eu/kanade/tachiyomi/extension/pt/mangayabu/MangaYabu.kt
> Update MangaYabu to match the new layout

- src/en/mangakisa/build.gradle
- src/en/mangakisa/src/eu/kanade/tachiyomi/extension/en/mangakisa/MangaKisa.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3121
> MangaKisa - fix chapters

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/Madara.kt
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3120
Also fixed Night Comic
>  Madara - MangaStream genres 

- src/en/mangahasu/build.gradle
- src/en/mangahasu/src/eu/kanade/tachiyomi/extension/en/mangahasu/Mangahasu.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3119
> Mangahasu - add filters

- src/ru/libmanga/build.gradle
- src/ru/libmanga/src/eu/kanade/tachiyomi/extension/ru/libmanga/LibManga.kt
In continue to https://github.com/inorichi/tachiyomi-extensions/pull/3131
> Fix mangalib chapter page parse

- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/Mangadex.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3108
> MangaDex - tweak group search

- src/en/mangasee/build.gradle
- src/en/mangasee/src/eu/kanade/tachiyomi/extension/en/mangasee/Mangasee.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3138
> Mangasee - change pageListParse

- src/en/inkr/build.gradle
- src/en/inkr/src/eu/kanade/tachiyomi/extension/en/inkr/INKR.kt
Update INKR to get all titles instead of fetching from latest, so users don't complain about lack of titles.
> Update INKR Browse

- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStreamFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3162
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3142
> WP Mangastream - add non-stop scans

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3152
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3115
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3140
> Madara - add reisubs, mangaread.org, remove mangstein

- src/en/comicextra/build.gradle
- src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3168
> ComicExtra - add filters

- src/en/readmanhwa/build.gradle
- src/en/readmanhwa/src/eu/kanade/tachiyomi/extension/en/readmanhwa/ReadManhwa.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3178
> ReadManhwa - null details fix

- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStreamFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3170
> WP Mangastream - add KomikTap

- src/all/genkan/build.gradle
- src/all/genkan/src/eu/kanade/tachiyomi/extension/all/genkan/GenkanFactory.kt
> adding kkj scans

- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStream.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3226
> WP Mangastream - fix details thumbnail

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> Madara ArazNovel - Add Custom GenreList

- src/en/madokami/build.gradle
- src/en/madokami/src/eu/kanade/tachiyomi/extension/en/madokami/Madokami.kt
> Fix Madokami ordering and parsing issues

- src/all/fmreader/build.gradle
- src/all/fmreader/src/eu/kanade/tachiyomi/extension/all/fmreader/FMReaderFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3260
> FMReader - add ManhwaSmut

- CONTRIBUTING.md
Primarily spelling and grammatical errors have been corrected.
> Resolving more mistakes in CONTRIBUTING.md

- src/all/mangabox/build.gradle
- src/all/mangabox/src/eu/kanade/tachiyomi/extension/all/mangabox/MangaBox.kt
- src/all/mangabox/src/eu/kanade/tachiyomi/extension/all/mangabox/MangaBoxFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3201
* Manganelo and Mangabat now have more advanced search capabilities.
* Removed MangaOnl (due to being down 3-4 weeks)
* Added Mangairo (but doesn't have search filters because it'd be more work and no one even asked for this)
> MangaBox - refactor search, source list changes

- src/en/comicextra/build.gradle
- src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3277
> ComicExtra - add genre details

- src/all/ninemanga/build.gradle
- src/all/ninemanga/src/eu/kanade/tachiyomi/extension/all/ninemanga/NineManga.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3227
> NineManga - more filters

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/Madara.kt
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3273
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3271
> Madara - add Manga347, referer for chapters

- src/en/readm/build.gradle
- src/en/readm/src/eu/kanade/tachiyomi/extension/en/readm/ReadM.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3305
> ReadM - fix latest

- src/id/maidmanga/build.gradle
- src/id/maidmanga/src/eu/kanade/tachiyomi/extension/id/maidmanga/MaidManga.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3300
> Maid Manga - site changed theme

- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStreamFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3294
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3290
Maid Manga changed themes, not going to support it in two extensions.
> WP Mangastream - add Matakomik, Komikindo.co, remove Maid Manga

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Change of Hiperdex URL to .com
> Change of Hiperdex URL

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> Added WebtoonXYZ

- src/vi/medoctruyentranh/build.gradle
- src/vi/medoctruyentranh/src/eu/kanade/tachiyomi/extension/vi/medoctruyentranh/MeDocTruyenTranh.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2901
> MeDocTruyenTranh - fixes

- src/all/foolslide/build.gradle
- src/all/foolslide/src/eu/kanade/tachiyomi/extension/all/foolslide/FoolSlideFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3285
> FoolSlide - add Mabushimajo

- src/en/mangasail/build.gradle
- src/en/mangasail/src/eu/kanade/tachiyomi/extension/en/mangasail/Mangasail.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3330
> Mangasail - fixe pages, refactor

- src/id/maidmanga/build.gradle
- src/id/maidmanga/src/eu/kanade/tachiyomi/extension/id/maidmanga/MaidManga.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3343
> Maid Manga - better chapterListSelector

- src/zh/manhuadui/build.gradle
- src/zh/manhuadui/src/eu/kanade/tachiyomi/extension/zh/manhuadui/Manhuadui.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3341
> Manhuadui - update domain name

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Also added some details for GetManhwa
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3326
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3317
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3107
> Madara - add Drope Scan, QueensManga

- src/en/tapastic/build.gradle
- src/en/tapastic/src/eu/kanade/tachiyomi/extension/en/tapastic/Tapastic.kt
Closes #3347 
Tapas redesigned part of their website; so had to rewrite how chapters are parsed, again. Think I covered all the details (future chapters, unlocked/locked chapters, etc) but I guess we'll see.
> Tapas - new chapter list parsing

- src/pt/goldenmangas/build.gradle
- src/pt/goldenmangas/src/eu/kanade/tachiyomi/extension/pt/goldenmangas/GoldenMangas.kt
> Update network client at Golden Mangás

- src/en/mangahere/build.gradle
- src/en/mangahere/src/eu/kanade/tachiyomi/extension/en/mangahere/Mangahere.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3371
> Mangahere - fix genre search

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> Added ManhwaTime to Madara Extension

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> Added MangaZen (arabic) to Madara

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> Added TheTopComic, Manytoon.me and Boyslove to Madara

- src/ar/teamx/build.gradle
- src/ar/teamx/src/eu/kanade/tachiyomi/extension/ar/teamx/TeamX.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3399
> Team X - update domain name

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3410
> Madara - fix Manga Arab Team images

- src/all/komga/build.gradle
- src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/Komga.kt
closes gotson/komga#169, gotson/komga#180
> [Komga] unread only filter, prefix book titles

- src/all/mangaplus/build.gradle
- src/all/mangaplus/src/eu/kanade/tachiyomi/extension/all/mangaplus/MangaPlus.kt
- src/all/mangaplus/src/eu/kanade/tachiyomi/extension/all/mangaplus/MangaPlusApi.kt
> Fix wrong status in completed titles at MangaPlus

- src/all/paprika/build.gradle
- src/all/paprika/src/eu/kanade/tachiyomi/extension/all/paprika/Paprika.kt
- src/all/paprika/src/eu/kanade/tachiyomi/extension/all/paprika/PaprikaAlt.kt
- src/all/paprika/src/eu/kanade/tachiyomi/extension/all/paprika/PaprikaFactory.kt
> add mangawindow.club and manganelos.com to Paprika

- src/all/fmreader/build.gradle
- src/all/fmreader/src/eu/kanade/tachiyomi/extension/all/fmreader/FMReader.kt
> FMReader: remove manga title from chaper names

- src/en/mangaeden/build.gradle
- src/en/mangaeden/src/eu/kanade/tachiyomi/extension/en/mangaeden/Mangaeden.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3438
> MangaEden - fix images

- src/en/mangaeden/build.gradle
For whatever reason my local gradle had the wrong version number; so the last PR didn't bump the version correctly.
> MangaEden - version bump

- src/all/mangabox/build.gradle
- src/all/mangabox/src/eu/kanade/tachiyomi/extension/all/mangabox/MangaBoxFactory.kt
> MangaBox - update search

- src/all/nhentai/build.gradle
- src/all/nhentai/src/eu/kanade/tachiyomi/extension/all/nhentai/NHentai.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3454
> NHentai - fix pages

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> Added WebNovel to Madara

- src/ru/remanga/build.gradle
- src/ru/remanga/src/eu/kanade/tachiyomi/extension/ru/remanga/Remanga.kt
- src/ru/remanga/src/eu/kanade/tachiyomi/extension/ru/remanga/dto/Dto.kt
Paid chapters support for https://remanga.ru
Chapter page in site devided by chanks. I've tried to make parallel requests to combine it
> Remanga: Paid chapter

- src/en/killsixbilliondemons/build.gradle
- src/en/killsixbilliondemons/src/eu/kanade/tachiyomi/extension/en/killsixbilliondemons/KillSixBillionDemons.kt
> Kill Six billion Demons: fix a bug

- src/it/mangaeden/build.gradle
- src/it/mangaeden/src/eu/kanade/tachiyomi/extension/it/mangaeden/Mangaeden.kt
Based on the english version, just changed links and variables to make it work with the italian verison
> [Mangaeden] Fix images italian version

- src/zh/dmzj/build.gradle
- src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/Dmzj.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3457
> Dmzj - encode imageUrl requests

- src/en/nineanime/build.gradle
- src/en/nineanime/src/eu/kanade/tachiyomi/extension/en/nineanime/NineAnime.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3469
> NineAnime - fix chapter names

- src/en/xkcd/build.gradle
- src/en/xkcd/src/eu/kanade/tachiyomi/extension/en/xkcd/Xkcd.kt
Should close https://github.com/inorichi/tachiyomi-extensions/issues/3461
> Xkcd - fix refresh/restore details

- src/ru/remanga/build.gradle
- src/ru/remanga/src/eu/kanade/tachiyomi/extension/ru/remanga/Remanga.kt
Some owe from https://github.com/inorichi/tachiyomi-extensions/pull/3451#issuecomment-641497647
> Remanga: Faster loading paid chapter

- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDex.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2645
> MangaDex - MangaPlus message

- src/en/mangaowl/build.gradle
- src/en/mangaowl/src/eu/kanade/tachiyomi/extension/en/mangaowl/MangaOwl.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3495
> MangaOwl - update date parsing

- src/en/mangapark/build.gradle
- src/en/mangapark/src/eu/kanade/tachiyomi/extension/en/mangapark/MangaPark.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2541
Improved on how chapter numbers are decided when parsing titles; so source preferences should work better.
> MangaPark - improved chapter parsing

- src/es/tmohentai/build.gradle
- src/es/tmohentai/src/eu/kanade/tachiyomi/extension/es/tmohentai/TMOHentai.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3494
> TMOHentai - fix search

- src/ru/libmanga/build.gradle
- src/ru/libmanga/src/eu/kanade/tachiyomi/extension/ru/libmanga/LibManga.kt
> Fix libmanga chapters page parse

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/Madara.kt
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> Fix wrong date parsing at Neox

- CONTRIBUTING.md
> [CI SKIP] add some points to CONTRIBUTING.md

- CONTRIBUTING.md
also added grade attribute for other code tags
> [CI SKIP] DataImage library info added to CONTRIBUTING.md

- src/all/wpcomics/build.gradle
- src/all/wpcomics/src/eu/kanade/tachiyomi/extension/all/wpcomics/WPComicsFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2899
> WP Comics - add NetTruyen

- src/en/myhentaicomics/build.gradle
- src/en/myhentaicomics/src/eu/kanade/tachiyomi/extension/en/myhentaicomics/MyHentaiComics.kt
> MyHentaiComics - fix pages

- src/en/nineanime/build.gradle
- src/en/nineanime/src/eu/kanade/tachiyomi/extension/en/nineanime/NineAnime.kt
Has to do with https://github.com/inorichi/tachiyomi-extensions/issues/3476
> NineAnime - add headers

- src/all/wpcomics/build.gradle
- src/all/wpcomics/src/eu/kanade/tachiyomi/extension/all/wpcomics/WPComicsFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3526
> WP Comics - fix xoxocomics chapters

- src/vi/iutruyentranh/build.gradle
- src/vi/iutruyentranh/src/eu/kanade/tachiyomi/extension/vi/iutruyentranh/IuTruyenTranh.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2900
> IuTruyenTranh - improvements, fix pages

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/Madara.kt
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3532
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3547
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3545
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3518
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3490
Added: Furio Scans, Shea Manga, TruyenTranhAudio (.com and .online), Manga Turf
> Madara - add sources, refactor date parsing

- src/all/mmrcms/build.gradle
- src/all/mmrcms/src/eu/kanade/tachiyomi/extension/all/mmrcms/MyMangaReaderCMSSource.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3561
> MMRCMS - fix mangas.pw decoding

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/Madara.kt
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3558
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3169
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2731
> Madara - headers

- src/all/ninehentai/build.gradle
- src/all/ninehentai/src/eu/kanade/tachiyomi/extension/all/ninehentai/NineHentai.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2042
> NineHentai - make details refreshable

- src/en/questionablecontent/build.gradle
- src/en/questionablecontent/src/eu/kanade/tachiyomi/extension/en/questionablecontent/QuestionableContent.kt
It's only for the most recent chapter, but it closes https://github.com/inorichi/tachiyomi-extensions/issues/2362
> Questionable Content - add chapter date

- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDex.kt
@CarlosEsco Do you think this is okay to do? I don't think the additional requests will be overly burdensome but I could be wrong.
> MangaDex - fewer broken covers 

- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStreamFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3574
> WP Mangastream - more kiryuu page filtering

- src/all/fmreader/build.gradle
- src/all/fmreader/src/eu/kanade/tachiyomi/extension/all/fmreader/FMReader.kt
- src/all/fmreader/src/eu/kanade/tachiyomi/extension/all/fmreader/FMReaderFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3573
Removing MangaBone as it's been useless for a long time.
> FMReader - fix RawLH & KissLove, remove MangaBone

- src/es/mangamx/build.gradle
- src/es/mangamx/src/eu/kanade/tachiyomi/extension/es/mangamx/MangaMx.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3492
> MangaMx - fix pages

- src/id/manhuaid/build.gradle
- src/id/manhuaid/src/eu/kanade/tachiyomi/extension/id/manhuaid/ManhuaID.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3555
> ManhuaID - change chapter selector

- src/all/ehentai/build.gradle
- src/all/ehentai/src/eu/kanade/tachiyomi/extension/all/ehentai/EHentai.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2910
> E-Hentai - backport changes from AZ, cleanup

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> Added AsuraScans to Madara

- src/en/comicpunch/build.gradle
- src/en/comicpunch/src/eu/kanade/tachiyomi/extension/en/comicpunch/Comicpunch.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3590
> Comicpunch - fix search

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes #3591 and Closes #3595 . Reisubs site has been taken down by the site owners for more than a month
> Added MangaRawr, CopyPasteScan and Removed Reisubs from Madara

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> Added AhStudios(es) to Madara

- src/all/nhentai/build.gradle
- src/all/nhentai/src/eu/kanade/tachiyomi/extension/all/nhentai/NHentai.kt
Add maybe all possible filters on the site
> NHentai: More filters

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> Added PMScans to Madara

- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStream.kt
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStreamFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3600
> WP Mangastream - update Komiktap

- src/all/komga/CHANGELOG.md
- src/all/komga/build.gradle
- src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/Komga.kt
- src/all/komga/src/eu/kanade/tachiyomi/extension/all/komga/dto/Dto.kt
add CHANGELOG.md
closes gotson/komga#211
> [Komga] filter by collection

- src/all/ehentai/build.gradle
- src/all/ehentai/src/eu/kanade/tachiyomi/extension/all/ehentai/EHentai.kt
Added some tags for filtering, browse returns its own results now instead duplicating latest, and added some more language filtering.
> E-Hentai - tag filtering, browsing changes

- src/all/fmreader/build.gradle
- src/all/fmreader/src/eu/kanade/tachiyomi/extension/all/fmreader/FMReaderFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3640
> FMReader - ManhwaSmut imageRequests

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3636
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3016
> Madara - apc genres, golden-manga fixes

- src/en/mangalife/build.gradle
- src/en/mangalife/src/eu/kanade/tachiyomi/extension/en/mangalife/MangaLife.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3624
> MangaLife - official translation filtering

- src/all/genkan/build.gradle
- src/all/genkan/src/eu/kanade/tachiyomi/extension/all/genkan/GenkanFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3649
> Genkan - add Kraken Scans, remove Wowe Scans

- src/all/mangabox/build.gradle
- src/all/mangabox/src/eu/kanade/tachiyomi/extension/all/mangabox/MangaBox.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3652
> MangaBox - fix Mangakakalots pages

- src/en/mangasee/build.gradle
- src/en/mangasee/src/eu/kanade/tachiyomi/extension/en/mangasee/Mangasee.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3661
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3654
New domain and new website. They're using the same theme and resources as Manga Life. Probably should make this a multi-source extension but that's a problem for a different day.
> Mangasee - update to use Manga Life code

- src/all/nhentai/build.gradle
- src/all/nhentai/src/eu/kanade/tachiyomi/extension/all/nhentai/NHentai.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3617
> NHentai - safe call

- src/all/webtoons/build.gradle
- src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/DongmanManhua.kt
- src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/Webtoons.kt
- src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/WebtoonsTranslate.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3673
> Webtoons - update search

- src/pt/supermangas/build.gradle
- src/pt/supermangas/src/eu/kanade/tachiyomi/extension/pt/supermangas/SuperMangasGeneric.kt
- src/pt/supermangas/src/eu/kanade/tachiyomi/extension/pt/supermangas/source/SuperHentais.kt
Partially fixes #3686.
SuperMangas is working fine now, but the chapter pagination on the SuperHentais website is broken.
I will try to work on a temporary alternative fix on the extension side later if they don't fix the website in the meanwhile.
> Fix chapters and manga info not loading at SuperMangas

- src/en/timelessleaf/build.gradle
- src/en/timelessleaf/src/eu/kanade/tachiyomi/extension/en/timelessleaf/TimelessLeaf.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3682
> TimelessLeaf - more page parsing

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3675
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3575
> Madara - add ComicKiba and KlanKomik

- src/all/mangadex/build.gradle
- src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MangaDex.kt
https://github.com/inorichi/tachiyomi-extensions/issues/3702
If chapter pages are requested more than 5 minutes after initial request, new tokens are requested.
> MangaDex - MD@Home token handling

- src/en/wutopia/build.gradle
- src/en/wutopia/src/eu/kanade/tachiyomi/extension/en/wutopia/Wutopia.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3690
Closes https://github.com/inorichi/tachiyomi-extensions/issues/2382
User can choose to see only free chapters or all chapters.
WebView (as called from info tab) only works on newer versions of Tachiyomi (e.g. preview, not stable; TachiyomiSy).
> Wutopia - chapter prefs, webview fix

- src/en/mangapark/build.gradle
- src/en/mangapark/src/eu/kanade/tachiyomi/extension/en/mangapark/MangaPark.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3734
As with other sources users may still have to occasionally retry but it eventually works.
> MangaPark - add cloudflareclient

- src/pt/supermangas/build.gradle
- src/pt/supermangas/src/eu/kanade/tachiyomi/extension/pt/supermangas/SuperMangasGeneric.kt
- src/pt/supermangas/src/eu/kanade/tachiyomi/extension/pt/supermangas/source/SuperHentais.kt
Closes #3751.
This is just a temporary solution while the chapter list pagination is broken.
> Fix chapters not loading at SuperHentais

- src/en/mangalife/build.gradle
- src/en/mangalife/src/eu/kanade/tachiyomi/extension/en/mangalife/MangaLife.kt
- src/en/mangasee/build.gradle
- src/en/mangasee/src/eu/kanade/tachiyomi/extension/en/mangasee/Mangasee.kt
Should fix some broken covers.
> MangaSee, MangaLife - update cover CDN

- src/all/paprika/build.gradle
- src/all/paprika/src/eu/kanade/tachiyomi/extension/all/paprika/Paprika.kt
- src/all/paprika/src/eu/kanade/tachiyomi/extension/all/paprika/PaprikaFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3767
> Paprika - add mangadogs.fun

- src/es/lectormanga/build.gradle
- src/es/lectormanga/src/eu/kanade/tachiyomi/extension/es/lectormanga/LectorManga.kt
- src/es/tumangaonline/build.gradle
- src/es/tumangaonline/src/eu/kanade/tachiyomi/extension/es/tumangaonline/TuMangaOnline.kt
> Fix TuMangaOnline & LetorManga

- src/en/mangalife/build.gradle
- src/en/mangalife/src/eu/kanade/tachiyomi/extension/en/mangalife/MangaLife.kt
- src/en/mangasee/build.gradle
- src/en/mangasee/src/eu/kanade/tachiyomi/extension/en/mangasee/Mangasee.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3778
> MangaSee, MangaLife - more accurate date parsing

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> Added TritiniaScans to Madara

- src/all/wpcomics/build.gradle
- src/all/wpcomics/src/eu/kanade/tachiyomi/extension/all/wpcomics/WPComicsFactory.kt
> Add ComicLatest

- src/all/webtoons/build.gradle
- src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/WebtoonsDefault.kt
Fixes #3680. Tested on both "chiller" and "shriek"
> Add motiontoon support to webtoons

- src/zh/manhuadui/build.gradle
- src/zh/manhuadui/src/eu/kanade/tachiyomi/extension/zh/manhuadui/Manhuadui.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3811
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3787
> Manhuadui - update decryption key

- src/en/mangafast/build.gradle
- src/en/mangafast/src/eu/kanade/tachiyomi/extension/en/mangafast/MangaFast.kt
> Manga fast

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Fixes #3832 and fixes #3833
EDIT: As per SnakeDoc's commits:
Closes #3831
Closes #3814
Closes #3827
> Change Manga Arab Team url

- src/all/wpcomics/build.gradle
- src/all/wpcomics/src/eu/kanade/tachiyomi/extension/all/wpcomics/WPComicsFactory.kt
Fixes #3839. Hopefully I haven't made any other glaring oversights that I haven't noticed.
> ComicLatest: Get following pages in search 

- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStreamFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3808
> WP Mangastream - update KomikTap domain

- src/ja/shonenjumpplus/build.gradle
- src/ja/shonenjumpplus/src/eu/kanade/tachiyomi/extension/ja/shonenjumpplus/ShonenJumpPlus.kt
> Fix chapters not opening at Shonen Jump+

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/Madara.kt
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Couple fixes too.
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3858
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3853
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3845
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3830
> Madara - add Skymanga, remove Novel France

- src/all/myreadingmanga/build.gradle
- src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3807
> MyReadingManga - fix pages

- src/en/mangareader/build.gradle
- src/en/mangareader/src/eu/kanade/tachiyomi/extension/en/mangareader/MRP.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3886
> Mangareader - fix genre tags

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Also fixed QueensManga.
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3875
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3866
> Madara - add toonily.net

- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStream.kt
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStreamFactory.kt
Fix NextPageSelector and LastUpdate
> WP Mangastream - update Sekte Komik, KomikStation, KomikAV

- src/all/mmrcms/build.gradle
- src/all/mmrcms/src/eu/kanade/tachiyomi/extension/all/mmrcms/MyMangaReaderCMSSource.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3885
> MMRCMS - fix Mangas.pw chapters

- src/zh/manhuadui/build.gradle
- src/zh/manhuadui/src/eu/kanade/tachiyomi/extension/zh/manhuadui/Manhuadui.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3883
> Manhuadui - update decryption, refactor pageListParse

- src/zh/manhuagui/build.gradle
- src/zh/manhuagui/src/eu/kanade/tachiyomi/extension/zh/manhuagui/Manhuagui.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3857
I think the source had already fixed it actually, but just in case, this would probably help. Also threw in some chapter sorting.
> Manhuagui - small tweaks

- src/ar/teamx/build.gradle
- src/ar/teamx/src/eu/kanade/tachiyomi/extension/ar/teamx/TeamX.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3893
> TeamX - update domain

- src/ru/remanga/build.gradle
- src/ru/remanga/src/eu/kanade/tachiyomi/extension/ru/remanga/Remanga.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3592
> Remanga - fix IllegalStateException and 401

- src/pt/mangahost/build.gradle
- src/pt/mangahost/src/eu/kanade/tachiyomi/extension/pt/mangahost/MangaHost.kt
> Fix pages and thumbnails not loading at MangaHost

- src/all/nhentai/build.gradle
- src/all/nhentai/src/eu/kanade/tachiyomi/extension/all/nhentai/NHentai.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3709
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3851
> NHentai - fix shortened titles

- src/all/genkan/build.gradle
- src/all/genkan/src/eu/kanade/tachiyomi/extension/all/genkan/Genkan.kt
- src/all/genkan/src/eu/kanade/tachiyomi/extension/all/genkan/GenkanFactory.kt
https://github.com/inorichi/tachiyomi-extensions/issues/3916
> Genkan - remove One Shot Scans

- src/pt/mangasproject/build.gradle
- src/pt/mangasproject/src/eu/kanade/tachiyomi/extension/pt/mangasproject/MangasProject.kt
Also added `Content-Length` and `Content-Type` to the search request.
> Add Accept header to requests at MangasProject

- src/all/paprika/build.gradle
- src/all/paprika/src/eu/kanade/tachiyomi/extension/all/paprika/PaprikaFactory.kt
https://github.com/inorichi/tachiyomi-extensions/issues/3916
> Paprika - update Mangazuki.xyz

- src/en/readmanhwa/build.gradle
- src/en/readmanhwa/src/eu/kanade/tachiyomi/extension/en/readmanhwa/ReadManhwa.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3936
> ReadManhwa - enable nsfw requests

- src/en/mangakatana/build.gradle
- src/en/mangakatana/src/eu/kanade/tachiyomi/extension/en/mangakatana/MangaKatana.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3937
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3935
> MangaKatana - fix pages

- src/ko/toonkor/build.gradle
- src/ko/toonkor/src/eu/kanade/tachiyomi/extension/ko/toonkor/Toonkor.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3947
> Toonkor - fix search

- src/all/zbulu/build.gradle
- src/all/zbulu/src/eu/kanade/tachiyomi/extension/all/zbulu/Zbulu.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3949
> zBulu - fix date parsing

- src/en/readmanhwa/build.gradle
- src/en/readmanhwa/src/eu/kanade/tachiyomi/extension/en/readmanhwa/ReadManhwa.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3950
> ReadManhwa - enable nsfw part 2

- src/zh/manhuadui/build.gradle
- src/zh/manhuadui/src/eu/kanade/tachiyomi/extension/zh/manhuadui/Manhuadui.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1897
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3955
The example given in #1897 isn't available anymore so I couldn't really test for differences.
> Manhuadui - update decryption, refactor chapter list parsing

- src/en/hbrowse/build.gradle
- src/en/hbrowse/src/eu/kanade/tachiyomi/extension/en/hbrowse/HBrowse.kt
Added a note for filters and a couple fixes.
> HBrowse - some tweaks

- src/ru/readmanga/build.gradle
- src/ru/readmanga/src/eu/kanade/tachiyomi/extension/ru/readmanga/Readmanga.kt
New domain - https://readmanga.live/
> ru-readmanga change domain to readmanga.live

- src/pt/yesmangas/build.gradle
- src/pt/yesmangas/src/eu/kanade/tachiyomi/extension/pt/yesmangas/YesMangas.kt
Closes the issue reported at the Discord server.
> Fix chapter images not loading at Yes Mangás

- src/fr/scantrad/build.gradle
- src/fr/scantrad/src/eu/kanade/tachiyomi/extension/fr/scantrad/Scantrad.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3987
> Scantrad - better chapter lists

- src/all/myreadingmanga/build.gradle
- src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3985
> MyReadingManga - refactor search

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/Madara.kt
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3980
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3906
https://github.com/inorichi/tachiyomi-extensions/issues/3916
Removed Happy Tea Scans, Teabeer Comics, Uknown Scans, Yo Manga, and Manga Byte
> Madara - add BestManga, TwilightScans, remove dead sources

- src/es/kumanga/build.gradle
- src/es/kumanga/src/eu/kanade/tachiyomi/extension/es/kumanga/Kumanga.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3989
> Kumanga - fix freeze on startup

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
> Change url of manga Arab team

- src/en/mangasee/build.gradle
- src/en/mangasee/src/eu/kanade/tachiyomi/extension/en/mangasee/Mangasee.kt
> Mangasee: fix chapter url suffix location

- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStreamFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4012
> WP Mangastream - fix Readkomik browse

- src/all/wpmangastream/build.gradle
- src/all/wpmangastream/src/eu/kanade/tachiyomi/extension/all/wpmangastream/WPMangaStreamFactory.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4035
Closes https://github.com/inorichi/tachiyomi-extensions/issues/3562
> WP Mangastream - add Manga Pro Z

- src/es/kumanga/build.gradle
- src/es/kumanga/src/eu/kanade/tachiyomi/extension/es/kumanga/Kumanga.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4016
> Kumanga - update parsing

- src/en/readmanhwa/build.gradle
- src/en/readmanhwa/src/eu/kanade/tachiyomi/extension/en/readmanhwa/ReadManhwa.kt
#4050 
added nsfw=true in query param
> nsfw true added in query param

- src/all/madara/build.gradle
- src/all/madara/src/eu/kanade/tachiyomi/extension/all/madara/MadaraFactory.kt
Added https://www.manga.detectiveconanar.com/ which have all detective Conan different manga chapters in Arabic.
> madara: Add manga.detectiveconanar.com

- src/all/ehentai/build.gradle
- src/all/fmreader/build.gradle
- src/all/ninehentai/build.gradle
- src/all/simplyhentai/build.gradle
- src/en/eggporncomics/build.gradle
- src/en/hentai2read/build.gradle
- src/en/hentaifox/build.gradle
- src/en/hentainexus/build.gradle
- src/en/myhentaicomics/build.gradle
- src/en/myhentaigallery/build.gradle
- src/es/ikuhentai/build.gradle
- src/es/tmohentai/build.gradle
- src/it/hentaifantasy/build.gradle
- src/it/perveden/build.gradle
- src/pt/hipercool/build.gradle
- src/pt/mundohentai/build.gradle
- src/pt/supermangas/build.gradle
- src/vi/hentaivn/build.gradle
Attempts to address #4055. Probably missing many more extensions that should be marked as nsfw, but it's a start.
> Mark extensions as nsfw

- src/pt/mangasproject/build.gradle
- src/pt/mangasproject/src/eu/kanade/tachiyomi/extension/pt/mangasproject/MangasProject.kt
- src/pt/mangasproject/src/eu/kanade/tachiyomi/extension/pt/mangasproject/MangasProjectFactory.kt
Also changed the source name to match the name used at the website.
> Add content type filter to Mangá Livre

- src/zh/manhuadui/build.gradle
- src/zh/manhuadui/src/eu/kanade/tachiyomi/extension/zh/manhuadui/Manhuadui.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4065
> Manhuadui - update decryption

- src/es/kumanga/build.gradle
- src/es/kumanga/src/eu/kanade/tachiyomi/extension/es/kumanga/Kumanga.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4071
> Kumanga - fix token

- src/all/nhentai/build.gradle
- src/all/nhentai/src/eu/kanade/tachiyomi/extension/all/nhentai/NHFactory.kt
- src/all/nhentai/src/eu/kanade/tachiyomi/extension/all/nhentai/NHentai.kt
Popular manga is unavailable with no filters, so I replaced it with the latest page
> NHentai - add a "other" language for those who want to use NHentai unfiltered

- src/ru/henchan/build.gradle
- src/ru/henchan/src/eu/kanade/tachiyomi/extension/ru/henchan/Henchan.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4082
> Henchan - fix cover not being set by mangaDetailsParse

- src/tr/MangaDenizi/build.gradle
- src/tr/MangaDenizi/src/eu/kanade/tachiyomi/extension/tr/mangadenizi/MangaDenizi.kt
Closes https://github.com/inorichi/tachiyomi-extensions/issues/4093
> MangaDenizi - fix date parsing
